== Chapter II.

His first journey, on a religious visit, into East Jersey,
in company with Abraham Farrington--Thoughts on merchandizing,
and learning a trade--Second journey, with Isaac Andrews, into Pennsylvania, Maryland,
Virginia, and North Carolina--Third journey, with Peter Andrews,
through part of West and East Jersey--Some account of his sister Elizabeth,
and her death--Fourth journey, with Peter Andrews, through New York and Long Island,
to New England--Fifth journey, with John Sykes, to the Eastern Shore of Maryland,
and the lower counties on Delaware.

My esteemed friend Abraham Farrington,
being about to make a visit to Friends on the eastern side of this province,
and having no companion, proposed to me to go with him;
and after a conference with some elderly Friends, I agreed to go.
We set out the 5th day of the ninth month, in the year 1743;
and had an evening meeting at a tavern in Brunswick,
a town in which none of our Society dwelt; the room was full, and the people quiet.
Thence to Amboy, and had an evening meeting in the court-house;
to which came many people, amongst whom were several members of assembly,
they being in town on the public affairs of the province:
in both these meetings my ancient companion was enlarged to preach,
in the love of the Gospel.
Thence we went to Woodbridge, Rahway, and Plainfield;
and had six or seven meetings in places where Friends`' meetings are not usually held,
being made up chiefly of Presbyterians,
and my beloved companion was frequently strengthened to
publish the word of life amongst them.
As for me, I was often silent through the meetings; and when I spake,
it was with much care, that I might speak only what Truth opened:
my mind was often tender, and I learned some profitable lessons.
We were out about two weeks.

Near this time, being on some outward business in which several families were concerned,
and which was attended with difficulties,
some things relating thereto not being clearly stated, nor rightly understood by all,
there arose some heat in the minds of the parties,
and one valuable Friend got off his watch.
I had a great regard for him, and felt a strong inclination, after matters were settled,
to speak to him concerning his conduct in that case; but I being a youth,
and he far advanced in age and experience, my way appeared difficult;
but after some days deliberation, and inward seeking to the Lord for assistance,
I was made subject; so that I expressed what lay upon me,
in a way which became my youth and his years: and though it was a hard task to me,
it was well taken, and, I believe, was useful to us both.

Having now been several years with my employer,
and he doing less at merchandize than heretofore,
I was thoughtful of some other way of business;
perceiving merchandize to be attended with much cumber,
in the way of trading in these parts.

My mind, through the power of Truth,
was in a good degree weaned from the desire of outward greatness,
and I was learning to be content with real conveniences, that were not costly;
so that a way of life free from much entanglement, appeared best for me,
though the income might be small.
I had several offers of business that appeared profitable,
but did not see my way clear to accept of them believing the
business proposed would be attended with more outward care and
cumber than it was required of me to engage in.

I saw that a humble man, with the blessing of the Lord, might live on a little:
and that where the heart was set on greatness,
success in business did not satisfy the craving;
but that commonly with an increase of wealth, the desire of wealth increased.
There was a care on my mind so to pass my time,
that nothing might hinder me from the most steady
attention to the voice of the true Shepherd.

My employer, though now a retailer of goods, was by trade a tailor,
and kept a servant man at that business; and I began to think about learning the trade,
expecting, that if I should settle, I might, by this trade,
and a little retailing of goods, get a living in a plain way,
without the load of great business.

I mentioned it to my employer, and we soon agreed on terms; and then,
when I had leisure from the affairs of merchandize, I worked with this man.
I believed the hand of Providence pointed out this
business for me and was taught to be content with it,
though I felt, at times, a disposition that would have sought for something greater.
But, through the revelation of Jesus Christ, I had seen the happiness of humility,
and there was an earnest desire in me to enter deeply into it; and, at times,
this desire arose to a degree of fervent supplication,
wherein my soul was so environed with heavenly light and consolation,
that things were made easy to me which had been otherwise.

After some time, my employer`'s wife died; she was a virtuous woman,
and generally beloved of her neighbours: and soon after this, he left shop-keeping;
and we parted.
I then wrought at my trade, as a tailor;
carefully attended meetings for worship and discipline
and found an enlargement of Gospel love in my mind,
and therein a concern to visit Friends in some of the
back settlements of Pennsylvania and Virginia.
Being thoughtful about a companion, I expressed it to my beloved friend Isaac Andrews,
who then told me that he had drawings to the same places;
and also to go through Maryland, Virginia, and Carolina.
After considerable time passed, and several conferences with him,
I felt easy to accompany him throughout, if way opened for it.
I opened the case in our Monthly Meeting, and Friends expressing their unity therewith,
we obtained certificates to travel as companions; his from Haddonfield,
and mine from Burlington.

We left our province on the 12th day of the third month, in the year 1746,
and had several meetings in the upper part of Chester county, and near Lancaster;
in some of which, the love of Christ prevailed, uniting us together in his service.
Then we crossed the river Susquehanna, and had several meetings in a new settlement,
called the Red-lands the oldest of which, as I was informed, did not exceed ten years.
It is the poorer sort of people who commonly begin to improve remote deserts:
with a small stock they have houses to build, lands to clear and fence, corn to raise,
clothes to provide, and children to educate; that Friends, who visit such,
may well sympathize with them in their hardships in (he wilderness;
and though the best entertainment such can give,
may seem coarse to some who are used to cities, or old-settled places,
it becomes the disciples of Christ to be content with it.
Our hearts were sometimes enlarged in the love
of our heavenly Father amongst these people;
and the sweet influence of his Spirit supported us through some difficulties:
to him be the praise.

We passed on to Manoquacy, Fairfax, Hopewell, and Shanandoah, and had meetings;
some of which were comfortable and edifying.
From Shanandoah,
we set off in the afternoon for the old settlements of Friends in Virginia;
and the first night, we, with our pilot, lodged in the woods, our horses feeding near us;
but he being poorly provided with a horse, and we young and having good horses,
were free to part with him; and next day did so.
In two days after, we reached our friend John Cheagle`'s, in Virginia;
and taking the meetings in our way through Virginia, were in some degree,
baptized into a feeling of the conditions of the people;
and our exercise in general was more painful in these old settlements,
than it had been amongst the back inhabitants:
but through the goodness of our heavenly Father, the well of living waters was, at times,
opened to our encouragement and the refreshment of the sincere-hearted.
We went on to Perquimons, in North Carolina; had several meetings, which were large,
and found some openness in those parts,
and a hopeful appearance amongst the young people.
We turned again into Virginia,
and attended most of the meetings which we had not been at before,
labouring amongst Friends in the love of Jesus Christ, as ability was given;
and thence went to the mountains, up James River, to a new settlement,
and had several meetings amongst the people,
some of whom had lately joined in membership with our Society.
In our journeying to and fro, we found some honest-hearted Friends,
who appeared to be concerned for the cause of Truth, among a backsliding people.

From Virginia, we crossed over the river Potomac, at Hoe`'s ferry,
and made a general visit to the meetings of Friends on the Western Shore of Maryland,
and were at their Quarterly Meeting.
We had some hard labour amongst them,
endeavouring to discharge our duty honestly as way opened, in the love of truth.
Taking sundry meetings in our way, we passed homeward, where,
through the favour of Divine Providence, we reached, the 16th day of the sixth month,
in the year 1746; and I may say, that through the assistance of the Holy Spirit,
which mortifies selfish desires, my companion and I travelled in harmony,
and parted in the nearness of true brotherly love.

Two things were remarkable to me in this journey: first, in regard to my entertainment;
when I eat, drank, and lodged free of cost,
with people who lived in ease on the hard labour of their slaves, I felt uneasy;
and as my mind was inward to the Lord, I found, from place to place,
this uneasiness return upon me, at times, through the whole visit.
Where the masters bore a good share of the burthen, and lived frugally,
so that their servants were well provided for, and their labour moderate,
I felt more easy; but where they lived in a costly way,
and laid heavy burthens on their slaves, my exercise was often great,
and I frequently had conversation with them, in private, concerning it.
Secondly;
the trade of importing slaves from their native
country being much encouraged amongst them,
and the white people and their children so generally living without much labour,
were frequently the subjects of my serious thoughts;
and I saw in these southern provinces so many vices and corruptions,
increased by this trade and this way of life,
that it appeared to me as a dark gloominess hanging over the land;
and though now many willingly run into it,
yet in future the consequences will be grievous to posterity.
I express it as it hath appeared to me, not at once, or twice,
but as a matter fixed on my mind.

Soon after my return home, I felt an increasing concern for Friends on our sea-coast;
and on the 8th day of the eighth month, in the year 1746, with the unity of Friends,
and in company with my beloved friend and neighbour Peter Andrews,
brother to my companion before-mentioned, I set forward,
and visited meetings generally about Salem, Cape May, Great and Little Egg Harbour;
and had meetings at Barnagat, Mannahockin, and Mane-Squan,
and so to the Yearly Meeting at Shrewsbury.
Through the goodness of the Lord way was opened,
and the strength of Divine love was sometimes felt in our assemblies,
to the comfort and help of those who were rightly concerned before him.
We were out twenty-two days, and rode, by computation, three hundred and forty miles.
At Shrewsbury Yearly Meeting,
we met with our dear friends Michael Lightfoot and Abraham Farrington,
who had good service there.

The winter following died my eldest sister, Elizabeth Woolman, jun., of the small-pox,
aged thirty-one years.
She was, from her youth, of a thoughtful disposition,
and very compassionate to her acquaintance in their sickness or distress,
being ready to help as far as she could.
She was dutiful to her parents; one instance whereof follows:--It happened that she,
and two of her sisters, being then near the estate of young women,
had an inclination one first-day after meeting to go on
a visit to some other young women at some distance off,
whose company, I believe, would have done them no good.
They expressed their desire to our parents; who were dissatisfied with the proposal,
and stopped them.
The same day, as my sisters and I were together,
and they talking about their disappointment,
Elizabeth expressed her contentment under it; signifying,
she believed it might be for their good.

A few years after she attained to mature age,
through the gracious visitations of God`'s love,
she was strengthened to live a self-denying exemplary life,
giving herself much to reading and meditation.

The following letter may show, in some degree, her disposition:

Haddonfield, Eleventh Month 1st, 1743.

Beloved brother, John Woolman,

In that love which desires the welfare of all men, I write unto thee.
I received thine, dated 2nd day of the tenth month last, with which I was comforted.
My spirit is bowed with thankfulness that I should be remembered, who am unworthy;
but the Lord is full of mercy,
and his goodness is extended to the meanest of his creation; therefore,
in his infinite love, he hath pitied and spared and showed mercy,
that I have not been cut off nor quite lost; but, at times,
I am refreshed and comforted as with the glimpse of his presence,
which is more to the immortal part, than all which this world can afford: so,
with desires for thy preservation with my own,

I remain Thy affectionate sister,

Elizabeth Woolman, Jun.

The fore part of her illness she was in great sadness and dejection of mind,
of which she told one of her intimate friends, and said,
when I was a young girl I was wanton and airy,
but I thought I had thoroughly repented for it; and added,
I have of late had great satisfaction in meetings.
Though she was thus disconsolate, still she retained a hope,
which was as an anchor to her: and some time after,
the same friend came again to see her, to whom she mentioned her former expressions,
and said, it is otherwise now, for the Lord hath rewarded me seven-fold;
and I am unable to express the greatness of his love manifested to me.
Her disorder appearing dangerous, and our mother being sorrowful, she took notice of it,
and said, dear mother, weep not for me; I go to my God: and many times,
with an audible voice, uttered praise to her Redeemer.

A Friend coming some miles to see her the morning before she died, asked her, how she did?
She answered, I have had a hard night, but shall not have another such, for I shall die,
and it will be well with my soul; and accordingly she died the next evening.

The following ejaculations were found amongst her writings; written, I believe,
at four times:

I+++.+++ Oh! that my head were as waters, and mine eyes as a fountain of tears,
that I might weep day and night, until acquainted with my God.

II. O Lord, that I may enjoy thy presence; or else my time is lost,
and my life a snare to my soul.

III.
O Lord, that I may receive bread from thy table, and that thy grace may abound in me.

IV. O Lord, that I may be acquainted with thy presence,
that I may be seasoned with thy salt, that thy grace may abound in me.

Of late I found drawings in my mind to visit Friends in New England,
and having an opportunity of joining in company with my beloved friend Peter Andrews,
we obtained certificates from our Monthly Meeting,
and set forward on the 16th day of the third month, in the year 1747,
and reached the Yearly Meeting at Long Island;
at which were our friends Samuel Nottingham from England, John Griffith, Jane Hoskins,
and Elizabeth Hudson, from Pennsylvania, and Jacob Andrews, from Chesterfield;
several of whom were favoured in their public exercise; and,
through the goodness of the Lord, we had some edifying meetings.
After this, my companion and I visited Friends on Long Island; and,
through the mercies of God, were helped in the work.

Besides going to the settled meetings of Friends,
we were at a general meeting at Setawket, chiefly made up of other societies,
and had a meeting at Oyster Bay, in a dwelling-house, at which were many people:
at the first of which there was not much said by way of testimony; but it was, I believe,
a good meeting: at the latter, through the springing up of living waters,
it was a day to be thankfully remembered.
Having visited the island, we went over to the main,
taking meetings in our way to Oblong,
Nine-Partners and New Milford.--In these back settlements we met with several people,
who, through the immediate workings of the Spirit of Christ on their minds,
were drawn from the vanities of the world, to an inward acquaintance with him:
they were educated in the way of the Presbyterians.
A considerable number of the youth, members of that Society,
were used to spend their time often together in merriment,
but some of the principal young men of that company being
visited by the powerful workings of the Spirit of Christ,
and thereby led humbly to take up his cross, could no longer join in those vanities;
and as these stood steadfast to that inward convincement,
they were made a blessing to some of their former companions; so that,
through the power of Truth,
several were brought into a close exercise
concerning the eternal wellbeing of their souls.
These young people continued for a time to frequent their public worship;
and besides that, had meetings of their own;
which meetings were a while allowed by their preacher, who sometimes met with them: but,
in time,
their judgment in matters of religion disagreeing with
some of the articles of the Presbyterians,
their meetings were disapproved by that Society;
and such of them who stood firm to their duty, as it was inwardly manifested,
had many difficulties to go through.
Their meetings were in a while dropped; some of them returning to the Presbyterians,
and others, after a time, joined our religious Society.

I had conversation with some of the latter, to my help and edification;
and believe several of them are acquainted with the nature of
that worship which is performed in Spirit and in Truth.
From hence, accompanied by Amos Powel, a Friend from Long Island,
we rode through Connecticut, chiefly inhabited by Presbyterians;
who were generally civil to us, so far as I saw: and after three days riding,
we came amongst Friends in the colony of Rhode Island.
We visited Friends in and about Newport and Dartmouth, and generally in those parts;
and then went to Boston; and proceeded eastward as far as Dover:
then returned to Newport, and not far from thence, we met our friend Thomas Gawthrop,
from England; who was then on a visit to these provinces.
From Newport we sailed to Nantucket; were there nearly a week,
and from thence came over to Dartmouth: and having finished our visit in these parts,
we crossed the sound from New London to Long Island;
and taking some meetings on the island, proceeded homeward;
where we reached the 13th day of the seventh month, in the year 1747,
having rode about fifteen hundred miles, and sailed about one hundred and fifty.

In this journey, I may say in general, we were sometimes in much weakness,
and laboured under discouragements; and at other times,
through the renewed manifestations of Divine love, we had seasons of refreshment,
wherein the power of Truth prevailed.

We were taught, by renewed experience, to labour for an inward stillness;
at no time to seek for words, but to live in the Spirit of Truth,
and utter that to the people which Truth opened in us.
My beloved companion and I belonged to one meeting,
came forth in the ministry near the same time, and were inwardly united in the work:
he was about thirteen years older than I, bore the heaviest burthen,
and was an instrument of the greatest use.

Finding a concern to visit Friends in the lower counties on Delaware,
and on the Eastern Shore of Maryland,
and having an opportunity to join with my well-beloved ancient friend John Sykes,
we obtained certificates, and set ofT the 7th day of the eighth month, in the year 1748;
were at the meetings of Friends in the lower counties,
attended the Yearly Meeting at Little Creek,
and made a visit to most of the meetings on the Eastern Shore;
and so home by the way of Nottingham: were abroad about six weeks; and rode,
by computation, about five hundred and fifty miles.

Our exercise, at times, was heavy; but, through the goodness of the Lord,
we were often refreshed: and I may say, by experience,
"`He is a strong hold in the day of trouble.`"
Though our Society, in these parts, appeared to me to be in a declining condition; yet,
I believe the Lord hath a people amongst them, who labour to serve him uprightly,
but have many difficulties to encounter.

