== Chapter III.

His marriage--The death of his father--His journies into the upper part of New Jersey,
and afterwards into Pennsylvania--Considerations on keeping slaves--Visits
to the families of Friends at several times and places--An epistle from the
General Meeting--Journey to Long Island--Considerations on trading,
and on the use of spirituous liquors and costly apparel--Letter to a Friend.

About this time believing it good for me to settle,
and thinking seriously about a companion, my heart was turned to the Lord,
with desires that he would give me wisdom to proceed therein agreeably to his will;
and He was pleased to give me a well-inclined damsel, Sarah Ellis;
to whom I was married the 18th day of the eighth month, in the year 1749.

In the fall of the year 1750, died my father, Samuel Woolman, with a fever,
aged about sixty years.
In his life-time he manifested much care for us his children,
that in our youth we might learn to fear the Lord;
often endeavouring to imprint in our minds the true principles of virtue,
and particularly to cherish in us a spirit of tenderness, not only towards poor people,
but also towards all creatures of which we had the command.

After my return from Carolina, in the year 1746,
I made some observations on keeping slaves,
which some time before his decease I showed him.
He perused the manuscript, proposed a few alterations,
and appeared well satisfied that I found a concern on that account.

In his last sickness, as I was watching with him one night,
he being so far spent that there was no expectation of his recovery,
but had the perfect use of his understanding, he asked me concerning the manuscript,
whether I expected soon to proceed to take the advice of Friends in publishing it?
and, after some conversation thereon, said,
I have all along been deeply affected with the oppression of the poor negroes; and now,
at last, my concern for them is as great as ever.

He made mention of his end, which he believed was now near; and signified,
that though he was sensible of many imperfections in the course of his life,
yet his experience of the power of Truth,
and of the love and goodness of God from time to time, even until now, was such,
that he had no doubt but that in leaving this life he should enter into one more happy.

The next day his sister Elizabeth came to see him,
and told him of the decease of their sister Ann; who died a few days before.
He said, I reckon sister Ann was free to leave this world?
Elizabeth said, she was: he then said, I also am free to leave it;
and being in great weakness of body said, I hope I shall shortly go to rest.
He continued in a weighty frame of mind, and was sensible until near the last.

On the 2nd day of the ninth month, in the year 1751,
feeling drawings in my mind to visit Friends at the Great Meadows,
in the upper part of West Jersey, with the unity of our Monthly Meeting, I went there;
and had some searching laborious exercise amongst Friends in those parts,
and found peace therein.

In the ninth month of the year 1753, in company with my well-esteemed friend John Sykes,
and with the unity of Friends, I travelled about two weeks,
visiting Friends in Bucks County.
We laboured in the love of the Gospel, according to the measure received; and,
through the mercies of Him, who is strength to the poor who trust in him,
we found satisfaction in our visit.
In the next winter,
way opening to visit Friends`' families within the compass of our Monthly Meeting,
partly by the labours of two Friends from Pennsylvania,
I joined in some part of the work;
having had a desire for some time that it might go forward amongst us.

About this time, a person at some distance lying sick,
his brother came to me to write his will.
I knew he had slaves; and asking his brother,
was told he intended to leave them as slaves to his children.
As writing is a profitable employ,
and as offending sober people was disagreeable to my inclination,
I was straitened in my mind; but as I looked to the Lord,
he inclined my heart to his testimony.
I told the man,
that I believed the practice of continuing slavery to this people was not right,
and had a scruple in my mind against doing writings of that kind:
that though many in our Society kept them as slaves,
still I was not easy to be concerned in it;
and desired to be excused from going to write the will.
I spake to him in the fear of the Lord; and he made no reply to what I said,
but went away: he also had some concern in the practice;
and I thought he was displeased with me.
In this case I had a fresh confirmation,
that acting contrary to present outward interest,
from a motive of Divine love and in regard to truth and righteousness,
and thereby incurring the resentments of people,
opens the way to a treasure better than silver and to a
friendship exceeding the friendship of men.

The manuscript before mentioned having laid by me several years,
the publication of it rested weightily upon me;
and this year I offered it to the revisal of Friends, who,
having examined and made some small alterations in it,
directed a number of copies thereof to be published and dispersed amongst Friends.

In the year 1754,
I found my mind drawn to join in a visit to Friends`'
families belonging to Chesterfield Monthly Meeting;
and having the approbation of our own,
I went to their Monthly Meeting in order to confer with Friends,
and see if way opened for it.
I had conference with some of their members,
the proposal having been opened before in their meeting,
and one Friend agreed to join with me as a companion for a beginning;
but when meeting was ended, I felt great distress of mind, and doubled what way to lake,
or whether to go home and wait for greater clearness.

I kept my distress secret; and going with a Friend to his house,
my desires were to the great Shepherd for his heavenly instruction;
and in the morning I felt easy to proceed on the visit, being very low in my mind:
and as mine eye was turned to the Lord, waiting in families in deep reverence before him,
he was pleased graciously to afford help; so that we had many comfortable opportunities,
and it appeared as a fresh visitation to some young people.
I spent several weeks this winter in the service;
part of which time was employed near home.
In the following winter I was several weeks in the same service;
some part of the time at Shrewsbury, in company with my beloved friend John Sykes;
and have cause humbly to acknowledge, that through the goodness of the Lord, our hearts,
were, at times, enlarged in his love; and strength was given to go through the trials,
which, in the course of our visit, attended us.

From a disagreement between the powers of England and France,
it was now a time of trouble on this continent;
and an epistle to Friends went forth from our General Spring meeting,
which I thought good to give a place in this journal.

An Epistle from our General Spring meeting of ministers and elders,
for Pennsylvania and New Jersey, held at Philadelphia, from the 20th of the third month,
to the 1st of the fourth month, inclusive, 1755; To Friends on the continent of America.

Dear Friends,

In an humble sense of Divine goodness,
and the gracious continuation of God`'s love to his people, we tenderly salute you;
and are at this time therein engaged in mind, that all of us who profess the Truth,
as held forth and published by our worthy predecessors in this latter age of the world,
may keep near to that Life which is the Light of men,
and be strengthened to hold fast the profession of our faith without wavering,
that our trust may not be in man, but in the Lord alone,
who ruleth in the army of heaven, and in the kingdoms of men,
before whom the earth is "`as the dust of the balance,
and her inhabitants as grasshoppers.`"

We, being convinced that the gracious design of the
Almighty in sending his Son into the world,
was to repair the breach made by disobedience, to finish sin and transgression,
that his kingdom might come, and his will be done on earth as it is in heaven,
have found it to be our duty to cease from those
national contests productive of misery and bloodshed,
and submit our cause to Him the Most High,
whose tender love to his children exceeds the most warm affections of natural parents,
and who hath promised to his seed throughout the earth, as to one individual,
"`I will never leave thee, nor forsake thee.`"
And as we, through the gracious dealings of the Lord our God,
have had experience of that work which is carried on "`not by earthly might,
nor by power, but by my Spirit, saith the Lord of Hosts;`" by which operation,
that spiritual kingdom is set up,
which is to subdue and break in pieces all kingdoms that oppose it,
and shall stand for ever; in a deep sense thereof, and of the safety,
stability and peace there is in it, we are desirous that all who profess the Truth,
may be inwardly acquainted with it,
and thereby be qualified to conduct in all parts
of our life as becomes our peaceable profession.
And we trust, as there is a faithful continuance to depend wholly upon the Almighty arm,
from one generation to another,
the peaceable kingdom will gradually be extended "`from sea to sea,
and from the river to the ends of the earth,`" to the
completion of those prophecies already begun,
that "`nation shall not lift up a sword against nation, nor learn war any more.`"

And, dearly beloved friends, seeing we have these promises,
and believe that God is beginning to fulfil them,
let us constantly endeavour to have our minds sufficiently
disentangled from the surfeiting cares of this life,
and redeemed from the love of the world,
that no earthly possessions or enjoyments may bias our judgments,
or turn us from that resignation, and entire trust in God,
to which his blessing is most surely annexed; then may we say, "`Our Redeemer is mighty,
he will plead our cause for us.`"
And if, for the further promoting of his most gracious purposes in the earth,
he should give us to taste of that bitter cup
which his faithful ones have often partaken of;
O that we may be rightly prepared to receive it!

And now, dear friends,
with respect to the commotions and stirrings of
the powers of the earth at this time near us,
we are desirous that none of us may be moved thereat;
"`but repose ourselves in the munition of that Rock,
that all these shakings shall not move,
even in the knowledge and feeling of the eternal power of God,
keeping us subjectly given up to his heavenly will,
and feel it daily to mortify that which remains in any of us which is of this world:
for the worldly part in any, is the changeable part, and that is up and down,
full and empty, joyful and sorrowful, as things go well or ill in this world.
For as the Truth is but one, and many are made partakers of its spirit,
so the world is but one, and many are made partakers of the spirit of it;
and as many as do partake of it, will be straitened and perplexed with it.
But they who are single to the Truth,
waiting daily to feel the life and virtue of it in their hearts,
shall rejoice in the midst of adversity,`" and have to experience with the prophet,
that "`Although the fig tree shall not blossom, neither shall fruit be in the vines;
the labour of the olive shall fail, and the fields shall yield no meat;
the flock shall be cut off from the fold, and there shall be no herd in the stall:
yet will they rejoice in the Lord, and joy in the God of their salvation.`"

If, contrary to this, we profess the Truth,
and not living under the power and influence of it,
are producing fruits disagreeable to the purity thereof,
and trust to the strength of man to support ourselves therein,
our confidence will be vain.
For He, who removed the hedge from his vineyard, and gave it to be trodden under foot,
by reason of the wild grapes it produced, Isaiah 5:5., remains unchangeable: and if,
for the chastisement of wickedness, and further promoting his own glory, he doth arise,
even to shake terribly the earth, who then may oppose him, and prosper!

We remain, in the love of the Gospel, your friends and brethren.

Signed by fourteen Friends.

Scrupling to do writings relative to keeping slaves,
having been a means of sundry small trials to me,
in which I have evidently felt my own will set aside,
I think it good to mention a few of them.
Tradesmen and retailers of goods, who depend on their business for a living,
are naturally inclined to keep the good will of their customers;
nor is it a pleasant thing for young men to be under a
necessity to question the judgment or honesty of elderly men,
and more especially of such who have a fair reputation.
Deep rooted customs, though wrong, are not easily altered;
but it is the duty of every one to be firm in
that which they certainly know is right for them.
A charitable benevolent man, well acquainted with a negro, may, I believe,
under some circumstances, keep him in his family as a servant,
on no other motives than the negro`'s good; but man, as man,
knows not what shall be after him,
nor hath he any assurance that his children will
attain to that perfection in wisdom and goodness,
necessary rightly to exercise such power.
Hence it is clear to me, that I ought not to be the scribe where wills are drawn,
in which some children are made absolute masters over others during life.

About this time, an ancient man of good esteem in the neighbourhood,
came to my house to get his will wrote.
He had young negroes; and I asked him privately, how he purposed to dispose of them?
he told me: I then said, I cannot write thy will without breaking my own peace,
and respectfully gave him my reasons for it.
He signified that he had a choice that I should have written it; but as I could not,
consistent with my conscience, he did not desire it:
and so he got it written by some other person.
A few years after, there being great alterations in his family,
he came again to get me to write his will: his negroes were yet young, and his son,
to whom he intended to give them, was, since he first spoke to me, from a libertine,
become a sober young, man; and he supposed that I would be free, on that account,
to write it.
We had much friendly talk on the subject, and then deferred it: a few days after,
he came again and directed their freedom; and so I wrote his will.

Near the time the last mentioned Friend first spoke to me,
a neighbour received a bad bruise in his body, and sent for me to bleed him;
which being done, he desired me to write his will.
I took notes; and amongst other things,
he told me to which of his children he gave his young negro.
I considered the pain and distress he was in, and knew not how it would end;
so I wrote his will, save only that part concerning his slave,
and carrying it to his bed-side, read it to him; and then told him in a friendly way,
that I could not write any instruments by which my fellow-creatures were made slaves,
without bringing trouble on my own mind.
I let him know that I charged nothing for what I had done;
and desired to be excused from doing the other part in the way he proposed:
we then had a serious conference on the subject and at length,
he agreeing to set her free, I finished his will.

Having found drawings in my mind to visit Friends on Long Island,
after obtaining a certificate from our Monthly Meeting,
I set off on the 12th day of the fifth month, in the year 1756.
When I reached the island,
I lodged the first night at the house of my dear friend Richard Hallet.
Next day being the first of the week, I was at the meeting at Newtown;
in which we experienced the renewed manifestations of the love of Jesus Christ,
to the comfort of the honest-hearted.
I went that night to Flushing; and the next day,
in company with my beloved friend Matthew Franklin, we crossed the ferry at White-stone;
were at three meetings on the main, and then returned to the island,
where I spent the remainder of the week in visiting meetings.
The Lord, I believe, hath a people in those parts,
who are honestly inclined to serve him; but many, I fear,
are too much clogged with the things of this life, and do not come forward,
bearing the cross, in such faithfulness as he calls for.

My mind was deeply engaged in this visit, both in public and private,
and at several places where I was, on observing that they had slaves,
I found myself under a necessity, in a friendly way, to labour with them on that subject;
expressing, as way opened,
the inconsistency of that practice with the purity of the Christian religion,
and the ill effects of it, manifested amongst us.

The latter end of the week, their Yearly Meeting began;
at which were our friends John Scarborough, Jane Hoskins and Susannah Brown,
from Pennsylvania: the public meetings were large,
and measurably favoured with Divine goodness.

The exercise of my mind at this meeting,
was chiefly on account of those who were considered as the foremost rank in the Society:
and in a meeting of ministers and elders, way opened,
so that I expressed in some measure what lay upon me;
and at a time when Friends were met for transacting the affairs of the church,
having sat awhile silent, I felt a weight on my mind, and stood up;
and through the gracious regard of our heavenly Father,
strength was given fully to clear myself of a burthen,
which for some days had been increasing upon me.

Through the humbling dispensations of Divine Providence,
men are sometimes fitted for his service.
The messages of the prophet Jeremiah were so disagreeable to the people,
and so reverse to the spirit they lived in, that he became the object of their reproach;
and in the weakness of nature, thought of desisting from his prophetic office; but,
saith he, "`His word was in my heart as a burning fire shut up in my bones,
and I was weary with forbearing, and could not stay.`"
I saw at this time, that if I was honest in declaring that which Truth opened in me,
I could not please all men; and laboured to be content in the way of my duty,
however disagreeable to my own inclination.
After this I went homeward, taking Woodbridge and Plainfield in my way;
in both which meetings, the pure influence of Divine love was manifested;
in an humbling sense whereof I went home: having been out about twenty-four days,
and rode about three hundred and sixteen miles.

While I was on this journey,
my heart was much affected with a sense of the
state of the churches in our southern provinces;
and believing the Lord was calling me to some further labour amongst them,
I was bowed in reverence before him,
with fervent desires that I might find strength to resign myself to his heavenly will.

Until this year, 1756, I continued to retail goods,
besides following my trade as a tailor;
about which time I grew uneasy on account of my business growing too cumbersome.
I had begun with selling trimmings for garments,
and from thence proceeded to sell cloths and linens; and at length,
having got a considerable shop of goods, my trade increased every year,
and the road to large business appeared open; but I felt a stop in my mind.

Through the mercies of the Almighty, I had, in a good degree,
learned to be content with a plain way of living: I had but a small family;
and on serious consideration,
I believed Truth did not require me to engage in many cumbering affairs.
It had been my general practice to buy and sell things really useful;
things that served chiefly to please the vain mind in people, I was not easy to trade in;
seldom did it; and whenever I did, I found it to weaken me as a Christian.

The increase of business became my burthen;
for though my natural inclination was toward merchandizing,
yet I believed Truth required me to live more free from outward cumber;
and there was now a strife in my mind between the two.
In this exercise my prayers were put up to the Lord, who graciously heard me,
and gave me a heart resigned to his holy will: then I lessened my business;
and as I had opportunity, told my customers of my intentions,
that they might consider what shop to turn to: and in awhile,
wholly laid down merchandize, following my trade as a tailor, myself only,
having no apprentice.
I also had a nursery of apple trees; in which I employed some of my time in hoeing,
grafting, trimming and inoculating.
In merchandize it is the custom, where I lived, to sell chiefly on credit,
and poor people often get in debt; and when payment is expected,
not having wherewith to pay, their creditors often sue for it at law.
Having often observed occurrences of this kind,
I found it good for me to advise poor people to take
such goods as were most useful and not costly.

In the time of trading,
I had an opportunity of seeing that the too liberal use of spirituous liquors,
and the custom of wearing too costly apparel, led some people into great inconveniences;
and these two things appear to be often connected one with the other.
By not attending to that use of things which is consistent with universal righteousness,
there is an increase of labour,
which extends beyond what our heavenly Father intends for us: by great labour,
and often by much sweating, there is, even among such who are not drunkards,
a craving of some liquors to revive the spirits: that,
partly by the luxurious drinking of some, and partly by the drinking of others,
led to it through immoderate labour,
very great quantities of rum are every year expended in our colonies;
the greater part of which we should have no need of,
did we steadily attend to pure wisdom.

Where men take pleasure in feeling their minds elevated with strong drink,
and so indulge their appetite as to disorder their understandings,
neglect their duty as members in a family or in civil society,
and cast off all regard to religion, their case is much to be pitied;
and where such whose lives are for the most part regular,
and whose examples have a strong influence on the minds of others,
adhere to some customs which powerfully draw to the use
of more strong liquor than pure wisdom allows;
this also, as it hinders the spreading of the spirit of meekness,
and strengthens the hands of the more excessive drinkers, is a case to be lamented.

As every degree of luxury hath some connexion with evil;
for those who profess to be disciples of Christ,
and are looked upon as leaders of the people, to have that mind in them,
which was also in Christ, and so stand separate from every wrong way,
is a means of help to the weaker.
As I have sometimes been much spent in the heat, and taken spirits to revive me,
I have found by experience, that in such circumstances the mind is not so calm,
nor so fitly disposed for Divine meditation, as when all such extremes are avoided;
and I have felt an increasing care to attend to that
holy Spirit which sets right bounds to our desires,
and leads those who faithfully follow it,
to apply all the gifts of Divine Providence to the purposes for which they were intended.
Did such who have the care of great estates,
attend with singleness of heart to this heavenly Instructor,
which so opens and enlarges the mind, that men love their neighbours as themselves,
they would have wisdom given them to manage,
without finding occasion to employ some people in the luxuries of life,
or to make it necessary for others to labour too hard;
but for want of steadily regarding this principle of Divine love,
a selfish spirit takes place in the minds of people,
which is attended with darkness and manifold confusions in the world.

Though trading in things useful is an honest employ; yet,
through the great number of superfluities which are bought and sold,
and through the corruption of the times, they who apply to merchandize for a living,
have great need to be well experienced in that precept
which the prophet Jeremiah laid down for his scribe;
"`Seekest thou great things for thyself?
seek them not.`"

In the winter, this year, I was engaged with Friends in visiting families;
and through the goodness of the Lord,
we had oftentimes experience of his heart-tendering presence amongst us.

A copy of a letter written to a Friend.

In this thy late affliction I have found a deep fellow-feeling with thee;
and had a secret hope throughout,
that it might please the Father of mercies to raise thee up,
and sanctify thy troubles to thee;
that thou being more fully acquainted with that way which the world esteems foolish,
may feel the clothing of Divine fortitude,
and be strengthened to resist that spirit which leads
from the simplicity of the everlasting Truth.

We may see ourselves crippled and halting,
and from a strong bias to things pleasant and easy, find an impossibility to advance;
but things impossible with men are possible with God;
and our wills being made subject to his, all temptations are surmountable.

This work of subjecting the will, is compared to the mineral in the furnace; which,
through fervent heat, is reduced from its first principle:
"`He refines them as silver is refined--He shall sit as a refiner,
and purifier of silver.`"
By these comparisons,
we are instructed in the necessity of the melting operation of the hand of God upon us,
to prepare our hearts truly to adore him, and to manifest that adoration,
by inwardly turning away from that spirit, in all its workings, which is not of him.
To forward this work, the all-wise God is sometimes pleased, through outward distress,
to bring us near the gates of death, that life being painful and afflicting,
and the prospect of eternity open before us, all earthly bonds may be loosened,
and the mind prepared for that deep and sacred instruction,
which otherwise would not be received.
If kind parents love their children and delight in their happiness, then He,
who is perfect goodness, in sending abroad mortal contagions,
doth assuredly direct their use.
Are the righteous removed by it, their change is happy;
are the wicked taken away in their wickedness, the Almighty is clear.
Do we pass through with anguish and great bitterness, and yet recover,
he intends that we should be purged from dross, and our ear opened to discipline.

And now on thy part, after thy sore affliction and doubts of recovery,
thou art again restored; forget not Him who hath helped thee,
but in humble gratitude hold fast his instructions,
thereby to shun those by-paths which lead from the firm foundation.
I am sensible of that variety of company, to which one in thy business must be exposed:
I have painfully felt the force of conversation
proceeding from men deeply rooted in an earthly mind,
and can sympathize with others in such conflicts, in that much weakness still attends me.

I find that to be a fool as to worldly wisdom, and commit my cause to God,
not fearing to offend men, who take offence at the simplicity of Truth,
is the only way to remain unmoved at the sentiments of others.

The fear of man brings a snare; by halting in our duty,
and giving back in the time of trial, our hands grow weaker,
our spirits get mingled with the people,
our ears grow dull as to hearing the language of the true Shepherd,
so that when we look at the way of the righteous,
it seems as though it was not for us to follow them.

There is a love clothes my mind while I write, which is superior to all expressions;
and I find my heart open to encourage to a holy emulation,
to advance in Christian firmness.
Deep humility is a strong bulwark; and as we enter into it,
we find safety and true exaltation: the foolishness of God is wiser than man,
and the weakness of God is stronger than man.
Being unclothed of our own wisdom, and knowing the abasement of the creature,
therein we find that power to arise, which gives health and vigor to us.

