== Chapter VI.

His visiting the Quarterly Meetings in Chester county;
and afterwards joining with Daniel Stanton and John Scarborough,
in a visit to such as kept slaves there--Some observations on the
conduct those should maintain who are concerned to speak in meetings
for discipline--Several visits to such who kept slaves:
and to Friends near Salem--Some account of the Yearly Meeting in the year 1759;
and of the increasing concern, in divers provinces,
to labour against buying and keeping slaves--The Yearly Meeting
epistle--His thoughts on the small-pox spreading--and on inoculation.

On the 11th day of the eleventh month, in the year 1758, I set out for Concord;
the Quarterly Meeting heretofore held there, was now,
by reason of a great increase of members, divided into two by the agreement of Friends,
at our last Yearly Meeting.
Here I met with our beloved friends Samuel Spavold and Mary Kirby from England,
and with Joseph White from Bucks county,
who had taken leave of his family in order to go
on a religious visit to Friends in England;
and through Divine goodness, we were favoured with a strengthening opportunity together.

After this meeting I joined with my friends Daniel Stanton and John Scarborough,
in visiting Friends who had slaves;
and at night we had a family meeting at William Trimble`'s, many young people being there;
and it was a precious reviving opportunity.
Next morning we had a comfortable sitting with a sick neighbour;
and thence to the burial of the corpse of a Friend at Uwchland meeting,
at which were many people, and it was a time of Divine favour; after which,
we visited some who had slaves; and at night had a family meeting at a Friend`'s house,
where the channel of Gospel love was opened,
and my mind was comforted after a hard day`'s labour.

The next day we were at Goshen Monthly Meeting:
and thence on the 18th day of the eleventh month, in the year 1758,
attended the Quarterly Meeting at London Grove, it being the first held at that place.
Here we met again with all the before mentioned Friends, and had some edifying meetings.
Near the conclusion of the meeting for business,
Friends were incited to constancy in supporting the testimony of Truth,
and reminded of the necessity which the disciples of
Christ are under to attend principally to his business,
as he is pleased to open it to us;
and to be particularly careful to have our minds redeemed from the love of wealth;
to have our outward affairs in as little room as may be;
that no temporal concerns may entangle our affections,
or hinder us from diligently following the dictates of Truth,
in labouring to promote the pure spirit of meekness and
heavenly-mindedness amongst the children of men,
in these days of calamity and distress;
wherein God is visiting our land with his just judgments.

Each of these Quarterly Meetings were large, and sat nearly eight hours.
Here I had occasion to consider that it is a weighty
thing to speak much in large meetings for business.
Except our minds are rightly prepared, and we clearly understand the case we speak to,
instead of forwarding, we hinder business,
and make more labour for those on whom the burden of the work is laid.

If selfish views or a partial spirit have any room in our minds,
we are unfit for the Lord`'s work; if we have a clear prospect of the business,
and proper weight on our minds to speak,
it behoves us to avoid useless apologies and repetitions.
Where people are gathered from afar,
and adjourning a meeting of business is attended with great difficulty,
it behoves all to be cautious how they detain a meeting;
especially when it has sat six or seven hours,
and Friends have a great distance to ride home.

In the beginning of the twelfth month of the year 1758,
I joined my friends John Sykes and Daniel Stanton, in visiting such who had slaves:
some whose hearts were rightly exercised about them, appeared to be glad of our visit;
but in some places our way was more difficult;
and I often saw the necessity of keeping down to
that root from whence our concern proceeded;
and have cause, in reverent thankfulness, humbly to bow down before the Lord,
who was near to me, and preserved my mind in calmness under some sharp conflicts,
and begat a spirit of sympathy and tenderness in me,
toward some who were grievously entangled by the spirit of this world.

In the first month of the year 1759,
having found my mind drawn to visit some of the more
active members in our Society at Philadelphia,
who had slaves, I met my friend John Churchman there by an agreement;
and we continued about a week in the city.
We visited some that were sick, and some widows and their families;
and the other part of our time was mostly employed in visiting such who had slaves.
It was a time of deep exercise, looking often to the Lord for his assistance; who,
in unspeakable kindness, favoured us with the influence of that spirit,
which crucifies to the greatness and splendour of this world,
and enabled us to go through some heavy labours, in which we found peace.

On the 24th day of the third month, of this year,
I was at our general spring meeting at Philadelphia;
after which I again joined with John Churchman on a visit to some Friends who had slaves,
in Philadelphia; and with thankfulness to our heavenly Father,
I may say that Divine love and a true sympathizing tenderness of heart,
prevailed at times in this service.

Having, at times, perceived a shyness in some Friends of considerable note, towards me,
I found an engagement in Gospel love to pay a visit to one of them;
and as I dwelt under the exercise, I felt a resignedness in my mind to go.
I went and told him in private,
that I had a desire to have an opportunity with him alone; to which he readily agreed:
and then in the fear of the Lord,
things relating to that shyness were searched to the bottom;
and we had a large conference, which, I believe, was of use to both of us;
and am thankful that way was opened for it.

On the 14th day of the sixth month, in the same year,
having felt drawings in my mind to visit Friends about Salem,
and having the approbation of our Monthly Meeting therein,
I attended their Quarterly Meeting, and was out seven days, and at seven meetings;
in some of which I was chiefly silent, and in others,
through the baptizing power of Truth, my heart was enlarged in heavenly love,
and I found a near fellowship with the brethren and sisters,
in the manifold trials attending their Christian progress through this world.

In the seventh month,
I found an increasing concern on my mind to visit some
active members in our Society who had slaves;
and having no opportunity of the company of such who
were named on the minutes of the Yearly Meeting,
I went alone to their houses, and in the fear of the Lord,
acquainted them with the exercise I was under: and thus, sometimes by a few words,
I found myself discharged from a heavy burden.

After this,
our friend John Churchman coming into our province with a view to be at some meetings,
and to join again in the visit to those who had slaves,
I bore him company in the said visit to some active members,
and found inward satisfaction.

At our Yearly Meeting in the year 1759, we had some weighty seasons,
where the power of Truth was largely extended, to the strengthening of the honest minded.
As Friends read over the epistles to be sent to the Yearly Meetings on this continent,
I observed in most of them, both this year and last,
that it was recommended to Friends to labour against buying and keeping slaves;
and in some of them closely treated upon.
As this practice hath long been a heavy exercise to me,
and I have often waded through mortifying labours on that account, and at times,
in some meetings, been almost alone therein,
observing now the increasing concern in our religious Society,
and seeing how the Lord was raising up and qualifying servants for his work,
not only in this respect, but for promoting the cause of Truth in general,
I was humbly bowed in thankfulness before him.
This meeting continued nearly a week; and for several days, in the forepart of it,
my mind was drawn into a deep inward stillness and
being at times covered with the spirit of supplication,
my heart was secretly poured out before the Lord.
Near the conclusion of the meeting for business way opened,
that in the pure flowings of Divine love, I expressed what lay upon me; which,
as it then arose in my mind,
was first to show how deep answers to deep in the hearts of the sincere and upright;
though in their different growths they may not all have attained to
the same clearness in some points relating to our testimony.

I was led to mention the integrity and constancy of many martyrs,
who gave their lives for the testimony of Jesus; and yet, in some points,
held doctrines distinguishable from some which we hold;
and that in all ages where people were faithful to the light
and understanding which the Most High afforded them,
they found acceptance with him; and that now,
though there are different ways of thinking amongst us in some particulars, yet,
if we mutually kept to that spirit and power which crucifies to the world,
which teaches us to be content with things really needful,
and to avoid all superfluities, giving up our hearts to fear and serve the Lord,
true unity may still be preserved amongst us.
If such who were at times under sufferings on account of some scruples of conscience,
kept low and humble, and in their conduct in life manifested a spirit of true charity,
it would be more likely to reach the witness in others,
and be of more service in the church,
than if their sufferings were attended with a contrary spirit and conduct.`"
In this exercise I was drawn into a sympathizing tenderness with the sheep of Christ,
however distinguished one from another in this world;
and the like disposition appeared to spread over others in the meeting.
Great is the goodness of the Lord toward his poor creatures.

An epistle went forth from this Yearly Meeting,
which I think good to give a place in this journal; being as follows:

"`From the Yearly Meeting held at Philadelphia, for Pennsylvania and New Jersey,
from the 22nd day of the ninth month, to the 28th day of the same, inclusive, 1759.

"`To the Quarterly and Monthly Meetings of Friends belonging to the said Yearly Meeting.

"`Dearly beloved friends and brethren,

"`In an awful sense of the wisdom and goodness of the Lord our God,
whose tender mercies have long been continued to us in this land,
we affectionately salute you, with sincere and fervent desires,
that we may reverently regard the dispensations of his providence,
and improve under them.

"`The empires and kingdoms of the earth are subject to his Almighty power.
He is the God of the spirits of all flesh;
and deals with his people agreeably to that wisdom,
the depth whereof is to us unsearchable.
We in these provinces, may say he hath, as a gracious and tender Parent,
dealt bountifully with us, even from the days of our fathers.
It was he who strengthened them to labour through the
difficulties attending the improvement of a wilderness,
and made way for them in the hearts of the natives;
so that by them they were comforted in times of want and distress.
It was by the gracious influences of his holy Spirit,
that they were disposed to work righteousness, and walk uprightly one towards another,
and towards the natives,
and in life and conversation to manifest the excellency of the
principles and doctrines of the Christian religion;
and thereby they retain their esteem and friendship.
Whilst they were labouring for the necessaries of life,
many of them were fervently engaged to promote piety and virtue in the earth,
and to educate their children in the fear of the Lord.

"`If we carefully consider the peaceable measures
pursued in the first settlement of the land,
and that freedom from the desolations of wars, which for a long time we enjoyed,
we shall find ourselves under strong obligations to the Almighty, who,
when the earth is so generally polluted with wickedness,
gave us a being in a part so signally favoured with tranquillity and plenty,
and in which the glad tidings of the Gospel of Christ are so freely published,
that we may justly say with the psalmist,
'`What shall we render unto the Lord for all his benefits`'?

"`Our own real good,
and the good of our posterity in some measure depend on the part we act;
and it nearly concerns us to try our foundations impartially.
Such are the different rewards of the just and unjust in a future state,
that to attend diligently to the dictates of the spirit of Christ,
to devote ourselves to his service and engage fervently in his cause,
during our short stay in this world,
is a choice well becoming a free intelligent creature.
We shall thus clearly see and consider that the
dealings of God with mankind in a national capacity,
as recorded in holy writ, sufficiently evidence the truth of that saying,
'`it is righteousness which exalteth a nation;`' and though he doth not at all
times suddenly execute his judgments on a sinful people in this life,
yet we see by many instances, that where '`men follow lying vanities,
they forsake their own mercies.`'
As a proud selfish spirit prevails and spreads among a people, so partial judgment,
oppression, discord, envy and confusions increase,
and provinces and kingdoms are made to drink the
cup of adversity as a reward of their own doings.
Thus the inspired prophet, reasoning with the degenerated Jews, saith,
'`Thine own wickedness shall correct thee, and thy backslidings shall reprove thee:
know therefore, that it is an evil thing and bitter,
that thou hast forsaken the Lord thy God, and that my fear is not in thee,
saith the Lord God of hosts.`'

"`The God of our fathers, who hath bestowed on us many benefits,
furnished a table for us in the wilderness,
and made the deserts and solitary places to rejoice,
doth now mercifully call upon us to serve him more faithfully.
We may truly say with the prophet, '`it is his voice which crieth to the city,
and men of wisdom see his name: They regard the rod,
and him who hath appointed it.`'--People who look chiefly at things outward,
too little consider the original cause of the present troubles;
but such who fear the Lord, and think often upon his name,
they see and feel that a wrong spirit is spreading among the inhabitants of our country;
that the hearts of many are waxed fat, and their ears dull of hearing;
that the Most High, in his visitations to us, instead of calling,
lifteth up his voice and crieth; he crieth to our country,
and his voice waxeth louder and louder.
In former wars between the English and other nations,
since the settlement of our provinces,
the calamities attending them have fallen chiefly on other places,
but of late they have reached our borders.
Many of our fellow subjects have suffered on and near our frontiers,
some have been slain in battle, some killed in their houses, and some in their fields,
some wounded and left in great misery,
and others separated from their wives and little children,
who have been carried captives among the Indians.
We have seen men and women, who have been witnesses of these scenes of sorrow,
and being reduced to want, have come to our houses asking relief.
It is not long since it was the case of many young men
in one of these provinces to be drafted,
in order to be taken as soldiers.
Some were at that time in great distress,
and had occasion to consider that their lives had been too little
conformable to the purity and spirituality of that religion which we profess,
and found themselves too little acquainted with that inward humility,
in which true fortitude to endure hardness for the Truth`'s sake is experienced.
Many parents were concerned for their children,
and in that time of trial were led to consider,
that their care to get outward treasure for them,
had been greater than their care for their settlement
in that religion which crucifieth to the world,
and enableth to bear a clear testimony to the peaceable government of the Messiah.
These troubles are removed, and for a time we are released from them.

"`Let us not forget that '`the Most High hath his way in the deep,
in clouds and in thick darkness`'--that it is his voice
which crieth to the city and to the country;
and oh! that these loud and awakening cries, may have a proper effect upon us,
that heavier chastisement may not become necessary!
For though things, as to the outward, may for a short time afford a pleasing prospect;
yet while a selfish spirit, that is not subject to the cross of Christ,
continueth to spread and prevail,
there can be no long continuance in outward peace and tranquillity.
If we desire an inheritance incorruptible,
and to be at rest in that state of peace and happiness, which ever continues;
if we desire in this life to dwell under the
favour and protection of that Almighty Being,
whose habitation is in holiness, whose ways are all equal and whose anger is now kindled,
because of our backslidings;
let us then awfully regard these beginnings of his sore judgments,
and with abasement and humiliation turn to him whom we have offended.

"`Contending with one equal in strength, is an uneasy exercise;
but if the Lord becomes our enemy, if we persist to contend with him who is omnipotent,
our overthrow will be unavoidable.

"`Do we feel an affectionate regard to posterity;
and are we employed to promote their happiness?
Do our minds in things outward, look beyond our own dissolution;
and are we contriving for the prosperity of our children after us?
Let us then like wise builders, lay the foundation deep;
and by our constant uniform regard to inward piety and virtue,
let them see that we really value it.
Let us labour in the fear of the Lord, that their innocent minds, while young and tender,
may be preserved from corruption; that as they advance in age,
they may rightly understand their true interest,
may consider the uncertainty of temporal things, and above all,
have their hope and confidence firmly settled in the
blessing of that Almighty Being who inhabits eternity,
and preserves and supports the world.

"`In all our cares about worldly treasures, let us steadily bear in mind,
that riches possessed by children who do not truly serve God,
are likely to prove snares that may grievously entangle
them in that spirit of selfishness and exaltation,
which stands in opposition to real peace and happiness;
and renders those enemies to the cross of Christ, who submit to the influence of it.

"`To keep a watchful eye towards real objects of charity,
to visit the poor in their lonesome dwelling-places, to comfort those who,
through the dispensations of Divine Providence,
are in strait and painful circumstances in this life,
and steadily to endeavour to honour God with our substance,
from a real sense of the love of Christ influencing our minds thereto,
is more likely to bring a blessing to our children,
and will afford more satisfaction to a Christian favoured with plenty,
than an earnest desire to collect much wealth to leave behind us;
for '`here we have no continuing city;`' may we
therefore diligently seek one that is to come,
whose builder and maker is God.

"`'`Finally, brethren, whatsoever things are true, whatsoever things are just,
whatsoever things are pure, whatsoever things are lovely,
whatsoever things are of good report; if there be any virtue, if there be any praise,
think on these things and do them, and the God of peace shall be with you.`'

"`Signed by appointment, and on behalf of our said meeting, by seven Friends.`"

On the 28th day of the eleventh month, in the year 1759,
I was at the Quarterly Meeting in Bucks county.
This day being the meeting of ministers and elders,
my heart was enlarged in the love of Jesus Christ;
and the favour of the Most High was extended to us in that and the ensuing meeting.

I had conversation at my lodging, with my beloved friend Samuel Eastburn;
who expressed a concern to join in a visit to
some Friends in that county who had negroes;
and as I had felt a draught in my mind to that work in the said county,
I came home and put things in order.
On the 11th day of the twelfth month following, I went over the river;
and on the next day was at Buckingham meeting; where,
through the descendings of heavenly dew,
my mind was comforted and drawn into near unity with the flock of Jesus Christ.

Entering upon this visit appeared weighty; and before I left home my mind was often sad;
under which exercise I felt at times, the Holy Spirit which helps our infirmities;
through which, in private, my prayers were at times put up to God,
that he would be pleased to purge me from all selfishness,
that I might be strengthened to discharge my duty faithfully,
how hard soever to the natural part.
We proceeded on the visit in a weighty frame of spirit,
and went to the houses of the most active members throughout the county who had negroes;
and through the goodness of the Lord,
my mind was preserved in resignation in times of trial,
and though the work was hard to~ nature,
yet through the strength of that love which is stronger than death,
tenderness of heart was often felt amongst us in our visits,
and we parted from several families with greater satisfaction than we expected.

We visited Joseph White`'s family, he being in England;
had also a family sitting at the house of an elder who bore us company,
and was at Makefield on a first-day;
at all which times my heart was truly thankful to the Lord,
who was graciously pleased to renew his loving kindness to us, his poor servants,
uniting us together in his work.

In the winter of this year, the small-pox being in our town, and many being inoculated,
of which a few died, some things were opened in my mind, which I wrote as follow:

The more fully our lives are conformable to the will of God, the better it is for us.
I have looked on the small-pox as a messenger from the Almighty,
to be an assistant in the cause of virtue,
and to incite us to consider whether we employ our time in such
things only as are consistent with perfect wisdom and goodness.

Building houses suitable to dwell in, for ourselves and our creatures;
preparing clothing suitable for the climate and season, and food convenient,
are duties incumbent on us: and under these general heads, are many branches of business,
in which we may venture health and life, as necessity may require.

This disease being in a house, and my business calling me to go near it,
it incites me to think, whether this business is a real indispensable duty;
whether it is not in conformity to some custom which would be better laid aside;
or whether it does not proceed from too eager a pursuit after outward treasure.
If the business before me springs not from a clear understanding,
and a regard to that use of things which perfect wisdom approves;
to be brought to a sense of it, and stopped in my pursuit, is a kindness;
for when I proceed to business without some evidence of duty, I have found by experience,
that it tends to weakness.

If I am so situated that there appears no probability of missing the infection,
it tends to make me think, whether my manner of life in things outward,
has nothing in it which may unfit my body to receive
this messenger in a way the most favourable to me.
Do I use food and drink in no other sort, and in no other degree,
than was designed by Him who gave these creatures for our sustenance?
Do I never abuse my body by inordinate labour,
striving to accomplish some end which I have unwisely proposed?
Do I use action enough in some useful employ?
Or do I sit too much idle, while some persons who labour to support me,
have too great a share of it?
If in any of these things I am deficient, to be incited to consider it, is a favour to me.

Employment is necessary in social life; and this infection which often proves mortal,
incites me to think, whether these social acts of mine are real duties:
if I go on a visit to the widows and fatherless,
do I go purely on a principle of charity, free from any selfish views?
If I go to a religious meeting, it puts me on thinking,
whether I go in sincerity and in a clear sense of duty;
or whether it is not partly in conformity to custom,
or partly from a sensible delight which my animal
spirits feel in the company of other people;
and whether to support my reputation as a religious man, has no share in it.

Do affairs relating to civil society, call me near this infection?
If I go, it is at the hazard of my health and life; and it becomes me to think seriously,
whether love to Truth and righteousness is the motive of my attending;
whether the manner of proceeding is altogether equitable; or whether ought of narrowness,
party interest, respect to outward dignities, names or distinctions among men,
stains the beauty of those assemblies, and renders it doubtful in point of duty,
whether a disciple of Christ ought to attend as a member united to the body or not.

Whenever there are blemishes which remain for a series of time,
that which is a means of stirring us up to look attentively on these blemishes,
and to labour according to our capacities,
to have health and soundness restored in our country,
we may justly account a kindness from our gracious Father, who appointed that mean.

The care of a wise and good man for his only son,
is inferior to the regard of the great Parent of the universe for his creatures.
He hath the command of all the powers and operations in nature;
and "`doth not afflict willingly,
nor grieve the children of men:`" chastisement is intended for instruction,
and instruction being received by gentle chastisement, greater calamities are prevented.

By an earthquake, hundreds of houses are sometimes shaken down in a few minutes,
and multitudes of people perish suddenly;
and many more being crushed and bruised in the ruins of the buildings,
pine away and die in great misery.

By the breaking in of enraged, merciless armies,
flourishing countries have been laid waste,
great numbers of people have perished in a short time,
and many more been pressed with poverty and grief.

By the pestilence, people have died so fast in a city, that through fear,
grief and confusion, those in health have found great difficulty in burying the dead,
even without coffins.

By famine, great numbers of people, in some places,
have been brought to the utmost distress,
and pined away for want of the necessaries of life.
Thus, where the kind invitations and gentle chastisements of
a gracious God have not been attended to,
his sore judgments have at times, been poured out upon people.

While some rules approved in civil society, and conformable to human policy, so called,
are distinguishable from the purity of Truth and righteousness; while many,
professing Truth, are declining from that ardent love and heavenly mindedness,
which were amongst the primitive followers of Jesus Christ,
it is a time for us to attend diligently to the intent of every chastisement,
and consider the most deep and inward design of them.

The Most High doth not often speak with an outward voice to our outward ears;
but if we humbly meditate on his perfections,
consider that he is perfect wisdom and goodness,
and that to afflict his creatures to no purpose, would be utterly averse to his nature,
we shall hear and understand his language,
both in his gentle and more heavy chastisements; and take heed that we do not,
in the wisdom of this world, endeavour to escape his hand by means too powerful for us.

Had he endowed men with understanding to hinder
the force of this disease by innocent means,
which had never proved mortal nor hurtful to our bodies,
such discovery might be considered as the period of chastisement by this distemper,
where that knowledge extended.
But as life and health are his gifts, and not to be disposed of in our own wills,
to take upon us, when in health, a distemper of which some die,
requires great clearness of knowledge, that it is our duty to do so.

