== Chapter VIII.

His visits to Pennsylvania,
Shrewsbury and Squan--Publishes the second part of his Considerations on
keeping negroes--The grounds of his appearing in some respects singular in
his dress--Visits the families of Friends of Ancocas and Mount Holly
meetings--Visit to the Indians at Wehaloosing on the river Susquehanna.

Having felt my mind drawn toward a visit to a few meetings in Pennsylvania,
I was very desirous to be rightly instructed as to the time of setting off.
On the 10th day of the fifth month, 1761, being the first-day of the week,
I went to Haddonfield meeting, concluding to seek for heavenly instruction,
and to come home or go on, as I might then believe best for me; and there,
through the springing up of pure love, I felt encouragement, and so crossed the river.
In this visit I was at two Quarterly and three Monthly Meetings;
and in the love of Truth,
felt my way open to labour with some noted Friends who kept negroes;
and as I was favoured to keep to the root,
and endeavoured to discharge what I believed was required of me,
I found inward peace therein from time to time; and thankfulness of heart to the Lord,
who was graciously pleased to be a guide to me.

In the eighth month, 1761,
having felt drawings in my mind to visit Friends in and about Shrewsbury, I went there,
and was at their Monthly Meeting, and the meeting on first-day; had a meeting at Squan,
and another at Squankum; and as way opened,
had conversation with some noted Friends concerning their slaves:
and I returned home in a thankful sense of the goodness of the Lord.

From the care I had felt growing in me for some years,
I wrote Considerations on keeping Negroes, part the second;
which was printed during this year 1762.
When the overseers of the press had done with it, they offered to get a number printed,
to be paid for out of the Yearly Meeting stock, and to be given away;
but I being most easy to publish them at my own expense,
and offering my reasons they appeared satisfied.

This stock is the contribution of the members of our religious Society in general;
amongst whom are some who keep negroes, and being inclined to continue them in slavery,
are not likely to be satisfied with those books being spread
amongst a people where many of the slaves are taught to read,
and especially at their expense; and such receiving them as a gift, often conceal them.

But as they who make a purchase, generally buy that which they have a mind for,
I believed it best to sell them; expecting, by that means,
they would more generally be read with attention.
Advertisements being signed by order of the overseers of the press,
directed to be read in Monthly Meetings of business within our own Yearly Meeting,
informing where the books were,
and that the price was no more than the cost of printing and binding them;
many were taken off in our parts; some I sent to Virginia, some to New York,
and some to Newport, to my acquaintance there; and some I kept,
expecting to give part of them away, where there appeared a prospect of service.

In my youth I was used to hard labour; and though I was middling healthy,
yet my nature was not fitted to endure so much as many others.
Being often weary, I was prepared to sympathize with those whose circumstances in life,
as free men, required constant labour to answer the demands of their creditors;
and with others under oppression.
In the uneasiness of body, which I have many times felt by too much labour,
not as a forced but a voluntary oppression,
I have often been excited to think on the original cause of
that oppression which is imposed on many in the world.
During the latter part of the time wherein I laboured on our plantation,
my heart through the fresh visitations of heavenly love, being often tender;
and my leisure time frequently spent in reading
the life and doctrines of our blessed Redeemer,
the account of the sufferings of martyrs,
and the history of the first rise of our Society;
a belief was gradually settled in my mind, that if such who have great estates,
generally lived in that humility and plainness which belongs to a Christian life,
and laid much easier rents and interests on their lands and monies,
and thus led the way to a right use of things,
so great a number of people might be employed in things useful,
that labour both for men and other creatures would need
to be no more than an agreeable employ;
and divers branches of business which serve chiefly to
please the natural inclinations of our minds,
and which, at present, seem necessary to circulate that wealth which some gather,
might in this way of pure wisdom be discontinued.
As I have thus considered these things, a query at times hath arisen;
Do I in all my proceedings,
keep to that use of things which is agreeable to universal righteousness?
And then there hath some degree of sadness at times come over me;
because I accustomed myself to some things which occasioned
more labour than I believe Divine wisdom intends for us.

From my early acquaintance with Truth, I have often felt an inward distress,
occasioned by the striving of a spirit in me,
against the operation of the heavenly principle;
and in this circumstance have been affected with a sense of my own wretchedness,
and in a mourning condition felt earnest longings for that Divine help,
which brings the soul into true liberty.
Sometimes in this state, retiring into private places,
the spirit of supplication hath been given me; and under a heavenly covering,
I have asked my gracious Father to give me a heart in
all things resigned to the direction of his wisdom;
and in uttering language like this,
the thoughts of my wearing hats and garments dyed with a dye hurtful to them,
have made lasting impressions on me.

In visiting people of note in the Society who had slaves,
and labouring with them in brotherly love on that account, I have seen,
and the sight has affected me,
that a conformity to some customs distinguishable from pure wisdom, has entangled many;
and that the desire of gain to support these customs, greatly opposed the work of Truth.
Sometimes when the prospect of the work before me has been such,
that in bowedness of spirit I have been drawn into retired places,
and besought the Lord with tears that he would take me wholly under his direction,
and show me the way in which I ought to walk; it has revived with strength of conviction,
that if I would be his faithful servant, I must in all things attend to his wisdom,
and be teachable; and cease from all customs contrary thereto,
however used amongst religious people.

As he is the perfection of power, of wisdom and of goodness,
so I believe he hath provided that so much labour shall
be necessary for men`'s support in this world,
as would, being rightly divided, be a suitable employment of their time;
and that we cannot go into superfluities,
or grasp after wealth in a way contrary to his wisdom,
without having connexion with some degree of oppression,
and with that spirit which leads to self-exaltation and strife,
and which frequently brings calamities on countries,
by parties contending about their claims.

Being thus fully convinced,
and feeling an increasing desire to live in the spirit of peace;
being often sorrowfully affected in thinking on the
unquiet spirit in which wars are generally carried on,
and with the miseries of many of my fellow-creatures engaged therein;
some suddenly destroyed; some wounded, and after much pain remain cripples;
some deprived of all their outward substance and reduced to want;
and some carried into captivity--thinking often on these things,
the use of hats and garments dyed with a dye hurtful to them,
and wearing more clothes in summer than are useful, grew more uneasy to me;
believing them to be customs which have not their foundation in pure wisdom.
The apprehension of being singular from my beloved friends, was a strait upon me;
and thus I remained in the use of some things contrary to my judgment.

On the 31st day of the fifth month, 1761, I was taken ill of a fever;
and after having it near a week, I was in great distress of body.
And one day there was a cry raised in me,
that I might understand the cause why I was afflicted, and improve under it.
My conformity to some customs which I believed were not right,
was then brought to my remembrance; and in the continuation of the exercise,
I felt all the powers in me yield themselves up into the hands of Him who gave me being;
and was made thankful that he had taken hold of me by his chastisement.
Feeling the necessity of further purifying, there was now no desire in me for health,
until the design of my correction was answered;
and thus I lay in abasement and brokenness of spirit,
and as I felt a sinking down into a calm resignation, so I felt as in an instant,
an inward healing in my nature; and from that time forward I grew better.

Though I was thus settled in mind in relation to hurtful dyes,
I felt easy to wear my garments heretofore made; and so continued about nine months.
Then I thought of getting a hat the natural colour of the fur;
but the apprehension of being looked upon as one affecting singularity,
felt uneasy to me.
Here I had occasion to consider, that things though small in themselves,
being clearly enjoined by Divine authority, became great things to us;
and I trusted that the Lord would support me in the trials that might attend singularity,
while that singularity was only for his sake.
On this account I was under close exercise of mind in
the time of our General Spring Meeting in 1762,
greatly desiring to be rightly directed;
and being deeply bowed in spirit before the Lord,
I was made willing to submit to what I apprehended was required of me;
and when I returned home, got a hat of the natural colour of the fur.

In attending meetings this singularity was a trial upon me,
and more especially at this time,
white hats being used by some who were fond of following the changeable modes of dress;
and as some Friends who knew not on what motives I wore it, carried shy of me,
I felt my way for a time shut up in the exercise of the ministry.
In this condition, my mind being turned toward my heavenly Father,
with fervent cries that I might be preserved to
walk before him in the meekness of wisdom,
my heart was often tender in meetings; and I felt inward consolation,
which to me was very precious under those difficulties.

I had several dyed garments fit for use,
which I believed it best to wear till I had occasion for new ones.
Some Friends were apprehensive that my wearing
such a hat savoured of an affected singularity;
and such who spoke with me in a friendly way, I generally informed in a few words,
that I believed my wearing it was not in my own will.
I had at times been sensible that a superficial friendship had been dangerous to me;
and many Friends being now uneasy with me,
I had an inclination to acquaint some with the manner of my being led into these things;
yet upon a deeper thought I was for a time most easy to omit it,
believing the present dispensation was profitable; and trusting that if I kept my place,
the Lord in his own time would open the hearts of Friends toward me:
since which I have had cause to admire his goodness and loving-kindness,
in leading about and instructing,
and opening and enlarging my heart in some of our meetings.

In the eleventh month of the year 1762,
feeling an engagement of mind to visit some families in Mansfield,
I joined my beloved friend Benjamin Jones,
and we spent a few days together in that service.
In the second month, 1763, I joined in company with Elizabeth Smith and Mary Noble,
on a visit to the families of Friends at Ancocas; in both which visits,
through the baptizing power of Truth, the sincere labourers were often comforted,
and the hearts of Friends opened to receive us.
In the fourth month following,
I accompanied some Friends in a visit to the families of Friends in Mount Holly;
in which my mind was often drawn into an inward awfulness,
wherein strong desires were raised for the everlasting welfare of my fellow-creatures;
and through the kindness of our heavenly Father, our hearts were at times enlarged,
and Friends invited in the flowings of Divine love,
to attend to that which would settle them on the sure foundation.

Having many years felt love in my heart toward the natives of this land,
who dwell far back in the wilderness,
whose ancestors were the owners and possessors of the land where we dwell;
and who for a very small consideration, assigned their inheritance to us;
and being at Philadelphia in the eighth month, 1761,
on a visit to some Friends who had slaves,
I fell in company with some of those natives who lived
on the east branch of the river Susquehanna,
at an Indian town called Wehaloosing, two hundred miles from Philadelphia.
In conversation with them by an interpreter,
as also by observations on their countenances and conduct,
I believed some of them were measurably acquainted with that Divine
power which subjects the rough and froward will of the creature;
and at times I felt inward drawings toward a visit to
that place of which I told none except my dear wife,
until it came to some ripeness.
In the winter of 1762, I laid it before Friends at our Monthly and Quarterly,
and afterwards at our General Spring Meeting; and having the unity of Friends,
and being thoughtful about an Indian pilot,
there came a man and three women from a little
beyond that town to Philadelphia on business.
Being informed thereof by letter, I met them in town in the fifth month, 1763;
and after some conversation, finding they were sober people,
with the concurrence of Friends in that place,
I agreed to join them as companions in their return.
On the 7th day of the sixth month following, we appointed to meet at Samuel Foulk`'s,
at Richland, in Bucks county.
As this visit felt weighty,
and was performed at a time when travelling appeared perilous,
so the dispensations of Divine Providence in preparing my mind for it,
have been memorable; and I believe it good for me to give some hints thereof.

After I had given up to go,
the thoughts of the journey were often attended with unusual sadness;
in which times my heart was frequently turned to the
Lord with inward breathings for his heavenly support,
that I might not fail to follow him wheresoever he might lead me.
Being at our Youths`' meeting at Chesterfield,
about a week before the time I expected to set off,
I was there led to speak on that prayer of our Redeemer to his Father;
"`I pray not that thou shouldst take them out of the world,
but that thou shouldst keep them from the evil.`"
In attending to the pure openings of Truth,
I had to mention what he elsewhere said to his Father;
"`I know that thou hearest me at all times:`" so
that as some of his followers kept their places,
and as his prayer was granted, it followed necessarily that they were kept from evil.
As some of those met with great hardships and afflictions in this world,
and at last suffered death by cruel men;
it appears that whatsoever befalls men while they live in pure obedience to God,
as it certainly works for their good,
so it may not be considered an evil as it relates to them.
As I spoke on this subject, my heart was much tendered, and great awfulness came over me;
and on the first-day of the next week at our own afternoon meeting,
my heart being enlarged in love,
I was led to speak on the care and protection of the Lord over his people,
and to make mention of that passage where a band of
Assyrians endeavouring to take the prophet captive,
were disappointed; and how the psalmist said,
"`the angel of the Lord encampeth round about them that fear him.`"
I parted from Friends in true love and tenderness,
expecting the next morning to proceed on my journey; and being weary, went early to bed:
and after I had been asleep a short time, I was awaked by a man calling at my door;
and arising, was invited to meet some Friends at a public house in our town,
who came from Philadelphia so late that Friends were generally gone to bed.
These Friends informed me that an express arrived the last morning from Pittsburgh,
and brought news that the Indians had taken a fort from the English westward,
and slain and scalped English people in divers places, some near Pittsburgh;
and that some elderly Friends in Philadelphia
knowing the time of my expecting to set off,
had conferred together, and thought good to inform me of these things before I left home,
that I might consider them and proceed as I believed best.

I went to bed again, and told not my wife till morning.
My heart was turned to the Lord for his heavenly instruction;
and it was an humbling time to me.
When I told my dear wife, she appeared to be deeply concerned about it;
but in a few hours time,
my mind became settled in a belief that it was my duty to proceed on my journey;
and she bore it with a good degree of resignation.
In this conflict of spirit,
there were great searchings of heart and strong cries to the Lord,
that no motion might be in the least degree attended to,
but that of the pure Spirit of Truth.

The subjects before mentioned, on which I had so lately spoken in public,
were now very fresh before me; and I was brought inwardly to commit myself to the Lord,
to be disposed of as he saw best.
I took leave of my family and neighbours in much bowedness of spirit,
and went to our Monthly Meeting at Burlington; and after taking leave of Friends there,
I crossed the river accompanied by my friends Israel and John Pemberton;
and parting the next morning with Israel, John bore me company to Samuel Foulk`'s;
where I met the before mentioned Indians, and we were glad to see each other.
Here my friend Benjamin Parvin met me, and proposed joining as a companion,
we having passed some letters before on the subject;
and now on his account I had a sharp trial; for as the journey appeared perilous,
I thought if he went chiefly to bear me company, and we should be taken captive,
my having been the means of drawing him into these difficulties,
would add to my own afflictions.
So I told him my mind freely, and let him know that I was resigned to go alone;
but after all, if he really believed it to be his duty to go on,
I believed his company would be very comfortable to me.
It was indeed a time of deep exercise,
and Benjamin appeared to be so fastened to the visit,
that he could not be easy to leave me; so we went on,
accompanied by our friends John Pemberton and William Lightfoot, of Pikeland,
and lodged at Bethlehem.
Parting there with John, William and we went forward on the 9th day of the sixth month,
and got lodging on the floor of a house about five miles from Fort Allen.
Here we parted with William.

At this place we met with an Indian trader, lately come from Wyoming;
and in conversation with him,
I perceived that white people often sell rum to the Indians,
which I believe is a great evil; first,
they being thereby deprived of the use of their reason,
and their spirits violently agitated, quarrels often arise which end in mischief;
and the bitterness and resentments occasioned hereby, are frequently of long continuance.
Again, their skins and furs, gotten through much fatigue and hard travels in hunting,
with which they intended to buy clothing, when they become intoxicated,
they often sell at a low rate for more rum; and afterward,
when they suffer for want of the necessaries of life,
are angry with those who for the sake of gain, took the advantage of their weakness.
Of this their chiefs have often complained, at their treaties with the English.
Where cunning people pass counterfeits,
and impose that on others which is good for nothing, it is considered as a wickedness;
but to sell that to people which woeknow does them harm,
and which often works their ruin, for the sake of gain,
manifests a hardened and corrupt heart;
and is an evil which demands the care of all true lovers of virtue to suppress.
While my mind this evening was thus employed,
I also remembered that the people on the frontiers, among whom this evil is too common,
are often poor; who venture to the outside of a colony,
that they may live more independently of such who are wealthy,
who often set high rents on their land.
I was renewedly confirmed in a belief,
that if all our inhabitants lived according to sound wisdom,
labouring to promote universal love and righteousness,
and ceased from every inordinate desire after wealth,
and from all customs which are tinctured with luxury,
the way would be easy for the inhabitants, though much more numerous than at present,
to live comfortably on honest employments,
without that temptation they are often under of being drawn into schemes to
make settlements on lands which have not been purchased of the Indians,
or of applying to the wicked practice of selling rum to them.

On the 10th day of the month we set out early in the morning,
and crossed the western branch of Delaware, called the Great Lehigh, near Fort Allen;
the water being high, we went over in a canoe.
Here we met an Indian, and had some friendly conversation with him,
and gave him some biscuit; and he having killed a deer,
gave the Indians with us some of it.
After travelling some miles,
we met several Indian men and women with a cow and horse and some household goods,
who were lately come from their dwelling at Wyoming,
and going to settle at another place; we made them some small presents;
and some of them understanding English,
I told them my motive in coming into their country; with which they appeared satisfied.

One of our guides talking a while with an ancient woman concerning us,
the poor old woman came to my companion and me,
and took her leave of us with an appearance of sincere affection.
So going on we pitched our tent near the banks of the same river,
having laboured hard in crossing some of those mountains called the Blue Ridge;
and by the roughness of the stones and the cavities between them,
and the steepness of the hills, it appeared dangerous: but we were preserved in safety,
through the kindness of Him whose works in those mountainous deserts appeared awful;
toward whom my heart was '`turned during this day`'s travel.

Near our tent, on the sides of large trees peeled for that purpose,
were various representations of men going to and returning from the wars,
and of some killed in battle.
This being a path heretofore used by warriors;
and as I walked about viewing those Indian histories,
which were painted mostly in red but some in black,
and thinking on the innumerable afflictions which the proud,
fierce spirit produceth in the world; thinking on the toils and fatigues of warriors,
travelling over mountains and deserts;
thinking on their miseries and distresses when wounded far from home by their enemies;
and of their bruises and great weariness in
chasing one another over the rocks and mountains;
and of their restless, unquiet state of mind, who live in this spirit;
and of the hatred which mutually grows up in the minds of the
children of those nations engaged in war with each other:
during these meditations,
the desire to cherish the spirit of love and peace amongst these people,
arose very fresh in me.
This was the first night that we lodged in the woods;
and being wet with travelling in the rain, the ground, our tent,
and the bushes which we purposed to lay under our blankets also wet,
all looked discouraging;
but I believed that it was the Lord who had thus far brought me forward,
and that he would dispose of me as he saw good, and therein I felt easy.
We kindled a fire with our tent open to it; and with some bushes next the ground,
and then our blankets, we made our bed; and lying down, got some sleep:
and in the morning feeling a little unwell, I went into the river; the water was cold,
but soon after I felt fresh and well.

The 11th day of the sixth month, the bushes being wet,
we tarried in our tent till about eight o`'clock; when going on,
crossed a high mountain supposed to be upward of four miles over;
the steepness on the north side exceeding all the others: we also crossed two swamps;
and it raining near night, we pitched our tent and lodged.

About noon,
on our way we were overtaken by one of the Moravian brethren going to Wehaloosing,
and an Indian man with him who could talk English;
and we being together while our horses eat grass, had some friendly conversation;
but they travelling faster than we, soon left us.
This Moravian, I understood had spent some time this spring at Wehaloosing;
and was by some of the Indians, invited to come again.

The 12th day of the sixth month and first of the week, it being rainy,
we continued in our tent;
and here I was led to think on the nature of the exercise which hath attended me.
Love was the first motion,
and thence a concern arose to spend some time with the Indians,
that I might feel and understand their life and the spirit they live in,
if haply I might receive some instruction from them,
or they be in any degree helped forward by my
following the leadings of Truth amongst them.
As it pleased the Lord to make way for my going at a
time when the troubles of war were increasing,
and by reason of much wet weather, travelling was more difficult than usual,
I looked upon it as a more favourable opportunity to season my mind,
and bring me into a nearer sympathy with them:
and as mine eye was to the great Father of mercies,
humbly desiring to learn what his will was concerning me, I was made quiet and content.

Our guide`'s horse, though hoppled, went away in the night; and after finding our own,
and searching some time for him,
his footsteps were discovered in the path going back again,
whereupon my kind companion went off in the rain,
and after about seven hours returned with him: we lodged here again;
tying up our horses before we went to bed, and loosing them to feed about break of day.

On the 13th day of the sixth month, the sun appearing, we set forward;
and as I rode over the barren hills,
my meditations were on the alteration in the circumstances of
the natives of this land since the coming in of the English.
The lands near the sea, are conveniently situated for fishing;
the lands near the rivers where the tides flow, and some above,
are in many places fertile, and not mountainous; while the running of the tides,
makes passing up and down easy with any kind of traffic.
Those natives have in some places, for trifling considerations,
sold their inheritance so favourably situated;
and in other places been driven back by superior force.
As their way of clothing themselves is now altered from what it was,
and they are far remote from us, they have to pass over mountains,
swamps and barren deserts, where travelling is very troublesome,
in bringing their skins and furs to trade with us.

By the extending of English settlements, and partly by English hunters,
the wild beasts they chiefly depend on for a subsistence, are not so plenty as they were;
and people too often for the sake of gain,
open a door for the Indians to waste their skins and furs,
in purchasing a liquor which tends to the ruin of them and their families.

My own will and desires being now very much broken,
my heart with much earnestness turned to the Lord,
to whom alone I looked for help in the dangers before me.
I had a prospect of the English along the coast, for upwards of nine hundred miles,
where I have travelled;
and their favourable situation and the difficulties attending the natives in many places,
and also the negroes, were open before me;
and a weighty and heavenly care came over my mind,
and love filled my heart toward all mankind,
in which I felt a strong engagement that we might be obedient to the Lord,
while in tender mercies he is yet calling to us;
and so attend to pure universal righteousness,
as to give no just cause of offence to the Gentiles who do not profess Christianity,
whether the blacks from Africa or the native inhabitants of this continent.
I was led into a close, laborious inquiry, whether as an individual,
I kept clear from all things which tended to stir up, or were connected with wars,
either in this land or Africa; and my heart was deeply concerned,
that in future I might in all things keep steadily to the pure Truth,
and live and walk in the plainness and simplicity of a sincere follower of Christ.
In this lonely journey this day, I greatly bewailed the spreading of a wrong spirit,
believing that the prosperous, convenient situation of the English,
requires a constant attention to Divine love and wisdom to guide and
support us in a way answerable to the will of that good,
gracious and Almighty Being, who hath an equal regard to all mankind.
Here, luxury and covetousness,
with the numerous oppressions and other evils attending them,
appeared very afflicting to me; and I felt in that which is immutable,
that the seeds of great calamity and desolation
are sown and growing fast on this continent:
nor have I words sufficient to set forth the longing I then felt,
that we who are placed along the coast, and have tasted the love and goodness of God,
might arise in his strength; and like faithful messengers,
labour to check the growth of these seeds,
that they may not ripen to the ruin of our posterity.

We reached the Indian settlement at Wyoming,
and were told that an Indian runner had been at that place a day or two before us,
and brought news of the Indians taking an
English fort westward and destroying the people,
and that they were endeavouring to take another;
and also that another Indian runner came there about
the middle of the night before we got there,
who came from a town about ten miles above Wehaloosing,
and brought news that some Indian warriors from distant parts,
came to that town with two English scalps;
and told the people that it was war with the English.

Our guides took us to the house of a very ancient man;
and soon after we had put in our baggage,
there came a man from another Indian house some distance off;
and I perceiving there was a man near the door, went out;
and he having a tomahawk under his matchcoat out of sight,
as I approached him he took it in his hand.
I however went forward,
and speaking to him in a friendly way perceived he understood some English:
my companion then coming out,
we had some talk with him concerning the nature of our visit in these parts;
and then he going into the house with us, and talking with our guides,
soon appeared friendly, and sat down and smoked his pipe.
Though his taking his hatchet in his hand at the instant I drew near to him,
had a disagreeable appearance,
I believe he had no other intent than to be in
readiness in case any violence was offered to him.

Hearing the news brought by these Indian runners,
and being told by the Indians where we lodged, that the Indians living about Wyoming,
expected in a few days to move to some larger towns,
I thought that to all outward appearance, it was dangerous travelling at this time.
After a hard day`'s journey, I was brought into a painful exercise at night,
in which I had to trace back and view over the steps I
had taken from my first moving in the visit;
and though I had to bewail some weakness which at times had attended me,
yet I could not find that I had ever given way to a wilful disobedience.
As I believed I had under a sense of duty come thus far,
I was now earnest in spirit beseeching the Lord to show me what I ought to do.
In this great distress I grew jealous of myself, lest the desire of reputation,
as a man firmly settled to persevere through dangers,
or the fear of disgrace arising on my returning without performing the visit,
might have some place in me.
Thus I lay full of thoughts during a great part of the night,
while my beloved companion lay and slept by me; until the Lord, my gracious Father,
who saw the conflicts of my soul, was pleased to give me quietness.
I was again strengthened to commit my life and all things relating thereto,
into his heavenly hands; and getting a little sleep toward day,
when morning came we arose.

On the 14th day of the sixth month,
we sought out and visited all the Indians hereabouts that we could meet with;
they being chiefly in one place, about a mile from where we lodged,
in all perhaps twenty.
I expressed the care I had on my mind for their good;
and told them that true love had made me willing
to leave my family to come and see the Indians,
and speak with them in their houses.
Some of them appeared kind and friendly.
We took our leave of these Indians, and went up the river Susquehanna about three miles,
to the house of an Indian called Jacob January, who had killed his hog;
and the women were making a store of bread, and preparing to move up the river.
Here our pilots left their canoe when they came down in the spring, which lying dry,
was leaky; and being detained some hours,
we had a good deal of friendly conversation with the family,
and after eating dinner with them, made them some small presents.
Then putting our baggage in the canoe, some of them pushed slowly up the stream,
and the rest of us rode our horses; and swimming them over a creek called Lahawahamunk,
we pitched our tent a little above it, there being a shower in the evening:
and in a sense of God`'s goodness in helping me in my distress,
sustaining me under trials and inclining my heart to trust in him,
I lay down in an humble bowed frame of mind, and had a comfortable night`'s lodging.

On the 15th day of the sixth month,
we proceeded until the afternoon ,• when a storm appearing,
we met our canoe at an appointed place and staid there all night;
the rain continuing so heavy, that it beat through our tent and wet as and our baggage.

On the 16th day,
we found on our way abundance of trees blown down with the storm yesterday;
and had occasion reverently to consider the kind dealings of the Lord,
who provided a safe place for us in a valley, while this storm continued.
By the falling of trees across our path we were much hindered,
and in some swamps our way was so stopped, that we got through with extreme difficulty.

I had this day often to consider myself as a sojourner in the world;
and a belief in the all-sufficiency of God to support
his people in their pilgrimage felt comfortable to me;
and I was industriously employed to get to a state of perfect resignation.

We seldom saw our canoe but at appointed places,
by reason of the path going off from the river: and this afternoon.
Job Chilaway, an Indian from Wehaloosing, who talks good English,
and is acquainted with several people in and about Philadelphia,
met our people on the river; and understanding where we expected to lodge,
pushed back about six miles, and came to us after night;
and in a while our own canoe came, it being hard work pushing up stream.
Job told us that an Indian came in haste to their town yesterday,
and told them that three warriors, coming from some distance,
lodged in a town above Wehaloosing a few nights past;
and that these three men were going against the English at Juniata.
Job was going down the river to the province store at Shamokin.
Though I was so far favoured with health as to continue travelling,
yet through the various difficulties in our journey,
and the different way of living from what I had been used to, I grew sick:
and the news of these warriors being on their march so near us,
and not knowing whether we might not fall in with them, was a fresh trial of my faith;
and though through the strength of Divine love,
I had several times been enabled to commit myself to the Divine disposal,
I still found the want of my strength being renewed, that I might persevere therein;
and my cries for help were put up to the Lord,
who in great mercy gave me a resigned heart, in which I found quietness.

On the 17th day, parting from Job Chilaway,
we went on and reached Wehaloosing about the middle of the afternoon;
and the first Indian we saw was a woman of a modest countenance, with a Bible,
who first spoke to our guide;
and then with a harmonious voice expressed her gladness at seeing us,
having before heard of our coming.
By the direction of our guide we sat down on a log,
and he went to the town to tell the people we were come.
My companion and I sitting thus together, in a deep inward stillness,
the poor woman came and sat near us; and great awfulness coming over us,
we i-ejoiced in a sense of God`'s love manifested to our poor souls.
After awhile we heard a conk-shell blow several times,
and then came John Curtis and another Indian man,
who kindly invited us into a house near the town, where we found, I suppose,
about sixty people sitting in silence.

After sitting a short time,
I stood up and in some tenderness of spirit acquainted them with the nature of my visit,
and that a concern for their good had made me willing to come thus far to see them;
all in a few short sentences, which some of them understanding,
interpreted to the others, and there appeared gladness amongst them.
Then I showed them my certificate, which was explained to them;
and the Moravian who overtook us on the way, being now here, bade me welcome.

On the 18th day we rested ourselves in the forenoon;
and the Indians knowing that the Moravian and I were of different religious societies,
and that some of their people had encouraged him to come and stay awhile with them,
were I believe concerned, that no jarring or discord might be in their meetings:
and they I suppose, having conferred together,
acquainted me that the people at my request,
would at any time come together and hold meetings; and also told me,
that they expected the Moravian would speak in their settled meetings,
which are commonly held morning and near evening.
I found a liberty in my heart to speak to the Moravian,
and told him of the care I felt on my mind for the good of these people;
and that I believed no ill effects would follow,
if I sometimes spoke in their meetings when love engaged me thereto,
without calling them together at times when they did not meet of course:
whereupon he expressed his good-will toward my speaking at any time,
all that I found in my heart to say.

Near evening I was at their meeting, where the pure Gospel love was felt,
to the tendering some of our hearts;
and the interpreters endeavouring to acquaint
the people with what I said in short sentences,
found some difficulty,
as none of them were quite perfect in the English and Delaware tongues,
so they helped one another, and we laboured along, Divine love attending.
Afterwards, feeling my mind covered with the spirit of prayer,
I told the interpreters that I found it in my heart to pray to God,
and believed if I prayed aright, he would hear me,
and expressed my willingness for them to omit interpreting;
so our meeting ended with a degree of Divine love.
Before the people went out, I observed Papunehang,
a man who had been zealous in labouring for a reformation in that town,
being then very tender, spoke to one of the interpreters;
and I was afterwards told that he said in substance;
"`I love to feel where words come from.`"

On the 19th day and first of the week,
this morninsr in the meeting the Indian who came with the Moravian,
being also a member of that society, prayed;
and then the Moravian spoke a short time to the people.
In the afternoon they coming together,
and my heart being filled with a heavenly care for their good,
I spoke to them awhile by interpreters; but none of them being perfect in the work,
and I feeling the current of love run strong,
told the interpreters that I believed some of the people would understand me,
and so I proceeded.
In which exercise, I believe the Holy Ghost wrought on some hearts to edification,
where all the words were not understood.
I looked upon it as a time of Divine favour,
and my heart was tendered and truly thankful before the Lord; and after I sat down,
one of the interpreters seemed spirited to give
the Indians the substance of what I had said.

Before our first meeting this morning,
I was led to meditate on the manifold difficulties of these Indians; who,
by the permission of the Six Nations, dwell in these parts;
and a near sympathy with them was raised in me;
and my heart being enlarged in the love of Christ,
I thought that the affectionate care of a good man for his only brother in affliction,
did not exceed what I then felt for that people.

I came to this place through much trouble; and though through the mercies of God,
I believed that if I died in the journey, it would be well with me;
yet the thoughts of falling into the hands of Indian warriors,
were in times of weakness afflicting to me; and being of a tender constitution,
the thoughts of captivity amongst them, were at times grievous;
supposing that they being strong and hardy,
might demand service of me beyond what I could well bear;
but the Lord alone was my keeper; and I believed if I went into captivity,
it would be for some good end; and thus from time to time,
my mind was centered in resignation, in which I always found quietness.
And now, this day, though I had the same dangerous wilderness between me and home,
I was inwardly joyful that the Lord had strengthened me to come on this visit,
and manifested a fatherly care over me in my poor lowly condition,
when in mine own eyes I appeared inferior to many amongst the Indians.

When the last mentioned meeting was ended, it being night, Papunehang went to bed;
and one of the interpreters sitting by me,
I observed Papunehang spoke with an harmonious voice, I suppose, a minute or two:
and asking the interpreter,
was told that "`he was expressing his thankfulness to
God for the favours he had received that day;
and prayed that he would continue to favour him with
the same which he had experienced in that meeting.`"
That though Papunehang had before agreed to receive the Moravians, and join with them,
he still appeared kind and loving to us.

On the 20th day I was at two meetings, and silent in them.

The 21st day.
This morning in meeting my heart was enlarged in pure love amongst them,
and in short plain sentences expressed several things that rested upon me,
which one of the interpreters gave the people pretty readily;
after which the meeting ended in supplication,
and I had cause humbly to acknowledge the loving-kindness of the Lord toward us;
and believed that a door remained open for the faithful disciples of Jesus Christ,
to labour amongst these people.

Feeling my mind at liberty to return, I took my leave of them in general,
at the conclusion of what I said in meeting; and so we prepared to go homeward:
but some of their most active men told us, that when we were ready to move,
the people would choose to come and shake hands with us;
which those who usually came to meeting did; and from a secret draught in my mind,
I went amongst some who did not use to go to meeting, and took my leave of them also:
the Moravian and his Indian interpreter, appeared respectful to us at parting.
This town stands on the bank of Susquehanna, and consists, I believe,
of about forty houses, mostly compact together; some about thirty feet long,
and eighteen wide; some larger, some less; mostly built of split plank,
one end set in the ground, and the other pinned to a plate,
on which lay rafters covered with bark.
I understand a great flood last winter overflowed the
chief part of the ground where the town stands,
and some were now about moving their houses to higher ground.

We expected only two Indians to be our company; but when we were ready to go,
we found many of them were going to Bethlehem with skins and furs,
who chose to go in company with us; so they loaded two canoes,
which they desired us to go in, telling us, the waters were so raised with the rains,
that the horses should be taken by persons who
were better acquainted with the fording places:
so we with several Indians went in the canoes, and others went on horses,
there being seven besides ours.
We met with the horsemen once on the way by appointment,
a little below a stream called Tunkhannock: we lodged there,
and some of the young men going out a little before dusk with their guns,
brought in a deer.

On the 22nd day, through diligence we reached Wyoming before night,
and understood the Indians were mostly gone from this place:
here we went up a small creek into the woods with our canoes, and pitching our tent,
carried out our baggage; and before dark our horses came to us.

On the 23d day in the morning, the horses were loaded,
and we prepared our baggage and set forward, being in all fourteen;
and with diligent travelling were favoured to get nearly halfway to Fort Allen.
The land on this road from Wyoming to our frontier being mostly poor,
and good grass scarce, they chose a piece of low ground to lodge on,
as the best for grassing; and I having sweat much in travelling, and being weary,
slept sound.
I perceived in the night that I had taken cold,
of which I was favoured to get better soon.

On the 24th day we passed Fort Allen, and lodged near it in the woods.

We forded the westerly branch of the Delaware three times, and thereby had a shorter way,
and missed going over the top of the Blue mountains, called the Second Ridge.
In the second time fording, where the river cuts through the mountain,
the waters being rapid and pretty deep,
and my companion`'s mare being a tall tractable animal,
he sundry times drove her through the river,
and they loaded her with the burthens of some small horses,
which they thought not sufficient to come through with their loads.

The troubles westward, and the difficulty for Indians to pass through our frontier,
I apprehend was one reason why so many came; expecting that our being in company,
would prevent the frontier inhabitants from being surprised.

On the 25th day we reached Bethlehem, taking care on the way to keep foremost,
and to acquaint people on and near the road who these Indians were:
this we found very needful;
for the frontier inhabitants were often alarmed at the
report of English being killed by Indians westward.

Amongst our company were some who I did not remember to have seen at meeting,
and some of these at first were very reserved; but we being several days together,
and behaving friendly toward them,
and making them suitable returns for the services they did us,
they became more free and sociable.

On the 26th day and first of the week,
having carefully endeavoured to settle all
affairs with the Indians relative to our journey,
we took leave of them, and I thought they generally parted with us affectionately.
We got to Richland, and had a very comfortable meeting amongst our friends:
here I parted with my kind friend and companion Benjamin Parvin;
and accompanied by my friend Samuel Foulk, we rode to John Cadwallader`'s,
from whence I reached home the next day, where I found my family middling well;
and they and my friends all along appeared glad to see me
return from a journey which they apprehended dangerous.
My mind while I was out, had been so employed in striving for a perfect resignation,
and I had so often been confirmed in a belief,
that whatever the Lord might be pleased to allot for me, would work for good,
that I was careful lest I should admit any degree of selfishness in being glad overmuch,
and laboured to improve by those trials in such a manner as my
gracious Father and protector intends for me.
Between the English settlements and Wehaloosing, we had only a narrow path,
which in many places is much grown up with bushes,
and interrupted by abundance of trees lying across it; these,
together with the mountains, swamps and rough stones, make it a difficult road to travel;
and the more so, for that rattlesnakes abound there, of which we killed four.
People who have never been in such places, have but an imperfect idea of them;
but I was not only taught patience, but also made thankful to God,
who thus led me about and instructed me,
that I might have a quick and lively feeling of the afflictions of my fellow-creatures,
whose situation in life is difficult.

