== Chapter IX.

His religious conversation with a company met to
see the tricks of a juggler--John Smith`'s advice;
proceedings of a committee at the Yearly Meeting in
1764--Contemplations on the nature of true wisdom,
occasioned by hearing of the cruelty of the Indians to their
captives--Visits the families of Friends at Mount Holly,
Mansfield and Burlington, in 1764,
and the meetings on the sea coast from Cape May toward Squan in 1765--Visit
to the lower counties on Delaware and the Eastern Shore of Maryland in 1766,
in company with John Sleeper; some account of Joseph Nichols and his followers;
and observations on the different state of the first settlers
in Pennsylvania who depended on their own labour,
and those of the Southern provinces who kept negroes--
Visit to the northern parts of New Jersey the same year,
and the western parts of Maryland and Pennsylvania in 1767,
and afterwards other parts of Pennsylvania and the families of Friends at Mount Holly;
and again several parts of Maryland in 1768--Further considerations on keeping slaves;
his concern for having formerly, as an executor, been party to the sale of one;
and what he did in consequence of it--Thoughts on
Friends exercising offices in civil government.

The latter part of the summer 1763, there came a man to Mount Holly,
who had before published by a printed advertisement,
that at a certain public house he would show many wonderful operations,
which he therein enumerated.
This man at the time appointed, did, by slight of hand, sundry things,
which to those gathered, appeared strange.

I heard of it next day, and understanding that the show was to be continued,
and the people to meet about sunset, I felt an exercise on that account:
so I went to the public house in the evening,
and told the man of the house that I had an
inclination to spend a part of the evening there;
with which he signified that he was content.
Then sitting down by the door, I spoke to the people as they came together,
concerning this show; and more coming and sitting down with us,
the seats at the door were mostly filled;
and I had conversation with them in the fear of the Lord,
and laboured to convince them that thus assembling to
see those tricks or slights of hand,
and bestowing their money to support men who in
that capacity were of no use in the world,
was contrary to the nature of the Christian religion.

There was one of the company who, for a time,
endeavoured by arguments to show the reasonableness of their proceedings;
but after considering some texts of Scripture and calmly debating the matter,
he gave up the point.
Having spent about an hour amongst them, and feeling my mind easy, I departed.

At our Yearly Meeting in Philadelphia, on the 25th day of the ninth month, 1764,
John Smith of Marlborough, aged upwards of eighty years, a faithful minister,
though not eloquent, stood up in our meeting of ministers and elders,
and appearing to be under a great exercise of spirit,
informed Friends in substance as follows, to wit:
"`That he had been a member of the Society upward of sixty years,
and well remembered that in those early times Friends were a plain lowly minded people;
and that there was much tenderness and contrition in
their meetings.--That at twenty years from that time,
the Society increasing in wealth,
and in some degree conforming to the fashions of the world,
true humility was less apparent,
and their meetings in general not so lively and edifying--that at the end of forty years,
many of them were grown very rich; that wearing fine costly garments,
and using silver and other watches, became customary with them,
their sons and their daughters,
and many of the Society made a spacious appearance in the world;
which marks of outward wealth and greatness,
appeared on some in our meetings of ministers and elders;
and as these things became more prevalent,
so the powerful overshadowings of the Holy Ghost were less manifest in the Society--
that there had been a continued increase of these ways of life even until now;
and that the weakness which hath overspread the Society,
and the barrenness manifest amongst us, is matter of much sorrow.`"
He then mentioned the uncertainty of his attending these meetings in future,
expecting his dissolution was now near; and having tenderly expressed his concern for us,
signified that he had seen in the true fight that the Lord would bring back
his people from these things into which they were thus degenerated,
but that his faithful servants must first go through great and heavy exercises.

On the 29th day,
the committee appointed by the Yearly Meeting to
visit the Quarterly and Monthly Meetings,
gave an account in writing of their proceedings in that service; in which they signified,
that in the course of it,
they had been apprehensive that some persons holding offices in government,
inconsistent with our principles; and others who kept slaves,
remaining active members in our meetings of discipline,
had been one means of weakness more and more prevailing
in the management thereof in some places.
After this report was read, an exercise revived on my mind,
which at times had attended me for several years,
and inward cries to the Lord were raised in me,
that the fear of man might not prevent me from doing what he required of me,
and standing up, I spoke in substance as follows:
"`I have felt a tenderness in my mind toward persons,
in two circumstances mentioned in that report; that is,
toward such active members who keep slaves,
and such who hold offices in civil government; and have desired,
that Friends in all their conduct may be kindly affectioned one toward another.
Many Friends who keep slaves, are under some exercise on that account; and at times,
think about trying them with freedom; but find many things in their way.
The way of living, and annual expenses of some of them are such,
that it seems impracticable for them to set their slaves free,
without changing their own way of life.
It has been my lot to be often abroad; and I have observed in some places,
at Quarterly and Yearly Meetings,
and at some houses where travelling Friends and their horses are often entertained,
that the yearly expense of individuals therein is very considerable.
Friends in some places crowding much on persons in these circumstances for entertainment,
hath rested as a burthen on my mind for some years past,
and I now express it in the fear of the Lord,
greatly desiring that Friends now present may duly consider it.`"

In the fall of this year having hired a man to work,
I perceived in conversation that he had been a soldier in the late war on this continent;
and in the evening giving a narrative of his captivity amongst the Indians,
he informed me that he saw two of his fellow captives
tortured to death in a very cruel manner.

This relation affected me with sadness, under which I went to bed; and the next morning,
soon after I awoke, a fresh and living sense of Divine love spread over my mind;
in which I had a renewed prospect of the nature of that wisdom from above,
which leads to a right use of all gifts, both spiritual and temporal,
and gives contentment therein: under a feeling thereof, I wrote as follows: "`Hath He,
who gave me a being attended with many wants unknown to brute creatures,
given me a capacity superior to theirs, and shown me,
that a moderate application to business is proper to my present condition; and that this,
attended with his blessing, may supply all outward wants,
while they remain within the bounds he hath fixed;
and no imaginary wants proceeding from an evil spirit, have any`' place in me?
Attend then, O my soul! to this pure wisdom,
as thy sure conducter through the manifold dangers in this world!

"`Doth pride lead to vanity?
Doth vanity form imaginary wants?
Do these wants prompt men to exert their power in requiring that of others,
from which they would rather be excused, were the same required of them?

"`Do these proceedings beget hard thoughts?
Do hard thoughts, when ripe, become malice?
Does malice, when ripe,
become revengeful and in the end inflict terrible pains on their fellow-creatures,
and spread desolations in the world?

"`Do mankind, walking in uprightness, delight in each other`'s happiness?
And do these creatures, capable of this attainment, by giving way to an evil spirit,
employ their wit and strength to afflict and destroy one another?

"`Remember then, O my soul! the quietude of those in whom Christ governs,
and in all thy proceedings feel after it!

"`Doth he condescend to bless thee with his presence?
To move and influence to action?
To dwell in thee and walk in thee?
Remember then thy station, as a being sacred to God;
accept of the strength freely offered thee; and lake heed that no weakness,
in conforming to expensive, unwise and hard hearted customs,
gendering to discord and strife, be given way to.
Doth he claim my body as his temple?
And graciously grant that I may be sacred to him.
Oh! that I may prize this favour;
and that my whole life may be conformable to this character!

"`Remember, O my soul! that the prince of peace is thy Lord:
that he communicates his unmixed wisdom to his family;
that they living in perfect simplicity,
may give no just cause of offence to any creature, but may walk as he walked!`"

Having felt an openness in my heart toward visiting families in our own meeting,
and especially in the town of Mount Holly, the place of my abode,
I mentioned it in our Monthly Meeting the fore part of the winter 1764;
which being agreed to, and several Friends of our meeting being united in the exercise,
we proceeded therein; and through Divine favour were helped in the work,
so that it appeared to me as a fresh reviving of godly care amongst Friends.
In the latter part of the same winter, I joined my friend William Jones,
in a visit to Friends`' families in Mansfield;
in which labour I had cause to admire the goodness of the Lord toward us.

Having felt my mind drawn to visit Friends along
the sea coast from Cape May to near Squan;
and also to visit some people in those parts, amongst whom there is no settled worship;
I joined with my beloved friend Benjamin Jones, in a visit there,
having Friends`' unity therein.
We set off the 24th day of the tenth month, 1765,
and had a prosperous and very satisfactory journey; feeling at times,
through the goodness of the heavenly Shepherd,
the Gospel to flow freely toward a poor people scattered in those places.
Soon after our return, I joined my friends John Sleeper and Elizabeth Smith,
in visiting Friends`' families at Burlington,
there being at this time about fifty families of our Society in that city;
and we had cause humbly to adore our heavenly Father,
who baptized us into a feeling of the state of the people,
and strengthened us to labour in true Gospel love amongst them.

An exercise having at times for several years attended me,
in regard to paying a religious visit to Friends on the Eastern Shore of Maryland;
such was the nature of it,
that I believed the Lord moved me to travel on foot amongst them,
that by so doing I might have a more lively
feeling of the condition of the oppressed slaves,
set an example of lowliness before the eyes of their masters,
and be more out of the way of temptation to unprofitable converse.

The time drawing near in which I believed it my duty to
lay my concern before our Monthly Meeting,
I perceived in conversation with my beloved friend John Sleeper,
that he was under a concern to travel the same way,
and also to go on foot in the form of a servant amongst them, as he expressed it.
This he told me before he knew aught of my exercise.

We being thus drawn the same way, laid our exercise and the nature of it before Friends;
and obtaining certificates, we set off the 6th day of the fifth month, 1766;
and were at meetings with Friends at Wilmington, Duck creek.
Little creek and Motherkill; my heart being at times tendered under the Divine influence,
and enlarged in love toward the people amongst whom we travelled.

From Motherkill,
we crossed the country about thirty-five miles to Friends at Tuckahoe in Maryland,
and had a meeting there and at Marshy creek.

At these our three last meetings, were a considerable number of people,
followers of one Joseph Nichols, a preacher; who, I understand,
is not in outward fellowship with any religious Society of people,
but professes nearly the same principles as our Society doth,
and often travels up and down appointing meetings, to which many people come.
I heard Friends speaking of some of their neighbours, who had been irreligious people,
that were now his followers, and were become sober well behaved men and women.

Some irregularities I hear have been amongst the people at several of his meetings;
but from the whole of what I have perceived, I believe the man and some of his followers,
are honestly disposed, but that skilful fathers are wanting among them:
from hence we went to Choptank and Third Haven;
and thence to Queen Ann`'s. The weather for some days past having been hot and dry,
and in order to attend meetings pursuant to appointment,
we having travelled pretty steadily, and had hard labour in meetings, I grew weakly;
at which I was for a time discouraged.
But looking over our journey,
and thinking how the Lord had supported our minds and bodies,
so that we got forward much faster than I expected before we came out,
I saw that I had been in danger of too strongly desiring to get soon through the journey,
and that this bodily weakness was a kindness to me; and then in contrition of spirit,
I became very thankful to my gracious Father, for this manifestation of his love;
and in humble submission to his will, my trust was renewed in him.

On this part of our journey I had many thoughts on the different
circumstances of Friends who inhabit Pennsylvania and Jersey,
from those who dwell in Maryland, Virginia and Carolina.
Pennsylvania and New Jersey were settled by Friends who were
convinced of our principles in England in times of suffering,
and coming over bought lands of the natives,
and applied themselves to husbandry in a peaceable way;
and many of their children were taught to labour for their living.

Few Friends, I believe, came from England to settle in any of these Southern provinces;
but by the faithful labours of travelling Friends in early times,
there were considerable convincements amongst the inhabitants of these parts.
Here I remembered my reading of the warlike disposition
of many of the first settlers in these provinces,
and of their numerous engagements with the natives, in which much blood was shed,
even in the infancy of those colonies.
The people inhabiting these places, being grounded in customs contrary to the pure Truth,
when some of them were affected with the powerful preaching of the Word of Life,
and joined in fellowship with our Society, they had a great work to go through.

It is observable in the History of the Reformation from Popery,
that it had a gradual progress from age to age.
The uprightness of the first reformers,
in attending to the light and understanding given them,
opened the way for sincere hearted people to proceed further afterward;
and thus each one truly fearing God,
and labouring in those works of righteousness appointed for them in their day,
findeth acceptance with him.
Through the darkness of the times and the corruption of manners and customs,
some upright men may have had little more for their day`'s work
than to attend to the righteous principle in their minds,
as it related to their own conduct in life,
without pointing out to others the whole extent of that,
which the same principle would lead succeeding ages into.
Thus for instance; amongst an imperious warlike people, supported by oppressed slaves,
some of these masters I suppose, are awakened to feel and see their error;
and through sincere repentance,
cease from oppression and become like fathers to their servants;
showing by their example, a pattern of humility in living and moderation in governing,
for the instruction and admonition of their oppressing neighbours;
those without carrying the reformation further,
I believe have found acceptance with the Lord.
Such was the beginning; and those who succeeded them,
and have faithfully attended to the nature and spirit of the reformation,
have seen the necessity of proceeding further;
and not only to instruct others by their example in governing well,
but also to use means to prevent their successors from
having so much power to oppress others.

Here I was renewedly confirmed in my mind, that the Lord,
whose tender mercies are over all his works,
and whose ear is open to the cries and groans of the oppressed,
is graciously moving on the hearts of people, to draw them off from the desire of wealth,
and bring them into such an humble, lowly way of living,
that they may see their way clearly, to repair to the standard of true righteousness;
and not only break the yoke of oppression,
but know him to be their strength and support in a time of outward affliction.

Passing on we crossed Chester river, and had a meeting there, and at Cecil and Sassafras.
Through my bodily weakness, joined with a heavy exercise of mind,
it was to me an humbling dispensation,
and I had a very lively feeling of the state of the oppressed;
yet I often thought that what I suffered was little,
compared with the sufferings of the blessed Jesus, and many of his faithful followers;
and may say with thankfulness, I was made content.

From Sassafras we went pretty directly home, where we found our families well;
and for several weeks after our return, I had often to look over our journey:
and though to me it appeared as a small service,
and that some faithful messengers will yet have more bitter
cups to drink for Christ`'s sake in those Southern provinces,
than we had; yet I found peace in that I had been helped to walk in sincerity,
according to the understanding and strength given me.

On the 13th day of the eleventh month, 1766,
with the unity of Friends at our Monthly Meeting,
in company with my beloved friend Benjamin Jones,
I set out on a visit to Friends in the upper part of this province,
having for a considerable time had drawings of love in my heart that way:
we travelled as far as Hardwick;
and I had inward peace in my labours of love amongst them.

Through the humbling dispensations of Divine Providence,
my mind hath been brought into a further feeling of the
difficulties of Friends and their servants south-westward:
and being often engaged in spirit on their account,
I believed it my duty to walk into some parts of the Western shore of Maryland,
on a religious visit.
Having obtained a certificate from Friends of our Monthly Meeting,
I took my leave of my family under the heart-tendering operation of Truth;
and on the 20th day of the fourth month, 1767,
I rode to the ferry opposite to Philadelphia, and from thence walked to William Home`'s,
at Darby, that evening; and next day pursued my journey alone,
and reached Concord week-day meeting.

Discouragements and a weight of distress, had at times attended me in this lonesome walk;
through which afflictions I was mercifully preserved: and now sitting down with Friends,
my mind was turned toward the Lord, to wait for his holy leadings; who, in infinite love,
was pleased to soften my heart into humble contrition,
and renewedly strengthen me to go forward;
that to me it was a time of heavenly refreshment in a silent meeting.

The next day I came to New Garden weekday meeting,
in which I sat with bowedness of spirit;
and being baptized into a feeling of the state of some present,
the Lord gave us a heart tendering season; to his name be the praise.

I passed on, and was at Nottingham Monthly Meeting;
and at a meeting at Little Britain on first-day:
and in the afternoon several Friends came to the house where I lodged,
and we had a little afternoon meeting; and through the humbling power of Truth,
I had to admire the loving-kindness of the Lord manifested to us.

On the 26th day I crossed the Susquehanna;
and coming amongst people living in outward ease and greatness,
chiefly on the labour of slaves, my heart was much affected; and in awful retiredness,
my mind was gathered inward to the Lord,
being humbly engaged that in true resignation I might receive instruction from him,
respecting my duty amongst this people.

Though travelling on foot was wearisome to my body;
yet it was agreeable to the state of my mind.

I went gently on, being weakly; and was covered with sorrow and heaviness,
on account of the spreading prevailing spirit of this world,
introducing customs grievous and oppressive on one hand,
and cherishing pride and wantonness on the other.
In this lonely walk and state of abasement and humiliation,
the state of the church in these parts was opened before me;
and I may truly say with the prophet, "`I was bowed down at the hearing of it;
I was dismayed at the seeing of it.`"
Under this exercise, I attended the Quarterly Meeting at Gunpowder;
and in bowedness of spirit, I had to open with much plainness,
what I felt respecting Friends living in fulness,
on the labours of the poor oppressed negroes;
and that promise of the Most High was now revived;
"`I will gather all nations and tongues; and they shall come and see my glory.`"
Here the sufferings of Christ and his tasting death for every man, and the travels,
sufferings and martyrdom of the apostles and primitive Christians,
in labouring for the conversion of the Gentiles, was livingly revived in me;
and according to the measure of strength afforded,
I laboured in some tenderness of spirit, being deeply affected amongst them.
The difference between the present treatment which these Gentiles, the negroes,
receive at our hands,
and the labours of the primitive Christians for the conversion of the Gentiles,
was pressed home, and the power of Truth came over us; under a feeling of which,
my mind was united to a tender-hearted people in those parts;
and the meeting concluded in a sense of God`'s
goodness toward his humble dependent children.

The next day was a general meeting for worship, much crowded:
in which I was deeply engaged in inward cries to the Lord for help,
that I might stand wholly resigned, and move only as he might be pleased to lead me:
and I was mercifully helped to labour honestly and fervently amongst them,
in which I found inward peace; and the sincere were comforted.

From hence I turned toward Pipe creek, and passed on to the Red Lands;
and had several meetings amongst Friends in those parts.
My heart was often tenderly affected, under a sense of the Lord`'s goodness,
in sanctifying my troubles and exercises, turning them to my comfort, and I believe,
to the benefit of many others; for I may say with thankfulness,
that this visit appeared like a fresh tendering visitation in most places.

I passed on to the western Quarterly Meeting in Pennsylvania;
during the several days of this meeting,
I was mercifully preserved in an inward feeling after the mind of Truth,
and my public labours tended to my humiliation, with which I was content.
After the Quarterly Meeting of worship ended,
I felt drawings to go to the women`'s meeting of business, which was very full;
and here the humility of Jesus Christ, as a pattern for us to walk by,
was livingly opened before me; and in treating on it my heart was enlarged,
and it was a baptizing time.
From hence I went on, and was at meetings at Concord, Middletown,
Providence and Haddonfield, and so home; where I found my family well.
A sense of the Lord`'s merciful preservation in this my journey,
excites reverent thankfulness to him.

On the 2nd day of the ninth month, 1767, with the unity of Friends,
I set off on a visit to Friends in the upper part of Berks and Philadelphia counties;
was at eleven meetings in about two weeks;
and have renewed cause to bow in reverence before the Lord, who,
by the powerful extendings of his humbling goodness, opened my way amongst Friends,
and made the meetings, I trust, profitable to us.
The following winter I joined in a visit to
Friends`' families in some part of our meeting;
in which exercise, the pure influence of Divine love made our visits reviving.

On the 5th day of the fifth month, 1768, I left home under the humbling hand of the Lord,
having obtained a certificate, in order to visit some meetings in Maryland;
and to proceed without a horse looked clearest to me.
I was at the Quarterly Meetings at Philadelphia and Concord;
and then went on to Chester river; and crossing the bay with Friends,
was at the Yearly Meeting at West river: thence back to Chester river;
and taking a few meetings in my way, proceeded home.
It was a journey of much inward waiting; and as my eye was to the Lord,
way was several times opened to my humbling admiration,
when things appeared very difficult.

In my return I felt a relief of mind very comfortable to me; having through Divine help,
laboured in much plainness, both with Friends selected, and in the more public meetings;
so that I trust the pure witness in many minds was reached.

The 11th day of the sixth month, 1769.
Sundry cases have happened of late years, within the limits of our Monthly Meeting,
respecting the exercise of pure righteousness toward the negroes;
in which I have lived under a labour of heart that equity might be steadily kept to.
On this account I have had some close exercises amongst Friends;
in which I may thankfully say, I find peace:
and as my meditations have been on universal love, my own conduct in time past,
became of late very grievous to me.

As persons setting negroes free in our province, are bound by law to maintain them,
in case they have need of relief, some who scrupled keeping slaves for term of life,
in the time of my youth,
were wont to detain their young negroes in their service until thirty years of age,
without wages, on that account: and with this custom I so far agreed,
that being engaged with another Friend in executing the will of a deceased Friend,
I once sold a negro lad till he might attain the age of thirty years,
and applied the money to the use of the estate.

With abasement of heart I may now say, that sometimes as I have sat in a meeting,
with my heart exercised toward that awful Being, who respecteth not persons nor colours,
and have looked upon this lad,
I have felt that all was not clear in my mind respecting him:
and as I have attended to this exercise, and fervently sought the Lord,
it hath appeared to me that I should make some restitution,
but in what way I saw not till lately.
Being under a concern that I may be resigned to
go on a visit to some part of the West Indies,
and under close engagement of spirit, seeking to the Lord for counsel herein,
my joining in the sale aforesaid, came heavily upon me, and my mind for a time,
was covered with darkness and sorrow; and under this sore affliction,
my heart was softened to receive instruction.
Here I saw, that as I had been one of the two executors,
who had sold this lad nine years longer than is common for our own children to serve,
so I should now offer a part of my substance to redeem the last half of that nine years;
but as the time was not yet come, I executed a bond, binding me and my executors,
to pay to the man he was sold to, what to candid men might appear equitable,
for the last four years and a half of his time, in case the said youth should be living,
and in a condition likely to provide comfortably for himself.

The 9th day of the tenth month, 1769.
My heart hath often been deeply afflicted under a feeling I have had,
that the standard of pure righteousness,
is not lifted up to the people by us as a Society,
in that clearness which it might have been,
had we been as faithful to the teachings of Christ as we ought to have been.
As my mind hath been inward to the Lord,
the purity of Christ`'s government hath been opened on my understanding;
and under this exercise, that of Friends being active in civil society,
in putting laws in force which are not agreeable to the purity of righteousness,
hath for several years been an increasing burthen upon me.
I have felt in the openings of universal love,
that where a people convinced of the truth of the inward teachings of Christ,
are active in putting laws in execution, which are not consistent with pure wisdom,
it hath a necessary tendency to bring dimness over their minds:
and as my heart hath been thus exercised,
and a tender sympathy in me toward my fellow members, I have within a few months past,
in several meetings for discipline, expressed my concern on this subject.
