== Chapter XI.

Preparing to visit Friends in England--Embarks at Chester, in company with Samuel Emlen,
in a ship bound to London--His deep exercise,
in observing the difficulties and hardships the common sailors are exposed,
to--Considerations on the dangers to which youth are exposed,
in being trained to a sea-faring life;
and its inconsistency with a pious education--Thoughts in a storm at sea;
with many instructive contemplations on the voyage--Arrival at London.

Having been some time under a religious concern to prepare for crossing the seas,
in order to visit Friends in the Northern parts of England,
and more particularly in Yorkshire; after weighty consideration,
I thought it expedient to inform Friends at our Monthly Meeting at Burlington of it;
who having unity with me therein, gave me a certificate.
I afterwards communicated the same to our Quarterly Meeting,
and they likewise certified their concurrence therewith.
Some time after, at the General Spring Meeting of ministers and elders,
I thought it my duty to acquaint them of the religious exercise which attended my mind;
and they likewise signified their unity by a certificate,
dated the 24th day of the eighth month, 1772, directed to Friends in Great Britain.

In the fourth month following,
I thought the time was come for me to make some inquiry for a suitable conveyance;
being apprehensive,
that as my concern was principally toward the Northern parts of England,
it would be most proper to go in a vessel bound to Liverpool or Whitehaven.
While I was at Philadelphia deliberating on this occasion,
I was informed that my beloved friend Samuel Emlen, jr., intending to go to London,
had taken passage for himself in the cabin of the ship called Mary and Elizabeth,
of which James Sparks was master, and John Head of the city of Philadelphia,
one of the owners; and I feeling a draft in my mind toward the steerage of the same ship,
went first and opened to Samuel the feeling I had concerning it.

My beloved friend wept when I spoke to him,
and appeared glad that I had thought of going in the vessel with him,
though my prospect was toward the steerage; and he offering to go with me,
we went on board, first into the cabin, a commodious room, and then into the steerage,
where we sat down on a chest, the sailors being busy about us;
the owner of the ship came and sat down with us.

Here my mind was turned toward Christ, the heavenly counsellor;
and feeling at this time my own will subjected, my heart was contrite before him.

A motion was made by the owner to go and sit in the cabin, as a place more retired;
but I felt easy to leave the ship, and made no agreement as to a passage in her;
but told the owner, if I took a passage in the ship,
I believed it would be in the steerage;
but did not say much as to my exercise in that case.

After I went to my lodgings, and the case was a little known in town,
a Friend laid before me the great inconvenience attending a passage in the steerage;
which for a time appeared very discouraging to me.

I soon after went to bed, and my mind was under a deep exercise before the Lord,
whose helping hand was manifested to me as I slept that night,
and his love strengthened my heart.
In the morning I went again with two Friends on board the vessel;
and after a short time spent therein, I went with Samuel Emlen to the house of the owner;
to whom, in the hearing of Samuel,
I opened my exercise in relation to a scruple I
felt with regard to a passage in the cabin,
which was in substance as follows:

I told the owner that on the outside of that part of the ship where the cabin was,
I observed sundry sorts of carved work and imagery;
that in the cabin I observed some superfluity of workmanship of several sorts;
and that according to the ways of men`'s reckoning,
the sum of money to be paid for a passage in that apartment,
had some relation to the expense in furnishing it to please
the minds of such who give way to a conformity to this world;
and that in this case, as in other cases, the monies received from the passengers,
are calculated to answer every expense relating to their passage,
and amongst the rest of these superfluities:
and that I felt a scruple with regard to paying my money to defray such expenses.

As my mind was now opened, I told the owner that I had at several times in my travels,
seen great oppressions on this continent; at which my heart had been much affected,
and brought into a feeling of the state of the sufferers.
And having many times been engaged, in the fear and love of God,
to labour with those under whom the oppressed have been borne down and afflicted,
I have often perceived a desire prevalent to get riches and provide estates for children,
to live conformably to customs,
which stand in that spirit wherein men have regard to the honours of this world.
In the pursuit of these things, I have seen many entangled in the spirit of oppression,
and the exercise of my soul has been such,
that I could not find peace in joining in any thing
which I saw was against that wisdom which is pure.

After this I agreed for a passage in the steerage;
and hearing that Joseph White had a desire to see me,
I felt the reviving of a desire to see him, and went to his house, and next day home,
where I tarried two nights: and then early in the morning, I parted with my family,
under a sense of the humbling hand of God upon me; and going to Philadelphia,
had opportunity with several of my beloved friends, who appeared to be concerned for me,
on account of the unpleasant situation of that part of the vessel,
where I was likely to lodge.

In these opportunities, my mind through the mercies of the Lord,
was kepi low in an inward waiting for his help;
and Friends having expressed their desire that I might
have a place more convenient than the steerage,
did not urge, but appeared disposed to leave me to the Lord.

Having staid two nights in Philadelphia, I went the next day to Darby Monthly Meeting;
where, through the strength of Divine love,
my heart was enlarged toward the youth then present;
under which I was helped to labour in some tenderness of spirit.
Then lodging at William Home`'s, I, with one Friend, went to Chester;
where meeting with Samuel Emlen, we went on board the 1st day of the fifth month, 1772:
and as I sat alone on the deck,
I felt a satisfactory evidence that my proceedings were not in my own will,
but under the power of the cross of Christ.

7th day of the fifth month: have had rough weather mostly, since I came on board;
and the passengers, James Reynolds, John Till Adams, Sarah Logan and her hired maid,
and John Bispham, all sea-sick, more or less, at times; from which sickness,
through the tender mercies of my heavenly Father, I have been preserved;
my afflictions now being of another kind.

There appeared an openness in the minds of the master
of the ship and in the cabin passengers toward me;
we were often together on the deck, and sometimes in the cabin.

My mind, through the merciful help of the Lord,
has been preserved in a good degree watchful, and inward; and I have this day,
great cause to be thankful that I continue to feel quietness of mind.

As my lodging in the steerage, now nearly a week,
has afforded me opportunities of seeing, hearing and feeling,
with respect to the life and spirit of many poor sailors;
an inward exercise of soul has attended me,
in regard to placing children and youth where they may be likely to
be exampled and instructed in the pure fear of the Lord.
Being much amongst the seamen, I have from a motion of love,
several times taken opportunities with one of them at a time alone;
and in a free conversation, laboured to turn their minds toward the fear of the Lord.
This day we had a meeting in the cabin,
where my heart was contrited under a feeling of Divine love.

Concerning lads being trained up as seamen;
I believe a communication by sea from one part of the world to other parts of it,
is at times, consistent with the will of our heavenly Father;
and to educate some youth in the practice of sailing, I believe may be right.
But how lamentable is the present corruption of the world! how
impure are the channels through which trade has a conveyance!
how great is the danger to which poor lads are exposed,
when placed on shipboard to learn the art of sailing!

Five lads training up for the seas, were now on board of this ship;
two of them brought up amongst our Society, and one has a right amongst Friends,
by name James Nayler, to whose father, James Nayler mentioned in Sewel`'s History,
appears to have been uncle.

I often feel a tenderness of heart toward these poor lads;
and at times look at them as though they were my children according to the flesh.

O that all may take heed and beware of covetousness!
O that all may learn of Christ,
who was meek and low of heart! and in faithfully following him,
he will teach us to be content with food and raiment,
without respect to the customs or honours of this world.

Men thus redeemed, will feel a tender concern for their fellow-creatures,
and a desire that those in the lowest stations may be assisted and encouraged;
and where owners of ships attain to the perfect law of liberty,
and are doers of the word, these will be blessed in their deeds.

A ship at sea commonly sails all night,
and the seamen take their watches four hours at a time.

Rising to work in the night, is not commonly pleasant in any case;
but in dark rainy nights it is very disagreeable,
even though each man were furnished with all conveniences.
But if men must go out at midnight to help manage the ship in the rain,
and having small room to sleep and lay their garments in,
are often beset to furnish themselves for the watch;
their garments or some thing relating to their business being wanting,
and not easily found; when from the urgency occasioned by high winds,
they are hastened and called up suddenly;
here is a trial of patience on the poor sailors, and the poor lads their companions.

If after they have been on deck several hours in the night,
they come down into the steerage soaking wet,
and are so closely stowed that proper convenience for
change of garment is not easily come at,
but for want of proper room their wet garments thrown in heaps,
and sometimes through much crowding, are trodden under foot,
in going to their lodgings and getting out of them, and great difficulty at times,
each one to find his own; here are trials on the poor sailors.

As I have been with them in my lodge, my heart has often yearned for them;
and tender desires been raised in me,
that owners and masters of vessels may dwell in the love of God,
and therein act uprightly; and by seeking less for gain,
and looking carefully to their ways,
may earnestly labour to remove all cause of provocation from the poor seamen,
either to fret or use excess of strong drink; for indeed the poor creatures at times,
in the wet and cold,
seem to apply to strong drink to supply the want of other conveniences.

Great reformation in the world is wanting,
and the necessity of it amongst those who do business on the great waters,
has at this time been abundantly opened before me.

The 8th day of the fifth month.--This morning the clouds gathered,
the wind blew strong from the south-eastward,
and before noon increased to a degree that made sailing appear dangerous.
The seamen then bound up some of their sails and took down some;
and the storm increasing, they put the dead lights, so called,
into the cabin windows and lighted a lamp as at night.

The wind now blew vehemently, and the sea wrought to such a degree,
that an awful seriousness prevailed in the cabin, in which I spent, I believe,
about seventeen hours; for I believed the poor wet toiling seamen,
had need of all the room in the crowded steerage,
and the cabin passengers had given me frequent invitations.

They ceased now from sailing, and put the vessel in the posture called lying-to.

My mind during this tempest, through the gracious assistance of the Lord,
was preserved in a good degree of resignation;
and I felt at times a few words in his love to my shipmates,
in regard to the all-sufficiency of Him who formed the great deep,
and whose care is so extensive, that a sparrow falls not without his notice.
Thus in a tender frame of mind I spoke to them of the necessity of our yielding,
in true obedience, to the instructions of our heavenly Father,
who sometimes through adversities, intendeth our refinement.

About eleven o`'clock at night I went out on the deck, when the sea wrought exceedingly,
and the high foaming waves, all around, had in some sort the appearance of fire;
but did not give much, if any light.
The sailor then at the helm, said he lately saw a corposant at the head of the mast.

About this time I observed the master of the ship ordered the carpenter to keep on deck;
and though he said little, I apprehended his care was,
that the carpenter with his axe might be in readiness, in case of any extremity.

Soon after this, the vehemency of the wind abated;
and before morning they again put the ship under sail.

The 10th day of the month and first of the week, being fine weather,
we had a meeting in the cabin, at which most of the seamen were present;
and to me it was a strengthening time.

The 13th day of the month.
As I continue to lodge in the steerage, I feel an openness this morning,
to express something further of the state of my mind,
in respect to lads bound apprentice to learn the art of sailing.
As I believe sailing is of some use in the world, a labour of soul attends me,
that the pure counsel of Truth may be humbly waited for, in this case,
by all concerned in the business of the seas.

A pious father, whose mind is exercised for the everlasting welfare of his child,
may not, with a peaceable mind, place him out to an employment amongst a people,
whose common course of life is manifestly corrupt and profane.
So great is the present defect amongst sea-faring men, in regard to piety and virtue,
and through an abundant traffic, and many ships of war,
so many people are employed on the sea,
that the subject of placing lads to this employment appears very weighty.

Profane examples are very corrupting and very forcible.
As my mind, day after day, and night after night,
has been affected with a sympathizing tenderness
toward children put to the employment of sailors,
I have sometimes had weighty conversation with the sailors in the steerage,
who were mostly respectful to me, and more so the longer I was with them.
They mostly appeared to take kindly what I said to them;
but their minds appeared to be so deeply impressed with
the almost universal depravity amongst sailors,
that the poor creatures in their answers to me on this subject,
revived in my remembrance, that of the degenerate Jews a little before the captivity,
as repeated by Jeremiah the prophet, "`There is no hope.`"

Under this exercise a sense of the desire of outward gain prevailing amongst us,
hath felt grievous; and a strong call to the professed followers of Christ,
hath been raised in me, that all may take heed, lest through loving this present world,
they be found in a continued neglect of duty,
with respect to a faithful labour for a reformation.

Silence, as to every motion proceeding from the love of money,
and an humble waiting upon God to know his will concerning us, appear necessary:
he alone is able to strengthen us to dig deep,
to remove all which lies between us and the safe foundation,
and so to direct us in our outward employments,
that pure universal love may shine forth in our proceedings.

Desires arising from the Spirit of Truth, are pure desires; and when a mind,
divinely opened toward a young generation, is made sensible of corrupting examples,
powerfully working and extensively spreading amongst them, how moving is the prospect!

There is a great trade to the coast of Africa for slaves;
of which I heard frequent conversation among the sailors!

A great trade in that which is raised and prepared through grievous oppression!

A great trade in superfluity of workmanship formed to
please the pride and vanity of people`'s minds!

Great and extensive is that depravity which prevails amongst the poor sailors!

When I remember that saying of the Most High, through his prophet,
"`This people have I formed for myself;
they shall show forth my praise,`" and think of placing children amongst them,
to learn the practice of sailing, the consistency of it with a pious education,
seems to me like that mentioned by the prophet, "`There is no answer from God.`"

In a world of dangers and difficulties, like a desolate thorny wilderness, how precious,
how comfortable, how safe, are the leadings of Christ, the good Shepherd; who said,
"`I know my sheep, and am known of mine.`"

The 16th day of the month.
Wind for several days past often high, what the sailors call squally,
rough sea and frequent rains.
This last night was a very trying one to the poor seamen;
the water during the chief part of it, running over the main deck,
and sometimes breaking waves came on the quarter deck.
The latter part of the night as I lay in bed,
my mind was humbled under the power of Divine love;
and resignedness to the great Creator of the earth and the seas,
was renewedly wrought in me,
whose fatherly care over his children felt precious to my soul.
Desires were now renewed in me,
to embrace every opportunity of being inwardly acquainted with
the hardships and difficulties of my fellow-creatures,
and to labour in his love for the spreading of pure universal righteousness on the earth.
The opportunities were frequent of hearing conversation amongst the sailors,
in respect to the voyages to Africa,
the manner of bringing the deeply oppressed slaves into our islands,
and their condition on board the vessels, frequently in chains and fetters,
with hearts loaded with grief, under the apprehensions of miserable slavery;
and my mind was frequently opened to meditate on these things.

On the 17th day of the month and first of the week, we had a meeting in the cabin;
to which the seamen generally came.
My spirit was contrite before the Lord; whose love at this time, affected my heart.

This afternoon I felt a lender sympathy of soul,
with my poor wife and family left behind;
in which state my heart was enlarged in desires that they may walk in that humble
obedience wherein the everlasting Father may be their guide and support,
through all the difficulties in this world; and a sense of that gracious assistance,
through which my mind hath been strengthened to take up the cross and leave them,
to travel in the love of Truth, begot thankfulness in my heart to our great Helper.

On the 24th day of the month and first of the week, a clear pleasant morning;
and as I sat on deck, I felt a reviving in my nature; which,
through much rainy weather and high winds, being shut up in a close unhealthy air,
was weakened.

Several nights of late I felt breathing so difficult,
that a little after the rising of the second watch, which is about midnight, I got up,
and stood, I believe, nearly an hour with my face near the hatchway,
to get the fresh air at a small vacancy under the hatch door,
which is commonly shut down, partly to keep out rain,
and sometimes to keep the breaking waves from dashing into the steerage.

I may, with thankfulness to the Father of mercies,
acknowledge that in my present weak state,
my mind hath been supported to bear the affliction with patience;
and I have looked at the present dispensation as
a kindness from the great Father of mankind,
who, in this my floating pilgrimage,
is in some degree bringing me to feel what many thousands of
my fellow-creatures often suffer in a greater degree.

My appetite failing, the trial has been the heavier;
and I have felt tender breathings in my soul after God, the fountain of comfort,
whose inward help has supplied, at times, the want of outward convenience:
and strong desires have attended me, that his family,
who are acquainted with the movings of his Holy Spirit,
may be so redeemed from the love of money,
and from that spirit in which men seek honour one of another;
that in all business by sea or land,
we may constantly keep in view the coming of his kingdom on earth, as it is in heaven;
and by faithfully following this safe guide, show forth examples,
tending to lead out of those things under which the creation groans!

This day we had a meeting in the cabin;
in which I was favoured in some degree to experience
the fulfilling of that saying of the prophet,
"`The Lord hath been a strength to the poor,
a strength to the needy in their distress;`" for which
my heart is bowed in thankfulness before him.

The 28th day of the month: wet weather of late, with small winds inclining to calms;
our seamen cast a lead, I suppose about one hundred fathoms, but found no bottom:
foggy weather this morning.

Through the kindness of the great Preserver of men, my mind remains quiet;
and a degree of exercise from day to day attends me,
that the pure peaceable government of Christ may spread and prevail amongst mankind.

The leading on of a young generation, in that pure way,
in which the wisdom of this world hath no place; where parents and tutors,
humbly waiting for the heavenly Counsellor,
may example them in the Truth as it is in Jesus, has for several days,
been the exercise of my mind.
O how safe, how quiet is that state,
where the soul stands in pure obedience to the voice of Christ,
and a watchful care is maintained, not to follow the voice of the stranger!

Here, Christ is felt to be our Shepherd;
and under his leading people are brought to a stability;
and where he doth not lead forward, we are bound in the bonds of pure love,
to stand still and wait upon him.
In the love of money, and in the wisdom of this world, business is proposed,
then the urgency of affairs pushes forward; nor can the mind in this state,
discern the good and perfect will of God concerning us.

The love of God is manifested in graciously calling us
to come out of that which stands in confusion;
but if we bow not in the name of Jesus; if we give not up those prospects of gain,
which in the wisdom of this world are open before us, but say in our hearts,
I must needs go on; and in going on, I hope to keep as near to the purity of Truth,
as the business before me will admit of; here the mind remains entangled,
and the shining of the light of life into the soul is obstructed.

This query opens in my mind in the love of Christ;
where shall a pious father place his son apprentice,
to be instructed in the practice of crossing the seas; and have faith to believe,
that Christ our holy Shepherd leads him to place his son there?

Surely the Lord calls to mourning and deep humiliation,
that in his fear we may be instructed,
and led safely on through the great difficulties and perplexities of the present age.

In an entire subjection of our wills, the Lord graciously opens a way for his people,
where all their wants are bounded by his wisdom;
and here we experience the substance of what Moses the
prophet figured out in the water of separation,
as a purification from sin.

Esau is mentioned as a child red all over, like a hairy garment:
in Esau is represented the natural will of man.
In preparing the water of separation, a red heifer without blemish,
on which there had been no yoke, was to be slain,
and her blood sprinkled by the priest seven
times toward the tabernacle of the congregation.
Then her skin, her flesh, and all pertaining to her, were to be burnt without the camp;
and of her ashes the water was prepared.
Thus the crucifying of the old man, or natural will, is represented;
and hence comes a separation from that carnal mind, which is death.

"`He who toucheth the dead body of a man,
and purifieth not himself with the water of separation,
he defileth the tabernacle of the Lord; he is unclean.`"

If any through the love of gain, go forth into business,
wherein they dwell as amongst the tombs, and touch the bodies of those who are dead:
if these, through the infinite love of God,
feel the power of the cross of Christ to crucify them to the world,
and therein learn humbly to follow the Divine Leader;
here is the judgment of this world--here the prince of this world is cast out.

The water of separation is felt; and though we have been amongst the slain,
and through the desire of gain have touched the dead body of a man;
yet in the purifying love of Christ, we are washed in the water of separation,
are brought off from that business, from that gain, and from that fellowship,
which are not agreeable to his holy will.
I have felt a renewed confirmation in the time of this voyage, that the Lord,
in his infinite love, is calling to his visited children,
so to give up all outward possessions and means of getting treasures,
that his Holy Spirit may have free course in their hearts,
and direct them in all their proceedings.

To feel the substance pointed at in this figure, man must know death, as to his own will.

"`No man can see God, and live:`" This was spoken by the Almighty to Moses the prophet;
and opened by our blessed Redeemer.

As death comes on our own wills, and a new life is formed in us,
the heart is purified and prepared to understand clearly.
"`Blessed are the pure in heart, for they shall see God.`"
In purity of heart,
the mind is Divinely opened to behold the nature of universal righteousness,
or the righteousness of the kingdom of God.
"`No man hath seen the Father, save he that is of God; he hath seen the Father.`"

The natural mind is active about the things of this life; and in this natural activity,
business is proposed, and there is a will in us to go forward in it.
And as long as this natural will remains unsubjected,
so long there remains an obstruction against the
clearness of Divine light operating in us;
but when we love God with all our heart, and with all our strength,
then in this love we love our neighbours as ourselves;
and a tenderness of heart is felt toward all people for whom Christ died,
even such who as to outward circumstances may be
to us as the Jews were to the Samaritans.
"`Who is my neighbour?`"
See this question answered by our Saviour, Luke 10:30.

In this love we can say, that Jesus is the Lord;
and the reformation in our souls is manifested in a full reformation of our lives,
wherein all things are new, and all things are of God; 2 Cor. 5:18.,
in this the desire of gain is subjected.

When employment is honestly followed in the light of Truth;
and people become diligent in business, "`fervent in spirit,
serving the Lord,`" the name is opened; "`This is the name by which he shall be called,
The Lord our righteousness.`"
Oh, how precious is this name!
It is like ointment poured out.

The chaste virgins are in love with the Redeemer;
and for promoting his peaceable kingdom in the world,
are content to endure hardness like good soldiers;
and are so separated in spirit from the desire of riches, that in their employments,
they become extensively careful to give no offence, either to Jews, or heathen,
or the church of Christ.

On the 31st day of the month, and first of the week, we had a meeting in the cabin,
with nearly all the ship`'s company; the whole being nearly thirty.
In this meeting the Lord, in mercy, favoured us with the extendings of his love.

The 2nd day of the sixth month.
Last evening the seamen found bottom at about twenty fathoms.

This morning there was a fair wind, and it was pleasant:
as I sat on deck my heart was overcome with the love of Christ,
and melted into contrition before him: and in this state, the prospect of that work,
to which I have felt my mind drawn when in my native land,
being in some degree opened before me, I felt like a little child;
and my cries were put up to my heavenly Father for preservation,
that in a humble dependence on him, my soul may be strengthened in his love,
and kept inwardly waiting for his counsel.

This afternoon we saw that part of England called the Lizard.

Some dunghill fowls yet remained of those the passengers took for their sea-stores:
I believe about fourteen perished in the storms at sea,
by the waves breaking over the quarterdeck; and a considerable number with sickness,
at different times.
I observed the cocks crew coming down the Delaware, and while we were near the land;
but afterward,
I think I did not hear one of them crow till we came near the land in England,
when they again crowed a few times.

In observing their dull appearance at sea, and the pining sickness of some of them,
I often remembered the fountain of Goodness, who gave being to all creatures,
and whose love extends even to caring for the sparrows; and I believe,
where the love of God is verily perfected,
and the true spirit of government watchfully attended to,
a tenderness toward all creatures made subject to us will be experienced;
and a care felt, that we do not lessen that sweetness of life, in the animal creation,
which the great Creator intends for them under our government.

The 4th day of the month.
Wet weather, with high winds, and so dark that we could see but a little way.
I perceived our seamen were apprehensive of missing the channel;
which I understood was narrow.
In a while it grew lighter; and they saw the land, and knew where we were.
Thus the Father of mercies was pleased to try us with the sight of dangers,
and then graciously from time to time deliver from them; sparing our lives,
that in humility and reverence, we may walk before him, and put our trust in him.

About noon a pilot came off from Dover;
where my beloved friend Samuel Emlen went on shore, and thence to London,
about seventy-two miles by land; but I felt easy in staying in the ship.

The 7th day of the month, and first of the week.
A clear morning; we lay at anchor for the tide,
and had a parting meeting with the ship`'s company;
in which my heart was enlarged in a fervent concern for them,
that they may come to experience salvation through Christ.
Had a head wind up the Thames; sometimes lay at anchor, and saw many ships passing,
and some at anchor near;
and had large opportunity of feeling the spirit in
which the poor bewildered sailors too generally live.
That lamentable degeneracy, which so much prevails among the people employed on the seas,
so affected my heart, that I may not easily convey to another the feeling I have had.

The present state of a sea-faring life in general,
appears so opposite to a pious education; so full of corruption,
and extreme alienation from God; so full of examples, the most dangerous to young people,
that in looking toward a young generation, I feel a care for them,
that they may have an education different from the present education of lads at sea:
and that all of us, who are acquainted with the pure Gospel spirit,
may lay this case to heart,
may remember the lamentable corruptions which attend
the conveyance of merchandise across the seas,
and so abide in the love of Christ, that being delivered from the love of money,
from the entangling expences of a curious, delicate and luxurious life,
we may learn contentment with a little; and promote the sea-faring life no further,
than that spirit, which leads into all truth, attends us in our proceedings.

