== Considerations on Pure Wisdom and Human Policy; On Labour; On Schools; and On the Right Use of the Lord`'s Outward Gifts.

First Printed In The Year 1768.

"`The wisdom that is from above, is first pure, then peaceable, gentle,
and easy to be entreated, full of mercy and good fruits, without partiality,
and without hypocrisy.`" James 3:17.


=== Introduction

My mind hath often been affected with sorrow,
on account of the prevailing of that spirit,
which leads from an humble waiting on the inward teaching of Christ,
to pursue ways of living, attended with unnecessary labour,
and which draws forth the minds of many people to seek after outward power,
and to strive for riches, which frequently introduce oppression,
and bring forth wars and grievous calamities.

It is with reverence that I acknowledge the mercies of our heavenly Father,
who in infinite love visited me in my youth, and wrought a belief in me,
that through true obedience a state of inward purity may be known in this life,
in which we may love mankind in the same love with which our Redeemer loveth us,
and therein learn resignation to endure hardships for the real good of others.

"`While the eye is single, the whole body is full of light;`" but for want of this,
selfish desires and an imaginary superiority, darken the mind;
hence injustice frequently proceeds; and where this is the case,
to convince the judgment, is the most effectual remedy.

Where violent measures are pursued in opposing injustice,
the passions and resentments of the injured,
frequently operate in the prosecution of their designs;
and after conflicts productive of very great calamities,
the minds of contending parties often remain as little
acquainted with the pure principle of Divine love,
as they were before;
but where people walk in that pure light in which all their "`works are
wrought in God,`" and under oppression persevere in the meek spirit,
and abide firm in the cause of Truth, without actively complying with oppressive demands,
through these the Lord hath often manifested his power,
in opening the understandings of others, to the promoting of righteousness in the earth.

A time I believe is coming, wherein this Divine work will so spread and prevail,
that "`Nation shall not lift up sword against nation, nor learn war any more.`"
And as we, through the tender mercies of God, do feel that this precious work is begun,
I am concerned to encourage my brethren and sisters in a holy care and diligence,
that each of us may so live under the sanctifying power of Truth,
as to be redeemed from all unnecessary cares; that our eye being single to him,
no customs, however prevalent, which are contrary to the wisdom from above,
may hinder us from faithfully following his holy leadings,
in whatsoever he may graciously appoint for us.

=== Considerations, etc.

To have our trust settled in the Lord,
and not to seek after nor desire outward treasures,
any further than his holy Spirit leads us therein, is a happy state,
as saith the prophet, "`Blessed is the man that trusteth in the Lord,
and whose hope the Lord is.`"

Pure wisdom leads people into lowliness of mind,
in which they learn resignation to the Divine will,
and contentment in suffering for his cause,
when they cannot keep a clear conscience without suffering.

In this pure wisdom the mind is attentive to the
root and original spring of motions and desires;
and as we know "`the Lord to be our refuge,`" and find
no safety but in humbly walking before him,
we feel an holy engagement,
that every desire which leads therefrom may be brought to judgment.

While we proceed in this precious way,
and find ardent longings for a full deliverance from every thing which defiles,
all prospects of gain that are not consistent with the wisdom from above,
are considered as snares, and an inward concern is felt,
that we may live under the cross, and faithfully attend to that holy Spirit,
which is sufficient to preserve out of them.

When I have considered that saying of Christ,
"`Lay not up for yourselves treasures upon earth,`" his
omnipotence hath often occurred to my mind.

While we believe that he is every where present with his people,
and that perfect goodness, wisdom and power, are united in him,
how comfortable is the consideration.

Our wants may be great, but his power is greater.
We may be oppressed and despised,
but he is able to turn our patient sufferings into profit to ourselves,
and to the advancement of his work on earth.
His people who feel the power of his cross, to crucify all that is selfish in them,
who are engaged in outward concerns, from a convincement that it is their duty,
and resign themselves and their treasures to him;
these feel that it is dangerous to give way to that in us,
which craves riches and greatness in this world.

As the heart truly contrite,
earnestly desires "`to know Christ and the fellowship of his
sufferings,`" so far as the Lord for gracious ends may lead into them;
as such feel that it is their interest to put their trust in God,
and to seek no gain but that which he by his holy Spirit, leads into; so on the contrary,
they who do not reverently wait for this Divine Teacher, and are not humbly concerned,
according to their measure,
"`to fill up that which is behind of the afflictions of Christ,`" in
patiently suffering for the promotion of righteousness in the earth;
but have an eye toward the power of men and the outward advantage of wealth,
these are often attentive to those employments which appear profitable,
even though the gains arise from such trade and
business as proceed from the workings of that spirit,
which is estranged from the self-denying life of an humble contrite Christian.

While I write on this subject,
I feel my mind tenderly affected toward those honestly disposed people,
who have been brought up in employments attended with these difficulties.

To such I may say, in the feeling of our heavenly Father`'s love,
and number myself with you,
O that our eyes may be single to the Lord! may we reverently wait on
him for strength to lay aside all unnecessary expense of every kind,
and learn contentment in a plain simple life.

May we in lowliness submit to the leadings of his spirit,
and enter upon any outward employ which he graciously points out to us,
and then whatever difficulties arise in consequence of our faithfulness,
I trust they will work for our good.

Small treasure to a resigned mind is sufficient.
How happy is it to be content with a little, to live in humility, and feel that in us,
which breathes out this language, Abba!
Father.

If that called the wisdom of this world, had no resemblance of true wisdom,
the name of wisdom, I suppose, had not been given to it.

As wasting outward substance to gratify vain desires, on one hand;
so slothfulness and neglect on the other,
do often involve men and their families in trouble, and reduce them to want and distress.
To shun both these vices is good in itself, and hath a resemblance of wisdom;
but while people thus provident, have it principally in view to get riches and power,
and the friendship of this world,
and do not humbly wait for the Spirit of Truth to lead them in purity; these,
through an anxious care to obtain the end desired,
reach forth for gain in worldly wisdom, and in regard to their inward state,
fall into divers temptations and snares.
And though such may think of applying wealth to good purposes,
and to use their power to prevent oppression,
yet wealth and power are often applied otherwise;
nor can we depart from the leadings of our holy Shepherd, without going into confusion.

Great wealth is frequently attended with power,
which nothing but Divine love can qualify the mind to use rightly;
and as to the humility and uprightness of our children after us,
how great is the uncertainty!
If, in acquiring wealth, we take hold on the wisdom which is from beneath,
and depart from the leadings of Truth, and example our children herein,
we have great cause to apprehend that wealth may be a snare to them,
and prove an injury to others, over whom their wealth may give them power.

To be redeemed from that wisdom which is from beneath,
and to walk in the light of the Lord, is a precious situation;
thus his people are brought to put their trust in him;
and in this humble confidence in his wisdom, goodness and power,
the righteous find a refuge in adversities, superior to the greatest outward help,
and a comfort more certain than any worldly advantages can afford.

=== On Labour.

Having from my childhood been used to bodily labour for a living,
I may express my experience therein.

Right exercise affords an innocent pleasure in the time of it,
and prepares us to enjoy the sweetness of rest; but from the extremes each way,
arise inconveniences.

Moderate exercise opens the pores, gives the blood a lively circulation,
and enables us to judge rightly respecting that
portion of labour which is the true medium.

"`The fowls of the air sow not, nor gather into barns,
yet our heavenly Father feedeth them;`" nor do I believe that
infinite goodness and power would have allotted labour to us,
had he not seen that labour was proper for us in this life.

The original design and true medium of labour,
is a subject that to me appears worthy of our serious consideration.

Idle men are often a burthen to themselves, neglect the duty they owe to their families,
and become burdensome to others also.

As outward labour directed by the wisdom from above,
tends to our health and adds to our happiness in this life; so on the contrary,
entering upon it in a selfish spirit, and pursuing it too long, or too hard,
have a contrary effect.

I have observed that too much labour not only makes the understanding dull,
but so intrudes upon the harmony of the body, that after ceasing from our toil,
we have another to pass through,
before we can be so composed as to enjoy the sweetness of rest.

From too much labour in the heat, frequently proceed immoderate sweats,
which often I believe open the way for disorders and impair our constitutions.

When we go beyond the true medium, and feel weariness approaching,
but think business may suffer if we cease,
at such a time spirituous liquors are frequently taken,
with a view to support nature under these fatigues.

I have found that too much labour in the summer heats the blood,
that taking strong drink to support the body under such labour, increaseth that heat,
and though a person may be so far temperate as not to manifest the least disorder,
yet the mind in such a circumstance, doth not retain that calmness and serenity,
in which we should endeavour to live.

Thus toiling in the heat and drinking strong liquor,
make men more resolute and less considerate,
and tend very much to disqualify for following him who is meek and low of heart.

As laying out more business than is consistent with pure wisdom is an evil,
so this evil frequently leads into more.
Too much business leads to hurry.
In the hurry and toil strong drink is often used,
and hereby many proceed to noise and wantonness, and some, though more considerate,
do often suffer loss, as to a true composedness of mind.

I feel sincere desires in my heart that no rent or interest
may be laid so high as to be a snare to tenants;
and that no desires of gain may draw any too far in business.
That no cares to support customs, which have not their foundation in pure wisdom,
may have place in our minds, but that we may build on the sure foundation,
and feel our holy Shepherd to lead us, who alone is able to preserve us,
and bring forth from every thing which defiles.

Having several times in my travels,
had opportunity to observe the labour and manner of life of great numbers of slaves,
it appears to me that the true medium is lamentably neglected by many,
who assign them their portion of labour.

Without saying much at this time, concerning buying and selling men for term of life,
who have as just a right to liberty as we have;
nor about the great miseries and effusion of blood,
consequent on promoting the slave-trade; and to speak as favourably as may be,
with regard to continuing those in bondage who are amongst us,
we cannot say there is no partiality in it:
for whatever tenderness may be manifested by individuals in their life time toward them,
yet for people to be transmitted from a man to his posterity,
in the helpless condition of slaves,
appears inconsistent with the nature of the Gospel spirit.
From such proceedings it often follows, that persons in the decline of life,
are deprived of monies equitably due to them, and committed to the care,
and subjected to the absolute power, of young inexperienced men,
who know but little about the weakness of old age,
nor understand the language of declining life.

Where parents give their estates to their children,
and then depend on them for a maintenance, they sometimes meet with great inconveniences;
but if the power of possession thus obtained,
often reverses the obligations of gratitude and filial duty,
and makes manifest that youth are often ignorant of the language of old age,
how hard is the case of ancient negroes who, deprived of the wages equitably due to them,
are left to young people, who have been used to look upon them as their inferiors.

For men to behold the fruits of their labour withheld from them, and possessed by others,
and in old age to find themselves destitute of those comfortable accommodations,
and that tender regard, which their time of life requires.
When they feel pains, and stiffness in their joints and limbs, weakness of appetite,
and that a little labour is wearisome,
and still behold themselves in the neglected uncomfortable condition of a slave,
and oftentimes to a young unsympathizing man.
For men to be thus treated from one generation to another who,
besides their own distresses, think on the slavery entailed on their posterity,
and are grieved,
what disagreeable thoughts must they have of the professed followers
of Jesus! and how must their groans ascend to that Almighty Being,
who "`will be a refuge for the oppressed.`"

=== On Schools.

"`Suffer little children to come unto me, and forbid them not,
for of such is the kingdom of God.`" Mark 10:14.


To encourage children to do things with a view to get the praise of men,
to me appears an obstruction to their being inwardly acquainted with the Spirit of Truth.
For it is the work of the holy Spirit to direct the mind to God,
that in all our proceedings we may have a single eye to him; to give alms in secret,
to fast in secret, and labour to keep clear of that disposition reproved by our Saviour,
"`But all their works they do for to be seen of men.`"

That Divine light which enlightens all men,
I believe does often shine in the minds of children very early,
and humbly to wait for wisdom,
that our conduct toward them may tend to forward their acquaintance with it,
and to strengthen them in obedience thereto, appears to me to be a duty on all of us.

By cherishing the spirit of pride, and the love of praise in them,
I believe they may sometimes improve faster in learning, than otherwise they would,
but to take measures to forward children in learning,
which naturally tend to divert their minds from true humility,
appears to me to savour of the wisdom of this world.

If tutors are not acquainted with sanctification of spirit,
nor experienced in an humble waiting for the leadings of Truth,
but follow the maxims of the wisdom of this world, children who are under their tuition,
appear to me to be in danger of imbibing thoughts and
apprehensions reverse to that meekness and lowliness of heart,
which is necessary for all the true followers of Christ.

Children at an age fit for schools,
are in a time of life which requires the patient attention of pious people,
and if we commit them to the tuition of those whose minds we believe are not
rightly prepared to "`train them up in the nurture and admonition of the Lord,`" we
are in danger of not acting the part of faithful parents toward them;
for our heavenly Father doth not require us to do evil, that good may come of it;
and it is needful that we deeply examine ourselves,
lest we get entangled in the wisdom of this world, and through wrong apprehensions,
take such methods in education, as may prove a great injury to the minds of our children.

It is a lovely sight to behold innocent children-;
and when they are sent to schools where their tender minds are
in imminent danger of being led astray by tutors,
who do not live a self-denying life,
or by the conversation of children who do not live in innocence,
it is a case much to be lamented.

While a pious tutor has the charge of no more children than he can take due care of,
and keeps his authority in the Truth, the good spirit in which he leads and governs,
works on the minds of such who are not hardened,
and his labours not only tend to bring them forward in outward learning,
but to open their understanding with respect to the true Christian life.
But where a person has charge of too many,
and his thoughts and time are so much employed in the outward affairs of his school,
that he does not so weightily attend to the spirit and conduct of each individual,
as to be enabled to administer rightly to all in due season;
through such omissions he not only suffers, as to the state of his own mind,
but the minds of the children are in danger of suffering also.

To watch the spirit of children, to nurture them in Gospel love,
and labour to help them against that which would mar the beauty of their minds,
is a debt we owe them; and a faithful performance of our duty,
not only tends to their lasting benefit, and our own peace,
but also to render their company agreeable to us.

Instruction thus administered,
reaches the pure witness in the minds of children who are not hardened,
and begets love in them toward those who thus lead them on;
but where too great a number are committed to a tutor, and he, through much cumber,
omits a careful attention to the minds of the children,
there is a danger of disorders gradually increasing amongst them,
until the effects thereof appear in their conduct, too strong to be easily remedied.

A care hath lived on my mind, that more time might be employed by parents at home,
and by tutors at school,
in weightily attending to the spirit and inclinations of children,
and that we may so lead, instruct and govern them, in this tender part of life,
that nothing may be omitted which is in our power,
to help them on their way to become the children of our Father, who is in heaven.

Meditating on the situation of schools in our provinces,
my mind has at times been affected with sorrow,
and under these exercises it has appeared to me,
that if those who have large estates were faithful stewards, and laid no rent,
or interest, or other demand, higher than is consistent with universal love;
and those in lower circumstances would, under a moderate employ,
shun unnecessary expense, even to the smallest article,
and all unite in humbly seeking to the Lord, he would graciously instruct us,
and strengthen us,
to relieve the youth from various snares in which many of them are entangled.

=== On the Right Use of the Lord`'s Outward gifts.

As our understandings are opened by the pure light,
we experience that through an inward approaching to God,
the mind is strengthened in obedience;
and that by gratifying those desires which are not of his begetting,
these approaches to him are obstructed, and the deceivable spirit gains strength.

These truths being as it were engraven upon our hearts,
and our everlasting interest in Christ evidently concerned therein,
we become fervently engaged,
that nothing may be nourished which tends to feed pride or self-love in us.
Thus in pure obedience, we are not only instructed in our duty to God,
but also in the affairs which necessarily relate to this life,
and the Spirit of Truth which guides into all truth,
leavens the mind with a pious concern, that "`whatsoever we do in word or deed,
may be done in His name.`"

Hence such buildings, furniture, food and raiment, as best answer our necessities,
and are the least likely to feed that selfish spirit which is our enemy,
are the most acceptable to us.

In this state the mind is tender, and inwardly watchful,
that the love of gain draw us not into any business
which may weaken our love to our heavenly Father,
or bring unnecessary trouble to any of his creatures.

Thus the way gradually opens to cease from that spirit
which craves riches and things fetched far,
which so mixes with the customs of this world,
and so intrudes upon the true harmony of life,
that the right medium of labour is very much departed from.
As the minds of people are settled in a steady concern,
not to hold or possess anything but what may be held
consistently with the wisdom which is from above,
they consider what they possess as the gift of God, and are inwardly exercised,
that in all parts of their conduct they may act agreeably to
the nature of the peaceable government of Christ.

A little supports such a life; and in a state truly resigned to the Lord,
the eye is single to see what outward employ he leads into as a means of our subsistence,
and a lively care is maintained to hold to that, without launching further.

There is a harmony in the several parts of this divine work in the hearts of people:
he who leads them to cease from those gainful employments,
carried on in that wisdom which is from beneath,
delivers also from the desire after worldly greatness,
and reconciles the mind to a life so plain, that a little suffices.

Here the real comforts of life are not lessened.
Moderate exercise, in the way of true wisdom, is pleasant both to mind and body.

Food and raiment sufficient, though in the greatest simplicity,
is accepted with contentment and gratitude.

The mutual love subsisting between the faithful followers of Christ,
is more pure than that friendship which is not seasoned with humility,
how specious soever the appearance.

Where people depart from pure wisdom in one case,
it is often an introduction to depart from it in many more;
and thus a spirit which seeks for outward greatness,
and leads into worldly wisdom to attain it and support it, gets possession of the mind.

In beholding the customary departure from the true medium of labour,
and that unnecessary toil which many go through, in supporting outward greatness,
and procuring delicacies;
in beholding how the true calmness of life is changed into hurry, and how many,
by eagerly pursuing outward treasure,
are in great danger of withering as to the inward state of the mind;
in meditating on the works of this spirit,
and on the desolations it makes amongst the professors of Christianity,
I may thankfully acknowledge, that I often feel pure love beget longings in my heart,
for the exaltation of the peaceable kingdom of Christ,
and an engagement to labour according to the gift bestowed on me,
for promoting an humble, plain, temperate way of living:
a life where no unnecessary cares or expenses may encumber our minds,
or lessen our ability to do good; where no desires after riches,
or greatness may lead into hard dealing; where no connexions with worldly minded men,
may abate our love to God, or weaken a true zeal for righteousness:
a life wherein we may diligently labour for resignedness to do
and suffer whatever our heavenly Father may allot for us,
in reconciling the world to himself.

When the prophet Isaiah had uttered his vision,
and declared that a time was coming wherein "`swords should be beaten into ploughshares,
and spears into pruning-hooks, and that nation should not lift up sword against nation,
neither shall they learn war any more;`" he immediately
directs the minds of people to the Divine teacher,
in this remarkable language: "`O house of Jacob,
come ye and let us walk in the light of the Lord.`"

To wait for the direction of this light, in all temporal as well as spiritual concerns,
appears necessary; for if in any case we enter lightly into temporal affairs,
without feeling this Spirit of Truth to open our way therein,
and through the love of this world proceed on,
and seek for gain by that business or traffic, which "`is not of the Father,
but of the world,`" we fail in our testimony to the purity and peace of his government,
and get into that which is for chastisement.

This matter hath lain heavy on my mind, it being evident, that a life less humble,
less simple and plain, than that which Christ leads his sheep into,
necessarily requires a support, for which pure wisdom does not provide;
hence there is no probability of our being "`a peculiar people, so zealous of good works,
as to have no fellowship with works of darkness,`" while we
have wants to supply which have their foundation in custom,
and do not come within the meaning of those expressions,
"`your heavenly Father knoweth that ye have need of all these things.`"

Those things which he beholds to be necessary for his people,
he fails not to give them in his own way and time; but as his ways are above our ways,
and his thoughts above our thoughts,
so imaginary wants are different "`from those
things which he knoweth that we have need of.`"

As my meditations have been on these things,
compassion hath filled my heart toward my fellow-creatures, involved in customs,
which have grown up in "`the wisdom of this world, which is foolishness with God.`"
O that the youth may be so thoroughly experienced in an humble walking before the Lord,
that they may be his children, and know him to be their refuge,
their safe unfailing refuge,
through the various dangers attending this uncertain state of being.

If those whose minds are redeemed from the love of wealth,
and who are contented with a plain, simple way of living,
find that to conduct the affairs of a family,
without giving countenance to unrighteous proceedings,
or having fellowship with works of darkness, the most diligent care is necessary;
If customs, distinguishable from universal righteousness,
and opposite to the true self-denying life, are now prevalent, and so mixed with trade,
and with almost every employ,
that it is only through humble waiting on the inward guidance of Truth,
that we may reasonably hope to walk safely,
and support an uniform testimony to the peaceable government of Christ;
if this be the case, how lamentably do they expose themselves to temptations,
who give way to the love of riches, conform to expensive living,
and reach forth for gain, to support customs which our holy Shepherd leads not into.


