== Remarks On Sundry Subjects.

First Printed In London, 1773.

=== Chapter I.On Loving our Neighbours As Ourselves.

When we love the Lord with all our hearts, and his creatures in his love,
we are then preserved in tenderness both toward mankind and the animal creation;
but if another spirit gets room in our minds, and we follow it in our proceedings,
we are then in the way of disordering the affairs of society.

If a man, successful in business, expends part of his income in things of no real use,
while the poor employed by him pass through great
difficulties in getting the necessaries of life,
this requires his serious attention.

If several principal men in business unite in
setting the wages of those who work for hire,
and therein have regard to a profit to themselves
answerable to unnecessary expense in their families,
while the wages of the others on a moderate industry
will not afford a comfortable living for their families,
and a proper education for their children;
this is like laying a temptation in the way of some to
strive for a place higher than they are in,
when they have not stock sufficient for it.

I feel a concern in the spring of pure love,
that all who have plenty of outward substance,
may example others in the right use of things;
may carefully look into the condition of poor people,
and beware of exacting on them with regard to their wages.

While hired labourers, by moderate industry, through the Divine blessing,
may live comfortably, rear up families, and give them suitable education,
it appears reasonable for them to be contented with their wages.

If they who have plenty, love their fellow-creatures in that love which is Divine,
and in all their proceedings have an equal regard to the good of mankind universally,
their place in society is a place of care, an office requiring attention,
and the more we possess, the greater is our trust, and with an increase of treasure,
an increase of care becomes necessary.

When our will is subject to the will of God, and in relation to the things of this world,
we have nothing in view,
but a comfortable living equally with the rest of our fellow-creatures,
then outward treasures are no further desirable than as
we feel a gift in our minds equal to the trust,
and strength to act as dutiful children in His service, who bath formed all mankind,
and appointed a subsistence for us in this world.

A desire for treasures on any other motive,
appears to be against that command of our blessed Saviour,
"`Lay not up for yourselves treasures on earth.`"

He forbids not laying up in the summer against the wants of winter;
nor doth he teach us to be slothful in that which
properly relates to our being in this world;
but in this prohibition he puts in yourselves,
"`Lay not up for yourselves treasures on earth.`"

Now in the pure light, this language is understood,
for in the love of Christ there is no respect of persons; and while we abide in his love,
we live not to ourselves, but to him who died for us.
And as we are thus united in spirit to Christ,
we are engaged to labour in promoting that work in the earth for which he suffered.

In this state of mind our desires are,
that every honest member in society may have a portion of treasure and share of trust,
answerable to that gift, with which our heavenly Father hath gifted us.

In great treasure, there is a great trust.

A great trust requireth great care.

But the laborious mind wants rest.

A pious man is content to do a share of business in society,
answerable to the gifts with which he is endowed,
while the channels of business are free from unrighteousness,
but is careful lest at any time his heart be overcharged.

In the harmonious spirit of society "`Christ is all in all.`"

Here it is that "`old things are put away, all things are become new,
all things are of God,`" and the desire for outward riches is at an end.

They of low degree who have small gifts, enjoy the help of those who have large gifts;
those with small gifts, have a small degree of care, while those with large gifts,
have a large degree of care: and thus to abide in the love of Christ,
and enjoy a comfortable living in this world,
is all that is aimed at by those members in society,
to whom Christ is made wisdom and righteousness.

But when they who have much treasure, are not faithful stewards of the gifts of God,
great difficulties attend.

This matter hath deeply affected my mind.
The Lord, through merciful chastisements, hath given me a feeling of that love,
in which the harmony of society standeth,
and a sight of the growth of that seed which bringeth
forth wars and great calamities in the world;
and a labour attends me to open it to others.

To act with integrity,
according to that strength of mind and body with
which our Creator hath endowed each of us,
appears necessary for all, and he who thus stands in the lowest station,
appears to be entitled to as comfortable and convenient a living,
as he whose gifts of mind are greater, and whose cares are more extensive.

If some endowed with strong understanding as men, abide not in the harmonious state,
in which we "`love our neighbours as ourselves,`" but walk in that spirit in
which the children of this world are wise in their generation;
these by the strength of contrivance may sometimes gather great treasure.
But the wisdom of this world is foolishness with God;
and if we gather treasures in worldly wisdom, we lay up "`treasures for ourselves;`"

and great treasures managed in any other spirit, than the Spirit of Truth,
disorder the affairs of society,
for hereby the good gifts of God in his outward
creation are turned into the channels of worldly honour,
and frequently applied to support luxury, while the wages of poor labourers are such,
that with moderate industry and frugality they may not live comfortably,
rear up families, and give them suitable education,
but through the straightness of their condition,
are often drawn on to labour under weariness, to toil through hardships themselves,
and frequently to oppress those useful animals with which we are entrusted.

From age to age, throughout all ages.
Divine love is that alone, in which dominion has been, is, and will be rightly conducted.

In this the endowments of men are so employed,
that the friend and the governor are united in one,
and oppressive customs come to an end.

Riches in the hands of individuals in society, are attended with some degree of power;
and so far as power is put forth separate from pure love,
so far the government of the Prince of peace is interrupted;
and as we know not that our children after us will
dwell in that state in which power is rightly applied,
to lay up riches for them appears to be against the nature of his government.

The earth, through the labour of men, under the blessing of Him who formed it,
yieldeth a supply for the inhabitants from generation to generation,
and they who walk in the pure light,
have their minds prepared to taste and relish
not only those blessings which are spiritual,
but also feel a sweetness and satisfaction in a right
use of the good gifts of God in the visible creation.

Here we see that man`'s happiness stands not in great possessions,
but in a heart devoted Jo follow Christ, in that use of things,
where customs contrary to universal love have no power over us.

In this state our hearts are prepared to trust in God,
and our desires for our children and posterity are, that they,
with the rest of mankind in ages to come, may be of that number of whom he hath said,
"`I will be a father to them, and they shall be my sons and daughters.`"

When wages in a fruitful land bear so small a proportion to the necessaries of life,
that poor honest people who have families,
cannot by a moderate industry attain to a comfortable living,
and give their children sufficient learning,
but must either labour to a degree of oppression,
or else omit that which appears to be a duty; while this is the case with the poor,
there is an inclination in the minds of most people,
to prepare at least so much treasure for their children,
that they with care and moderate industry may live free
from the hardships which the poor pass through.

This subject requires our serious consideration:
to labour that our children may be put in a way to live comfortably,
appears in itself to be a duty,
so long as our labours are consistent with universal righteousness;
but if in striving to shun poverty,
we do not walk in that state where "`Christ is our life,`" then we wander.
"`He that hath the Son, hath life.`"
"`This life is the light of men.`"
If we walk not in this light, we walk in darkness, and "`he that walketh in darkness,
knoweth not whither he goeth.`"

To keep to right means in labouring to attain a right end is necessary:
if in striving to shun poverty,
we strive only in that state where Christ is the light of our life,
our labours will stand in the true harmony of society;
but if people are confident that the end aimed at is good,
and in this confidence pursue it so eagerly,
as not to wait for the Spirit of Truth to lead them, then they come to loss.
"`Christ is given to be a leader and commander of the people.`"
Again, "`The Lord shall guide thee continually.`"
Again, "`Lord, thou wilt ordain peace for us,
for thou also hast wrought all our works in us.`"
"`In the Lord have we righteousness and strength.`"

In this state our minds are preserved watchful in following
the leadings of his spirit in all our proceedings,
and a care is felt for a reformation in general; that our own posterity,
with the rest of mankind in succeeding ages, may not be entangled by oppressive customs,
transmitted to them through our hands.
But if people in the narrowness of natural love,
are afraid that their children will be oppressed by the rich,
and through an eager desire to get treasures,
depart from the pure leadings of Truth in one case,
though it may seem to be a small matter,
yet the mind even in that small matter may be
emboldened to continue in a way of proceeding,
without waiting for the Divine Leader.

Thus people may grow expert in business, wise in the wisdom of this world,
retain a fair reputation amongst men, and yet being strangers to the voice of Christ,
the safe leader of his flock, the treasures thus gotten,
may be like snares to the feet of their posterity.

In keeping faithful to the pure Counsellor,
and under trying circumstances suffering adversity for righteousness sake,
there is a reward.

If we being poor, are hardly dealt with by those who are rich,
and under this difficulty are frugal and industrious,
and in true humility open our case to them who oppress us,
this may reach the pure witness in their minds;
and though we should remain under difficulties as to the outward,
yet if we abide in the love of Christ, all will work for our good.

When we feel what it is to suffer in the true suffering state,
we experience the truth of those expressions,
that "`as the sufferings of Christ abound in us,
so our consolation aboundeth by Christ.`"

But if poor people who are hardly dealt with, do not attain to the true suffering state,
do not labour in true love with those who deal hardly with them,
but envy their outward greatness, murmur in their hearts because of their own poverty,
and strive in the wisdom of this world to get riches for themselves and their children;
this is like wandering in the dark.

If we who are of a middle station between riches and poverty,
are affected at times with the oppressions of the poor,
and feel a tender regard for our posterity after us;
O how necessary is it that we wait for the pure counsel of Truth!

Many who have seen the hardships of the poor,
have felt an eager desire that their children
may be put in a way to escape these hardships;
but how few have continued in that pure love which openeth our
understandings to proceed rightly under these difficulties!

How few have faithfully followed that holy Leader who prepares his people to
labour for the restoration of true harmony amongst our fellow-creatures!

 "`In the pure Gospel spirit we walk by faith and not by sight.`"

In the obedience of faith we die to the narrowness of self-love,
and our life being hid with Christ in God,
our hearts are enlarged toward mankind universally;
but in departing from the true light of life,
many in striving to get treasures have stumbled upon the dark mountains.

That purity of life which proceeds from faithfulness in following the Spirit of Truth,
that state where our minds are devoted to serve God,
and all our wants are bounded by his wisdom,
this habitation has often been opened before me as a
place of retirement for the children of the light,
where we may stand separated from that which
disordereth and confuseth the affairs of society,
and where we may have a testimony of our innocence in the hearts of those who behold us.

Through departing from the Truth as it is in Jesus,
through introducing ways of life attended with unnecessary expences,
many wants have arisen, the minds of people have been employed in studying to get wealth,
and in this pursuit some departing from equity, have retained a profession of religion;
others have looked at their example,
and thereby been strengthened to proceed further in the same way:
thus many have encouraged the trade of taking men from Africa and selling them as slaves.

It has been computed that nearly one hundred thousand Negroes
have of late years been taken annually from that coast,
by ships employed in the English trade.

As I have travelled on religious visits in some parts of America,
I have seen many of these people under the command of overseers, in a painful servitude.

I have beheld them as Gentiles under people professing Christianity,
not only kept ignorant of the holy Scriptures, but under great provocations to wrath;
of whom it may truly be said, "`They that rule over them make them to howl,
and the holy Name is abundantly blasphemed.`"
Where children are taught to read the Sacred Writings while young,
and exampled in meekness and humility, it is often helpful to them;
nor is this any more than a debt due from us to a succeeding age.

But where youth are pinched for want of the necessaries of life,
forced to labour hard under the harsh rebukes of rigorous overseers,
and many times endure unmerciful whippings;
in such an education how great are the disadvantages they lie under!
And how forcibly do these things work against the
increase of the government of the Prince of peace.

Humphrey Smith, in his works, page 125,
speaking of the tender feelings of the love of God in his heart when he was a child,
said, "`By the violent wrathful nature that ruled in others, was my quietness disturbed,
and anger begotten in me toward them, yet that of God in me was not wholly overcome,
but his love was felt in my heart,
and great was my grief when the earthly-mindedness and wrathful nature so provoked me,
that I was estranged from it.

"`And this I write as a warning to parents and others,
that in the fear of the living God you may train up the youth,
and may not be a means of bringing them into such alienation.`"

Many are the vanities and luxuries of the present age,
and in labouring to support a way of living conformable to the present world,
the departure from that wisdom that is pure and peaceable, has been great.

Under the sense of a deep revolt, and an overflowing stream of unrighteousness,
my life has been often a life of mourning, and tender desires are raised in me,
that the nature of this practice may be laid to heart.

I have read some books written by people who were
acquainted with the manner of getting slaves in Africa.
I have had verbal relations of this nature from several negroes brought from Africa,
who have learned to talk English.

I have sundry times heard Englishmen speak on this subject,
who have been in Africa on this business;
and from all these accounts it appears evident that great violence is committed,
and much blood shed in Africa in getting slaves.

When three or four hundred slaves are put in the hold of a vessel in a hot climate,
their breathing soon affects the air.
Were that number of free people to go passengers with all things proper for their voyage,
there would inconvenience arise from their number; but slaves are taken by violence,
and they frequently endeavour to kill the white people,
that they may return to their native land.
Hence they are kept under confinement,
by means of which a scent ariseth in the hold of a ship,
and distempers often break out amongst them, of which many die.
Of this tainted air in the hold of ships freighted with slaves,
I have had several accounts, some in print and some verbal,
and all agree that the scent is grievous.
When these people are sold in America and in the islands,
they are made to labour in a manner more servile and constant,
than that which they were used to at home, that with grief,
with different diet from what has been common with them, and with hard labour,
some thousands are computed to die every year, in what is called the seasoning.

+++[+++Note from the Editors of the original Friend`'s Library:
In perusing the writings of this worthy man,
the reader cannot fail to observe how large a portion of his attention was occupied
in contemplating the wrongs and cruelties of negro slavery and the slave trade,
and how deeply and tenderly he sympathised with
the suffering victims of those crying evils.
The firm but temperate tone of his writings in relation to them,
and his earnest and moving remonstrances with the oppressors,
are models worthy of imitation.
It is the benign,
the just and the merciful spirit of the Gospel which must eradicate
slavery from our country if it is done by peaceful methods;
and the closer we keep to the leadings of this spirit,
the more successful will be our efforts in this righteous cause.
If the evils attendant on slavery,
occasioned so much painful concern and exercise of mind to John Woolman,
at the time in which he lived, how much more deeply would he suffer now,
when the number of its helpless victims is so vastly multiplied.
We must not admit the idea,
that praiseworthy as were his sympathy and benevolent
exertions on behalf of these oppressed people,
they were suited to other times and other circumstances than those under which we live,
and that we are exempted from the obligation of those principles and feelings which
actuated him and his fellow-labourers in the cause of suffering humanity.
Within these United States,
more than two millions of our fellow-beings are
groaning under the wrongs and cruelties of hopeless,
unconditional bondage,
and we cannot doubt but that the sighs and the tears
extorted from them by the iron hand of oppression,
are noticed by that gracious and impartial Being,
who made of one blood all the families of the earth,
and who declares himself to be the refuge of the poor,
the refuge of the needy in his distress.

Since the enactment of laws for the abolishment of the
foreign slave trade and declaring it piracy,
it has claimed but a small share of the public attention,
and the idea seems to have obtained considerable currency, that it had nearly ceased.
But the truth is, that not only the extent of the traffic is greatly increased,
but the horrors and cruelties attendant on its prosecution are dreadfully aggravated.

The trade being contraband, the vessels employed in it are constructed for fast sailing,
in order to elude the vigilance of the cruisers who are watching them.
This mode of construction diminishes the space allowed the poor
slaves and increases their sufferings to a frightful degree,
while the laws which regulated the number of slaves taken on board,
in proportion to the tonnage of the vessel,
and made some other humane provisions to lessen their sufferings,
are of course all inoperative.
Thus the wretched victims of this abominable traffic
are wholly at the mercy of a class of men,
who seem actuated only by cupidity and the worst
passions which degrade the human species.

The following statements founded mainly on official documents,
will give some idea of the present state of the foreign slave-trade.

It appears that after making ample allowance for all doubtful cases,
not less than one hundred and fifty thousand slaves are
annually imported from Africa into Cuba,
Brazil and Porto Rico, besides a large number,
(not less than fifty thousand more) who are carried every year to Texas,
the United States and other countries.

As these slaves are chiefly the victims of rapine,
or prisoners taken in predatory warfare,
the number who are killed in procuring them is great,
not less probably than those who are captured.
During the long forced marches to the sea coast, over burning sands,
destitute of food and of water, and subjected to great cruelties, vast numbers perish;
and while waiting for a market at the places of deposit on the sea-board,
contagious diseases and sickness occasioned by grief, confinement and starvation,
occasion great mortality.

On the passage across the Atlantic, it is well ascertained,
that the deaths are fully twenty-five per cent, of the whole number shipped;
and of those who are landed at the places of destination, twenty per cent,
die in the seasoning and from other causes.

Thus we are warranted in the conclusion, that at a moderate estimate,
for the two hundred thousand slaves annually taken from Africa,
three hundred thousand are sacrificed,
and that the continent is thus despoiled of half a million of its inhabitants every year.

We have already said that many of the slaves were prisoners of war:
These wars are not the consequence of a disposition naturally quarrelsome,
but are the immediate offspring of cupidity,
sharpened up and roused to action by the arrival of a slave ship.
Others of these wretched beings are the innocent
victims of a corrupt system of jurisprudence,
which owes its existence to the same fruitful source of human misery.
This unjust system places the poor natives wholly at
the mercy of the petty despots who rule the country.
He who has enriched himself by his industry,
or who has a numerous family of fine children,
the sale of which would produce a handsome sum,
seldom escapes the notice of his chieftain.
Crimes are invented and promoted, and accusations multiplied,
solely with the hope of procuring condemnations, the punishment annexed to which is,
'`Sale to the Slave Merchant.`'
Many are the victims of a system of avowed rapine and plunder--
peacefully pursuing their agricultural or mechanical occupations,
they are seized by ruffians who had concealed themselves in ambush, are gagged, bound,
and borne away to the slave ship.

All these are the effects of the strong temptations
held out by the white men who visit their shores,
to procure cargoes of slaves; for the natives, when unprovoked by their artifices,
evince mild and pacific dispositions; but no sooner does a ship drop anchor,
than avarice, hatred, revenge,
and all the malevolent passions which agitate the human breast,
seem at once roused into action.

Upon the authority of Muno-o Parke, an eye witness of the facts,
and whose interesting travels in Africa are before the public,
we state the following facts:--Those who are captured
or stolen in the vicinity of the sea coast,
suffer comparatively but little from the fatigue of travelling;
but such as are brought from the interior of the country endure the
most grievous sufferings during a journey of several moons,
over rugged rocks and burning sands, and through inhospitable and dangerous deserts.
They are secured by locking the right leg of one and
the left leg of another in the same pair of fetters,
which they must support by a string in order to
enable them to walk without very great torture.
Every four slaves are tied together by a rope of strong twisted thongs,
passed round their necks,
and at night an additional pair of fetters is put upon their hands.
The scorching heat of the sun and sand, the weight of their irons,
added to the burdens which they are compelled to carry,
weary and oppress them to so dreadful a degree as to induce sickness, vomiting,
and frequently fainting; but regardless of their sufferings,
they are goaded and spurred along by the cruel application of the lacerating lash,
till many actually expire under their complicated miseries.

In an investigation into the character and effects of the slave-trade,
which took place before a committee of the British Parliament,
numerous witnesses who were examined under the
solemn obligation of an oath or affirmation,
agree in stating that when on board the vessels,
the slaves appear melancholy and dejected,
that many continue so during the whole of the voyage,
and that their dejection evidently arises from the anguish of
their feelings on being separated forever from their country,
their homes, their beloved families and friends.
From the same respectable and authentic source we draw the following information:
The men are chained together in pairs--the right leg of
one is fettered to the left leg of another,
in which situation they are stowed into the hold of the vessel--the women and children,
however, are not chained and ironed like the men.
When the weather is fair,
they are brought up out of their prisons for the benefit of a pure air,
and to take their meals.
For this purpose the men are distributed on the deck in long rows, two by two,
from head to stern, but to prevent their rising,
and to secure them from jumping overboard, which they often attempt,
a long chain is passed through the irons of each
couple and locked down to the deck at both ends.

When the vessel is full, their condition is wretched indeed.
In the best regulated ships,
a full grown man has no more space allowed him to lie upon than sixteen inches,
which is less than he would have in a coffin--while the
height of the apartment is about thirty-two inches.
There are few vessels, however, in which even this limited space is allowed them.
In many they are so closely stowed that the poor
creatures are compelled to lie upon their sides,
while the top of the hold in which they are crammed is
so very low as wholly to prevent their sitting upright.
Beside all these evils, they are entirely naked, and lie upon the bare boards,
in which situation the constant motion of the vessel bruises
and excoriates different parts of their bodies--the rubbing of
their irons lacerates and inflames their legs,
occasioning constant torture,
from which they can seldom procure even the smallest intermission.

But horrible beyond all description, are the agonies which they endure,
when it blows a heavy gale, and the hatches and gratings are of necessity shut down.
No language can possibly portray even a faint picture of their deplorable condition.
In the extremity of anguish they are often heard
to cry out in the language of their country,
"`We are dying!
We are dying!`"
Imagine to yourselves several hundreds of human beings
shut up close in the hold of a vessel in a warm climate,
the circulation of air wholly excluded, while the heat, the excretions of their bodies,
and the filth of the boards they lie upon,
are emitting the most noisome effluvia--add to this,
the dreadful effects of the increased motion of the vessel, the shrieks of the swooning,
and the groans of the dying,
and your imagination may present some idea of what these miserable
beings are compelled to suffer in a voyage to our country.
The steam which comes at this time from their bodies,
and which ascends through the little crevices of the gratings,
has been compared by some of the witnesses,
to that which issues from the mouth of a furnace.
Many of them fainting from the heat, stench and corrupted air,
have been brought upon deck in a dying state,
while others have actually expired of suffocation,
who but a few hours before were in apparent health.
Horrible as this description may appear,
many circumstances are omitted which would greatly aggravate it.
We can refer to the most credible testimony for cases,
where they have been afflicted with contagious diseases, especially the flux, when,
says one of the witnesses,
the floor of their prison was covered with blood and mucus like that of a slaughter-
house.--See the Evidence before the Committee of Parliament before referred to.

It is not surprising that these poor creatures,
groaning under the horrors of such complicated misery should seek that relief in death,
which they have no reason to hope for from any other source,
and hence it is that opportunities for destroying themselves are
anxiously watched for and seized with an avidity almost beyond belief.
The most common method of effecting this, is by throwing themselves into the sea,
although every avenue of escape by such means is carefully guarded.

The men are not only locked to the deck as before mentioned,
but strong nettings are fastened around the ship which reach
from the deck to a considerable height in the rigging.
But notwithstanding these precautions,
and the terrible example of shooting some who attempt to leap overboard,
the instances where they thus destroy themselves are numerous,
and where they are frustrated in the attempt this way,
they resort to other means to obtain their object.
The keenest foresight on the part of their oppressors cannot always prevent them.

When ropes have been left about the deck,
some have seized the opportunity and strangled themselves--when small instruments,
or even pieces of iron have come within their reach,
others have been discovered to have made mortal wounds with them upon their bodies,
and many to whom all these means have failed, resolutely refuse to take any sustenance,
when after pining in great misery for several days,
the welcome hand of death has at last terminated their sufferings.
Numerous are the instances of females of very delicate temperament of body and mind,
whose feelings are more tender, and who have a more acute sense of their situation,
but possess less resolution,
where a continually increasing melancholy has terminated in madness,
in which pitiable condition they have remained for the short remnant of their days.
Such are the melancholy scenes which are continually passing on board
the slave ships from the period of leaving the coast of Africa,
until they arrive at the place of destination,
during which time a considerable mortality occurs.
From the evidence before quoted,
it appears that out of seven thousand nine hundred and four
slaves who sailed with the witnesses at different times,
two thousand and fifty-three perished in the short space of six or eight weeks,
though all of them were young and healthy when brought on board--the
oldest slave seldom being more than twenty-five years of age.

What a murderous, what a cruel devastation of the human race is hereby occasioned!
What an impious rebellion against the will and the designs of a beneficent Providence!

It is impossible that men can frequently participate in such
scenes as those we have been endeavouring to describe,
without becoming hardened in cruelty and in wickedness.
There is no doubt that many when they first commence this diabolical employ,
find it necessary to suppress and stifle the feelings of humanity;
but every suppression of benevolent feeling does
violence to the tenderness of the human heart;
it steels and blunts its virtuous sensibility,
and prepares it for the commission of acts of greater atrocity.
Such is precisely the case of slave traders.
By degrees they are brought to view with indifference,
and then to perpetrate acts of the most shocking barbarity--acts,
the bare recital of which would cause a feeling mind to shudder with
abhorrence.--They are taught by repeated cruelties,
to regard the cries, the tears,
and the sufferings of a fellow-creature whom they have purchased,
no more than they would the drowning of a fly!
To the truth of our assertions let the following facts testify:
"`On board a foreign ship called the Zong, many of the slaves had died,
and the mortality was spreading so rapidly that the
captain began to fear he should lose them all.
He therefore came to the diabolical resolution of selecting
those who were the most sickly and throwing them into the sea,
conceiving that if he could plead a necessity for the deed,
the loss of the slaves would fall upon the underwriters.
The plea which he proposed to set up, was want of water,
though neither the crew nor the slaves had been put upon allowance.
He selected accordingly one hundred and thirty-two of the most sickly,
fifty-four of whom were immediately thrown overboard,
and forty-two on the succeeding day.
But here the wretch was left without the shadow of an excuse,
for a shower of rain came on, which lasted for three days.
Notwithstanding this,
the remaining twenty-six were brought on deck to share the same fate.
The first sixteen submitted to be thrown into the sea,
but the remainder would not permit any of the crew to touch them,
but leaped in after their companions.

These circumstances were all fully proved before a court of justice, held at Guildhall,
in London,
in the prosecution of a suit brought to recover their
value from the insurers--the result of which however,
was, that the loss was adjudged to fall upon the owners.

"`The case of the Rodeur, captain B+++_______+++ , a French vessel of two hundred tons burden,
is remarkable.

She left Havre for the coast of Africa, where she arrived and anchored before Bonny,
in the river Calabar, and took in a cargo of slaves,
contrary to the French law for the abolition of the trade.
She soon after sailed with them for Gaudaloupe.
In about a fortnight, when the vessel had nearly reached the Equator,
a dreadful ophthalmia, sore eyes, broke out among the negroes,
and spread with alarming rapidity.
By the advice of the surgeon to the ship, the negroes,
who till then had been confined to the hold, were successively brought upon deck,
in order that they might breathe a purer air;
but it soon became necessary to abandon this salutary measure,
for many of them leaped into the sea, embracing each other,
undaunted by the severity of the captain,
who made a terrible example by shooting some and hanging others who attempted it.
The danger of the disease, and probably the cause of the contagion were increased,
by a violent dysentery, which now broke out among them.
The disorder increased daily, as well as the number of those who became blind;
and it spread with such alarming rapidity among the crew,
that in a little time there was only one man left who could steer the ship.

At this period a large ship approached the Rodeur,
which appeared to be totally at the mercy of the winds and waves.
She was the Spanish slave ship St. Leon.
Her crew, hearing the voices of the Rodeur`'s men, cried out most vehemently for help.
They told the melancholy tale as they passed along,
that the contagion had seized the eyes of all on board,
and that there was not one individual left, either sailor or slave, who could see!

But alas--this pitiable tale of woe was utterly in vain--no help could be
given them--the St. Leon passed on and was never heard of more!

"`At length by a concurrence of very favourable circumstances,
and the skill and perseverance of one man, who only preserved his sight unimpaired,
the Rodeur reached Gaudaloupe.
By this time thirty-nine of the slaves had become blind,
twelve had lost one eye and fourteen were affected with blemishes.
Out of the crew consisting of twenty-two, twelve had lost their sight,
among whom was the surgeon, five had become blind of one eye,
and four others were partially injured.

"`Now what will the reader suppose was the first act of this captain and
crew when they found themselves safely entering the port of Gaudaloupe.
Doubtless he will imagine they were employed in returning unfeigned
thanks to God for so signal and so unmerited a deliverance.
But he will mistake if he thinks so.
They possessed neither gratitude to God nor humanity towards his creatures.
Destitute of every virtuous and tender feeling,
they evinced their impious ingratitude by absolutely
throwing into the sea all those slaves,
to the number of thirty-nine, who were incurably blind.
This they did upon the wicked plea that if they
carried them on shore nobody would purchase them,
and they would of course be at the expense of their maintenance; and further,
by feigning an act of necessity, they might claim their value from the underwriters.`"

Sir George Collier of the Tartar frigate,
gave chase to a vessel supposed to be a slave ship.
In the course of the chase several casks were observed to be floating in the sea,
which the Tartar passed.
After a long pursuit they boarded her, and she proved to be the La Jeune Estelle,
of Martinique, Olympia Sanguines, master.
The captain declared that he had no slaves on board,
having been plundered of them by a Spanish pirate.
The agitation and alarm which marked every countenance on board the vessel,
excited strong suspicions in the mind of the chief officer of the Tartar,
and he ordered the hold to be searched.

During the examination one of the sailors happened to
strike a cask which was tightly closed up,
when he heard a faint sound issue from it like the voice of some creature expiring.
The cask was immediately opened, when two slave girls,
about twelve or fourteen years of age,
in the last stage of suffocation were found packed up in it.

They were carried on board the Tartar, revived by the fresh air,
and were thus saved from a miserable death.
These girls, when brought on the deck of the Tartar,
were recognised by a person who had seen them in their own country,
and who had been taken from another slave ship,
as being the property of captain Richards, of the schooner Swift, of New York.
An investigation afterwards took place, in the course of which,
it appeared in evidence that captain Richards
had died at Trade town on the coast of Africa,
leaving behind him fourteen slaves of whom these girls were a part;
and that after his death,
captain Sanguines had landed his men armed with swords and pistols,
and carried off the whole fourteen slaves on board the Teune Estelle.
Sir George Collier conceiving that the other
twelve might possibly be concealed in the vessel,
ordered her re-searched.
The result was that a negro man, not however of the twelve, was rescued from death.
A platform of loose boards had been raised upon the water casks of the vessel,
forming a between-decks of about twenty-three inches in height,
which was the intended receptacle of the cargo of human
beings which captain Sanguines designed to procure.
Beneath this platform, with one of the boards resting upon his body,
jammed into the crevice between two water casks, was found this wretched negro,
in a situation so extremely distressing,
that it was matter of great astonishment to find him alive.
The search for the other twelve proving fruitless,
the officers and crew of the Tartar recollected with feelings
of horror the casks which they had seen floating on the ocean;
the painful conviction now forced itself upon their minds that the captain,
fearing lest he should be captured by the Tartar and detained, had during the chase,
packed up his slaves in casks and thrown them into the sea;
an apprehension which is corroborated by the reflection,
that had he thrown them overboard without some such covering,
their bodies would in all probability have met
the view of the officers and crew of the Tartar,
and disclosed the horrid catastrophe.

But alas! it was now too late to attempt any plan for rescuing them.
The chase had carried them many leagues to the windward of the casks,
and should they even fall in with them, which was scarcely possible,
there was not the smallest probability of finding any of the wretched negroes alive,
for the casks being tight they must have perished from suffocation.
See Papers laid on the table of the House of Commons--Report of Sir George
Collier--Speech of Due de Boglie--Report of African Institution,
vol.
16.

The schooner , Don Morales, master, arrived in the Rio Pongos,
where she took on board two hundred slaves.
Our informant states, that Morales while trading for the cargo,
exhibited many instances of savage ferocity toward the slaves,
but after leaving the river, his cruelty seems to have had full scope.

The number of slaves on board being greatly
disproportioned to the stowage of the schooner,
he was obliged from the first to issue short rations of water and rice,
in consequence of which some of the slaves evinced some signs of discontent.

Morales, deaf to their wants,
kept them all below for three days without food of any kind,
and with a barbarity unparalleled except among slave traders,
discharged all the fire arms in his vessel among the wretched beings,
bound down and chained together as they were.
Some of the sailors presumed to interfere,
but the barbarian silenced their complaints by
killing the foremost of them with his sabre.
He then made sail again for the Rio Pongos, where,
with the assistance of the slave factors, he got every thing put to rights,
took in slaves to supply the number he had killed, and bore away for Havanna.

Captain Hayes, R. N., mentions the case of a slaver,
having a large cargo of human beings chained together: '`The master of the vessel,
with more humanity than his fellows, permitted some of them to come on deck,
but still chained together, for the benefit of the air,
when they immediately commenced jumping overboard, hand in hand,
and drowning in couples.`'
He explains the cause of this circumstance by saying,
they were just brought from a situation between decks,
and to which they knew they must return,
where the scalding perspiration was running from one to the other,
covered also with their own filth,
and where it is no uncommon occurrence for women to be bringing forth children,
and men dying by their side, with, full in their view,
living and dead bodies chained together, and the living,
in addition to all their other torments, labouring under the most famishing thirst,
being in very few instances allowed more than a pint of water a day.`'
He goes on to say, "`I have now an officer on board the '`Dryad,`' who,
on examining one of these slave vessels,
found not only living men chained to dead bodies, but the latter in a putrid state;
and we have now a case which, if true, is too horrible and disgusting to be described.`"

In a letter from captain Wauchope, dated 13th of eighth month, 1838, he says,
"`In second month, 1836, I was informed by Commander Puget, that the Spanish slaver,
Argus, three months before this date, was chased by the Charybdis, Lieutenant Mercer;
that during the chase ninety-seven slaves had been thrown overboard,
and that a Spanish captain he had captured,
declared he would never hesitate to throw the slaves overboard, to prevent being taken.`"

"`Captain Wauchope in the same letter informs, that on the 18th of ninth month, 1836,
the Thalia captured the Portuguese brig Felix, five hundred and ninety slaves on board.
'`After capture,`' he says, '`I went on board,
and such a scene of horror it is not easy to describe; the long`'-boat on the booms,
and the deck aft, were crowded with little children, sickly, poor little unhappy things,
some of them rather pretty, and some much marked and tattoed;
much pains must have been taken by their miserable parents to ornament and beautify them.

"`The women lay between decks aft, much crowded, and perfectly naked;
they were not barred down, the hatchway, a small one, being off;
but the place for the men was too horrible, the wretches, chained two and two,
gasping and striving to get at the bars of the hatchways,
and such a steam and stench as to make it intolerable even to look down.
It requires much caution at first, in allowing them to go on deck,
as it is a common practice for them to jump overboard to get quit of their misery.

"`The slave-deck was not more than three feet six inches in height,
and the human beings stowed, or rather crushed as close as possible;
many appeared very sickly.
There was no way of getting into the slave-room but by the hatchway.
I was told, when they were all on deck to be counted,
that it was impossible for any of our people to
go into the slave-room for a single minute,
so intolerable was the stench.
The colour of these poor creatures was of a dark squalid yellow,
so different from the fine glossy black of our liberated Africans and Kroomen.
I was shown a man much bit and bruised;
it was done in a struggle at the gratings of their hatchways,
for a mouthful of fresh air.`'

"`The Carolina, captured in 1834, off Wydah.
This vessel was only seventy-five tons burden,
yet she had three hundred and fifty negroes crammed on board of her,
one hundred and eighty of whom were literally so stowed as to
have barely sufficient height to hold themselves up,
when in a sitting posture.
The poor creatures crowded round their deliverers,
with their mouths open and their tongues parched for want of water,
presenting a perfect spectacle of human misery.

"`In a letter from the Cape of Good Hope, of date 20th of first month, 1837,
we find it stated that the British brig Dolphin,
had lately captured the corvette Incomprehensible; and that on taking possession of her,
the scene presented on board was harrowing in the extreme.
One hundred had died from sickness, out of the eight hundred embarked;
another hundred were lying nearly lifeless on her decks, in wretchedness and misery,
and all the agony of despair;
the remaining six hundred were so cramped from
the close manner in which they were packed,
like herrings in a barrel, and the length of time they had been on their voyage,
and the cold they had endured in rounding the Cape, in a state of nudity,
that it took the utmost exertions of the English sailors, favoured by a hot sun,
to straighten them.`'
In a letter from Colonel NicoUs, at the Bahamas, of date 1st of eighth month, 1837,
it is stated that '`the Esperanza, a Spanish slave schooner,
had been wrecked on one of these islands during the preceding month.
It was ascertained that this vessel had embarked three
hundred and twenty negroes on the coast of Africa;
of these only two hundred and twenty were landed at the time of the wreck.
It appears that between sixty and seventy murders had been
committed daring the voyage on the helpless Africans;
and in this manner:--When any of the slaves refused their food or became sick,
the boatswain`'s mate, with a weighty club struck them on the back of the neck,
when they fell, and were thrown overboard.`"

Shocking as these details are, the truth of them is indisputable;
and while a system exists which inflicts such
sufferings upon our innocent fellow-creatures,
it cannot be a matter of indifference or unconcern to us.
But especially are we called upon deeply to ponder this affecting subject,
and to dwell under the weight of it, by the fact that our own country is implicated,
in no small degree in the guilt of the traffic,
it being well ascertained that American vessels, American capital and American citizens,
are employed in its prosecution.
– Editors.]

Thus it appears evident,
that great numbers of these people are brought every year to an untimely end;
many of them being persons who never injured us.

Where the innocent suffer under hard-hearted men, even unto death,
and the channels of equity are so obstructed,
that the cause of the sufferers is not judged in righteousness,
"`the land is polluted with blood.`"

Where blood hath been shed unrighteously, and remains unatoned for,
the cry thereof is very piercing.

Under the humbling dispensations of Divine Providence,
this cry hath deeply affected my heart, and I feel a concern to open,
as I may be enabled, that which lieth heavy on my mind.

When "`the iniquity of the house of Israel and of Judah was exceedingly great,
when the land was defiled with blood, and the city full of perverseness;
some were found sighing and crying for the abominations of the times.`"
And those who live under a right feeling of our condition as a nation,
I trust will be sensible that the Lord at this day doth call to mourning,
though many are ignorant of it.
So powerful are bad customs when they become general,
that people growing bold through the example one of another,
have often been unmoved at the most serious warnings.

Our blessed Saviour speaking of the people of the old world, said, "`They eat,
they drank, they married and were given in marriage,
until the day that Noah went into the ark, and the flood came and destroyed them all.`"

The like he spoke concerning the people of Sodom,
who are also represented by the prophet, as haughty, luxurious and oppressive;

 "`This was the sin of Sodom, pride, fulness of bread,
and abundance of idleness was found in her, and in her daughters;
neither did she strengthen the hands of the poor and needy.`"

In a revolt so deep as this, when much blood has been shed unrighteously,
in carrying on the slave trade, and in supporting the practice of keeping slaves,
which at this day is un-atoned for,
and crieth from the earth and from the seas against the oppressor;
while this practice is continued,
and under a great load of guilt there is more unrighteousness committed,
the state of things is very moving.

There is a love which stands in nature,
and a parent beholding his child in misery hath a feeling of the affliction;
but in Divine love the heart is enlarged towards mankind universally,
and prepared to sympathize with strangers, though in the lowest stations in life.

Of this the prophet appears to have had a feeling, when he said,
"`Have we not all one Father?
Hath not one God created us?
Why then do we deal treacherously every man with his brother,
in profaning the covenant of our fathers?`"

He who of old heard the groans of the children
of Israel under the hard task-masters in Egypt,
I trust hath looked down from his holy habitation on
the miseries of these deeply oppressed people.
Many lives have been shortened through extreme oppression,
while they laboured to support luxury and worldly greatness;
and though many people in outward prosperity may think little of those things,
yet the gracious Creator hath regard to the cries of the innocent,
however unnoticed by men.

The Lord in the riches of his goodness is leading some
into the feeling of the condition of this people,
who cannot rest without labouring as their advocates;
of which in some measure I have had experience,
for in the movings of his love in my heart,
these poor sufferers have been brought near to me.

The unoffending aged and infirm are made to labour too hard,
kept on a diet less comfortable than their weak state requires,
and exposed to great difficulties under hard-hearted men,
to whose sufferings I have often been a witness,
and under the heart-melting power of Divine love,
their misery hath felt to me like the misery of my parents.

Innocent youth are taken by violence from their native land,
from their friends and acquaintance; put on board ships with hearts laden with sorrow;
exposed to great hardships at sea,
and placed under people where their lives are attended
with great provocation to anger and revenge.

With the condition of these youth my mind has often been affected,
as with the afflictions of my children, and in a feeling of the misery of these people,
and of that great offence which is ministered to them,
my tears have been often poured out before the Lord.

That holy Spirit which affected my heart when I was a youth,
I trust is often felt by the negroes in their native land,
inclining their minds to that which is righteous;
and had the professed followers of Christ in all their conduct toward them,
manifested a disposition answerable to the pure principle in their hearts,
how might the holy Name have been honoured amongst the Gentiles,
and how might we have rejoiced in the fulfilling of that prophecy,
"`I the Lord love judgment, I hate robbery for burnt-offerings,
and I will direct their work in truth, and make an everlasting covenant with them.
Their seed shall be known amongst the Gentiles, and their offspring amongst the people;
all that see them shall acknowledge them,
that they are the seed which the Lord hath blessed.`"

But in the present state of things, how contrary is our practice to that meek spirit,
in which our Saviour laid down his life for us,
that all the ends of the earth might know salvation in his name!

How are the sufferings of our blessed Redeemer set at naught,
and his name blasphemed amongst the Gentiles,
through the unrighteous proceedings of his professed followers!

My mind has often been affected, even from the days of my youth,
under a sense of that marvellous work,
for which God in infinite goodness sent his Son into the world.

The opening of that spring of living waters,
which the true believers in Christ experience,
by which they are redeemed from pride and covetousness,
and brought into a state of meekness,
where their hearts are enlarged in true love toward their fellow creatures universally;
is a work that to me has been precious,
and spreading the knowledge of the Truth amongst the Gentiles, is very desirable.
And the professed followers of Christ joining in customs evidently unrighteous,
which manifestly tend to stir up wrath and increase wars and desolations,
has often covered my mind with sorrow.

If we bring this matter home, and as Job proposed to his friends,
"`Put our soul in their soul`'s stead;`" if we consider
ourselves and our children as exposed to the hardships which
these people lie under in supporting an imaginary greatness,
and in such case, beheld an increase of luxury and superfluity amongst our oppressors,
and therewith felt an increase of the weight of our burdens,
and expected our posterity to groan under oppression after us; under all this misery,
had we none to plead our cause, nor any hope of relief from man,
how would our cries ascend to the God of the spirits of all flesh,
who judgeth the world in righteousness,
and in his own time is a refuge for the oppressed!

If they who thus afflicted us, continued to lay claim to religion,
and were assisted in their business by others, esteemed pious people,
who through a friendship with them strengthened their hands in tyranny;
if when we were hunger-bitten, we could not have sufficient nourishment,
but saw them in fulness pleasing their taste with things fetched from far;
if when we were wearied with labour, we were denied the liberty to rest,
and saw them spending their time at ease;
if garments answerable to our necessities were denied us,
while we saw them clothed in that which was costly and delicate; under such affliction,
how would these painful feelings rise up as witnesses against their pretended devotion!
And if the name of their religion was mentioned in our hearing,
how would it sound in our ears like a word which
signified self-exaltation and hardness of heart!

When a trade is carried on productive of much misery,
and they who suffer by it are some thousands of miles off, the danger is the greater,
of not laying their sufferings to heart.

In procuring slaves on the coast of Africa, many children are stolen privately;
wars also are encouraged amongst the negroes, but all is at a great distance.

Many groans arise from dying men, which we hear not.

Many cries are uttered by widows and fatherless children, which reach not our ears.

Many cheeks are wet with tears and faces sad with unutterable grief, which we see not.

Cruel tyranny is encouraged.
The hands of robbers are strengthened, and thousands reduced to the most abject slavery,
who never injured us.

Were we for the term of one year only to be eye
witnesses to what passes in getting these slaves;
Was the blood which is there shed to be sprinkled on our garments;
Were the poor captives bound with thongs and heavy laden with elephants`' teeth,
to pass before our eyes on their way to the sea:
Were their bitter lamentations day after day to ring in our ears,
and their mournful cries in the night to hinder us from sleeping:
Were we to hear the sound of the tumult when the slaves
on board the ships attempt to kill the English,
and behold the issue of those bloody conflicts:
What pious man could be a witness to these things,
and see a trade carried on in this manner, without being deeply affected with sorrow?

Through abiding in the love of Christ we feel a
tenderness in our hearts toward our fellow-creatures,
entangled in oppressive customs; and a concern so to walk,
that our conduct may not be a means of strengthening them in error.

It was the command of the Lord through Moses,
"`Thou shalt not suffer sin upon thy brother: thou shalt in any wise rebuke thy brother,
and shalt not suffer sin upon him.`"

Again; "`Keep far from a false matter; and the innocent and righteous slay thou not.`"

The prophet Isaiah mentions oppression as that which the true
church in time of outward quiet should not only be clear of,
but should be far from it; "`Thou shalt be far from oppression.`"
Now these words, far from, appear to have an extensive meaning,
and to convey instruction in regard to that of which Solomon speaks,
"`Though hand join in hand, the wicked shall not go unpunished.`"

It was a complaint against one of old, "`When thou sawest a thief,
thou consentedst with him.`"

The prophet Jeremiah represents the degrees of preparation toward idolatrous sacrifice,
in the similitude of a work carried on by children, men and women.
"`The children gather wood, the fathers kindle the fire,
and the women knead the dough to bake cakes for the queen of heaven.`"

It was a complaint of the Lord against Israel, through his prophet Ezekiel,
that "`they strengthened the hands of the wicked,
and made the hearts of the righteous sad.`"

Some works of iniquity carried on by the people were represented by the prophet Hosea,
in the similitude of ploughing, reaping and eating the fruit;
"`You have ploughed wickedness, reaped iniquity, eaten the fruit of lying,
because thou didst trust in thy own way, to the multitude of thy mighty men.`"

I have felt great distress of mind since I came on this island,
on account of the members of our Society being mixed
with the world in various sorts of business and traffic,
carried on in impure channels.
Great is the trade to Africa for slaves;
and in loading these ships abundance of people are employed in the manufactories.

Friends in early time refused on a religious principle,
to make or trade in superfluities, of which we have many large testimonies on record,
but for want of faithfulness some gave way,
even some whose examples were of note in society,
and from thence others took more liberty.
Members of our Society worked in superfluities, and bought and sold them,
and thus dimness of sight came over many.
At length Friends got into the use of some superfluities in dress,
and in the furniture of their houses, and this hath spread from less to more,
till superfluity of some kinds is common amongst us.

In this declining state many look at the example one of another,
and too much neglect the pure feeling of Truth.
Of late years a deep exercise hath attended my mind, that Friends may dig deep,
may carefully cast forth the loose matter and get down to the rock, the sure foundation,
and there hearken to that Divine voice which gives a clear and certain sound.

I have felt in that which doth not deceive, that if Friends who have known the Truth,
keep in that tenderness of heart where all views of outward gain are given up,
and their trust is only on the Lord,
he will graciously lead some to be patterns of deep self-denial,
in things relating to trade and handicraft labour;
and that some who have plenty of the treasures of this world,
will example in a plain frugal life, and pay wages to those whom they may hire,
more liberally than is now customary in some places.

The prophet speaking of the true church, said, "`Thy people also shall be all righteous.`"
Of the depth of this Divine work several have spoken.

John Gratton, in his Journal, page 45, said "`The Lord is my portion, I shall not want.
He hath wrought all my works in me.
I am nothing but what I am in him.`"

Gilbert Latey, through the powerful operations of the spirit of Christ in his soul,
was brought to that depth of self-denial,
that he could not join with that proud spirit in other people,
which inclined them to want vanities and superfluities.
This Friend was often amongst the chief rulers of the nation in times of persecution,
and it appears by the testimony of Friends,
that his dwelling was so evidently in the pure life of Truth,
that in his visits to those great men, he found a place in their minds;
and that King James the second, in the times of his troubles,
made particular mention in a very respectful manner of what Gilbert once said to him.

The said Gilbert found a concern to write an epistle, in which are these expressions;
"`Fear the Lord, ye men of all sorts, trades and callings,
and leave off all the evil that is in them,
for the Lord is grieved with all the evils used
in your employments which you are exercised in.`"

"`It is even a grief to see how you are servants to sin, and instruments of satan.`"
See his works, page 42, etc.

George Fox, in an epistle writes thus: "`Friends, stand in the eternal power of God,
witnesses against the pomps and vanities of this world.

"`Such tradesmen who stand as witnesses in the power of God,
cannot fulfill the people`'s minds in these vanities,
and therefore they are offended at them.

"`Let all trust in the Lord, and wait patiently on him;
for when Truth first broke forth in London,
many tradesmen could not take so much money in their shops for some time,
as would buy them bread and water, because they withstood the world`'s ways,
fashions and customs;
yet by their patient waiting on the Lord in their good life and conversation,
they answered the Truth in people`'s hearts, and thus their business increased.`"
Book of Doctrinals, page 824.

Christ our holy leader graciously continueth to open the understandings of his people,
and as circumstances alter from age to age,
some who are deeply baptized into a feeling of the state of things,
are led by his holy spirit into exercises in some respects different
from those which attended the faithful in foregoing ages,
and through the constrainings of pure love,
are engaged to open the feelings they have to others.

In faithfully following Christ, the heart is weaned from the desire of riches,
and we are led into a life so plain and simple, that a little doth suffice,
and thus the way openeth to deny ourselves,
under all the tempting allurements of that gain,
which we know is the gain of unrighteousness.

The apostle speaking on this subject, asketh this question;
"`What fellowship hath righteousness with unrighteousness?`"
And again saith, "`Have no fellowship with the unfruitful works of darkness,
but rather reprove them.`"
Again, "`Be not partaker of other men`'s sins, keep thyself pure.`"

Where people through the power of Christ are thoroughly settled in a right use of things,
and freed from all unnecessary care and expense,
the mind in this true resignation is at liberty from the bands of a narrow self-interest,
to attend from time to time on the movings of his spirit upon us,
though he leads into that through which our faith is closely tried.

The language of Christ is pure,
and to the pure in heart this pure language is intelligible; but in the love of money,
the mind being intent on gain, is too full of human contrivance to attend to it.

It appears evident that some channels of trade are defiled with unrighteousness,
and that the minds of many are intent on getting treasures to support a life,
in which there are many unnecessary expenses.

I feel a living concern attend my mind,
that under these difficulties we may humbly follow our heavenly Shepherd,
who graciously regardeth his flock,
and is willing and able to supply us both inwardly and outwardly with clean provender,
that has been winnowed with the shovel and the fan,
where we may "`sow to ourselves in righteousness,
reap in mercy,`" and not be defiled with the works of iniquity.

Where customs contrary to pure wisdom are transmitted to posterity,
it appears to be an injury committed against them;
and I often feel tender compassion toward a young generation,
with desires that their difficulties may not be increased
through unfaithfulness in us of the present age.

=== Chapter II.On a Sailor`'s life.

In the trade to Africa for slaves, and in the management of ships going on these voyages,
many of our lads and young men have a considerable part of their education.

What pious father beholding his son placed in one of
these ships to learn the practice of a mariner,
could forbear mourning over him?

Where youth are exampled in means of getting money so full of violence,
and used to exercise such cruelties on their fellow-creatures,
the disadvantage to them in their education is very great.

But I feel it in my mind to write concerning the seafaring life in general.

In the trade carried on from the West Indies, and from some parts of the continent,
the produce of the labour of slaves is a considerable part.

Sailors are frequently at ports where slaves abound,
and converse often with people who oppress them without the appearance of remorse,
and often with other sailors employed in the slave trade,
and how powerfully do these evil examples spread amongst the seafaring youth!

I have had many opportunities to feel and understand
the general state of the seafaring life amongst us,
and my mind hath often been sad on account of so many lads and
young men being trained up amidst so great corruption.

Under the humbling power of Christ I have seen,
that if the leadings of his holy Spirit were faithfully
attended to by his professed followers in general,
the heathen nations would be exampled in righteousness,
a less number of people would be employed on the seas,
the channels of trade would be more free from defilement,
and fewer people would be employed in vanities and superfluities.

The inhabitants of cities would also be less in number,
and those who have much land would become fathers to the poor.

More people would be engaged in the sweet employment of husbandry,
and in the path of pure wisdom, labour would be an agreeable, healthful employment.

In the opening of these things in my mind,
I feel a living concern that we who have felt Divine
love in our hearts may faithfully abide in it,
and like good soldiers endure hardness for Christ`'s sake.

He, our blessed Saviour, exhorting his followers to love one another, adds,
"`As I have loved you.`"
He loved Lazarus, yet in his sickness he did not heal him,
but left him to endure the pains of death, that in restoring him to life,
the people might be confirmed in the true faith.

He loved his disciples, but sent them forth on a message attended with great difficulty,
amongst hard-hearted people,
some of whom thought that in killing them they did God service.

So deep is Divine love, that in steadfastly abiding in it,
we are prepared to deny ourselves of all gain which is contrary to pure wisdom,
and to follow Christ, even under contempt and through sufferings.

While Friends were kept truly humble and walked
according to the purity of our principles,
the Divine witness in many hearts was reached; but when a worldly spirit got entrance,
therewith came in luxuries and superfluities, and spread by little and little,
even amongst the foremost rank in society,
and from thence others took liberty in that way more abundantly.

In the continuation of these things from parents to children,
there were many wants to supply,
even wants unknown to Friends while they faithfully followed Christ.
In striving to supply these wants many have exacted on the poor,
and many have entered on employments,
in which they often labour in upholding pride and vanity.
Many have looked on one another, been strengthened in these things,
one by the example of another, and as to the pure divine seeing,
dimness has come over many, and the channels of true brotherly love have been obstructed.

People may have no intention to oppress, yet by entering on expensive ways of life,
their minds may be so entangled therein and so engaged to support expensive customs,
as to be estranged from the pure sympathizing spirit.

As I have travelled in England,
I have had a tender feeling of the condition of poor people,
some of whom though honest and industrious,
have nothing to spare toward paying for the schooling of their children.

There is a right proportion between labour and the necessaries of life,
and in true brotherly love the mind is open to feel after the necessities of the poor.

Amongst the poor there are some that are weak through age, and others of a weakly nature,
who pass through straits in very private life, without asking relief from the public.

Those who are strong and healthy may do business, which to the weakly may be oppressive;
and in performing that in a day which is esteemed a day`'s labour,
weakly persons in the field and in the shops,
and weakly women who spin and knit in the manufactories, often pass through weariness;
and many sighs I believe are uttered in secret,
unheard by some who might ease their burdens.

Labour in the right medium is healthy,
but in too much of it there is a painful weariness;
and the hardships of the poor are sometimes increased
through the want of more agreeable nourishment,
more plentiful fuel for fire,
and warmer clothing in the winter than their wages will answer.

When I have beheld plenty in some houses to a degree of luxury;
the condition of poor children brought up without learning,
and the condition of the weakly and aged, who strive to live by their labour,
have often revived in my mind,
as cases of which some who live in fulness need to be put in remembrance.

There are few if any,
who could behold their fellow-creatures lie long in distress and forbear to help them,
when they could do it without any inconvenience;
but customs requiring much labour to support them, do often lie heavily on the poor,
while they who live in these customs are so
entangled in a multitude of unnecessary concerns,
that they think but little of the hardships which the poor people go through.

=== Chapter III.On Silent Worship.

Worship in silence hath often been refreshing to my mind,
and a care attends me that a young generation may feel the nature of this worship.

Great expense is incurred in relation to that which is called Divine worship.

A considerable part of this expense is applied toward outward greatness,
and many poor people in raising of tithe,
labour in supporting customs contrary to the simplicity that there is in Christ,
toward whom my mind hath often been moved with pity.

In pure silent worship, we dwell under the holy anointing,
and feel Christ to be our shepherd.

Here the best of teachers ministers to the several conditions of his flock,
and the soul receives immediately from the Divine fountain,
that with which it is nourished.

I have travelled at times where those of other societies have attended our meetings,
and have perceived how little some of them knew of the nature of silent worship;
and I have felt tender desires in my heart that
we who often sit silently in our meetings,
may live answerably to the nature of an inward fellowship with God,
that no stumbling block through us, may be laid in their way.

Such is the load of unnecessary expense laid in many
places on that which is called Divine service,
and so much are the minds of many people employed in outward forms and ceremonies,
that the opening of an inward silent worship in this nation, to me,
has appeared to be a precious opening.

Within the last four hundred years, many pious people have been deeply exercised in soul,
on account of the superstition which prevailed amongst the professed followers of Christ,
and in support of their testimony against oppressive idolatry,
some in several ages have finished their course in the flames.

It appears by the history of the reformation,
that through the faithfulness of the martyrs,
the understandings of many have been opened, and the minds of people, from age to age,
been more and more prepared for spiritual worship.

My mind is often affected with a sense of the condition of those people,
who in different ages have been meek and patient,
following Christ through great afflictions.
And while I behold the several steps of reformation, and that clearness,
to which through Divine Goodness, it hath been brought by our ancestors,
I feel tender desires that we who sometimes meet in silence,
may never by our conduct lay stumbling blocks in the way of others,
and hinder the progress of the reformation in the world.

It was a complaint against some who were called the Lord`'s people,
that they brought polluted bread to his altar,
and said the table of the Lord was contemptible.

In real silent worship the soul feeds on that which is Divine;
but we cannot partake of the table of the Lord,
and that table which is prepared by the god of this world.

If Christ is our shepherd and feedeth us, and we are faithful in following him,
our lives will have an inviting language, and the table of the Lord will not be polluted.
