[quote.epigraph, , Isaiah 32:17]
____
The work of righteousness shall be peace;
and the effect of righteousness, quietness and assurance forever.
____

[#testimony-yorkshire.style-blurb, short="Testimony of Yorkshire Friends"]
== The Testimony of Friends in Yorkshire, at their Quarterly Meeting held at York, the 24th and 25th of the third month, 1773, concerning John Woolman, of Mount Holly, in the province of New Jersey, in America, who departed this life at the house of our friend Thomas Priestman, in the suburbs of this city, the 7th of the tenth month, 1772, and was interred in the burying-ground of Friends, the 9th of the same, aged about fifty-two years.

This our valuable friend having been under a religious engagement for some time,
to visit Friends in this nation, and more especially us in the northern parts,
undertook the same with the full concurrence and near
sympathy of his friends and brethren at home,
as appeared by certificates from the Monthly and Quarterly Meetings to which he belonged,
and from the Spring-meeting of ministers and elders, held at Philadelphia,
for Pennsylvania and New Jersey.

He arrived in the city of London at the beginning of the last Yearly Meeting,
and after attending that meeting travelled northward,
visiting the Quarterly Meetings of Hertfordshire, Buckinghamshire, Northamptonshire,
Oxfordshire and Worcestershire, and various particular meetings in his way.

He visited many meetings on the west side of this county,
also some in Lancashire and Westmoreland,
from which he came to our Quarterly Meeting in the last ninth month;
and though much out of health,
yet was enabled to attend all the sittings of that meeting except the last.

His disorder, which proved to be the smallpox, increased speedily upon him,
and was very afflicting; under which he was supported in much meekness,
patience and Christian fortitude.
To those who attended him in his illness,
his mind appeared to be centered in Divine love, under the precious influence whereof,
we believe he finished his course, and entered into the mansions of everlasting rest.

In the early part of his illness he requested a Friend to write,
and then broke forth thus:
"`O Lord my God! the amazing horrors of darkness were gathered
around me and covered me all over and I saw no way to go forth.
I felt the misery of my fellow creatures separated from the Divine harmony
and it was heavier than I could bear--I was crushed down under it.
I lifted up my hand, and stretched out my arm, but there was none to help me.
I looked round about and was amazed.
In the depths of misery, O Lord!
I remembered that you are omnipotent, that I had called you Father.
I felt that I loved you, and I was made quiet in your will.
I waited for deliverance from you, and you had pity upon me, when no man could help me.
I saw that meekness under suffering was showed
to us in the most affecting example of your Son,
and that you were teaching me to follow him: and I said, your will, O Father, be done.`"
Many more of his weighty expressions might have been inserted here,
but it was deemed unnecessary, they being already published.

He was a man endued with a large natural capacity,
and being obedient to the manifestations of Divine grace,
having in patience and humility endured many deep baptisms,
he became thereby sanctified and fitted for the Lord`'s work,
and was truly serviceable in his church.
Dwelling in awful fear and watchfulness,
he was careful in his public appearances to feel the putting forth of the Divine Hand,
so that the spring of the Gospel ministry often flowed
through him with great sweetness and purity,
as a refreshing stream to the weary travelers towards the city of God.

Skillful in dividing the word,
he was furnished by Him in whom are hid all the treasures of wisdom and knowledge,
to communicate freely to the several states of the people where his lot was cast.
His conduct at other times was seasoned with the like watchful
circumspection and attention to the guidance of Divine wisdom,
which rendered his whole conversation edifying.

He was fully persuaded, that as the life of Christ comes to reign in the earth,
all abuse and unnecessary oppression,
both of the human and brute creation will come to an end;
but under the sense of a deep revolt, and an overflowing stream of unrighteousness,
his life was often a life of mourning.

He was deeply concerned on account of that inhuman and
iniquitous practice of making slaves of the people of Africa,
or holding them in that state;
and on that account we understand he not only wrote some books,
but travelled much on the continent of America, in order to make the Negro masters,
especially those in profession with us, sensible of the evil of such a practice;
and though in this journey to England he was far
removed from the outward sight of their sufferings,
yet his deep exercise of mind remained,
as appears by a short treatise he wrote in this journey,
and his frequent concern to open the miserable state of this deeply injured people.

His testimony in the last meeting he attended was on this subject, wherein he remarked,
that as we as a Society,
when under outward sufferings had often found it our
concern to lay them before those in authority,
and thereby in the Lord`'s time, had obtained relief,
so he recommended this oppressed part of the creation to our notice,
that as way may open, we may represent their sufferings in an individual,
if not a Society capacity to those in authority.

Deeply sensible that the desire to gratify people`'s
inclinations in luxury and superfluities,
is the principal ground of oppression, and the occasion of many unnecessary needs,
he believed it to be his duty to be a pattern of great self-denial,
with respect to the things of this life,
and earnestly to labor with Friends in the meekness of wisdom,
to impress on their minds the great importance of our testimony in these things;
recommending them to the guidance of the blessed Truth in this and all other concerns,
and cautioning such as are experienced therein,
against contenting themselves with acting up to the standard of others,
but to be careful to make the standard of Truth manifested to them,
the measure of their obedience; for said he,
"`That purity of life which proceeds from faithfulness in following the Spirit of Truth;
that state where our minds are devoted to serve God,
and all our needs are bounded by his wisdom;
this habitation has often been opened before me as a
place of retirement for the children of the light,
where they may stand separated from that which
disorders and confuses the affairs of Society,
and where we may have a testimony of our
innocence in the hearts of those who behold us.`"
We conclude with fervent desires, that we as a people may thus, by our example,
promote the Lord`'s work in the earth; and our hearts being prepared,
may unite in prayer to the great Lord of the harvest,
that as in his infinite wisdom he has greatly stripped the church,
by removing of late several faithful ministers and elders,
he may be pleased to send forth many more faithful laborers into his harvest.

Signed in, by order, and on behalf of said meeting.

Thomas Bennett, John Storr, Joseph Eglin, Thomas Perkinson, Joseph Wright,
Samuel Briscoe, John Turner, Joshua Robinson, Thomas Priestman,
and several other Friends.
