[#testimony-burlington.style-blurb, short="Testimony of Burlington Friends"]
== A Testimony of the Monthly Meeting of Friends, held in Burlington, the 1st day of the eighth month, in the year of our Lord, 1774, concerning our esteemed friend, John Woolman, deceased.

He was born in Northampton, in the county of Burlington, and province of West New Jersey,
in the eighth month, 1720, of religious parents,
who instructed him very early in the principles of the Christian religion,
as professed by the people called Quakers, which he esteemed a blessing to him,
even in his young years, tending to preserve him from the infection of wicked children.
But through the workings of the enemy, and the levity incident to youth,
he frequently deviated from those parental precepts,
by which he laid a renewed foundation for repentance,
that was finally succeeded by a godly sorrow not to be repented of,
and so became acquainted with that sanctifying
power which qualifies for true Gospel ministry,
into which he was called about the twenty-second year of his age,
and by a faithful use of the talents committed to him, he experienced an increase,
until he arrived at the state of a father,
capable of dividing the word aright to the different states he ministered unto;
dispensing milk to babes, and meat to those of riper years.
Thus he found the efficacy of that power to arise, which, in his own expressions,
"`prepares the creature to stand like a trumpet through which the Lord speaks to his people.`"
He was a loving husband, a tender father,
and very humane to every part of the creation under his care.

His concern for the poor and those in affliction was evident by his visits to them;
and he frequently relieved them by his assistance and charity.
He was for many years deeply exercised on account of the poor enslaved Africans,
whose cause, as he sometimes mentioned, lay almost continually upon him,
and to obtain liberty to those captives, he labored both in public and private,
and was favored to see his endeavors crowned with considerable success.
He was particularly desirous that Friends should not be
instrumental to lay burdens on this oppressed people,
but remember the days of suffering from which they had been providentially delivered,
that if times of trouble should return,
no injustice dealt to those in slavery might rise in judgment against us, but,
being clear, we might on such occasions address the Almighty with a degree of confidence,
for his interposition and relief; being particularly careful as to himself,
not to countenance slavery,
even by the use of those conveniences of life which were furnished by their labor.

He was desirous to have his own mind, and the minds of others,
redeemed from the pleasures and immoderate profits of this world,
and to fix them on those joys which fade not away;
his principal care being after a life of purity,
endeavoring to avoid not only the grosser pollutions, but those also,
which appearing in a more refined dress,
are not sufficiently guarded against by some well disposed people.
In the latter part of his life he was remarkable
for the plainness and simplicity of his dress,
and as much as possible, avoided the use of plate, costly furniture and feasting;
thereby endeavoring to become an example of temperance and self-denial,
which he believed himself called unto, and was favored with peace therein,
although it carried the appearance of great austerity in the view of some.
He was very moderate in his charges in the way of business,
and in his desires after gain; and though a man of industry,
avoided and strove much to lead others out of extreme
labor and anxiousness after perishable things;
being desirous that the strength of our bodies might
not be spent in procuring things unprofitable,
and that we might use moderation and kindness to the brute animals under our care,
to prize the use of them as a great favor, and by no means to abuse them;
that the gifts of Providence should be thankfully
received and applied to the uses they were designed for.

He several times opened a school at Mount Holly,
for the instruction of poor Friends`' children and others,
being concerned for their help and improvement therein.
His love and care for the rising youth among us was truly great,
recommending to parents and those who have the charge of them,
to choose conscientious and pious tutors, saying,
"`It is a lovely sight to behold innocent children,`" and "`to labor
for their help against that which would mar the beauty of their minds,
is a debt we owe them.`"
His ministry was sound, very deep and penetrating,
sometimes pointing out the dangerous situation which indulgence and custom lead into;
frequently exhorting others, especially the youth,
not to be discouraged at the difficulties which occur, but to press after purity.

He often expressed an earnest engagement that pure wisdom should be attended to,
which would lead into lowliness of mind and resignation to the Divine will,
in which state small possessions here would be sufficient.

In transacting the affairs of discipline, his judgment was sound and clear,
and he was very useful in treating with those who had done amiss:
he visited such in a private way in that plainness which Truth dictates,
showing great tenderness and Christian forbearance.

He was a constant attender of our Yearly Meeting, in which he was a good example,
and particularly useful;
assisting in the business thereof with great weight and attention.
He several times visited most of the meetings of
Friends in this and the neighboring provinces,
with the concurrence of the Monthly Meeting to which he belonged,
and we have reason to believe had good service therein,
generally or always expressing at his return how it had fared with him,
and the evidence of peace in his mind for thus performing his duty.
He was often concerned with other Friends in the important service of visiting families,
which he was enabled to go through to satisfaction.

In the minutes of the meeting of ministers and elders for this quarter,
at the foot of a list of the members of that meeting,
made about five years before his death,
we find in his hand writing the following observation and reflections.

[.embedded-content-document]
--

As looking over the minutes made by persons who have put off this body,
has sometimes revived in me a thought how ages pass away;
so this list may probably revive a like thought in some,
when I and the rest of the persons above-named,
are centered in another state of being.--The Lord, who was the guide of my youth,
has in tender mercies helped me hitherto; he has healed me of wounds,
he has helped me out of grievous entanglements; he remains to be the strength of my life;
to whom I desire to devote myself in time, and in eternity.

[.signed-section-signature]
Signed, John Woolman.

--

In the twelfth month, 1771,
he acquainted this meeting that he found his mind drawn
towards a religious visit to Friends in some parts of England,
particularly in Yorkshire.

In the first month, 1772, he obtained our certificate,
which was approved and endorsed by our Quarterly Meeting,
and by the Half-year`'s meeting of ministers and elders at Philadelphia.

He embarked on his voyage in the fifth,
and arrived in London in the sixth month following,
at the time of their annual meeting in that city.
During his short visit to Friends in that kingdom,
we are informed that his services were acceptable and edifying.

In his last illness he uttered many lively and comfortable expressions,
being "`perfectly resigned, having no will either to live or die,`"
as appears by the testimony of Friends at York,
in Great Britain, in the suburbs whereof, at the house of our friend Thomas Priestman,
he died of the small-pox, on the 7th day of the tenth month, 1772,
and was buried in Friends`' burying-ground in that city, on the 9th of the same,
after a large and solid meeting held on the occasion, aged nearly fifty-two years;
a minister upwards of thirty years,
during which time he belonged to Mount Holly particular Meeting,
which he diligently attended when at home and in health of body,
and his labors of love and pious care for the prosperity of Friends in the blessed Truth,
we hope may not be forgotten, but that his good works may be remembered to edification.

Signed in, and by order of the said meeting, by Samuel Allinson, Clerk.

Read and approved at our Quarterly Meeting,
held at Burlington the 29th of the eighth month, 1774.

Signed by order of said meeting, Daniel Smith, Clerk.
