== Chapter I.

[.chapter-synopsis]
* His birth and parentage, with some account of the operations of Divine grace on his mind in his youth
* his first appearance in the ministry
* considerations while young on keeping slaves.

I have often felt a motion of love to leave some hints
in writing of my experience of the goodness of God;
and now, in the thirty-sixth year of my age, I begin this work.

I was born in Northampton, in Burlington county, West Jersey, in the year 1720;
and before I was seven years old I began to be
acquainted with the operations of Divine love.

Through the care of my parents,
I was taught to read nearly as soon as I was capable of it;
and as I went from school one seventh-day, I remember,
while my companions went to play by the way, I went forward out of sight,
and sitting down, I read the twenty-second chapter of the Revelations;
"`He showed me a pure river of water of life, clear as crystal,
proceeding out of the throne of God and of the Lamb, etc.;`" and in reading it,
my mind was drawn to seek after that pure habitation, which, I then believed,
God had prepared for his servants.
The place where I sat, and the sweetness that attended my mind, remain fresh in my memory.

This, and the like gracious visitations, had such an effect upon me,
that when boys used ill language, it troubled me;
and through the continued mercies of God, I was preserved from it.

The pious instructions of my parents were often fresh
in my mind when I happened to be among wicked children,
and were of use to me.
My parents having a large family of children,
used frequently on first-days after meeting, to put us to read in the Holy Scriptures,
or some religious books, one after another,
the rest sitting by without much conversation; which, I have since often thought,
was a good practice.
From what I had read and heard, I believed there had been, in past ages,
people who walked in uprightness before God,
in a degree exceeding any that I knew or heard of, now living:
and the apprehension of there being less steadiness and
firmness amongst people in this age than in past ages,
often troubled me while I was a child.

A thing remarkable in my childhood was, that once going to a neighbor's house,
I saw on the way, a robin sitting on her nest, and as I came near she went off, but,
having young ones, flew about and with many cries expressed her concern for them.
I stood and threw stones at her, till one striking her, she fell down dead:
at first I was pleased with the exploit, but after a few minutes was seized with horror,
for having, in a sportive way,
killed an innocent creature while she was careful for her young.
I beheld her lying dead, and thought those young ones, for which she was so careful,
must now perish for lack of their dam to nourish them;
and after some painful considerations on the subject, I climbed up the tree,
took all the young birds and killed them,
supposing that better than to leave them to pine away and die miserably; and believed,
in this case, that Scripture proverb was fulfilled,
"`The tender mercies of the wicked are cruel.`"
I then went on my errand, but, for some hours,
could think of little else but the cruelties I had committed, and was much troubled.

Thus He, whose tender mercies are over all his works,
has placed a principle in the human mind,
which incites to exercise goodness towards every living creature;
and this being singly attended to, people become tender-hearted and sympathizing;
but being frequently and totally rejected,
the mind becomes shut up in a contrary disposition.

About the twelfth year of my age, my father being abroad,
my mother reproved me for some misconduct, to which I made an undutiful reply;
and the next first-day, as I was with my father returning from meeting,
he told me he understood I had behaved amiss to my mother,
and advised me to be more careful in future.
I knew myself blamable, and in shame and confusion remained silent.

Being thus awakened to a sense of my wickedness, I felt remorse in my mind,
and getting home, I retired and prayed to the Lord to forgive me;
and do not remember that I ever, after that, spoke unhandsomely to either of my parents,
however foolish in some other things.

Having attained the age of sixteen years, I began to love wanton company;
and though I was preserved from profane language, or scandalous conduct,
still I perceived a plant in me which produced many wild grapes.

Yet my merciful Father forsook me not utterly, but at times, through his grace,
I was brought seriously to consider my ways;
and the sight of my backslidings affected me with sorrow;
but for lack of rightly attending to the reproofs of instruction,
vanity was added to vanity, and repentance to repentance.
Upon the whole, my mind was more and more alienated from the Truth,
and I hastened toward destruction.
While I meditate on the gulf towards which I travelled,
and reflect on my youthful disobedience, for these things I weep,
mine eye runs down with water.

Advancing in age, the number of my acquaintance increased,
and thereby my way grew more difficult.
Though I had found comfort in reading the Holy Scriptures,
and thinking on heavenly things, I was now estranged therefrom.
I knew that I was going from the flock of Christ, and had no resolution to return;
hence serious reflections were uneasy to me,
and youthful vanities and diversions my greatest pleasure.
Running in this road I found many like myself;
and we associated in that which is the reverse to true friendship.

But in this swift race it pleased God to visit me with sickness,
so that I doubted of recovering; and then did darkness, horror and amazement,
with full force, seize me, even when my pain and distress of body were very great.
I thought it would have been better for me never to have had a being,
than to see the day which I now saw.
I was filled with confusion; and in great affliction, both of mind and body,
I lay and bewailed myself.

I had not confidence to lift up my cries to God, whom I had thus offended;
but in a deep sense of my great folly, I was humbled before' him: and at length,
that word which is as a fire and a hammer, broke and dissolved my rebellious heart,
and then my cries were put up in contrition;
and in the multitude of his mercies I found inward relief, and felt a close engagement,
that if he was pleased to restore my health, I might walk humbly before him.

After my recovery, this exercise remained with me a considerable time; but by degrees,
giving way to youthful vanities, they gained strength,
and getting with wanton young people I lost ground.
The Lord had been very gracious, and had spoken peace to me in the lime of my distress;
and I now most ungratefully turned again to folly; on which account, at times,
I felt sharp reproof, but did not get low enough to cry for help.
I was not so hardy as to commit things scandalous;
but to exceed in vanity and promote mirth, were my chief study.
Still I retained a love and esteem for pious people;
and their company brought an awe upon me.
My dear parents, several times admonished me in the fear of the Lord,
and their admonition entered into my heart, and had a good effect for a season;
but not getting deep enough to pray rightly, the tempter, when he came, found entrance.

I remember that once, having spent a part of the day in wantonness,
as I went to bed at night, a Bible lay in a window near my bed, which I opened,
and first cast my eye on the text, "`we lie down in our shame,
and our confusion covers us;`" this I knew to be my case;
and meeting with so unexpected a reproof, I was somewhat affected with it,
and went to bed under remorse of conscience; which I soon cast off again.

Thus time passed on: my heart was replenished with mirth and wantonness,
while pleasing scenes of vanity were presented to my imagination,
till I attained the age of eighteen years;
near which time I felt the judgments of God in my soul, like a consuming fire;
and looking over my past life, the prospect was moving.
I was often sad, and longed to be delivered from those vanities; then again,
my heart was strongly inclined to them, and there was in me a sore conflict.
At times I turned to folly; and then sorrow and confusion took hold of me.
In a while, I resolved totally to leave off some of my vanities;
but there was a secret reserve in my heart, of the more refined part of them,
and I was not low enough to find true peace.
Thus, for some months, I had great troubles, there remaining in me an unsubjected will,
which rendered my labors fruitless, till at length,
through the merciful continuance of heavenly visitations,
I was made to bow down in spirit before the Lord.
I remember one evening I had spent some time in reading a pious author;
and walking out alone, I humbly prayed to the Lord for his help,
that I might be delivered from all those vanities which so ensnared me.

Thus being brought low, he helped me; and as I learned to bear the cross,
I felt refreshment to come from his presence;
but not keeping in that strength which gave victory, I lost ground again;
the sense of which greatly affected me; and I sought deserts and lonely places,
and there with tears did confess my sins to God, and humbly craved help of him.

I may say with reverence, he was near to me in my troubles,
and in those times of humiliation opened my ear to discipline.
I was now led to look seriously at the means by which I was drawn from the pure truth,
and learned this,
that if I would live in the life which the faithful servants of God lived in,
I must not go into company as heretofore in my own will;
but all the cravings of sense must be governed by a Divine principle.
In limes of sorrow and abasement these instructions were sealed upon me,
and I felt the power of Christ prevail over selfish desires,
so that I was preserved in a good degree of steadiness; and being young, and believing,
at that time, that a single lite was best for me,
I was strengthened to keep from such company as had often been a snare to me.

I kept steadily to meetings;
spent first-day afternoon chiefly in reading the Scriptures and other good books;
and was early convinced in my mind, that true religion consisted in an inward life,
wherein the heart does love and reverence God the Creator,
and learns to exercise true justice and goodness, not only toward all men,
but also toward the brute creatures.
That as the mind is moved by an inward principle,
to love God as an invisible incomprehensible Being;
by the same principle it is moved to love him in
all his manifestations in the visible world.
That, as by his breath the flame of life was kindled in all sensible creatures,
to say we love God as unseen, and, at the same time,
exercise cruelty toward the least creature moving by his life,
or by life derived from him, is a contradiction in itself.

I found no narrowness respecting sects and opinions; but believed,
that sincere upright-hearted people, in every society, who truly love God,
were accepted of him.

As I lived under the cross, and simply followed the openings of Truth, my mind,
from day to day, was more enlightened;
my former acquaintance were left to judge of me as they would,
for I found it safest for me to live in private,
and to keep these things sealed up in my own breast.
While I silently ponder on that change wrought in me,
I find no language equal to +++[+++describe]
it, nor any means to convey to another a clear idea of it.
I looked upon the works of God in this visible creation, and an awfulness covered me;
my heart was tender and often contrite,
and universal love to my fellow-creatures increased in me:
this will be understood by such who have trodden in the same path.

Some glances of real beauty may be seen in their faces who dwell in true meekness.

There is a harmony in the sound of that voice to which Divine love gives utterance,
and some appearance of right order in their temper and conduct,
whose passions are regulated;
yet all these do not fully show forth that inward life to such who have not felt it
but this white stone and new name are known rightly to such only who have them.

Though I had been thus strengthened to bear the cross,
I still found myself in great danger, having many weaknesses attending me,
and strong temptations to wrestle with;
in the feeling whereof I frequently withdrew into private places,
and often with tears besought the Lord to help me, whose gracious ear was open to my cry.

All this time I lived with my parents, and wrought on the plantation;
and having had schooling pretty well for a planter,
I used to improve it in winter evenings, and other leisure times;
and being now in the twenty-first year of my age, a man,
in much business at shop-keeping and baking,
asked me if I would hire with him to tend shop and keep books.
I acquainted my father with the proposal; and, after some deliberation,
it was agreed for me to go.

At home I had lived retired;
and now having a prospect of being much in the way of company,
I felt frequent and fervent cries in my heart to God, the Father of mercies,
that he would preserve me from all taint and corruption; that,
in this more public employment, I might serve Him, my gracious Redeemer,
in that humility and self-denial, with which I had been, in a small degree,
exercised in a more private life.
The man, who employed me, furnished a shop in Mount Holly,
about five miles from my father's house, and six from his own; and there I lived alone,
and tended his shop.
Shortly after my settlement here,
T was visited by several young people my former acquaintance,
who knew not but vanities would be as agreeable to me now as ever; and, at these times,
I cried to the Lord in secret for wisdom and strength;
for I felt myself encompassed with difficulties,
and had fresh occasion to bewail the follies of time past,
in contracting a familiarity with libertine people:
and as I had now left my father's house outwardly,
I found my heavenly Father to be merciful to me beyond what I can express.

By day I was much amongst people, and had many trials to go through; but in the evenings,
I was mostly alone, and may with thankfulness acknowledge, that, in those times,
the spirit of supplication was often poured upon me;
under which I was frequently exercised, and felt my strength renewed.

In a few months after I came here, my master bought several Scotchmen as servants,
from on board a vessel, and brought them to Mount Holly to sell;
one of whom was taken sick, and died.

In the latter part of his sickness, he, being delirious,
used to curse and swear most sorrowfully; and the next night after his burial,
I was left to sleep alone in the same chamber where he died.
I perceived in me a timorousness; I knew, however, that I had not injured the man,
but assisted in taking care of him according to my capacity;
and was not free to ask anyone, on that occasion, to sleep with me: nature was feeble;
but every trial was a fresh incitement to give myself up wholly to the service of God,
for I found no helper like him in times of trouble.

After awhile, my former acquaintance gave over expecting me as one of their company;
and I began to be known to some whose conversation was helpful to me.
As I had experienced the love of God, through Jesus Christ,
to redeem me from many pollutions, and to be a succor to me through a sea of conflicts,
with which no person was fully acquainted,
and as my heart was often enlarged in this heavenly principle,
I felt a tender compassion for the youth,
who remained entangled in snares like those
which had entangled me from one time to another;
this love and tenderness increased;
and my mind was more strongly engaged for the good of my fellow-creatures.

I went to meetings in an awful frame of mind,
and endeavored to be inwardly acquainted with the language of the true Shepherd;
and one day, being under a strong exercise of spirit, I stood up,
and said some words in a meeting; but not keeping close to the Divine opening,
I said more than was required of me; and being soon sensible of my error,
I was afflicted in mind some weeks, without any light or comfort,
even to such a degree that I could not take satisfaction in anything.
I remembered God and was troubled; and, in the depth of my distress, he had pity upon me,
and sent the Comforter.
I then felt forgiveness for my offense, and my mind became calm and quiet,
being truly thankful to my gracious Redeemer for his mercies; and after this,
feeling the spring of Divine love opened, and a concern to speak,
I said a few words in a meeting, in which I found peace; this, I believe,
was about six weeks from the first time.
As I was thus humbled and disciplined under the cross,
my understanding became more strengthened to distinguish the
pure Spirit which inwardly moves upon the heart,
and taught me to wait in silence, sometimes many weeks together,
until I felt that rise which prepares the creature to stand like a trumpet,
through which the Lord speaks to his flock.

From an inward purifying, and a steadfast abiding under it,
springs a lively operative desire for the good of others:
all the faithful are not called to the public ministry; but whoever are,
are called to minister of that which they have tasted and handled spiritually.
The outward modes of worship are various;
but wherever any are true ministers of Jesus Christ,
it is from the operation of his Spirit upon their hearts, first purifying them,
and thus giving them a just sense of the conditions of others.

This truth was early fixed in my mind; and I was taught to watch the pure opening,
and to take heed, lest, while I was standing to speak, my own will should get uppermost,
and cause me to utter words from worldly wisdom,
and depart from the channel of the true Gospel ministry.
In the management of my outward affairs, I may say with thankfulness,
I found truth to be my support; and I was respected in my master's family,
who came to live in Mount Holly within two years after my going there.

About the twenty-third year of my age, I had many fresh and heavenly openings,
in respect to the care and providence of the Almighty over his creatures in general,
and over man as the most noble amongst those which are visible.
And being clearly convinced in my judgment,
that to place my whole trust in God was best for me, I felt renewed engagements,
that in all things I might act on an inward principle of virtue,
and pursue worldly business no further than Truth opened my way therein.

About the time called Christmas, I observed that many people from the country,
and dwellers in town, resorting to public-houses,
spent their time in drinking and vain sports, tending to corrupt one another;
on which account I was much troubled.
At one house in particular there was much disorder;
and I believed it was a duty incumbent on me to go and speak to the master of that house.
I considered I was young,
and that several elderly Friends in town had an opportunity to see these things;
but though I would gladly have been excused, yet I could not feel my mind clear.

The exercise was heavy: and as I was reading what the Almighty said to Ezekiel,
respecting his duty as a watchman, the matter was set home more clearly; and then,
with prayers and tears, I besought the Lord for his assistance,
who, in loving-kindness, gave me a resigned heart.
Then, at a suitable opportunity, I went to the public-house;
and seeing the man amongst much company, I went to him,
and told him I wanted to speak with him; so we went aside, and there,
in the fear and dread of the Almighty, I expressed to him what rested on my mind;
which he took kindly, and afterward showed more regard to me than before.
In a few years afterwards he died, middle-aged; and I often thought,
that had I neglected my duty in that case, it would have given me great trouble;
and I was humbly thankful to my gracious Father, who had supported me herein.

My employer having a negro woman, sold her, and desired me to write a bill of sale,
the man being waiting who bought her.
The thing was sudden;
and though the thoughts of writing an instrument of
slavery for one of my fellow-creatures felt uneasy,
yet I remembered that I was hired by the year,
that it was my master who directed me to do it, and that it was an elderly man,
a member of our Society, who bought her; so, through weakness, I gave way, and wrote it;
but, at the executing of it, I was so afflicted in my mind, that I said,
before my master and the Friend,
that I believed slave-keeping to be a practice inconsistent with the Christian religion.
This in some degree abated my uneasiness; yet, as often as I reflected seriously upon it,
I thought I should have been clearer, if I had desired to be excused from it,
as a thing against my conscience; for such it was.
Some time after this, a young man of our Society,
spoke to me to write a conveyance of a slave to him;
he having lately taken a negro into his house.

I told him, I was not easy to write it; for,
though many of our meeting and in other places kept slaves,
I still believed the practice was not right; and desired to be excused from the writing.
I spoke to him in good will; and he told me,
that keeping slaves was not altogether agreeable to his mind;
but that the slave being a gift made to his wife, he had accepted of her.
