== Chapter IV.

[.chapter-synopsis]
* His visiting the families of Friends at Burlington
* His journey to Pennsylvania, Maryland, Virginia and North Carolina
* Considerations on the state of Friends there, and the exercise he was under in traveling among those concerned in keeping slaves: with some observations on this subject
* His epistle to Friends at New Garden and Cane creek
* His thoughts on the neglect of a religious care in the education of the negroes.

The 13th day of the second month, in the year 1757, being then in good health,
and abroad with Friends visiting families, I lodged at a Friend`'s house in Burlington;
and going to bed about the time usual with me, I awoke in the night, and my meditations,
as I lay, were on the goodness and mercy of the Lord;
in a sense whereof my heart was contrite.

After this, I went to sleep again; and sleeping a short time, I awoke; it was yet dark,
and no appearance of day or moonshine; and as I opened mine eyes,
I saw a light in my chamber at the apparent distance of five feet,
about nine inches diameter, of a clear easy brightness,
and near its centre the most radiant.

As I lay still without any surprise looking upon it, words were spoken to my inward ear,
which filled my whole inward man: they were not the effect of thought,
nor any conclusion in relation to the appearance,
but as the language of the Holy One spoken in my mind; the words were:
Certain Evidence of Divine Truth; and were again repeated exactly in the same manner;
whereupon the light disappeared.

Feeling the exercise in relation to a visit to
the southern provinces to increase upon me,
I acquainted our Monthly Meeting therewith, and obtained their certificate.
Expecting to go alone, one of my brothers, who lived in Philadelphia,
having some business in North Carolina, proposed going with me part of the way;
but as he had a view of some outward affairs,
to accept of him as a companion seemed some difficulty with me.
I had conversation with him at sundry times, and at length, feeling easy in my mind,
I had conversation with several elderly Friends of Philadelphia on the subject;
and he obtaining a certificate suitable to the occasion,
we set off in the fifth month of the year 1757.
Coming to Nottingham week-day meeting, we lodged at John Churchman`'s,
and here I met with our friend Benjamin Buffington, from New England,
who was returning from a visit to the southern provinces.
From there we crossed the river Susquehanna, and lodged at William Cox`'s in Maryland;
and soon after I entered this province, a deep and painful exercise came upon me,
of which I had often had some feeling since my mind was drawn toward these parts,
and with which I had acquainted my brother before we agreed to join as companions.

As the people in this and the southern provinces live much on the labor of slaves,
many of whom are used hardly, my concern was,
that I might attend with singleness of heart to the voice of the true Shepherd,
and be so supported as to remain unmoved at the faces of men.

As it is common for Friends on such a visit to have entertainment free of cost,
a difficulty arose in my mind with respect to saving my money by kindness received,
which to me appeared to be the gain of oppression.
Receiving a gift, considered as a gift,
brings the receiver under obligations to the benefactor,
and has a natural tendency to draw the obliged into a party with the giver.

To prevent difficulties of this kind, and to preserve the minds of judges from any bias,
was that Divine prohibition; "`You shall not receive any gift:
for a gift blinds the wise, and perverts the words of the righteous.`"
As the disciples were sent forth without any provision for their journey,
and our Lord said the workman is worthy of his meat,
their labor in the Gospel was considered as a reward for their entertainment,
and therefore not received as a gift; yet, in regard to my present journey,
I could not see my way clear in that respect.
The difference appeared thus: The entertainment the disciples met with,
was from such whose hearts God had opened to receive them, from a love to them,
and the truth they published.
But we, considered as members of the same religious Society,
look upon it as a piece of civility to receive each other in such visits;
and such reception, at times, is partly in regard to reputation,
and not from an inward unity of heart and spirit.

Conduct is more convincing than language; and where people, by their actions,
manifest that the slave-trade is not so disagreeable to
their principles but that it may be encouraged,
there is not a sound uniting with some Friends who visit them.

The prospect of so weighty a work,
and being so distinguished from many whom I esteemed before myself, brought me very low;
and such were the conflicts of my soul, that I had a near sympathy with the prophet,
in the time of his weakness, when he said, "`If you deal thus with me, kill me,
I pray you,
if I have found favor in your sight;`" but I soon saw that this
proceeded from the lack of a full resignation to the Divine will.
Many were the afflictions which attended me; and in great abasement, with many tears,
my cries were to the Almighty, for his gracious and fatherly assistance; and then,
after a time of deep trial,
I was favored to understand the state mentioned by the psalmist,
more clearly than ever I had before; namely: "`My soul is even as a weaned child.`"
Being thus helped to sink down into resignation,
I felt a deliverance from that tempest in which I had been sorely exercised,
and in calmness of mind went forward, trusting that the Lord Jesus Christ,
as I faithfully attended to him, would be a counsellor to me in all difficulties;
and that by his strength I should be enabled even to leave
money with the members of Society where I had entertainment,
when I found that omitting it would obstruct
that work to which I believed he had called me.

And as I copy this after my return, I may add, that oftentimes I did so,
under a sense of duty.
The way in which I did it was thus;
when I expected soon to leave a Friend`'s house where I had had entertainment,
if I believed that I should not keep clear from
the gain of oppression without leaving money,
I spoke to one of the heads of the family privately,
and desired him to accept of some pieces of silver,
and give them to such of the negroes as he believed would make the best use of them;
and at other times I gave them to the negroes myself, as the way looked clearest to me.
As I expected this before I came out, I had provided a large number of small pieces;
and thus offering them to some who appeared to be wealthy people,
was a trial both to me and them: but the fear of the Lord so covered me at times,
that my way was made easier than I expected; and few, if any,
manifested any resentment at the offer, and most of them, after some talk,
accepted of them.

The 7th day of the fifth month, in the year 1757, I lodged at a Friend`'s house;
and the next day being the first of the week, was at Patapsco meeting;
then crossed Patuxent river, and lodged at a public house.

On the 9th breakfasted at a Friend`'s house; who putting us a little on our way,
I had conversation with him in the fear of the Lord, concerning his slaves;
in which my heart was tender, and I used much plainness of speech with him,
which he appeared to take kindly.
We pursued our journey without appointing meetings,
being pressed in my mind to be at the Yearly Meeting in Virginia.

In my traveling on the road, I often felt a cry rise from the centre of my mind, O Lord,
I am a stranger on the earth, hide not your face from me.
On the 11th day of the fifth month, we crossed the rivers Potomac and Rappahannock,
and lodged at Port Royal:
and on the way happening in company with a colonel of the militia,
who appeared to be a thoughtful man,
I took occasion to remark on the difference in general between
a people used to labor moderately for their living,
training up their children in frugality and business,
and those who live on the labor of slaves; the former, in my view,
being the most happy life: with which he concurred,
and mentioned the trouble arising from the untoward, slothful disposition of the negroes;
adding, that one of our laborers would do as much in a day as two of their slaves.
I replied, that free men, whose minds were properly on their business,
found a satisfaction in improving, cultivating and providing for their families;
but negroes, laboring to support others who claim them as their property,
and expecting nothing but slavery during life,
had not the like inducement to be industrious.

After some further conversation, I said that men having power, too often misapplied it;
that though we made slaves of the negroes, and the Turks made slaves of the Christians,
I believed that liberty was the natural right of all men equally; which he did not deny;
but said the lives of the negroes were so wretched in their own country,
that many of them lived better here than there.
I only said there is great odds in regard to us, on what principle we act;
and so the conversation on that subject ended.
I may here add, that another person, some time afterward,
mentioned the wretchedness of the negroes, occasioned by their intestine wars,
as an argument in favor of our fetching them away for slaves; to which I then replied,
if compassion on the Africans, in regard to their domestic troubles,
were the real motives of our purchasing them,
that spirit of tenderness being attended to, would incite us to use them kindly,
that as strangers brought out of affliction, their lives might be happy among us;
and as they are human creatures, whose souls are as precious as ours,
and who may receive the same help and comfort from the holy Scriptures as we do,
we could not omit suitable endeavors to instruct them therein.
But while we manifest by our conduct,
that our views in purchasing them are to advance ourselves;
and while our buying captives taken in war, animates those parties to push on that war,
and increase desolation among them; to say they live unhappily in Africa,
is far from being an argument in our favor.
I further said, the present circumstances of these provinces to me appear difficult;
the slaves look like a burdensome stone to such who burden themselves with them,
and that if the white people retain a resolution to prefer
their outward prospects of gain to all other considerations,
and do not act conscientiously toward them as fellow creatures,
I believe that burden will grow heavier and heavier,
until times change in a way disagreeable to us.
At this the person appeared very serious, and owned,
that in considering their condition and the manner of their treatment in these provinces,
he had sometimes thought it might be just in the Almighty so to order it.

Having travelled through Maryland, we came among Friends at Cedar creek in Virginia,
on the 12th day of the fifth month; and the next day rode,
in company with several Friends, a day`'s journey to Camp creek.

As I was riding along in the morning,
my mind was deeply affected in a sense I had of the lack of Divine
aid to support me in the various difficulties which attended me;
and in an uncommon distress of mind, I cried in secret to the Most High,
O Lord! be merciful, I beseech you, to your poor afflicted creature.

After some time, I felt inward relief; and soon after,
a Friend in company began to talk in support of the slave-trade,
and said the negroes were understood to be the offspring of Cain,
their blackness being the mark God set upon him after he murdered Abel, his brother,
and that it was the design of Providence they should be slaves,
as a condition proper to the race of so wicked a man as Cain was.
Then another spoke in support of what had been said.
To all which, I replied in substance as follows:
Noah and his family were all who survived the flood, according to Scripture;
and as Noah was of Seth`'s race, the family of Cain was wholly destroyed.
One of them said, that after the flood Ham went to the land of Nod, and took a wife;
that Nod was a land far distant, inhabited by Cain`'s race,
and that the flood did not reach it;
and as Ham was sentenced to be a servant of servants to his brethren,
these two families being thus joined, were undoubtedly fit only for slaves.
I replied, the flood was a judgment upon the world for their abominations;
and it was granted that Cain`'s stock was the most wicked,
and therefore unreasonable to suppose they were spared:
as to Ham`'s going to the land of Nod for a wife, no time being fixed.
Nod might be inhabited by some of Noah`'s family, before Ham married a second time;
moreover the text says, "`That all flesh died that moved upon the earth.`"
I further reminded them, how the prophets repeatedly declare,
"`that the son shall not suffer for the iniquity of the father;
but every one be answerable for his own sins.`"
I was troubled to perceive the darkness of their imaginations;
and in some pressure of spirit said,
the love of ease and gain are the motives in general of keeping slaves,
and men are wont to take hold of weak arguments to support a cause which is unreasonable.

I have no interest on either side,
save only the interest which I desire to have in the Truth;
and as I believe liberty is their right, and see they are not only deprived of it,
but treated in other respects with inhumanity in many places, I believe He,
who is a refuge for the oppressed, will in his own time, plead their cause;
and happy will it be for such, who walk in uprightness before him:
thus our conversation ended.

On the 14th day of the fifth month I was at Camp creek Monthly Meeting,
and then rode to the mountains up James river, and had a meeting at a Friend`'s house;
in both which I felt sorrow of heart, and my tears were poured out before the Lord,
who was pleased to afford a degree of strength by which way
was opened to clear my mind among Friends in those places.
From there I went to Fork creek, and so to Cedar creek again;
at which place I now had a meeting.
Here I found a tender seed;
and as I was preserved in the ministry to keep low with the Truth,
the same Truth in their hearts answered it,
so that it was a time of mutual refreshment from the presence of the Lord.
I lodged at James Stanley`'s, father of William Stanley,
one of the young men who suffered imprisonment at Winchester last summer,
on account of their testimony against fighting;
and I had some satisfactory conversation with him concerning it.
Hence I went to the Swamp and Wainoak meetings; and then crossed James river,
and lodged near Burleigh.
From the time of my entering Maryland I have been much under sorrow,
which of late so increased upon me, that my mind was almost overwhelmed;
and I may say with the psalmist, "`in my distress I called upon the Lord,
and cried to my God;`" who, in infinite goodness, looked upon my affliction,
and in my private retirement sent the Comforter for my relief;
for which I humbly bless his holy name.

The sense I had of the state of the churches, brought a weight of distress upon me:
the gold to me appeared dim, and the fine gold changed;
and though this is the case too generally, yet the sense of it in these parts has,
in a particular manner, borne heavily upon me.
It appeared to me, that through the prevailing of the spirit of this world,
the minds of many were brought to inward desolation;
and instead of the spirit of meekness, gentleness and heavenly wisdom,
which are the necessary companions of the true sheep of Christ,
a spirit of fierceness and the love of dominion, too generally prevailed.
From small beginnings in error, great buildings by degrees, are raised,
and from one age to another are more and more
strengthened by the general concurrence of the people.
As men obtain reputation by their profession of the Truth,
their virtues are mentioned as arguments in favor of general error;
and those of less note, to justify themselves, say, such and such good men did the like.
By what other steps could the people of Judah rise to such a height in wickedness,
as to give just ground for the prophet Isaiah to declare in the name of the Lord,
"`that none calls for justice,
nor any pleads for truth:`" or for the Almighty to call upon the great city of Jerusalem,
just before the Babylonish captivity, "`If you can find a man,
if there be any who executes judgment, that seeks the Truth, and I will pardon it.`"
The prospect of a road lying open to the same degeneracy,
in some parts of this newly settled land of America,
in respect to our conduct toward the negroes, has deeply bowed my mind in this journey;
and though to relate briefly how these people are treated is no agreeable work,
yet after often reading over the notes I made as I travelled,
I find my mind engaged to preserve them.
Many of the white people in those provinces take little or no care of negro marriages;
and when negroes marry after their own way,
some make so little account of those marriages, that with views of outward interest,
they often part men from their wives by selling them far asunder;
which is common when estates are sold by executors at vendue.
Many whose labor is heavy, being followed at their business in the field,
by a man with a whip, hired for that purpose,
have in common little else allowed but one peck
of Indian corn and some salt for one week,
with a few potatoes;
the potatoes they commonly raise by their labor on the first-day of the week.

The correction ensuing on their disobedience to overseers, or slothfulness in business,
is often very severe, and sometimes desperate.
Men and women have many times scarcely clothes enough to hide their nakedness,
and boys and girls, ten and twelve years old,
are often quite naked among their master`'s children.

Some of our Society, and some of the Society called New Lights,
use some endeavors to instruct those they have in reading;
but in common this is not only neglected, but disapproved.
These are the people by whose labor the other
inhabitants are in a great measure supported,
and many of them in the luxuries of life:
these are the people who have made no agreement to serve us,
and who have not forfeited their liberty that we know of:
these are the souls for whom Christ died, and for our conduct toward them,
we must answer before Him who is no respecter of persons.

They who know the only true God, and Jesus Christ whom he has sent,
and are thus acquainted with the merciful, benevolent,
Gospel spirit,
will therein perceive that the indignation of
God is kindled against oppression and cruelty;
and in beholding the great distress of so numerous a people,
will find cause for mourning.

From my lodgings I went to Burleigh meeting,
where I felt my mind drawn into a quiet resigned state; and after long silence,
I felt an engagement to stand up; and through the powerful operation of Divine love,
we were favored with an edifying meeting.
The next meeting we had was at Black Water;
and so to the Yearly Meeting at the Western Branch.
When its business began, some queries were considered by some of their members,
to be now produced; and if approved,
to be answered hereafter by their respective Monthly Meetings.
They were the Pennsylvania queries,
which had been examined by a committee of Virginia Yearly Meeting appointed last year,
who made some alterations in them;
one of which alterations was made in favor of a custom which troubled me.
The query was, "`Are there any concerned in the importation of negroes,
or buying them after imported?`"
which they altered thus: "`Are there any concerned in the importation of negroes,
or buying them to trade in?`"
As one query admitted with unanimity was,
"`Are any concerned in buying or vending goods unlawfully imported, or prize goods?`"
I found my mind engaged to say, that as we professed the Truth,
and were there assembled to support the testimony of it,
it was necessary for us to dwell deep, and act in that wisdom which is pure,
or otherwise we could not prosper.
I then mentioned the alteration; and referring to the last mentioned query, added,
as purchasing any merchandise taken by the sword,
was always allowed to be inconsistent with our principles; negroes being captives of war,
or taken by stealth,
those circumstances make it inconsistent with our testimony to buy them;
and their being our fellow creatures, who are sold as slaves,
adds greatly to the iniquity.
Friends appeared attentive to what was said;
some expressed a care and concern about their negroes; none made any objection,
by way of reply to what I said; but the query was admitted as they had altered it.
As some of their members have heretofore traded in negroes, as in other merchandise,
this query, being admitted, will be one step further than they have hitherto gone.
I did not see it my duty to press for an alteration;
but felt easy to leave it all to Him, who alone is able to turn the hearts of the mighty,
and to make way for the spreading of Truth on the earth,
by means agreeable to his infinite wisdom.

But in regard to those they already had, I felt my mind engaged to labor with them;
and said, that,
as we believe the Scriptures were given forth by
holy men as they were moved by the Holy Ghost,
and many of us know by experience that they are often helpful and comfortable,
and believe ourselves bound in duty to teach our children to read them;
I believe that if we were divested of all selfish views,
the same good Spirit that gave them forth, would engage us to teach the negroes to read,
that they might have the benefit of them: there were some among them who, at this time,
manifested a concern in regard to taking more care in the education of their negroes.

On the 29th day of the fifth month, at the house where I lodged,
was a meeting of ministers and elders, at the ninth hour in the morning;
at which time I found an engagement to speak freely and
plainly to them concerning their slaves;
mentioning how they, as the first rank in the Society,
whose conduct in that case was much noticed by others,
were under the stronger obligations to look carefully to themselves:
expressing how needful it was for them, in that situation,
to be thoroughly divested of all selfish views; that living in the pure Truth,
and acting conscientiously toward those people in their education and otherwise,
they might be instrumental in helping forward a work so exceedingly necessary,
and so much neglected among them.
At the twelfth hour the meeting of worship began, which was solid.

On the 30th day, about the tenth hour, Friends met to finish their business,
and then the meeting for worship ensued, which to me was a laborious time;
but through the goodness of the Lord, Truth, I believe, gained some ground;
and it was a strengthening opportunity to the honest-hearted.

About this time I wrote an epistle to Friends in the back settlements of North Carolina,
as follows: To Friends at their Monthly Meeting at New Garden and Cane creek,
in North Carolina.

[.embedded-content-document.letter]
--
[.salutation]
Dear Friends,

It having pleased the Lord to draw me forth on a
visit to some parts of Virginia and Carolina,
you have often been in my mind;
and though my way is not clear to come in person to visit you,
yet I feel it in my heart to communicate a few things,
as they arise in the love of Truth.
First, my dear friends, dwell in humility;
and take heed that no views of outward gain get too deep hold of you,
that so your eyes being single to the Lord, you may be preserved in the way of safety.
Where people let loose their minds after the love of outward things,
and are more engaged in pursuing the profits and seeking the friendships of this world,
than to be inwardly acquainted with the way of true peace, such walk in a vain shadow,
while the true comfort of life is lacking; their examples are often hurtful to others;
and their treasures, thus collected,
do many times prove dangerous snares to their children.

But where people are sincerely devoted to follow Christ,
and dwell under the influence of his holy Spirit, their stability and firmness,
through a Divine blessing, is at times like dew on the tender plants around about them,
and the weightiness of their spirits secretly works on the minds of others;
and in this condition through the spreading influence of Divine love,
they feel a care over the flock and way is
opened for maintaining good order in the Society.
And though we meet with opposition from another spirit, yet,
as there is a dwelling in meekness, feeling our spirits subject,
and moving only in the gentle peaceable wisdom, the inward reward of quietness,
will be greater than all our difficulties.
Where the pure life is kept to,
and meetings of discipline are held in the authority of it,
we find by experience that they are comfortable, and tend to the health of the body.

While I write, the youth come fresh in my way.--Dear young people,
choose God for your portion; love his Truth, and be not ashamed of it;
choose for your company such who serve him in uprightness; and shun, as most dangerous,
the conversation of those whose lives are of an ill savor;
for by frequenting such company, some hopeful young people have come to great loss,
and been drawn from less evils to greater to their utter ruin.
In the bloom of youth no ornament is so lovely as that of virtue,
nor any enjoyments equal to those which we partake of,
in fully resigning ourselves to the Divine will.
These enjoyments add sweetness to all other comforts,
and give true satisfaction in company and conversation,
where people are mutually acquainted with it;
and as your minds are thus seasoned with the Truth,
you will find strength to abide steadfast to the testimony of it,
and be prepared for services in the church.

And now, dear friends and brethren, as you are improving a wilderness,
and may be numbered among the first planters in one part of a province, I beseech you,
in the love of Jesus Christ, wisely to consider the force of your examples,
and think how much your successors may be thereby affected.
It is a help in a country, yes, a great favor and a blessing, when customs first settled,
are agreeable to sound wisdom; so when they are otherwise,
the effect of them is grievous;
and children feel themselves encompassed with
difficulties prepared for them by their predecessors.

As moderate care and exercise, under the direction of true wisdom,
is useful both to mind and body; so by this means in general,
the real needs of life are easily supplied;
our gracious Father having so proportioned one to the other, that,
keeping in the true medium, we may pass on quietly.
Where slaves are purchased to do our labor, numerous difficulties attend.
To rational creatures bondage is uneasy,
and frequently occasions sourness and discontent in them; which affects the family,
and such who claim the mastery over them:
and thus people and their children are many times encompassed with vexations,
which arise from their applying to wrong methods to get a living.

I have been informed that there are a large number of Friends in your parts,
who have no slaves; and in tender and most affectionate love,
I beseech you to keep clear from purchasing any.
Look, my dear friends, to Divine Providence;
and follow in simplicity that exercise of body, that plainness and frugality,
which true wisdom leads to;
so may you be preserved from those dangers which attend
such who are aiming at outward ease and greatness.

Treasures, though small, attained on a true principle of virtue,
are sweet in the possession; and while we walk in the light of the Lord,
there is true comfort and satisfaction.

Here, neither the murmurs of an oppressed people,
nor the throbbing of an uneasy conscience,
nor anxious thoughts about the event of things, hinder the enjoyment of life.

When we look toward the end of life,
and think on the division of our substance among our successors;
if we know that it was collected in the fear of the Lord, in honesty, in equity,
and in uprightness of heart before him, we may consider it as his gift to us;
and with a single eye to his blessing, bestow it on those we leave behind us.
Such is the happiness of the plain way of true virtue.

"`The work of righteousness shall be peace and the effect of righteousness,
quietness and assurance forever.`"
Dwell here, my dear friends; and then in remote and solitary deserts,
you may find true peace and satisfaction.
If the Lord be our God, in truth and reality, there is safety for us;
for he is a strong hold in the day of trouble, and knows them that trust in him.

[.signed-section-signature]
John Woolman

[.signed-section-context-close]
Isle of Wight county, in Virginia, 29th of the Fifth month, 1757.

--

From the Yearly Meeting in Virginia, I went to Carolina;
and on the 1st day of the sixth month, was at Wells Monthly Meeting,
where the spring of the Gospel ministry was opened,
and the love of Jesus Christ experienced among us: to his name be the praise.

Here my brother joined with some Friends from New Garden, who were going homeward;
and I went next to Simons creek Monthly Meeting,
where I was silent during the meeting for worship.
When business came on, my mind was exercised concerning the poor slaves;
but I did not feel my way clear to speak:
in this condition I was bowed in spirit before the Lord;
and with tears and inward supplication besought him, so to open my understanding,
that I might know his will concerning me; and at length, my mind was settled in silence.
Near the end of their business, a member of the meeting expressed a concern,
that had some time lain upon him,
on account of Friends so much neglecting their duty in the education of their slaves,
and proposed having meetings sometimes appointed for them on a week-day,
to be only attended by some Friends to be named in their Monthly Meetings.
Many present appeared to unite with the proposal:
one said he had often wondered that they,
being our fellow creatures and capable of religious understanding,
had been so exceedingly neglected: another expressed the like concern,
and appeared zealous that Friends in future, might more closely consider it:
at length a minute was made;
and the further consideration of it referred to their next Monthly Meeting.

The Friend who made this proposal has negroes: he told me that he was at New Garden;
about two hundred and fifty miles from home, and came back alone;
and that in this solitary journey,
this exercise in regard to the education of their negroes, was, from time to time,
renewed in his mind.
A Friend of some note in Virginia, who has slaves, told me,
that he being far from home on a lonesome journey, had many serious thoughts about them;
and that his mind was so impressed therewith, that he believed he saw a time coming,
when Divine Providence would alter the circumstance of these people,
respecting their condition as slaves.

From hence I went to Newbegun creek, and sat a considerable time in much weakness;
then I felt Truth open the way to speak a little in much plainness and simplicity, till,
at length, through the increase of Divine love among us,
we had a seasoning opportunity.

From there I went to the head of Little river, where was, on a first-day,
a crowded meeting; and I believe, through Divine goodness,
it was made profitable to some.
From there to the Old Neck;
where I was led into a careful searching out the
secret workings of the mystery of iniquity,
which, under a cover of religion, exalts itself against that pure spirit,
which leads in the way of meekness and self-denial.
From there to Piney-woods; which was the last meeting I was at in Carolina,
and was large; and my heart being deeply engaged,
I was drawn forth in fervent labor among them.

When I was at Newbegun creek, a Friend was there who labored for his living,
having no negroes, and had been a minister many years.
He came to me the next day, and as we rode together,
signified that he wanted to talk with me concerning a difficulty he had been under,
and related it nearly as follows:
That as monies had been raised by a tax of late years to carry on war,
he had a scruple in his mind in regard to paying it,
and chose rather to suffer the seizure of his goods than pay it;
and as he was the only person who refused it in those parts,
and knew not that anyone else was in the like circumstances,
he signified that it had been a heavy trial to him, and more so,
for that some of his brethren had been uneasy with his conduct in that case.
He added, that from a sympathy he felt with me yesterday in meeting,
he found freedom thus to open the matter,
in the way of querying concerning Friends in our parts.

I told him the state of Friends among us, as well as I was able; and also,
that I had for some time been under the like scruple.
I believed him to be one who was concerned to walk uprightly before the Lord;
and esteemed it my duty to preserve this note concerning him; his name was Samuel Newby.

From hence I went back into Virginia, and had a meeting near James Cowpland`'s;
it was a time of inward suffering; but through the goodness of the Lord,
I was made content: then to another meeting; where, through the renewings of pure love,
we had a very comfortable season.

Traveling up and down of late, I have had renewed evidences,
that to be faithful to the Lord and contented with his will concerning me,
is a most necessary and useful lesson for me to be learning;
looking less at the effects of my labor,
than at the pure motion and reality of the concern, as it arises from heavenly love.
In the Lord Jehovah is everlasting strength; and as the mind, by humble resignation,
is united to him,
and we utter words from an inward knowledge that they arise from the heavenly spring,
though our way may be difficult, and require close attention to keep in it;
and though the manner in which we may be led may tend to our own abasement; yet,
if we continue in patience and meekness, heavenly peace is the reward of our labors.

From there I went to Curies meeting; which, though small,
was reviving to the honest-hearted.
From there to Black creek and Caroline meetings; from which,
accompanied by William Stanley, before mentioned, we rode to Goose creek,
being much through the woods, and about one hundred miles.
We lodged the first night, at a public house; the second in the woods;
and the next day we reached a Friend`'s house, at Goose creek.

In the woods we lay under some disadvantage,
having no fire-works nor bells for our horses; but we stopped a little before night,
and let them feed on the wild grass which was plenty;
in the mean time cutting with our knives a store against night, and then tied them;
and gathering some bushes under an oak, we lay down;
but the mosquitoes being plenty and the ground damp, I slept but little.

Lying in the wilderness, and looking at the stars,
I was led to contemplate the condition of our first parents,
when they were sent forth from the garden; but the Almighty,
though they had been disobedient, continued to be a Father to them,
and showed them what tended to their felicity as intelligent creatures,
and was acceptable to him.
To provide things relative to our outward living, in the way of true wisdom is good;
and the gift of improving in things useful, is a good gift,
and comes from the Father of lights.
Many have had this gift; and from age to age,
there have been improvements of this kind made in the world:
but some not keeping to the pure gift, have,
in the creaturely cunning and self-exaltation, sought out many inventions;
which inventions of men, distinct from that uprightness in which man was created,
as the first motion to them was evil, so the effects have been and are evil.
At this day, it is as necessary for us constantly to attend on the heavenly gift,
to be qualified to use rightly the good things in this life amidst great improvements,
as it was for our first parents, when they were without any improvements,
without any friend or father but God only.

I was at a meeting at Goose creek; and next at a Monthly Meeting at Fairfax; where,
through the gracious dealing of the Almighty with us,
his power prevailed over many hearts.

From there to Manoquacy and Pipe creek, in Maryland;
at both which places I had cause humbly to adore Him,
who supported me through many exercises,
and by whose help I was enabled to reach the true witness in the hearts of others:
there were some hopeful young people in those parts.
I had meetings at John Everit`'s in Monallen, and at Huntingdon;
and was made humbly thankful to the Lord,
who opened my heart among the people in these new settlements,
so that it was a time of encouragement to the honest minded.

At Monallen, a Friend gave me some account of a religious society, among the Dutch,
called Mennonists; and among other things, related a passage in substance as follows:
-- One of the Mennonists having acquaintance with a man
of another society at a considerable distance,
and being with his wagon on business near the house of his said acquaintance,
and night coming on, he had thoughts of putting up with him; but passing by his fields,
and observing the distressed appearance of his slaves,
he kindled a fire in the woods nearby, and lay there that night.

His acquaintance hearing where he lodged, and afterward meeting the Mennonist,
told him of it; adding, he should have been heartily welcome at his house;
and from their acquaintance in former time, he wondered at his conduct in that case.
The Mennonist replied, ever since I lodged by your field,
I have wanted an opportunity to speak with you.
I intended to come to your house for entertainment, but seeing your slaves at their work,
and observing the manner of their dress, I had no liking to come to partake with you:
he then admonished him to use them with more humanity, and added,
as I lay by the fire that night, I thought that as I was a man of substance,
you would have received me freely; but if I had been as poor as one of your slaves,
and had no power to help myself,
I should have received from your hand no kinder usage than they.

From hence I was at three meetings in my way, and so went home,
under a humbling sense of the gracious dealings of the Lord with me,
in preserving me through many trials and afflictions in my journey.
I was out about two months, and travelled about eleven hundred and fifty miles.
