== Chapter V.

[.chapter-synopsis]
* Considerations on the payment of a tax laid for carrying on the war against the Indians
* Some notes on Thomas a Kempis and John Huss
* Meetings of the committee of the Yearly Meeting at Philadelphia
* The present circumstances of Friends in Pennsylvania and New Jersey very different from those of our predecessors
* The drafting of the militia in New Jersey to serve in the army; with some observations on the state of the members of our Society at that time
* His visit to Friends in Pennsylvania, accompanied by Benjamin Jones
* Proceedings at the Monthly, Quarterly and Yearly Meetings in Philadelphia, respecting those who keep slaves.

A few years past, money being made current in our province for carrying on wars,
and to be called in again by taxes laid on the inhabitants,
my mind was often affected with the thoughts of paying such taxes;
and I believe it right for me to preserve a memorandum concerning it.
I was told, that Friends in England frequently paid taxes,
when the money was applied to such purposes.
I had conversation with several noted Friends on the subject,
who all favored the payment of such taxes; some of whom I preferred before myself,
and this made me easier for a time; yet there was in the deeps of my mind,
a scruple which I never could get over; and at certain times,
I was greatly distressed on that account.

I all along believed that there were some upright-hearted men, who paid such taxes;
but could not see that their example was a sufficient reason for me to do so,
while I believed that the Spirit of Truth required of me, as an individual,
to suffer patiently the distress of goods, rather than pay actively.

I have been informed that Thomas a Kempis lived and
died in the profession of the Roman Catholic religion:
and in reading his writings, I have believed him to be a man of a true Christian spirit;
as fully so,
as many who died martyrs because they could not
join with some superstitions in that church.

All true Christians are of the same spirit, but their gifts are diverse;
Jesus Christ appointing to each one their peculiar office,
agreeably to his infinite wisdom.

John Huss contended against the errors crept into the church,
in opposition to the council of Constance;
which the historian reports to have consisted of some thousand persons.
He modestly vindicated the cause which he believed was right;
and though his language and conduct toward his judges appear to have been respectful,
yet he never could be moved from the principles settled in his mind.
To use his own words; "`This I most humbly require and desire of you all,
even for his sake who is the God of us all,
that I be not compelled to the thing which my conscience does repugn or strive against.`"
And again, in his answer to the emperor: "`I refuse nothing, most noble emperor,
whatsoever the council shall decree or determine upon me, only this one thing I except,
that I do not offend God and my conscience.`"
Fox's Acts and Monuments, page 233. At length,
rather than act contrary to that which he believed the Lord required of him,
he chose to suffer death by fire.
Thomas a Kempis, without disputing against the articles then generally agreed to,
appears to have labored, by a pious example as well as by preaching and writing,
to promote virtue and the inward spiritual religion:
and I believe they were both sincere-hearted followers of Christ.

True charity is an excellent virtue: and to labor sincerely for their good, whose belief,
in all points, does not agree with ours, is a happy state.
To refuse the active payment of a tax which our Society generally paid,
was exceedingly disagreeable; but to do a thing contrary to my conscience,
appeared yet more dreadful.
When this exercise came upon me, I knew of none under the like difficulty;
and in my distress, I besought the Lord to enable me to give up all,
that so I might follow him wheresoever he was pleased to lead me.
Under this exercise I went to our Yearly Meeting at Philadelphia, in the year 1755;
at which a committee was appointed of some from each quarter,
to correspond with the Meeting for Sufferings in London;
and another to visit our Monthly and Quarterly Meetings; and after their appointment,
before the last adjournment of the meeting,
it was agreed that these two committees should meet
together in Friends' school-house in the city,
at a time then concluded on,
to consider some things in which the cause of Truth was concerned.
These committees meeting together, had a weighty conference in the fear of the Lord;
at which time,
I perceived there were many Friends under a scruple like that before-mentioned.^
footnote:[Christians refused to pay taxes to support Heathen temples.
See [.book-title] #Primitive Christianity#, part III. page 327]

As scrupling to pay a tax on account of the application,
has seldom been heard of heretofore, even amongst men of integrity,
who have steadily borne their testimony against war, in their time;
I may here note some things which have occurred to my mind,
as I have been inwardly exercised on that account.
From the steady opposition which faithful Friends, in early times,
made to wrong things then approved of,
they were hated and persecuted by men living in the spirit of this world;
and suffering with firmness, they were made a blessing to the church,
and the work prospered.
It equally concerns men in every age, to take heed to their own spirit;
and in comparing their situation with ours,
it looks to me that there was less danger of their
being infected with the spirit of this world,
in paying such taxes, than there is of us now.
They had little or no share in civil government; and many of them declared, they were,
through the power of God, separated from the spirit in which wars were;
and being afflicted by the rulers on account of their testimony,
there was less likelihood of uniting in spirit with
them in things inconsistent with the purity of Truth.
We, from the first settlement of this land, have known little or no troubles of that sort.
Their profession for a time, was accounted reproachful; but at length,
the uprightness of our predecessors being understood by the rulers,
and their innocent sufferings moving them, our way of worship was tolerated;
and many of our members in these colonies became active in civil government.
Being thus tried with favor and prosperity, this world has appeared inviting;
our minds have been turned to the improvement of our country,
to merchandize and sciences, amongst which are many things useful,
being followed in pure wisdom; but in our present condition,
that a carnal mind is gaining upon us, I believe will not be denied.

Some of our members, who are officers in civil government, are, in one case or other,
called upon in their respective stations to assist in things relative to the wars.
Such being in doubt whether to act, or crave to be excused from their office,
seeing their brethren united in the payment of a tax to carryon the said wars,
might think their case not much different,
and so quench the tender movings of the Holy Spirit in their minds; and thus,
by small degrees, there might be an approach toward fighting, until we came so near it,
as that the distinction would be little else but the name of a peaceable people.

It requires great self-denial and resignation of ourselves to God,
to attain that state wherein we can freely cease from fighting when wrongfully invaded,
if by our fighting, there was a probability of overcoming the invaders.

Whoever rightly attains to it, does, in some degree,
feel that spirit in which our Redeemer gave his life for us; and through Divine goodness,
many of our predecessors, and many now living, have learned this blessed lesson.

But many others, having their religion chiefly by education,
and not being enough acquainted with that cross which crucifies to the world,
manifest a temper distinguishable from that of an entire trust in God.
In calmly considering these things, it has not appeared strange to me,
that an exercise has now fallen upon some, which, as to the outward means of it,
is different from what was known to many of those who went before us.

Some time after the Yearly Meeting,
a day being appointed and letters written to distant members,
the said committees met at Philadelphia; and by adjournments, continued several days.
The calamities of war were now increasing;
the frontier inhabitants of Pennsylvania were frequently surprised, some slain,
and many taken captive by the Indians; and while these committees sat,
the corpse of one so slain was brought in a wagon,
and taken through the streets of the city, in his bloody garments, to alarm the people,
and rouse them up to war.

Friends thus met were not all of one mind in relation to the tax; which,
to such who scrupled it, made the way more difficult.
To refuse an active payment at such a time, might be construed into an act of disloyalty,
and appeared likely to displease the rulers, not only here but in England.
Still there was a scruple so fastened upon the minds of many Friends,
that nothing moved it: it was a conference the most weighty that ever I was at,
and the hearts of many were bowed in reverence before the Most High.
Some Friends of the said committees who appeared easy to pay the tax,
after several adjournments withdrew, others of them continued till the last.
At length, an epistle of tender love and caution to Friends in Pennsylvania,
was drawn by some Friends concerned, on that subject;
and being read several times and corrected,
was then signed by such of them as were free to sign it,
and afterward sent to the Monthly and Quarterly Meetings.

On the 9th day of the eighth month, in the year 1757, at night,
orders came to the military officers in our county,
(Burlington) directing them to draft the militia
and prepare a number of men to go as soldiers,
to the relief of the English at fort William Henry, in New York government.
A few days after, there was a general review of the militia at Mount Holly,
and a number of men chosen and sent off under some officers.
Shortly after, there came orders to draft three times as many,
to hold themselves in readiness to march when fresh orders came;
and on the 17th day of the eighth month,
there was a meeting of the military officers at Mount Holly, who agreed on a draft,
and orders were sent to the men so chosen,
to meet their respective captains at set times and places;
those in our township to meet at Mount Holly;
amongst whom were a considerable number of our Society.
My mind being affected herewith,
I had fresh opportunity to see and consider the
advantage of living in the real substance of religion,
where practice does harmonize with principle.

Amongst the officers are men of understanding,
who have some regard to sincerity where they see it;
and in the execution of their office,
when they have men to deal with whom they believe to be upright-hearted,
to put them to trouble on account of scruples of conscience, is a painful task,
and likely to be avoided as much as easily may be.
But where men profess to be so meek and heavenly minded,
and to have their trust so firmly settled in God, that they cannot join in wars; and yet,
by their spirit and conduct in common life, manifest a contrary disposition,
their difficulties are great at such a time.

Officers, who, in great anxiety,
are endeavoring to get troops to answer the demands of their superiors,
seeing men who are insincere, pretend a scruple of conscience,
in hopes of being excused from a dangerous employment, are likely to handle them roughly.
In this time of commotion some of our young men left the parts,
and tarried abroad till it was over; some came and proposed to go as soldiers;
others appeared to have a real tender scruple in their minds against joining in wars,
and were much humbled under the apprehension of a trial so near.
I had conversation with several of these to my satisfaction.

At the set time when the captain came to town,
some of those last-mentioned went and told him in substance as
follows:--That they could not bear arms for conscience-sake;
nor could they hire any to go in their places, being resigned as to the event of it:
at length the captain acquainted them all, that they might return home for the present,
and required them to provide themselves as soldiers,
and to be in readiness to march when called upon.
This was such a time as I had not seen before; and yet I may say,
with thankfulness to the Lord, that I believed this trial was intended for our good;
and I was favored with resignation to him.
The French army taking the fort they were besieging, destroyed it and went away:
the company of men first drafted, after some days march, had orders to return home;
and those on the second draft, were no more called upon on that occasion.

On the 4th day of the fourth month, in the year 1758,
orders came to some officers in Mount Holly, to prepare quarters a short time,
for about one hundred soldiers: an officer and two other men,
all inhabitants of our town, came to my house;
and the officer told me that he came to speak with me,
to provide lodging and entertainment for two soldiers,
there being six shillings a week per man allowed as pay for it.
The case being new and unexpected, I made no answer suddenly; but sat a time silent,
my mind being turned inward.

I was fully convinced,
that the proceedings in wars are inconsistent with the purity of the Christian religion;
and to be hired to entertain men, who were then under pay as soldiers,
was a difficulty with me.
I expected they had legal authority for what they did; and after a short time,
I said to the officer, if the men are sent here for entertainment,
I believe I shall not refuse to admit them into my house;
but the nature of the case is such, that I expect I cannot keep them on hire:
one of the men intimated,
that he thought I might do it consistently with my religious principles;
to which I made no reply, believing silence, at that time, best for me.
Though they spoke of two, there came only one, who tarried at my house about two weeks,
and behaved himself civilly, and when the officer came to pay me,
I told him I could not take pay for it,
having admitted him into my house in passive obedience to authority.

I was on horseback when he spoke to me; and as I turned from him, he said,
he was obliged to me: to which I said nothing; but thinking on the expression,
I grew uneasy; and afterwards being near where he lived,
I went and told him on what grounds I refused taking pay for keeping the soldier.

Near the beginning of the year 1758, I went one evening in company with a Friend,
to visit a sick person; and before our return, we were told of a woman living near, who,
of late, had been disconsolate several days, occasioned by a dream;
wherein death and the judgments of the Almighty after death,
were represented to her mind in a moving manner.

Her sadness on that account being worn off, the Friend with whom I was in company,
went to see her, and had some religious conversation with her and her husband:
with this visit they were somewhat affected; and the man,
with many tears expressed his satisfaction: and in a short time after,
the poor man being on the river in a storm of wind, he with one more was drowned.

In the eighth month of the year 1758,
having had drawings in my mind to be at the Quarterly Meeting in Chester county,
and at some meetings in the county of Philadelphia,
I went first to said Quarterly Meeting, which was large;
and several weighty matters came under consideration and debate;
and the Lord was pleased to qualify some of his servants with strength and firmness,
to bear the burden of the day.
Though I said but little, my mind was deeply exercised; and under a sense of God's love,
in anointing and fitting some young men for his work, I was comforted,
and my heart was tendered before him.
From hence I went to the Youths' meeting at Darby,
where my beloved friend and brother Benjamin Jones met me,
by an appointment before I left home, to join in the visit.
We were at Radnor, Merion, Richland, North Wales, Plymouth and Abington meetings;
and had cause to bow in reverence before the Lord our gracious God,
by whose help way was opened for us from day to day.
I was out about two weeks, and rode about two hundred miles.

The Monthly Meeting of Philadelphia having been
under a concern on account of some Friends,
who this summer, 1758, had bought negro slaves;
the said meeting moved it to their Quarterly Meeting,
to have the minute reconsidered in the Yearly Meeting,
which was made last on that subject.
The said Quarterly Meeting appointed a committee to consider it,
and report to their next; which committee having met once and adjourned,
and I going to Philadelphia to meet a committee of the Yearly Meeting,
was in town the evening on which the Quarterly Meeting's committee met the second time;
and finding an inclination to sit with them, was with some others admitted;
and Friends had a weighty conference on the subject.
Soon after their next Quarterly Meeting,
I heard that the case was coming to our Yearly Meeting;
which brought a weighty exercise upon me, and under a sense of my own infirmities,
and the great danger I felt of turning aside from perfect purity,
my mind was often drawn to retire alone, and put up my prayers to the Lord,
that he would be graciously pleased to strengthen me;
that setting aside all views of self-interest and the friendship of this world,
I might stand fully resigned to his holy will.

In this Yearly Meeting several weighty matters were considered; and toward the last,
that in relation to dealing with persons who purchase slaves.
During the several sittings of the said meeting,
my mind was frequently covered with inward prayer; and I could say with David,
"`that tears were my meat day and night.`"
The case of slave-keeping lay heavy upon me;
nor did I find any engagement to speak directly to any other matter before the meeting.
When this case was opened, several faithful Friends spoke weightily thereto,
with which I was comforted; and feeling a concern to cast in my mite,
I said in substance, as follows: "`In the difficulties attending us in this life,
nothing is more precious than the mind of Truth inwardly manifested;
and it is my earnest desire, that in this weighty matter,
we may be so truly humbled as to be favored with
a clear understanding of the mind of Truth, and follow it;
this would be of more advantage to the Society than any
medium not in the clearness of Divine wisdom.
The case is difficult to some who have slaves; but if such set aside all self-interest,
and come to be weaned from the desire of getting estates,
or even from holding them together, when Truth requires the contrary,
I believe way will open that they will know how to steer through those difficulties.`"
Many Friends appeared to be deeply bowed under the weight of the work;
and manifested much firmness in their love to the cause
of Truth and universal righteousness on the earth.
Though none openly justified the practice of slave-keeping in general,
yet some appeared concerned,
lest the meeting should go into such measures as might give uneasiness to many brethren;
alleging that if Friends patiently continued under the exercise,
the Lord in time to come, might open a way for the deliverance of these people.

Finding an engagement to speak, I said,
"`My mind is often led to consider the purity of the Divine Being,
and the justice of his judgments; and herein my soul is covered with awfulness.
I cannot omit to hint of some cases,
where people have not been treated with the purity of justice,
and the event has been lamentable.
Many slaves on this continent are oppressed,
and their cries have reached the ears of the Most High.

Such are the purity and certainty of his judgments,
that he cannot be partial in our favor.
In infinite love and goodness, he has opened our understandings from one time to another,
concerning our duty toward this people, and it is not a time for delay.
Should we now be sensible of what he requires of us,
and through a respect to the private interest of some persons,
or through a regard to some friendships which do not stand on an immutable foundation,
neglect to do our duty in firmness and constancy,
still waiting for some extraordinary means to bring about their deliverance,
it may be that God may answer us, in this matter, by terrible things in righteousness.`"
Many faithful brethren labored with great firmness; and the love of Truth,
in a good degree, prevailed.
Several Friends who had negroes, expressed their desire that a rule might be made,
to deal with such Friends as ofTenders who bought slaves in future.
To this it was answered, that the root of this evil would never be effectually struck at,
until a thorough search was made into the circumstances of such Friends who kept negroes,
with respect to the righteousness of their motives in keeping them,
that impartial justice might be administered throughout.
Several Friends expressed their desire,
that a visit might be made to such as kept slaves;
and many Friends said that they believed liberty was the negroes right; to which,
at length, no opposition was made publicly.
A minute was made on that subject, more full than any heretofore;
and the names of several Friends entered,
who were free to join in a visit to such who kept slaves.
