== Chapter VII

[.chapter-synopsis]
* His visit in company with Samuel Eastburn, to Long Island, Rhode Island, Boston, etc., in New England
* Remarks on the slave trade at Newport, and his exercise on that account; also on lotteries
* Some observations on the island of Nantucket.

Having for some time past felt a sympathy in my mind with Friends eastward,
I opened my concern in our Monthly Meeting; and obtaining a certificate,
set forward on the 17th day of the fourth month, in the year 1760, joining in company,
by a previous agreement, with my beloved friend Samuel Eastburn.
We had meetings at Woodbridge, Rahway and Plainfield;
and were at their Monthly Meeting of ministers and elders in Rahway.
We labored under some discouragement; but through the invisible power of Truth,
our visit was made reviving to the lowly minded, with whom I felt a near unity of spirit,
being much reduced in my mind.

We passed on and visited most of the meetings on Long Island.
It was my concern from day to day,
to say no more nor less than what the Spirit of Truth opened in me,
being jealous over myself,
lest I should speak anything to make my testimony look agreeable to that mind in people,
which is not in pure obedience to the cross of Christ.

The spring of the ministry was often low; and through the subjecting power of Truth,
we were kept low with it; and from place to place,
such whose hearts were truly concerned for the cause of Christ,
appeared to be comforted in our labors;
and though it was in general a time of abasement of the creature,
yet through His goodness, who is a helper of the poor,
we had some truly edifying seasons both in meetings and in families where we tarried;
and sometimes found strength to labor earnestly with the unfaithful,
especially with those whose station in families, or in the Society was such,
that their example had a powerful tendency to open the way for others
to go aside from the purity and soundness of the blessed Truth.
At Jericho, on Long Island, I wrote home as follows:`"

[.embedded-content-document.letter]
--

[.signed-section-context-open]
24th of the Fourth month, 1760.

[.salutation]
Dearly beloved wife,

We are favored with health; have been at sundry meetings in East Jersey,
and on this island: my mind has been much in an inward watchful frame since I left you,
greatly desiring that our proceedings may be singly in the will of our heavenly Father.

As the present appearance of things is not joyous,
I have been much shut up from outward cheerfulness, remembering that promise,
"`Then shall you delight yourself in the Lord.`"
As this, from day to day, has been revived in my memory,
I have considered that his internal presence on our minds,
is a delight of all others the most pure;
and that the honest-hearted not only delight in this, but in the effect of it upon them.
He who regards the helpless and distressed,
reveals his love to his children under affliction,
and they delight in beholding his benevolence,
and feeling Divine charity moving upon them.

Of this I may speak a little; for though, since I left you,
I have often found an engaging love and affection toward you and my daughter,
and friends about home, that going out at this time,
when sickness is so great amongst you, as a trial upon me;
yet I often remember there are many widows and fatherless, many who have poor tutors,
many who have evil examples before them, and many whose minds are in captivity;
for whose sake my heart is at times moved with compassion,
that I feel my mind resigned to leave you for a season,
to exercise that gift which the Lord has bestowed on me; which, though small,
compared with some, yet in this I rejoice,
that I feel love unfeigned toward my fellow-creatures.
I recommend you to the Almighty, who, I trust, cares for you;
and under a sense of his heavenly love, remain,

[.signed-section-closing]
Your loving husband,

[.signed-section-signature]
John Woolman

--

We crossed from the east end of Long Island to New London, about thirty miles,
in a large open boat; while we were out, the wind rising high,
the waves several times beat over us, and to me it appeared dangerous;
but my mind was at that time, turned to Him who made and governs the deep,
and my life was resigned to him: and as he was mercifully pleased to preserve us,
I had fresh occasion to consider every day as a day lent to me;
and felt a renewed engagement to devote my time and all I had to Him who gave it.

We had five meetings in Narraganset; and went from there to Newport on Rhode Island.
Our gracious Father preserved us in a humble dependence on him through deep exercises,
that were mortifying to the creaturely will.
In several families in the country where we lodged,
I felt an engagement on my mind to have a conference
with them in private concerning their slaves;
and through Divine aid, I was favored to give up thereto.

Though, in this concern,
I appear singular from many whose service in traveling I believe is greater than mine,
I do not think hard of them for omitting it;
nor do I repine at having so unpleasant a task assigned me,
but look with awfulness to Him,
who appoints to his servants their respective employments,
and is good to all who serve him sincerely.

We got to Newport in the evening, and on the next day visited two sick persons,
and had comfortable sittings with them;
and in the afternoon attended the burial of a Friend.

The next day we were at meetings at Newport, in the forenoon and afternoon;
where the spring of the ministry was opened,
and strength given to declare the word of life to the people.

The next day we went on our journey; but the great number of slaves in these parts,
and the continuance of that trade from there to Guinea, made a deep impression on me;
and my cries were often put up to my heavenly Father in secret,
that he would enable me to discharge my duty faithfully,
in such way as he might be pleased to point out to me.

We took Swansea, Freetown and Taunton, in our way to Boston; where also we had a meeting;
our exercise was deep, and the love of Truth prevailed, for which I bless the Lord.

We went eastward about eighty miles beyond Boston, taking meetings,
and were in a good degree preserved in a humble dependence on that arm which drew us out;
and though we had some hard labor with the disobedient,
laying things closely home to such as were stout against the Truth;
yet through the goodness of God,
we had at times to partake of heavenly comfort with them who were meek,
and were often favored to part with Friends in the nearness of true Gospel fellowship.

We returned to Boston, and had another comfortable opportunity with Friends there;
and from there rode back a day's journey eastward of Boston.
Our guide being a heavy man, and the weather hot, and ray companion and I considering it,
expressed our freedom to go on without him, to which he consented,
and we respectfully took our leave of him; we did this,
believing the journey would be hard to him and his horse.

We visited the meetings in those parts,
and were measurably baptized into a feeling of the state of the Society;
and in bowedness of spirit went to the Yearly Meeting at Newport;
where I understood that a large number of slaves
had been imported from Africa into that town,
and were then on sale by a member of our Society.
At this meeting we met with John Storer from England, Elizabeth Shipley, Ann Gaunt,
Hannah Foster, and Mercy Redman from our parts, all ministers of the Gospel,
of whose company I was glad.

At this time my appetite failed, and I grew outwardly weak,
and had a feeling of the condition of Habbakuk,
as thus expressed "`When I heard my belly trembled, my lips quivered,
I trembled in myself that I might rest in the day of trouble.`"
I had many cogitations, and was sorely distressed;
and was desirous that Friends might petition the legislature,
to use their endeavors to discourage the future importation of slaves;
for I saw that this trade was a great evil,
and tended to multiply troubles and bring distresses on the people in those parts,
for whose welfare my heart was deeply concerned.

But I perceived several difficulties in regard to petitioning;
and such was the exercise of my mind,
that I thought of endeavoring to get an opportunity to
speak a few words in the House of Assembly,
then sitting in town.

This exercise came upon me in the afternoon, on the second day of the Yearly Meeting,
and going to bed, I got no sleep till my mind was wholly resigned therein;
and in the morning I inquired of a Friend how long the
Assembly were likely to continue sitting;
who told me, they were expected to be prorogued that day or the next.

As I was desirous to attend the business of the meeting,
and perceived that the Assembly were likely to depart before the business was over;
after considerable exercise, humbly seeking to the Lord for instruction,
my mind settled to attend on the business of the meeting.

I had prepared a short essay of a petition to be presented to the legislature,
if way opened; and being informed that there were some appointed by that Yearly Meeting,
to speak with those in authority, in cases relating to the Society,
I opened my mind to several of them, and showed them the essay I had made;
and afterward opened the case in the meeting for business, in substance as follows:
"`I have been under a concern for some time,
on account of the great number of slaves who are imported into this colony.
I am aware that it is a tender point to speak to,
but apprehend I am not clear in the sight of heaven without speaking to it.
I have prepared an essay of a petition, if way open, to be presented to the legislature;
and what I have to propose to this meeting is,
that some Friends may be named to withdraw and look over it,
and report whether they believe it suitable to be read in the meeting;
if they should think well of reading it, it will remain for the meeting,
after hearing it,
to consider whether to take any further notice of it as a meeting or not.`"
After a short conference some Friends went out, and looking over it,
expressed their willingness to have it read; which being done,
many expressed their unity with the proposal; and some signified,
that to have the subjects of the petition enlarged upon,
and to be signed out of meeting by such who were free,
would be more suitable than to do it there.
Though I expected at first, that if it was done it would be in that way;
yet such was the exercise of my mind,
that to move it in the hearing of Friends when assembled, appeared to me a duty.
My heart yearned toward the inhabitants of these parts;
believing that by this trade there had been an increase of inquietude amongst them,
and a way made easy for the spreading of a spirit opposite to that meekness and humility,
which is a sure resting-place for the soul;
and that the continuance of this trade would not
only render their healing more difficult,
but increase their malady.

Having proceeded thus far, I felt easy to leave the essay amongst Friends,
for them to dispose of as they believed best.
And now an exercise revived on my mind in relation to lotteries,
which were common in those parts.

I had moved it in a former sitting of this meeting,
when arguments were used in favor of Friends being held excused,
who were only concerned in such lotteries as were agreeable to law.
On moving it again, it was opposed as before;
but the hearts of some solid Friends appeared to be
united to discourage the practice amongst their members;
and the matter was zealously handled by some on both sides.

In this debate it appeared very clear to me,
that the spirit of lotteries was a spirit of selfishness,
which tended to confusion and darkness of understanding;
and that pleading for it in our meetings, set apart for the Lord's work, was not right:
and in the heat of zeal, I once made reply to what an ancient Friend said,
and when I sat down, I saw that my words were not enough seasoned with charity;
and after this I spoke no more on the subject.

At length a minute was made;
a copy of which was agreed to be sent to their several Quarterly Meetings,
inciting Friends to labor to discourage the practice amongst all professing with us.

Some time after this minute was made,
I remaining uneasy with the manner of my speaking to the ancient Friend,
could not see my way clear to conceal my uneasiness,
but was concerned that I might say nothing to weaken the cause in which I had labored.

After some close exercise and hearty repentance that I
had not attended closely to the safe guide,
I stood up and reciting the passage,
acquainted Friends that though I dare not go from what I had said as to the matter,
yet I was uneasy with the manner of my speaking,
believing milder language would have been better.
As this was uttered in some degree of creaturely abasement,
it appeared to have a good savor amongst us, after a warm debate.

The Yearly Meeting being now over, there remained on my mind a secret,
though heavy exercise in regard to some leading active members about Newport,
being in the practice of slave-keeping.
This I mentioned to two ancient Friends who came out of the country,
and proposed to them, if way opened, to have some conversation with those Friends:
and thereupon, one of those country Friends and I,
consulted one of the most noted elders who had slaves; and he, in a respectful manner,
encouraged me to proceed to clear myself of what lay upon me.
I had had, near the beginning of the Yearly Meeting,
a private conference with this elder and his wife, concerning theirs;
so that the way seemed clear to me, to advise with him about the manner of proceeding.
I told him, I was free to have a conference with them all together in a private house;
or if he thought they would take it unkind to be asked to come together,
and to be spoken with in the hearing of each other,
I was free to spend some time among them, and visit them all in their own houses.
He expressed his liking to the first proposal,
not doubting their willingness to come together; and as I proposed a visit to ministers,
elders and overseers only; he named some other's, whom he desired might be present also.
As a careful messenger was needed to acquaint them in a proper manner,
he offered to go to all their houses to open the matter to them and did so.
About the eighth hour next morning, we met in the meeting-house chamber,
and the last mentioned country friend, also my companion and John Storer, with us; when,
after a short time of retirement,
I acquainted them with the steps I had taken in procuring that meeting,
opened the concern I was under, and we proceeded to a free conference upon the subject.
My exercise was heavy, and I was deeply bowed in spirit before the Lord,
who was pleased to favor with the seasoning virtue of Truth,
which wrought a tenderness amongst us;
and the subject was mutually handled in a calm and peaceable spirit.
At length feeling my mind released from the burden which I had been under,
I took my leave of them in a good degree of satisfaction;
and by the tenderness they manifested in regard to the practice,
and the concern several of them expressed in relation to the
manner of disposing of their negroes after their decease,
I believed that a good exercise was spreading amongst them;
and I am humbly thankful to God, who supported my mind,
and preserved me in a good degree of resignation through these trials.

You, who sometimes travels in the work of the ministry,
and are made very welcome by your friends, and see many tokens of their satisfaction,
in having you for their guest; it is good for you to dwell deep,
that you may feel and understand the spirits of people.
If we believe Truth points towards a conference on some subjects, in a private way,
it is needful for us to take heed that their kindness, their freedom and affability,
do not hinder us from the Lord's work.
I have seen, that in the midst of kindness and smooth conduct,
to speak close and home to them who entertain us,
on points that relate to their outward interest, is hard labor;
and sometimes when I have felt Truth lead toward it,
I have found myself disqualified by a superficial friendship.

As the sense thereof has abased me, and my cries have been to the Lord,
I have been humbled and made content to appear weak, or as a fool for his sake;
and thus a door has opened to enter upon it.
To attempt to do the Lord's work in our own way,
and to speak of that which is the burden of the word, in a way easy to the natural part,
does not reach the bottom of the disorder.
To see the failings of our friends, and think hard of them,
without opening that which we ought to open, and still carry a face of friendship,
this tends to undermine the foundation of true unity.

The office of a minister of Christ is weighty; and they who now go forth as watchmen,
had need to be steadily on their guard against the
snares of prosperity and an outside friendship.

After the Yearly Meeting we were at meetings at Newtown, Acushnet, Cushnet, Long Plain,
Rochester and Dartmouth.
From there we sailed for Nantucket, in company with Ann Gaunt and Mercy Redman,
and several other Friends: the wind being slack,
we only reached Tarpawling Cove the first day; where, going on shore,
we found room in a public house, and beds for a few of us,
the rest sleeping on the floor.
We went on board again about break of day; and though the wind was small,
we were favored to come within about four miles of Nantucket;
and about ten of us getting into our boat, we rowed to the harbor before dark;
whereupon a large boat going off, brought in the rest of the passengers about midnight.
The next day but one was their Yearly Meeting, which held four days;
the last of which was the Monthly Meeting for business.
We had a laborious time amongst them; our minds were closely exercised,
and I believe it was a time of great searching of heart: the longer I was on the island,
the more I became sensible that there was a
considerable number of valuable Friends there,
though an evil spirit tending to strife, had been at work amongst them.
I was cautious of making any visits, but as my mind was particularly drawn to them;
and in that way we had some sittings in Friends' houses,
where the heavenly wing was at times spread over us, to our mutual comfort.

My beloved companion had very acceptable service on this island.
When meeting was over, we all agreed to sail the next day,
if the weather was suitable and we well;
and being called up the latter part of the night, we went on board a vessel,
being in all about fifty; but the wind changing,
the seamen thought best to stay in the harbor till it altered; so we returned on shore.
Feeling clear as to any further visits, I spent my time in our chamber chiefly alone;
and after some hours, my heart being filled with the spirit of supplication,
my prayers and tears were poured out before my heavenly Father,
for his help and instruction in the manifold difficulties which attended me in life.

While I was waiting upon the Lord, there came a messenger from the women Friends,
who lodged at another house, desiring to confer with us about appointing a meeting,
which to me appeared weighty, as we had been at so many before;
but after a short conference, and advising with some elderly Friends,
a meeting was appointed, in which the Friend who first moved it,
and who had been much shut up before, was largely opened in the love of the Gospel.
The next morning about break of day, going again on board the vessel,
we reached Falmouth on the main before night; where our horses being brought,
we proceeded toward Sandwich Quarterly Meeting.Being two days in going to Nantucket,
and having been there once before, I observed many shoals in their bay,
which make sailing more dangerous, especially in stormy nights; also, that a great shoal,
which encloses their harbor, prevents their going in with sloops,
except when the tide is up.
Waiting without this shoal for the rising of the tide, is sometimes hazardous in storms:
waiting within, they sometimes miss a fair wind.
I took notice that on this small island was a great number of inhabitants,
and the soil not very fertile; the timber so gone, that for vessels, fences and firewood,
they depend chiefly on the buying from the main; to answer the cost whereof,
with most of their other expenses, they depend principally upon the whale fishery.

I considered that as towns grew larger,
and lands near navigable waters were more cleared,
it would require more labor to get timber and wood.
I understood that the whales being much hunted, and sometimes wounded and not killed,
grew more shy and difficult to come at: I considered that the formation of the earth,
the seas, the islands, bays and rivers, the motion of the winds and great waters,
which cause bars and shoals in particular places,
were all the works of Him who is perfect wisdom and goodness;
and as people attend to his heavenly instruction, and put their trust in him,
he provides for them in all parts, where he gives them a being.
In this visit to these people,
I felt a strong desire for their firm establishment on the sure foundation;
and besides what was said more publicly, I was concerned to speak with the women Friends,
in their Monthly Meeting of business, many being present;
and in the fresh spring of pure love, to open before them the advantage,
both inward and outward, of attending singly to the pure guidance of the Holy Spirit,
and therein to educate their children in true humility,
and the disuse of all superfluities,
reminding them of the difficulties their husbands and
sons were frequently exposed to at sea;
and that the more plain and simple their way of living was,
the less need there would be of running great hazards to support them in it.
I encouraged the young women in their neat decent way
of attending themselves on the affairs of the house;
showing, as the way opened, that where people were truly humble,
used themselves to business, and were content with a plain way of life,
it had ever been attended with more true peace and calmness of mind,
than they have had who, aspiring to greatness and outward show,
have grasped hard for an income to support themselves in it.

As I observed they had few or no slaves amongst them,
I had to encourage them to be content without them;
making mention of the numerous troubles and vexations,
which frequently attend the minds of people, who depend on slaves to do their labor.

We attended the Quarterly Meeting at Sandwich,
in company with Ann Gaunt and Mercy Redman, which was preceded by a Monthly Meeting,
and in the whole held three days.
We were, in various ways exercised amongst them in Gospel love,
according to the several gifts bestowed on us; and were at times,
overshadowed with the virtue of Truth,
to the comfort of the sincere and the stirring up of the negligent.
Here we parted with Ann and Mercy, and went to Rhode Island,
taking one meeting in our way, which was a satisfactory time;
and reaching Newport the evening before their Quarterly Meeting, we attended it;
and after that had a meeting with our young people,
separated from those of other societies.
We went through much labor in this town; and now in taking leave of it,
though I felt close inward exercise to the last, I found peace;
and was in some degree comforted in a belief, that a good number remain in that place,
who retain a sense of Truth;
and that there are some young people attentive to the voice of the heavenly Shepherd.
The last meeting in which Friends from the several parts of the quarter came together,
was select; and through the renewed manifestation of the Father's love,
the hearts of the sincere were united together.

That poverty of spirit and inward weakness,
with which I was much tried during the fore part of this journey,
has of late appeared to me to be a dispensation of kindness.
Appointing meetings never appeared more weighty to me.
I was led into a deep search,
whether in all things my mind was resigned to the will of God;
often querying with myself, what should be the cause of such inward poverty;
and greatly desired that no secret reserve in my heart
might hinder my access to the Divine fountain.
In these humbling times I was made watchful,
and excited to attend to the secret movings of the heavenly
principle in my mind which prepared the way to some duties,
that in more easy and prosperous times as to the outward,
I believe I should have been in danger of omitting.

From Newport we went to Greenwich, Shanticut and Warwick;
and were helped to labor amongst Friends in the love of our gracious Redeemer; and then,
accompanied by our friend John Casey from Newport, we rode through Connecticut to Oblong,
visited the meetings of Friends in those parts,
and from there proceeded to the Quarterly Meeting at Ryewoods;
and through the gracious extendings of Divine help,
had some seasoning opportunities in those places.
We visited Friends at New York and Flushing; and from there to Rahway;
and here our roads parting,
I took leave of my beloved companion and true yoke-mate Samuel Eastburn;
and reached home on the 10th day of the eighth month, 1760, where I found my family well:
and for the favors and protection of the Lord, both inward and outward,
extended to me in this journey, my heart is humbled in grateful acknowledgements;
and I find renewed desires to dwell and walk in resignedness before him.
