== Chapter X.

[.chapter-synopsis]
* His exercise for the good of the people in the West Indies
* Communicates to Friends his resignation to visit some of these islands
* The state of his mind, and the close considerations he has led into while under this exercise
* Preparations to embark, and considerations on the trade to these islands; released from the concern he had been under
* Religious engagements after his return home
* His sickness, in which he was brought to a very low state; and the prospects he then had.

The 12th day of the third month, 1770, having for some years past,
dieted myself on account of a lump gathering on my nose, I grew weak in body,
and not of ability to travel by land as heretofore.
I was at times favored to look with awfulness toward the Lord,
before whom are all my ways, who alone has the power of life and death;
and to feel thankfulness raised in me, for this his fatherly chastisement,
believing if I was truly humbled under it, all would work for good.
While I was under this bodily weakness,
my mind being at times exercised for my fellow-creatures in the West Indies,
I grew jealous over myself,
lest the disagreeableness of the prospect should
hinder me from obediently attending thereto:
for though I knew not that the Lord required me to go there,
yet I believed that resignation was now called for in that respect.
Feeling a danger of not being wholly devoted to him,
I was frequently engaged to watch unto prayer, that I might be preserved;
and upwards of a year having passed, as I walked one day in a solitary wood,
my mind being covered with awfulness, cries were raised in me to my merciful Father,
that he would graciously keep me in faithfulness;
and it then settled on my mind as a duty,
to open my condition to Friends at our Monthly Meeting; which I did soon after,
as follows: "`An exercise has attended me for some time past,
and of late been more weighty upon me, under which,
I believe it is required of me to be resigned to
go on a visit to some part of the West Indies.`"

In the Quarterly and General Spring Meeting,
I found no clearness to express anything further,
than that I believed resignation herein was required of me;
and having obtained certificates from all the said meetings,
I felt like a sojourner at my outward habitation, kept free from worldly encumbrances,
and was often bowed in spirit before the Lord, with inward breathings to him,
that I might be rightly directed.
I may here note, that what I have before related of my being when young,
joined as an executor with another Friend, in executing a will,
our having sold a negro lad till he might attain the age of thirty years,
was now the occasion of great sorrow to me.
After having settled matters relating to this youth, I provided seastores, a bed,
and other things for the voyage;
and hearing of a vessel likely to sail from Philadelphia for Barbados,
I spoke with one of the owners at Burlington,
and soon after went to Philadelphia on purpose to speak with him again.
He told me there was a Friend in town who was part owner of the said vessel;
but I felt no inclination to speak with him, but returned home.
A while after, I took leave of my family, and going to Philadelphia,
had some weighty conversation with the first-mentioned owner, and showed him a writing,
as follows: "`On the 25th day of the eleventh month, 1769.
As an exercise, with respect to a visit to Barbados, has been weighty on my mind,
I may express some of the trials which have attended me, under which,
I have at times rejoiced that I have felt my own self-will subjected.

"`Some years ago, I retailed rum, sugar and molasses, the fruits of the labor of slaves;
but then had not much concern about them,
save only that the rum might be used in moderation;
nor was this concern so weightily attended to, as I now believe it ought to have been.
But of late years being further informed respecting the
oppressions too generally exercised in these islands,
and thinking often on the degrees there are in the connexions
of interest and fellowship with the works of darkness,
Ephe. 5:11.;
and feeling an increasing concern to be wholly
given up to the leadings of the Holy Spirit,
it has appeared to me, that the small gain I got by this branch of trade,
should be applied in promoting righteousness on the earth;
and was the first motion toward a visit to Barbados.
I believed the outward substance I possess should be applied in paying my passage,
if I go, and providing things in a lowly way for my subsistence;
but when the time drew near, in which I believed it required of me to be in readiness,
a difficulty arose, which has been a continued trial for some months past; under which,
I have with abasement of mind, from day to day, sought the Lord for instruction;
and often had a feeling of the condition of one formerly, who bewailed himself,
for that the Lord hid his face from him.
During these exercises,
my heart has been often contrite and I have had a tender
feeling of the temptations of my fellow-creatures,
laboring under those expensive customs distinguishable
from the simplicity that there is in Christ, 2 Cor. 2:3.
, and sometimes in the renewings of Gospel love,
I have been helped to minister to others.

"`That which has so closely engaged my mind in seeking to the Lord for instruction is,
whether after so full information of the oppression which the
slaves who raise the West India produce lie under,
as I had in reading a caution and warning to Great Britain and her colonies,
written by Anthony Benezet,
it is right for me to take a passage in a vessel employed in the West India trade.

"`To trade freely with oppressors,
and without laboring to dissuade from their unkind treatment,
seek for gain by such traffic, tends, I believe,
to make them more easy respecting their conduct, than they would be,
if the cause of universal righteousness was humbly and firmly attended to,
by those with whom they have commerce.
That complaint of the Lord by his prophet,
"`They have strengthened the hands of the wicked,`" has very often revived in my mind;
and I may here add some circumstances preceding any prospect of a visit there.
The case of David has often been before me of late years:
he longed for some water in a well beyond an army of Philistines, at war with Israel;
and some of his men to please him, ventured their lives in passing through this army,
and brought that water,
"`It does not appear that the Israelites were then scarce of water, but rather,
that David gave way to delicacy of taste;
but having thought on the danger these men were exposed to,
he considered this water as their blood,
and his heart smote him that he could not drink it, but poured it out to the Lord.

The oppression of the slaves which I have seen in several journeys southward,
on this continent,
and the report of their treatment in the West Indies has deeply affected me;
and a care to live in the spirit of peace,
and minister just cause of offense to none of my fellow-creatures, has,
from time to time, livingly revived on my mind; and under this exercise,
I have for some years past, declined to gratify my palate with those sugars.

"`I do not censure my brethren in these things; but believe the Father of mercies,
to whom all mankind by creation are equally related,
has heard the groans of these oppressed people;
and is preparing soon to have a tender feeling of their condition: and the trading in,
or frequent use of any produce known to be raised by the
labors of those who are under such lamentable oppression,
has appeared to be a subject which may yet require the more
serious consideration of the humble followers of Christ,
the prince of peace.

"`After long and mournful exercise,
I am now free to mention how things have opened in my mind,
with desires that if it may please the Lord,
further to open his will to any of his children in this matter,
they may faithfully follow him in such further manifestation.

"`The number of those who decline the use of the West India produce,
on account of the hard usage of the slaves who raise it, appears small,
even amongst people truly pious; and the labors in Christian love on that subject,
of those who do, are not very extensive.

"`Were the trade from this continent to the West Indies to be quite stopped at once,
I believe many there would suffer for lack of bread.

"`Did we on this continent, and the inhabitants of the West Indies,
generally dwell in pure righteousness, I believe a small trade between us might be right.
Under these considerations,
when the thoughts of wholly declining the use of trading vessels,
and of trying to hire a vessel to go in ballast have arisen in my mind,
I have believed that the labors in Gospel love,
yet bestowed in the cause of universal righteousness, are not arrived to that height.

"`If the trade to the West Indies was no more than was consistent with pure wisdom,
I believe the passage money would, for good reasons, be higher than it is now;
and under deep exercise of mind,
I have believed that I should not take the advantage of
this great trade and small passage money;
but as a testimony in favor of less trading,
should pay more than is common for others to pay, if I go at this time.`"
The first mentioned owner having read the paper,
expressed a willingness to go with me to the other owner; and we going,
the other owner read over the paper, and we had some solid conversation; under which,
I felt my soul bowed in reverence before the Most High.
At length one of them asked me, if I would go and see the vessel;
but I had not clearness in my mind to go; but went to my lodgings and retired in private.

I was now under great exercise of mind; and my tears were poured out before the Lord,
with inward cries that he would graciously help me under these trials.
In this case I believe my mind was resigned, but did not feel clearness to proceed;
and my own weakness and the necessity of Divine instruction, were impressed upon me.

I was for a time as one who knew not what to do, and was tossed as in a tempest;
under which affliction,
the doctrine of Christ "`Take no thought for the morrow,`" arose livingly before me.
I remembered that it was some days before they expected the vessel to sail,
and was favored to get into a good degree of stillness;
and having been nearly two days in town,
I believed my obedience to my heavenly Father consisted in returning homeward.

I went over amongst Friends on the Jersey shore,
and tarried till the morning on which they had appointed to sail;
and as I lay in bed the latter part of that night, my mind was comforted;
and I felt what I esteemed a fresh confirmation,
that it was the Lord`'s will I should pass through some further exercises near home.

So I went home, and still felt like a sojourner with my family,
and in the fresh spring of pure love, had some labors in a private way amongst Friends,
on a subject relating to Truth`'s testimony;
under which I had frequently been exercised in heart for some years.
I remember, as I walked on the road under this exercise,
that passage in Ezekiel came fresh before me, "`Whithersoever their faces were turned,
there they went;`" and I was graciously helped to discharge my duty,
in the fear and dread of the Almighty.

After a few weeks it pleased the Lord to visit me with a pleurisy;
and after I had lain a few days, and felt the disorder very grievous,
I was thoughtful how it might end.

I had of late, through various exercises,
been much weaned from the pleasant things of this life;
and I now thought if it was the Lord`'s will to put an end to my labors,
and graciously receive me into the arms of his mercy, death would be acceptable to me;
but if it was his will further to refine me under affliction, and make me in any degree,
useful in his church, I desired not to die.
I may with thankfulness say, that in this case I felt resignedness wrought in me,
and had no inclination to send for a doctor; believing if it was the Lord`'s will,
through outward means, to raise me up,
some sympathizing Friends would be sent to minister to me; who were accordingly.
But though I was carefully attended, yet the disorder was at times so heavy,
that I had no thoughts of recovery.

One night in particular, my bodily distress was great; my feet grew cold,
and cold increased up my legs toward my body,
and at that time I had no inclination to ask my nurse to apply anything warm to my feet,
expecting my end was near.
After I had lain nearly ten hours in this condition, I closed my eyes,
thinking whether I might now be delivered out of the body;
but in these awful moments my mind was livingly opened to behold the church,
and strong engagements were begotten in me,
for the everlasting well-being of my fellow-creatures;
and I felt in the spring of pure love, that I might remain some time longer in the body,
in filling up according to my measure, that which remains of the afflictions of Christ,
and in laboring for the good of the church.
After this I requested my nurse to apply warmth to my feet, and I revived.

The next night feeling a weighty exercise of spirit,
and having a solid Friend sitting up with me, I requested him to write what I said;
which he did, as follows: "`4th day of the first month, 1770,
about five o`'clock in the morning.--I have seen in the light of the Lord,
that the day is approaching, when the man that is the most wise in human policy,
shall be the greatest fool; and the arm that is mighty to support injustice,
shall be broken to pieces.
The enemies of righteousness shall make a terrible rattle,
and shall mightily torment one another;
for He that is omnipotent is rising up to judgment,
and will plead the cause of the oppressed; and he commanded me to open the vision.`"
Near a week after this, feeling my mind livingly opened, I sent for a neighbor, who,
at my request, wrote as follows: "`The place of prayer is a precious habitation;
for I now saw that the prayers of the saints were precious incense:
and a trumpet was given me, that I might sound forth this language,
that the children might hear it, and be invited to gather to this precious habitation,
where the prayers of the saints, as precious incense,
arise up before the throne of God and the Lamb--I saw this habitation to be safe;
to be inwardly quiet, when there were great stirrings and commotions in the world.

"`Prayer at this day, in pure resignation, is a precious place: the trumpet is sounded,
the call goes forth to the church, that she gather to the place of pure inward prayer;
and her habitation is safe.`"
