== Chapter XII.

[.chapter-synopsis]
* Attends the Yearly Meeting in London
* Proceeds towards Yorkshire, visiting several Quarterly and other meetings in the counties of Hertford, Warwick, Oxford, Nottingham, York, and Westmoreland; and from there again into Yorkshire, and to the city of York
* Some instructive thoughts and observations
* Letters on several subjects
* Hears of the decease of William Hunt; some account of him
* Sickness at York; and death there.

On the 8th day of the sixth month, 1772, we landed at London;
and I went straightway to the Yearly Meeting of ministers and elders,
which had been gathered, I suppose, about half an hour.

In this meeting, my mind was humbly contrite: in the afternoon,
the meeting of business opened, which by adjournments held nearly a week.
In these meetings,
I often felt a living concern for the establishment of Friends in the pure life of Truth;
and my heart was enlarged in the meeting of ministers, meeting of business,
and in several meetings for public worship;
and I felt my mind united in true love to the faithful
laborers now gathered at this Yearly Meeting.

On the 15th day of the month I left London, and went to a Quarterly Meeting at Hertford.

The 1st day of the seventh month.
I have been at Quarterly Meetings at Sherrington, Northampton, Banbury and Shipton,
and had sundry meetings between.
My mind has been bowed under a sense of Divine goodness manifested amongst us;
my heart being often enlarged in true love, both amongst ministers and elders,
and in public meetings; and through the Lord's goodness,
I believe it has been a fresh visitation to many, in particular to the youth.

The 17th day of the month.
Was this day at Birmingham: have been at meetings at Coventry, Warwick in Oxfordshire,
and sundry other places; I have felt the humbling hand of the Lord upon me,
and through his tender mercies find peace in the labors I have gone through.

The 26th day of the month.
I have continued traveling northward visiting meetings: was this day at Nottingham;
which, in the forenoon especially, was through Divine love a heart-tendering season:
next day had a meeting with Friends' children and some Friends; this,
through the strengthening arm of the Lord, was a time to be thankfully remembered.

The 2nd day of the eighth month, and first of the week, was this day at Sheffield,
a large inland town: I have been at sundry meetings last week,
and feel inward thankfulness for that Divine support,
which has been graciously extended to me.

The 9th day of the month, and first of the week, was at Rushworth:
have lately passed through some painful labor; but I have been comforted,
under a sense of that Divine visitation, which I feel extended toward many young people.

The 16th day of the month, and first of the week, was at Settle:
it has of late been a time of inward poverty; under which,
my mind has been preserved in a watchful tender state,
feeling for the mind of the holy Leader,
and find peace in the labors I have passed through.

On inquiry, in many places, I find the price of rye about five shillings,
and wheat about eight shillings, per bushel;
oatmeal twelve shillings for a hundred and twenty pounds;
mutton from three-pence to five-pence per pound; bacon, from seven-pence to ninepence;
cheese, from four-pence to sixpence; butter, from eight-pence to ten-pence; house rent,
for a poor man, from twenty-five shillings to forty shillings per year,
to be paid weekly; wood for fire, very scarce and dear; coal, in some places,
two shillings and sixpence per hundred weight; but near the pits, not a quarter so much.
O, may the wealthy consider the poor!
The wages of laboring men in several counties toward London,
are ten-pence per day in common business, the employer finds smallbeer,
and the laborer finds his own food; but in harvest and hay time,
wages are about one shilling per day, and the laborer has all his diet.
In some parts of the north of England, poor laboring men have their food where they work;
and appear, in common, to do rather better than nearer London.
Industrious women, who spin in the factories, get some four-pence, some five-pence,
and so on to six, seven, eight, nine or ten-pence per day,
and find their own house-room and diet.
Great numbers of poor people live chiefly on
bread and water in the southern parts of England,
and some in the northern parts; and there are many poor children not taught even to read.

May those who have plenty, lay these things to heart!
Stage-coaches frequently go upwards of a hundred miles in twenty-four hours;
and I have heard Friends say, in several places,
that it is common for horses to be killed with hard driving,
and many others are driven until they grow blind.

Post-boys pursue their business, each one to his stage, all night through the winter:
some boys who ride long stages, suffer greatly during winter nights;
and at several places I have heard of their being frozen to death.
So great is the hurry in the spirit of this world,
that in aiming to do business quick and to gain wealth,
the creation at this day does loudly groan!
As my journey has been without a horse,
I have had several offers of being assisted on my way in stage-coaches;
but have not been in them; nor have I had freedom to send letters by these posts,
in the present way of their riding; the stages being so fixed,
and one boy dependent on another as to time,
that they commonly go upward of one hundred miles in twenty-four hours;
and in the cold long winter nights, the poor boys suffer much.

I heard in America of the way of these posts;
and cautioned Friends in the General Meeting of ministers and elders at Philadelphia,
and in the Yearly Meeting of ministers and elders at London,
not to send letters to me on any common occasion by post.
And though on this account,
I may be likely to hear more seldom from my family left behind,
yet for righteousness sake, I am through Divine favor made content.

I have felt great distress of mind, since I came on this island,
on account of the members of our Society being mixed with the world,
in various sorts of business and traffic, carried on in impure channels.
Great is the trade to Africa for slaves! and in loading these ships,
abundance of people are employed in the factories; amongst whom are many of our Society.
Friends in early times refused on a religious principle,
to make or trade in superfluities, of which we have many large testimonies on record:
but for lack of faithfulness some gave way,
even some whose examples were of note in our Society;
and from there others took more liberty.
Members of our Society worked in superfluities, and bought and sold them;
and thus dimness of sight came over many.
At length, Friends got into the use of some superfluities in dress,
and in the furniture of their houses; and this has spread from less to more,
until superfluity of some kinds is common amongst us.

In this declining state, many look at the example one of another,
and too much neglect the pure feeling of Truth.
Of late years, a deep exercise has attended my mind, that Friends may dig deep,
may carefully cast forth the loose matter, and get down to the Rock, the sure foundation,
and there hearken to that Divine voice which gives a clear and certain sound.
I have felt in that which does not deceive, that if Friends who have known the Truth,
keep in that tenderness of heart, where all views of outward gain are given up,
and their trust is only on the Lord,
he will graciously lead some to be patterns of deep self-
denial in things relating to trade and handicraft labor;
and that some who have plenty of the treasures of this world,
will set an example of a plain frugal life, and pay wages to such whom they may hire,
more liberally than is now customary in some places.

The 23d day of the month; was this day at Preston-Patrick, and had a comfortable meeting.

I have several times been entertained at the houses of Friends,
who had sundry things about them which had the appearance of outward greatness;
and as I have kept inward, way has opened for conversation with such in private,
in which Divine goodness has favored us together with heart-tendering times.

The 26th day of the month.
Being now at George Crosfield's, in the county of Westmoreland,
I feel a concern to commit to writing, that which to me has been a case uncommon.

In a time of sickness with the pleurisy, a little upward of two years and a half ago,
I was brought so near the gates of death, that I forgot my name:
being then desirous to know who I was, I saw a mass of matter of a dull gloomy color,
between the south and the east; and was informed,
that this mass was human beings in as great misery as they could be, and live;
and that I was mixed in with them,
and that henceforth I might not consider myself as a distinct or separate being.
In this state I remained several hours.
I then heard a soft melodious voice, more pure and harmonious than any I had heard before.
I believed it was the voice of an angel, who spake to the other angels,
and the words were these, John Woolman is dead.
I soon remembered that I once was John Woolman;
and being assured that I was alive in the body,
I greatly wondered what that heavenly voice could mean.

I believed beyond doubting that it was the voice of a holy angel;
but as yet it was a mystery to me.
I was then carried in spirit to the mines,
where poor oppressed people were digging rich treasures for those called Christians;
and I heard them blaspheme the name of Christ, at which I was grieved;
for his name to me was precious.
Then I was informed, that these heathen were told,
that those who oppressed them were the followers of Christ;
and they said amongst themselves.
If Christ directed them to use us in this sort, then Christ is a cruel tyrant.

All this time the song of the angel remained a mystery; and in the morning,
my dear wife and some others coming to my bed-side, I asked them if they knew who I was;
and they telling me I was John Woolman, thought I was light-headed:
for I told them not what the angel said, nor was I disposed to talk much to anyone;
but was very desirous to get so deep, that I might understand this mystery.

My tongue was often so dry,
that I could not speak till I had moved it about and gathered some moisture,
and as I lay still for a time,
at length I felt Divine power prepare my mouth that I could speak; and then I said,
"`I am crucified with Christ, nevertheless I live; yet not I, but Christ lives in me:
and the lite I now live in the flesh, I live by the faith of the Son of God,
who loved me, and gave himself for me.`"
Then the mystery was opened;
and I perceived there was joy in heaven over a sinner who had repented;
and that that language (John Woolman is dead)
meant no more than the death of my own will.

Soon after this I coughed, and raised much bloody matter;
which I had not done during this vision:
and now my natural understanding returned as before.
Here I saw, that people getting silver vessels to set off their tables at entertainments,
was often stained with worldly glory; and that in the present state of things,
I should take heed how I fed myself out of silver vessels.

Soon after my recovery, going to our Monthly Meeting,
I dined at a Friend's house where drink was brought in silver vessels,
and not in any other; and needing some drink, I told him my case with weeping;
and he ordered some drink for me in another vessel.

The like I afterwards went through in several Friends' houses in America,
and have also in England, since I came here: and have cause, with humble reverence,
to acknowledge the loving-kindness of my heavenly Father,
who has preserved me in such a tender frame of mind, that none, I believe,
have ever been offended at what I have said on that occasion.

After this sickness, I spake not in public meetings for worship for nearly one year;
but my mind was very often in company with the oppressed slaves, as I sat in meetings:
and though under this dispensation, I was shut up from speaking,
yet the spring of the Gospel ministry was many times livingly opened in me;
and the Divine gift operated by abundance of weeping,
in feeling the oppression of this people.
It being long since I passed through this dispensation,
and the matter remaining fresh and livingly in my mind,
I believe it safest for me to commit it to writing.

The 30th day of the month.
This morning I wrote a letter, in substance as follows;

[.embedded-content-document.letter]
--

[.salutation]
Beloved friend,

My mind is often affected as I pass along,
under a sense of the state of many poor people,
who sit under that sort of ministry which requires much outward labor to support it;
and the loving-kindness of our heavenly Father,
in opening a pure Gospel ministry in this nation,
has often raised thankfulness in my heart to him.
I often remember the conflicts of the faithful under persecution,
and now look at the free exercise of the pure gift, uninterrupted by outward laws,
as a trust committed to us, which requires our deepest gratitude,
and most careful attention.
I feel a tender concern, that the work of reformation,
so prosperously carried on in this land within a few ages past,
may go forward and spread amongst the nations; and may not go backward,
through dust gathering on our garments,
who have been called to a work so great and so precious.

Last evening I had a little opportunity at your house
with some of your family in your absence,
in which I rejoiced; and feeling a sweetness on my mind toward you,
I now endeavor to open a little of the feeling I had there.

I have heard that in these parts, you had, at certain seasons meetings of conference,
in relation to Friends living up to our principles,
in which several meetings unite in one; with which I feel unity.
I have in some measure, felt Truth lead that way amongst Friends in America;
and have found, my dear friend, that in these labors,
all superfluities in our own living are against us.
I feel that pure love toward you, in which there is freedom.

I look at that precious gift bestowed on you, with awfulness before Him who gave it;
and feel a care, that we may be so separated to the Gospel of Christ,
that those things which proceed from the spirit of this world,
may have no place amongst us.

[.signed-section-closing]
Your friend,

[.signed-section-signature]
John Woolman.

--

I rested a few days, in body and mind, with our friend Jane Crosfleld,
who was once in America: was on the sixth day of the week, at Kendal in Westmoreland;
and at Grayrig meeting the 30th day of the month, and first of the week.

I have known poverty of late, and been graciously supported to keep in the patience;
and am thankful,
under a sense of the goodness of the Lord toward those that are of a contrite spirit.

The 6th day of the ninth month and first of the week; was this day at Counterside,
a large meeting-house and very full: and through the opening of pure love,
it was a strengthening time to me, and I believe to many more.

The 13th day of the month.
Was this day at Richmond, a small meeting; but the town's people coming in,
the house was crowded: it was a time of heavy labor;
and I believe was a profitable meeting.

At this place I heard that my kinsman William Hunt from North Carolina,
who was on a religious visit to Friends in England,
departed this life on the 9th day of the ninth month instant, of the small-pox,
at Newcastle.
He appeared in the ministry when a youth; and his labors therein were of good savor.
He travelled much in that work in America.
I once heard him say in public testimony, that his concern was, in that visit,
to be devoted to the service of Christ so fully,
that he might not spend one minute in pleasing himself; which words,
joined with his example, were a means of stirring up the pure mind in me.

Having of late travelled often in wet weather,
through narrow streets in towns and villages, where there were dirtiness under foot,
and the scent arising from that filth,
which more or less infects the air of all thickly settled towns; and being but weakly,
I have felt distress both in body and mind, with that which is impure.

In these journeys I have been where much cloth has been dyed;
and sundry times walked over ground, where much of the dye stuffs has drained away.
I have felt a longing in my mind, that people might come into cleanness of spirit,
cleanness of person, and cleanness about their houses and garments.

Some who are great, carry delicacy to a great height themselves,
and yet real cleanliness is not generally promoted.
Dyes being invented partly to please the eye, and partly to hide dirt,
I have felt in this weak state,
traveling in dirtiness and affected with unwholesome scents,
a strong desire that the practice of dyeing
cloth to hide dirt may be more fully considered.

To hide dirt in our garments, appears opposite to real cleanliness.
To wash garments and keep them sweet, appears cleanly.
Through giving way to hiding dirt in our garments,
a spirit which would cover that which is disagreeable, is strengthened.
Real cleanness becomes a holy people:
but hiding that which is not clean by coloring our garments,
appears contrary to the sweetness of sincerity.

Through some sorts of dyes, cloth is less useful; and if the value of dye-stuffs,
the expense of dyeing, and the damage done to cloth were all added together,
and that expense applied to keep all sweet and clean,
how much more cleanly would people be.

On this visit to England I have felt some instructions sealed on my mind,
which I am concerned to leave in writing,
for the use of such who are called to the station of a minister of Christ.

Christ being the Prince of peace, and we being no more than ministers,
I find it necessary for us, not only to feel a concern in our first going forth,
but to experience the renewing thereof, in the appointment of meetings.

I felt a concern in America, to prepare for this voyage;
and being through the mercy of God brought safely here,
my heart was like a vessel that needed vent, and for several weeks at first,
when my mouth was opened in meetings,
it often felt like the raising of a gate in a water course,
where a weight of water lay upon it;
and in these labors there appeared a fresh visitation to many, especially the youth;
but sometimes after this, I felt empty and poor,
and yet felt a necessity to appoint meetings.

In this state I was exercised to abide in the pure life of Truth,
and in all my labors to watch diligently against the motions of self in my own mind.
I have frequently felt a necessity to stand up, when the spring of the ministry was low,
and to speak from the necessity, in that which subjects the will of the creature;
and herein I was united with the suffering seed,
and found inward sweetness in these mortifying labors.

As I have been preserved in a watchful attention
to the Divine Leader under these dispensations,
enlargement at times has followed,
and the power of Truth has risen higher in some meetings,
than I ever knew it before through me.

Thus I have been more and more instructed as to the necessity of depending,
not upon a concern which I felt in America, to come on a visit to England;
but upon the fresh instructions of Christ the Prince of peace, from day to day.

Now of late, I felt a stop in the appointment of meetings, not wholly but in part;
and I do not feel liberty to appoint them so
quickly one after another as I have heretofore.

The work of the ministry being a work of Divine love,
I feel that the openings thereof are to be waited for in all our appointments.

Oh how deep is Divine wisdom!
Christ puts forth his ministers, and goes before them;
and oh how great is the danger of departing from
the pure feeling of that which leads safely!
Christ knows the state of the people, and in the pure feeling of the Gospel ministry,
their states are opened to his servants.

Christ knows when the fruit-bearing branches themselves have need of purging.
Oh that these lessons may be remembered by me! and that all who appoint meetings,
may proceed in the pure feeling of duty.

I have sometimes felt a necessity to stand up,
but that spirit which is of the world has so much prevailed in many,
and the pure life of Truth has been so pressed down, that I have gone forward,
not as one traveling in a road cast up and well prepared,
but as a man walking through a miry place, in which are stones here and there,
safe to step on; but so situated that one step being taken,
time is necessary to see where to step next, I find that in the pure obedience,
the mind learns contentment in appearing weak and
foolish to that wisdom which is of the world;
and in these lowly labors, they who stand in a low place,
rightly exercised under the cross, will find nourishment.

The gift is pure, and while the eye is single in attending thereto,
the understanding is preserved clear; self is kept out;
and we rejoice in filling up that which remains of the afflictions of Christ,
for his body's sake, which is the church.

The natural man loves eloquence, and many love to hear eloquent orations;
and if there is not a careful attention to the gift,
men who have once labored in the pure Gospel ministry, growing weary of suffering,
and ashamed of appearing weak, may kindle a fire,
compass themselves about with sparks and walk in the light,
not of Christ who is under suffering, but of that fire,
which they going from the gift have kindled.
And that in hearers which is gone from the meek suffering state into the worldly wisdom,
may be warmed with this fire, and speak highly of these labors.
That which is of God gathers to God; and that which is of the world is owned by the world.
In this journey a labor has attended my mind,
that the ministers amongst us may be preserved in the meek, feeling life of Truth,
where we may have no desire, but to follow Christ and be with him;
that when he is under suffering we may suffer with him;
and never desire to rise up in dominion,
but as he by the virtue of his own spirit may raise us.

A few days after writing these considerations,
our dear friend in the course of his religious visit, came to the city of York,
and attended most of the sittings of the Quarterly Meeting there; but before it was over,
was taken ill of the small-pox.
Our friend Thomas Priestman and others who attended him,
preserved the following minutes of his expressions in the time of his sickness,
and of his decease.

First-day, the 27th of the ninth month, 1772, His disorder appeared to be the smallpox:
being asked to have a doctor's advice,
he signified he had not freedom or liberty in his mind so to do,
standing wholly resigned to his will who gave him life,
and whose power he had witnessed to raise and heal him in sickness before,
when he seemed nigh unto death; and if he was to wind up now, he was perfectly resigned,
having no will either to live or die, and did not choose any should be sent for to him.
But a young man an apothecary' coming of his own accord the next day,
and desiring to do something for him,
he said he found a freedom to confer with him and the other Friends about him,
and if anything should be proposed, as to medicine,
that did not come through defiled channels or oppressive hands,
he should be willing to consider and take it, so far as he found freedom.

Second-day.
He said he felt the disorder to affect his head, so that he could think little,
and but as a child; and desired if his understanding should be more affected,
to have nothing given him that those about him knew he had a testimony against.

Third-day he uttered the following prayer.

"`O Lord my God,
the amazing horrors of darkness were gathered around me and covered me all over,
and I saw no way to go forth.
I felt the depth and extent of the misery of my fellow
creatures separated from the Divine harmony,
and it was heavier than I could bear, and I was crushed down under it.

I lifted up my hand, I stretched out my arm, but there was none to help me.
I looked round about and was amazed.
In the depths of misery, O Lord!
I remembered that you are omnipotent, that I had called you Father,
and I felt that I loved you, and I was made quiet in your will,
and I waited for deliverance from you.
You had pity upon me when no man could help me.
I saw that meekness under suffering was showed
to us in the most affecting example of your Son,
and you taught me to follow him, and I said, your will O Father be done.`"
Fourth-day morning, being asked how he felt himself, he meekly answered,
I don't know that I have slept this night.
I feel the disorder making its progress,
but my mind is mercifully preserved in stillness and peace.

Sometime after he said he was sensible the pains of death must be hard to bear,
but if he escaped them now, he must sometime pass through them,
and he did not know that he could be better prepared, but had no will in it.
He said he had settled his outward affairs to his mind,
and had taken leave of his wife and family as never to return,
leaving them to the Divine protection; adding,
"`and though I feel them near to me at this time, yet I freely give them up,
having a hope that they will be provided for.`"
A little after he said, "`This trial is made easier than I could have thought,
my will being wholly taken away;
for if I was anxious for the event it would have been harder, but I am not,
and my mind enjoys a perfect calm.`"

In the night a young woman +++[+++Sarah Grubb, at sixteen years of age]
having given him something to drink, he said,
"`My child you seems very kind to me a poor creature, the Lord will reward you for it.`"
Awhile after he cried out with great earnestness of spirit,
"`Oh my Father! my Father!`" and soon after he said,
"`Oh my Father! my Father! how comfortable are you to my soul in this trying season.`"
Being asked if he could take a little nourishment, after some pause he replied,
"`My child I cannot tell what to say to it;
I seem nearly arrived where my soul shall have rest from all its troubles.`"
After giving in something to be inserted in his Journal, he said,
"`I believe the Lord will now excuse me from exercises of this kind.
I see no work but one, which is to be the last wrought by me in this world;
the messenger will come that will release me from all these troubles;
but it must be in the Lord's time, which I am waiting for.`"
He said he had labored to do whatever was required, according to the ability received,
in the remembrance of which he had peace; and though the disorder was strong at times,
and would like a whirlwind come over his mind,
yet it had hitherto been kept steady and centered in everlasting love; adding,
"`and if that be mercifully continued, I ask or desire no more.`"
Another time he said, he had long had a view of visiting this nation,
and sometime before he came had a dream,
in which he saw himself in the northern parts of it,
and that the spring of the Gospel was opened in him much as in the beginning of Friends,
such as George Fox and William Dewsbury; and he saw the different states of the people,
as clearly as he had ever seen flowers in a garden;
but in his going along he was suddenly stopped, though he could not see for what end;
but looking towards home, fell into a flood of tears which wakened him.

At another time he said, "`my draught seemed strongest towards the North,
and I mentioned in my own Monthly Meeting, that attending the Quarterly Meeting at York,
and being there looked like home to me.`"
Fifth-day night,
having repeatedly consented to take medicine with a view to settle his stomach,
but without effect; the Friend then waiting on him, said through distress.
What shall I do now?
He answered with great composure, "`Rejoice ever more, and in every thing give thanks;
but added a little after, this is sometimes hard to come at.`"

Sixth-day morning early, he broke forth in supplication in this way, "`O Lord,
it was your power that enabled me to forsake sin in my youth,
and I have felt your bruises for disobedience, but as I bowed under them you healed me,
continuing a father and a friend.
I feel your power now,
and I beg that in the approaching trying moment
you will keep my heart steadfast unto you.`"
Upon his giving directions to a friend concerning some little things,
she said I will take care, but hope you will live to order them yourself; he replied,
"`my hope is in Christ, and though I may seem a little better,
a change in the disorder may soon happen, and my little strength be dissolved,
and if it so happens, I shall be gathered to my everlasting rest.`"
On her saying she did not doubt that,
but could not help mourning to see so many faithful servants removed at so low a time;
he said, "`all good comes from the Lord, whose power is the same,
and can work as he sees best.`"
The same day he had given directions about wrapping his corpse;
and perceiving a Friend to weep,
he said "`I would rather you would guard against weeping for me, my sister; I sorrow not,
though I have had some painful conflicts,
but now they seem over and matters well settled,
and I look at the face of my dear Redeemer,
for sweet is his voice and his countenance is comely.`"

First-day, 4th of the tenth month,
being very weak and in general difficult to be understood,
he uttered a few words in commemoration of the Lord's goodness; and added,
"`how tenderly have I been waited on in this time of affliction,
in which I may say in Job's words,
"`Tedious days and wearisome nights are appointed unto me;`" and how
many are spending their time and money in vanity and superfluities,
while thousands and tens of thousands lack the necessaries of life,
who might be relieved by them, and their distresses at such a time as this,
in some degree softened by the administering suitable things.`"

Second-day morning, the apothecary who appeared very anxious to assist him,
being present,
he queried about the probability of such a load of matter being thrown off his weak body,
and the apothecary making some remarks implying that he thought it might;
he spoke with an audible voice in this way, "`My dependence is on the Lord Jesus,
who I trust will forgive my sins, which is all I hope for,
and if it be his will to raise up this body again, I am content; and if to die,
I am resigned; and if you can not be easy without trying to assist nature,
I submit:`" after which his throat was so much affected,
that it was very difficult for him to speak so as to be understood,
and he frequently wrote when he lacked anything.
About the second hour on fourth-day morning he asked for pen and ink,
and at several times with much difficulty wrote thus,
"`I believe my being here is in the wisdom of Christ, I know not as to life or death.`"
About a quarter before six o'clock the same morning he seemed to fall into an easy sleep,
which continued about half an hour, when seeming to awake,
he breathed a few times with more difficulty, and expired without sigh, groan,
or struggle.

[.the-end]
END OF THE JOURNAL
