== CHAPTER XII.

Attends the Yearly Meeting in London--proceeds towards Yorkshire,
visiting several Quarterly and other meetings in the counties of Hertford, Warwick,
Oxford, Nottingham, York, and Westmoreland; and from there again into Yorkshire,
and to the city of York--some instructive thoughts and observations--
letters on several subjects--hears of the decease of William Hunt;
some account of him--sickness at York; and death there.

On the 8th day of the sixth month, 1772, we landed at London;
and I went straightway to the Yearly Meeting of ministers and elders,
which had been gathered, I suppose, about half an hour.

In this meeting, my mind was humbly contrite: in the afternoon,
the meeting of business opened, which by adjournments held nearly a week.
In these meetings,
I often felt a living concern for the establishment of Friends in the pure life of Truth;
and my heart was enlarged in the meeting of ministers, meeting of business,
and in several meetings for public worship;
and I felt my mind united in true love to the faithful
laborers now gathered at this Yearly Meeting.

On the 15th day of the month I left London, and went to a Quarterly Meeting at Hertford.

The 1st day of the seventh month.
I have been at Quarterly Meetings at Sherrington, Northampton, Banbury and Shipton,
and had sundry meetings between.
My mind has been bowed under a sense of Divine goodness manifested amongst us;
my heart being often enlarged in true love, both amongst ministers and elders,
and in public meetings; and through the Lord's goodness,
I believe it has been a fresh visitation to many, in particular to the youth.

The 17th day of the month.
Was this day at Birmingham: have been at meetings at Coventry, Warwick in Oxfordshire,
and sundry other places; I have felt the humbling hand of the Lord upon me,
and through his tender mercies find peace in the labors I have gone through.

The 26th day of the month.
I have continued traveling northward visiting meetings: was this day at Nottingham;
which, in the forenoon especially, was through Divine love a heart-tendering season:
next day had a meeting with Friends' children and some Friends; this,
through the strengthening arm of the Lord, was a time to be thankfully remembered.

The 2nd day of the eighth month, and first of the week, was this day at Sheffield,
a large inland town: I have been at sundry meetings last week,
and feel inward thankfulness for that Divine support,
which has been graciously extended to me.

The 9th day of the month, and first of the week, was at Rushworth:
have lately passed through some painful labor; but I have been comforted,
under a sense of that Divine visitation, which I feel extended toward many young people.

The 16th day of the month, and first of the week, was at Settle:
it has of late been a time of inward poverty; under which,
my mind has been preserved in a watchful tender state,
feeling for the mind of the holy Leader,
and find peace in the labors I have passed through.

On inquiry, in many places, I find the price of rye about five shillings,
and wheat about eight shillings, per bushel;
oatmeal twelve shillings for a hundred and twenty pounds;
mutton from three-pence to five-pence per pound; bacon, from seven-pence to ninepence;
cheese, from four-pence to sixpence; butter, from eight-pence to ten-pence; house rent,
for a poor man, from twenty-five shillings to forty shillings per year,
to be paid weekly; wood for fire, very scarce and dear; coal, in some places,
two shillings and sixpence per hundred weight; but near the pits, not a quarter so much.
O, may the wealthy consider the poor!
The wages of laboring men in several counties toward London,
are ten-pence per day in common business, the employer finds smallbeer,
and the laborer finds his own food; but in harvest and hay time,
wages are about one shilling per day, and the laborer has all his diet.
In some parts of the north of England, poor laboring men have their food where they work;
and appear, in common, to do rather better than nearer London.
Industrious women, who spin in the factories, get some four-pence, some five-pence,
and so on to six, seven, eight, nine or ten-pence per day,
and find their own house-room and diet.
Great numbers of poor people live chiefly on
bread and water in the southern parts of England,
and some in the northern parts; and there are many poor children not taught even to read.

May those who have plenty, lay these things to heart!
Stage-coaches frequently go upwards of a hundred miles in twenty-four hours;
and I have heard Friends say, in several places,
that it is common for horses to be killed with hard driving,
and many others are driven until they grow blind.

Post-boys pursue their business, each one to his stage, all night through the winter:
some boys who ride long stages, suffer greatly during winter nights;
and at several places I have heard of their being frozen to death.
So great is the hurry in the spirit of this world,
that in aiming to do business quick and to gain wealth,
the creation at this day does loudly groan!
As my journey has been without a horse,
I have had several offers of being assisted on my way in stage-coaches;
but have not been in them; nor have I had freedom to send letters by these posts,
in the present way of their riding; the stages being so fixed,
and one boy dependent on another as to time,
that they commonly go upward of one hundred miles in twenty-four hours;
and in the cold long winter nights, the poor boys suffer much.

I heard in America of the way of these posts;
and cautioned Friends in the General Meeting of ministers and elders at Philadelphia,
and in the Yearly Meeting of ministers and elders at London,
not to send letters to me on any common occasion by post.
And though on this account,
I may be likely to hear more seldom from my family left behind,
yet for righteousness sake, I am through Divine favor made content.

I have felt great distress of mind, since I came on this island,
on account of the members of our Society being mixed with the world,
in various sorts of business and traffic, carried on in impure channels.
Great is the trade to Africa for slaves! and in loading these ships,
abundance of people are employed in the factories; amongst whom are many of our Society.
Friends in early times refused on a religious principle,
to make or trade in superfluities, of which we have many large testimonies on record:
but for lack of faithfulness some gave way,
even some whose examples were of note in our Society;
and from there others took more liberty.
Members of our Society worked in superfluities, and bought and sold them;
and thus dimness of sight came over many.
At length, Friends got into the use of some superfluities in dress,
and in the furniture of their houses; and this has spread from less to more,
until superfluity of some kinds is common amongst us.

In this declining state, many look at the example one of another,
and too much neglect the pure feeling of Truth.
Of late years, a deep exercise has attended my mind, that Friends may dig deep,
may carefully cast forth the loose matter, and get down to the Rock, the sure foundation,
and there hearken to that Divine voice which gives a clear and certain sound.
I have felt in that which does not deceive, that if Friends who have known the Truth,
keep in that tenderness of heart, where all views of outward gain are given up,
and their trust is only on the Lord,
he will graciously lead some to be patterns of deep self-
denial in things relating to trade and handicraft labor;
and that some who have plenty of the treasures of this world,
will set an example of a plain frugal life, and pay wages to such whom they may hire,
more liberally than is now customary in some places.

The 23d day of the month; was this day at Preston-Patrick, and had a comfortable meeting.

I have several times been entertained at the houses of Friends,
who had sundry things about them which had the appearance of outward greatness;
and as I have kept inward, way has opened for conversation with such in private,
in which Divine goodness has favored us together with heart-tendering times.

The 26th day of the month.
Being now at George Crosfield's, in the county of Westmoreland,
I feel a concern to commit to writing, that which to me has been a case uncommon.

In a time of sickness with the pleurisy, a little upward of two years and a half ago,
I was brought so near the gates of death, that I forgot my name:
being then desirous to know who I was, I saw a mass of matter of a dull gloomy color,
between the south and the east; and was informed,
that this mass was human beings in as great misery as they could be, and live;
and that I was mixed in with them,
and that henceforth I might not consider myself as a distinct or separate being.
In this state I remained several hours.
I then heard a soft melodious voice, more pure and harmonious than any I had heard before.
I believed it was the voice of an angel, who spake to the other angels,
and the words were these, John Woolman is dead.
I soon remembered that I once was John Woolman;
and being assured that I was alive in the body,
I greatly wondered what that heavenly voice could mean.

I believed beyond doubting that it was the voice of a holy angel;
but as yet it was a mystery to me.
I was then carried in spirit to the mines,
where poor oppressed people were digging rich treasures for those called Christians;
and I heard them blaspheme the name of Christ, at which I was grieved;
for his name to me was precious.
Then I was informed, that these heathen were told,
that those who oppressed them were the followers of Christ;
and they said amongst themselves.
If Christ directed them to use us in this sort, then Christ is a cruel tyrant.

All this time the song of the angel remained a mystery; and in the morning,
my dear wife and some others coming to my bed-side, I asked them if they knew who I was;
and they telling me I was John Woolman, thought I was light-headed:
for I told them not what the angel said, nor was I disposed to talk much to anyone;
but was very desirous to get so deep, that I might understand this mystery.

My tongue was often so dry,
that I could not speak till I had moved it about and gathered some moisture,
and as I lay still for a time,
at length I felt Divine power prepare my mouth that I could speak; and then I said,
"`I am crucified with Christ, nevertheless I live; yet not I, but Christ lives in me:
and the lite I now live in the flesh, I live by the faith of the Son of God,
who loved me, and gave himself for me.`"
Then the mystery was opened;
and I perceived there was joy in heaven over a sinner who had repented;
and that that language (John Woolman is dead)
meant no more than the death of my own will.

Soon after this I coughed, and raised much bloody matter;
which I had not done during this vision:
and now my natural understanding returned as before.
Here I saw, that people getting silver vessels to set off their tables at entertainments,
was often stained with worldly glory; and that in the present state of things,
I should take heed how I fed myself out of silver vessels.

Soon after my recovery, going to our Monthly Meeting,
I dined at a Friend's house where drink was brought in silver vessels,
and not in any other; and needing some drink, I told him my case with weeping;
and he ordered some drink for me in another vessel.

The like I afterwards went through in several Friends' houses in America,
and have also in England, since I came here: and have cause, with humble reverence,
to acknowledge the loving-kindness of my heavenly Father,
who has preserved me in such a tender frame of mind, that none, I believe,
have ever been offended at what I have said on that occasion.

After this sickness, I spake not in public meetings for worship for nearly one year;
but my mind was very often in company with the oppressed slaves, as I sat in meetings:
and though under this dispensation, I was shut up from speaking,
yet the spring of the Gospel ministry was many times livingly opened in me;
and the Divine gift operated by abundance of weeping,
in feeling the oppression of this people.
It being long since I passed through this dispensation,
and the matter remaining fresh and livingly in my mind,
I believe it safest for me to commit it to writing.

The 30th day of the month.
This morning I wrote a letter, in substance as follows;

"`Beloved friend,`"

My mind is often affected as I pass along,
under a sense of the state of many poor people,
who sit under that sort of ministry which requires much outward labor to support it;
and the loving-kindness of our heavenly Father,
in opening a pure Gospel ministry in this nation,
has often raised thankfulness in my heart to him.
I often remember the conflicts of the faithful under persecution,
and now look at the free exercise of the pure gift, uninterrupted by outward laws,
as a trust committed to us, which requires our deepest gratitude,
and most careful attention.
I feel a tender concern, that the work of reformation,
so prosperously carried on in this land within a few ages past,
may go forward and spread amongst the nations; and may not go backward,
through dust gathering on our garments,
who have been called to a work so great and so precious.

"`Last evening I had a little opportunity at your house
with some of your family in your absence,
in which I rejoiced; and feeling a sweetness on my mind toward you,
I now endeavor to open a little of the feeling I had there.

"`I have heard that in these parts, you had, at certain seasons meetings of conference,
in relation to Friends living up to our principles,
in which several meetings unite in one; with which I feel unity.
I have in some measure, felt Truth lead that way amongst Friends in America;
and have found, my dear friend, that in these labors,
all superfluities in our own living are against us.
I feel that pure love toward you, in which there is freedom.

"`I look at that precious gift bestowed on you, with awfulness before Him who gave it;
and feel a care, that we may be so separated to the Gospel of Christ,
that those things which proceed from the spirit of this world,
may have no place amongst us.

"`Your friend, John Woolman.`"

I rested a few days, in body and mind, with our friend Jane Crosfleld,
who was once in America: was on the sixth day of the week, at Kendal in Westmoreland;
and at Grayrig meeting the 30th day of the month, and first of the week.

I have known poverty of late, and been graciously supported to keep in the patience;
and am thankful,
under a sense of the goodness of the Lord toward those that are of a contrite spirit.

The 6th day of the ninth month and first of the week; was this day at Counterside,
a large meeting-house and very full: and through the opening of pure love,
it was a strengthening time to me, and I believe to many more.

The 13th day of the month.
Was this day at Richmond, a small meeting; but the town's people coming in,
the house was crowded: it was a time of heavy labor;
and I believe was a profitable meeting.

At this place I heard that my kinsman William Hunt from North Carolina,
who was on a religious visit to Friends in England,
departed this life on the 9th day of the ninth month instant, of the small-pox,
at Newcastle.
He appeared in the ministry when a youth; and his labors therein were of good savor.
He travelled much in that work in America.
I once heard him say in public testimony, that his concern was, in that visit,
to be devoted to the service of Christ so fully,
that he might not spend one minute in pleasing himself; which words,
joined with his example, were a means of stirring up the pure mind in me.

Having of late travelled often in wet weather,
through narrow streets in towns and villages, where there were dirtiness under foot,
and the scent arising from that filth,
which more or less infects the air of all thickly settled towns; and being but weakly,
I have felt distress both in body and mind, with that which is impure.

In these journeys I have been where much cloth has been dyed;
and sundry times walked over ground, where much of the dye stuffs has drained away.
I have felt a longing in my mind, that people might come into cleanness of spirit,
cleanness of person, and cleanness about their houses and garments.

Some who are great, carry delicacy to a great height themselves,
and yet real cleanliness is not generally promoted.
Dyes being invented partly to please the eye, and partly to hide dirt,
I have felt in this weak state,
traveling in dirtiness and affected with unwholesome scents,
a strong desire that the practice of dyeing
cloth to hide dirt may be more fully considered.

To hide dirt in our garments, appears opposite to real cleanliness.
To wash garments and keep them sweet, appears cleanly.
Through giving way to hiding dirt in our garments,
a spirit which would cover that which is disagreeable, is strengthened.
Real cleanness becomes a holy people:
but hiding that which is not clean by coloring our garments,
appears contrary to the sweetness of sincerity.

Through some sorts of dyes, cloth is less useful; and if the value of dye-stuffs,
the expense of dyeing, and the damage done to cloth were all added together,
and that expense applied to keep all sweet and clean,
how much more cleanly would people be.

On this visit to England I have felt some instructions sealed on my mind,
which I am concerned to leave in writing,
for the use of such who are called to the station of a minister of Christ.

Christ being the Prince of peace, and we being no more than ministers,
I find it necessary for us, not only to feel a concern in our first going forth,
but to experience the renewing thereof, in the appointment of meetings.

I felt a concern in America, to prepare for this voyage;
and being through the mercy of God brought safely here,
my heart was like a vessel that needed vent, and for several weeks at first,
when my mouth was opened in meetings,
it often felt like the raising of a gate in a water course,
where a weight of water lay upon it;
and in these labors there appeared a fresh visitation to many, especially the youth;
but sometimes after this, I felt empty and poor,
and yet felt a necessity to appoint meetings.

In this state I was exercised to abide in the pure life of Truth,
and in all my labors to watch diligently against the motions of self in my own mind.
I have frequently felt a necessity to stand up, when the spring of the ministry was low,
and to speak from the necessity, in that which subjects the will of the creature;
and herein I was united with the suffering seed,
and found inward sweetness in these mortifying labors.

As I have been preserved in a watchful attention
to the Divine Leader under these dispensations,
enlargement at times has followed,
and the power of Truth has risen higher in some meetings,
than I ever knew it before through me.

Thus I have been more and more instructed as to the necessity of depending,
not upon a concern which I felt in America, to come on a visit to England;
but upon the fresh instructions of Christ the Prince of peace, from day to day.

Now of late, I felt a stop in the appointment of meetings, not wholly but in part;
and I do not feel liberty to appoint them so
quickly one after another as I have heretofore.

The work of the ministry being a work of Divine love,
I feel that the openings thereof are to be waited for in all our appointments.

Oh how deep is Divine wisdom!
Christ puts forth his ministers, and goes before them;
and oh how great is the danger of departing from
the pure feeling of that which leads safely!
Christ knows the state of the people, and in the pure feeling of the Gospel ministry,
their states are opened to his servants.

Christ knows when the fruit-bearing branches themselves have need of purging.
Oh that these lessons may be remembered by me! and that all who appoint meetings,
may proceed in the pure feeling of duty.

I have sometimes felt a necessity to stand up,
but that spirit which is of the world has so much prevailed in many,
and the pure life of Truth has been so pressed down, that I have gone forward,
not as one traveling in a road cast up and well prepared,
but as a man walking through a miry place, in which are stones here and there,
safe to step on; but so situated that one step being taken,
time is necessary to see where to step next, I find that in the pure obedience,
the mind learns contentment in appearing weak and
foolish to that wisdom which is of the world;
and in these lowly labors, they who stand in a low place,
rightly exercised under the cross, will find nourishment.

The gift is pure, and while the eye is single in attending thereto,
the understanding is preserved clear; self is kept out;
and we rejoice in filling up that which remains of the afflictions of Christ,
for his body's sake, which is the church.

The natural man loves eloquence, and many love to hear eloquent orations;
and if there is not a careful attention to the gift,
men who have once labored in the pure Gospel ministry, growing weary of suffering,
and ashamed of appearing weak, may kindle a fire,
compass themselves about with sparks and walk in the light,
not of Christ who is under suffering, but of that fire,
which they going from the gift have kindled.
And that in hearers which is gone from the meek suffering state into the worldly wisdom,
may be warmed with this fire, and speak highly of these labors.
That which is of God gathers to God; and that which is of the world is owned by the world.
In this journey a labor has attended my mind,
that the ministers amongst us may be preserved in the meek, feeling life of Truth,
where we may have no desire, but to follow Christ and be with him;
that when he is under suffering we may suffer with him;
and never desire to rise up in dominion,
but as he by the virtue of his own spirit may raise us.

A few days after writing these considerations,
our dear friend in the course of his religious visit, came to the city of York,
and attended most of the sittings of the Quarterly Meeting there; but before it was over,
was taken ill of the small-pox.
Our friend Thomas Priestman and others who attended him,
preserved the following minutes of his expressions in the time of his sickness,
and of his decease.

First-day, the 27th of the ninth month, 1772, His disorder appeared to be the smallpox:
being asked to have a doctor's advice,
he signified he had not freedom or liberty in his mind so to do,
standing wholly resigned to his will who gave him life,
and whose power he had witnessed to raise and heal him in sickness before,
when he seemed nigh unto death; and if he was to wind up now, he was perfectly resigned,
having no will either to live or die, and did not choose any should be sent for to him.
But a young man an apothecary' coming of his own accord the next day,
and desiring to do something for him,
he said he found a freedom to confer with him and the other Friends about him,
and if anything should be proposed, as to medicine,
that did not come through defiled channels or oppressive hands,
he should be willing to consider and take it, so far as he found freedom.

Second-day.
He said he felt the disorder to affect his head, so that he could think little,
and but as a child; and desired if his understanding should be more affected,
to have nothing given him that those about him knew he had a testimony against.

Third-day he uttered the following prayer.

"`O Lord my God,
the amazing horrors of darkness were gathered around me and covered me all over,
and I saw no way to go forth.
I felt the depth and extent of the misery of my fellow
creatures separated from the Divine harmony,
and it was heavier than I could bear, and I was crushed down under it.

I lifted up my hand, I stretched out my arm, but there was none to help me.
I looked round about and was amazed.
In the depths of misery, O Lord!
I remembered that you are omnipotent, that I had called you Father,
and I felt that I loved you, and I was made quiet in your will,
and I waited for deliverance from you.
You had pity upon me when no man could help me.
I saw that meekness under suffering was showed
to us in the most affecting example of your Son,
and you taught me to follow him, and I said, your will O Father be done.`"
Fourth-day morning, being asked how he felt himself, he meekly answered,
I don't know that I have slept this night.
I feel the disorder making its progress,
but my mind is mercifully preserved in stillness and peace.

Sometime after he said he was sensible the pains of death must be hard to bear,
but if he escaped them now, he must sometime pass through them,
and he did not know that he could be better prepared, but had no will in it.
He said he had settled his outward affairs to his mind,
and had taken leave of his wife and family as never to return,
leaving them to the Divine protection; adding,
"`and though I feel them near to me at this time, yet I freely give them up,
having a hope that they will be provided for.`"
A little after he said, "`This trial is made easier than I could have thought,
my will being wholly taken away;
for if I was anxious for the event it would have been harder, but I am not,
and my mind enjoys a perfect calm.`"

In the night a young woman +++[+++Sarah Grubb, at sixteen years of age]
having given him something to drink, he said,
"`My child you seems very kind to me a poor creature, the Lord will reward you for it.`"
Awhile after he cried out with great earnestness of spirit,
"`Oh my Father! my Father!`" and soon after he said,
"`Oh my Father! my Father! how comfortable are you to my soul in this trying season.`"
Being asked if he could take a little nourishment, after some pause he replied,
"`My child I cannot tell what to say to it;
I seem nearly arrived where my soul shall have rest from all its troubles.`"
After giving in something to be inserted in his Journal, he said,
"`I believe the Lord will now excuse me from exercises of this kind.
I see no work but one, which is to be the last wrought by me in this world;
the messenger will come that will release me from all these troubles;
but it must be in the Lord's time, which I am waiting for.`"
He said he had labored to do whatever was required, according to the ability received,
in the remembrance of which he had peace; and though the disorder was strong at times,
and would like a whirlwind come over his mind,
yet it had hitherto been kept steady and centered in everlasting love; adding,
"`and if that be mercifully continued, I ask or desire no more.`"
Another time he said, he had long had a view of visiting this nation,
and sometime before he came had a dream,
in which he saw himself in the northern parts of it,
and that the spring of the Gospel was opened in him much as in the beginning of Friends,
such as George Fox and William Dewsbury; and he saw the different states of the people,
as clearly as he had ever seen flowers in a garden;
but in his going along he was suddenly stopped, though he could not see for what end;
but looking towards home, fell into a flood of tears which wakened him.

At another time he said, "`my draught seemed strongest towards the North,
and I mentioned in my own Monthly Meeting, that attending the Quarterly Meeting at York,
and being there looked like home to me.`"
Fifth-day night,
having repeatedly consented to take medicine with a view to settle his stomach,
but without effect; the Friend then waiting on him, said through distress.
What shall I do now?
He answered with great composure, "`Rejoice ever more, and in every thing give thanks;
but added a little after, this is sometimes hard to come at.`"

Sixth-day morning early, he broke forth in supplication in this way, "`O Lord,
it was your power that enabled me to forsake sin in my youth,
and I have felt your bruises for disobedience, but as I bowed under them you healed me,
continuing a father and a friend.
I feel your power now,
and I beg that in the approaching trying moment
you will keep my heart steadfast unto you.`"
Upon his giving directions to a friend concerning some little things,
she said I will take care, but hope you will live to order them yourself; he replied,
"`my hope is in Christ, and though I may seem a little better,
a change in the disorder may soon happen, and my little strength be dissolved,
and if it so happens, I shall be gathered to my everlasting rest.`"
On her saying she did not doubt that,
but could not help mourning to see so many faithful servants removed at so low a time;
he said, "`all good comes from the Lord, whose power is the same,
and can work as he sees best.`"
The same day he had given directions about wrapping his corpse;
and perceiving a Friend to weep,
he said "`I would rather you would guard against weeping for me, my sister; I sorrow not,
though I have had some painful conflicts,
but now they seem over and matters well settled,
and I look at the face of my dear Redeemer,
for sweet is his voice and his countenance is comely.`"

First-day, 4th of the tenth month,
being very weak and in general difficult to be understood,
he uttered a few words in commemoration of the Lord's goodness; and added,
"`how tenderly have I been waited on in this time of affliction,
in which I may say in Job's words,
"`Tedious days and wearisome nights are appointed unto me;`" and how
many are spending their time and money in vanity and superfluities,
while thousands and tens of thousands lack the necessaries of life,
who might be relieved by them, and their distresses at such a time as this,
in some degree softened by the administering suitable things.`"

Second-day morning, the apothecary who appeared very anxious to assist him,
being present,
he queried about the probability of such a load of matter being thrown off his weak body,
and the apothecary making some remarks implying that he thought it might;
he spoke with an audible voice in this way, "`My dependence is on the Lord Jesus,
who I trust will forgive my sins, which is all I hope for,
and if it be his will to raise up this body again, I am content; and if to die,
I am resigned; and if you can not be easy without trying to assist nature,
I submit:`" after which his throat was so much affected,
that it was very difficult for him to speak so as to be understood,
and he frequently wrote when he lacked anything.
About the second hour on fourth-day morning he asked for pen and ink,
and at several times with much difficulty wrote thus,
"`I believe my being here is in the wisdom of Christ, I know not as to life or death.`"
About a quarter before six o'clock the same morning he seemed to fall into an easy sleep,
which continued about half an hour, when seeming to awake,
he breathed a few times with more difficulty, and expired without sigh, groan,
or struggle.

END OF THE JOURNAL

[.asterism]
'''

CONSIDERATIONS ON THE KEEPING OF NEGROES;
RECOMMENDED TO THE PROFESSORS OF CHRISTIANITY OF EVERY DENOMINATION.

FIRST PRINTED IN THE YEAR 1754.

INTRODUCTION.

Customs generally approved, and opinions received by youth from their superiors,
become like the natural produce of a soil,
especially when they are suited to favorite inclinations:
but as the judgments of God are without partiality,
by which the state of the soul must be tried,
it would be the highest wisdom to forego customs and popular opinions,
and try the treasures of the soul by the infallible standard.
Truth.

Natural affection needs a careful examination: operating upon us in a soft manner,
it kindles desires of love and tenderness,
and there is danger of taking it for something higher.
To me it appears an instinct like that which inferior creatures have; each of them,
we see, by the ties of nature, love self best; that which is a part of self,
they love by the same tie or instinct.
In them it in some measure does the offices of reason, by which, among other things,
they watchfully keep and regularly feed their helpless offspring.

Thus natural affection appears to be a branch of self-love, good in the animal race,
and in us likewise, with proper limitations; but otherwise it is productive of evil,
by exciting desires to promote some by means prejudicial to others.

Our blessed Saviour seems to give a check to this irregular fondness in nature,
and at the same time, a precedent for us: "`Who is my mother, and who are my brethren?`"
thereby intimating that the earthly ties of
relationship are comparatively inconsiderable to such,
who through a steady course of obedience,
have come to the happy experience of the spirit of God bearing
witness with their spirits that they are his children:--"`And
he stretched forth his hands towards his disciples,
and said, Behold my mother and my brethren:
For whosoever shall do the will of my Father which is in heaven,
(arrives at the more noble part of true relationship) the same is my brother, and sister,
and mother.`"
This doctrine agrees well with a state truly complete,
where love necessarily operates according to the agreeableness of things,
on principles unalterable and in themselves perfect.

If endeavoring to have my children eminent amongst men after my death,
be that which no reasons grounded on those principles can be brought to support;
then to be temperate in my pursuit after gain,
and to keep always within the bounds of those principles, is an indispensable duty,
and to depart from it, a dark unfruitful toil.

In our present condition, to love our children is needful;
but except this love proceeds from the true heavenly
principle which sees beyond earthly treasures,
it will rather be injurious than of any real advantage to them:
where the fountain is corrupt, the streams must necessarily be impure.

That important injunction of our Savior, Matt. 6:33, with the promise annexed,
contains a short but comprehensive view of our duty and
happiness:--If then the business of mankind in this life,
is first to seek another; if this cannot be done but by attending to the means;
if a summary of the means is, not to do that to another which, in like circumstances,
we would not have done unto us, then these are points of moment,
and worthy of our most serious consideration.

What I write on this subject is with reluctance,
and the hints given are in as general terms as my concern would allow.
I know it is a point about which, in all its branches,
men that appear to aim well are not generally agreed;
and for that reason I chose to avoid being very particular.
If I may happily let drop anything that may excite such as are concerned in
the practice to a close thinking on the subject treated of,
the candid amongst them may easily do the subject such further justice,
as on an impartial inquiry it may appear to deserve;
and such an inquiry I would earnestly recommend.

CONSIDERATIONS, etc.

' Forasmuch as you did it to the least of these my brethren, you did it unto me.`" Matt. 25:40.


As many times there are different motives to the same action;
and one does that from a generous heart, which another does for selfish ends;
the like may be said in this case.

There are various circumstances among those that keep negroes,
and different ways by which they fall under their care; and I doubt not,
there are many well disposed persons amongst them who desire
rather to manage wisely and justly in this difficult matter,
than to make gain of it.

But the general disadvantage which these poor Africans
lie under in an enlightened Christian country,
having often filled me with real sadness, and been like undigested matter on my mind,
I now think it my duty, through Divine aid,
to offer some thoughts thereon to the consideration of others.

When we remember that all nations are of one blood, Gen. 3:20,
that in this world we are but sojourners,
that we are subject to the like afflictions and infirmities of body,
the like disorders and frailties in mind, the like temptations, the same death,
and the same judgment, and that the all-wise Being is Judge and Lord over us all,
it seems to raise an idea of general brotherhood,
and a disposition easy to be touched with a feeling of each other's afflictions:
but when we forget those things, and look chiefly at our outward circumstances,
in this and some ages past,
constantly retaining in our minds the distinction between us and them,
with respect to our knowledge and improvement in things Divine, natural and artificial,
our breasts being apt to be filled with fond notions of superiority,
there is danger of erring in our conduct toward them.

We allow them to be of the same species with ourselves; the odds is,
we are in a higher station, and enjoy greater favors than they.
And when it is thus that our heavenly Father endows
some of his children with distinguished gifts,
they are intended for good ends;
but if those thus gifted are thereby lifted up above their brethren,
not considering themselves as debtors to the weak,
nor behaving themselves as faithful stewards,
none who judge impartially can suppose them free from ingratitude.

When a people dwell under the liberal distribution of favors from heaven,
it behoves them carefully to inspect their ways,
and consider the purposes for which those favors are bestowed, lest,
through forgetfulness of God and misusing his gifts, they incur his heavy displeasure,
whose judgments are just and equal, who exalts and humbles to the dust, as he sees meet.

It appears, by Holy Record,
that men under high favors have been apt to err in their opinions concerning others.
Thus Israel, according to the description of the prophet, Isa.
Ixv. 5., when exceedingly corrupted and degenerated,
yet remembered they were the chosen people of God; and could say, "`Stand by yourself,
come not near me, for I am holier than you.`"
That this was no chance language, but their common opinion of other people,
more fully appears,
by considering the circumstances which attended when God was beginning to
fulfill his precious promises concerning the gathering of the Gentiles.

The Most High, in a vision undeceived Peter, first prepared his heart to believe,
and at the house of Cornelius showed him of a
certainty that God is no respecter of persons.

The effusion of the Holy Ghost upon a people, with whom they,
the Jewish Christians would not so much as eat, was strange to them.
All they of the circumcision were astonished to see it;
and the apostles and brethren of Judea contended with Peter about it,
till he having rehearsed the whole matter,
and fully shown that the Father's love was unlimited,
they are thereat struck with admiration, and cry out,
"`Then has God also to the Gentiles granted repentance unto life.`"
The opinion of peculiar favors being confined to them, was deeply rooted,
or else the above instance had been less strange to them, for these reasons: First,
They were generally acquainted with the writings of the prophets,
by whom this time was repeatedly spoken of, and pointed at.
Secondly, Our blessed Lord shortly before expressly said,
"`I have other sheep not of this fold, them also must I bring,`" etc.
Lastly, His words to them after his resurrection, at the very time of his ascension,
"`You shall be witnesses to me, not only in Jerusalem, Judea, and Samaria,
but to the uttermost parts of the earth.`"
These concurring circumstances, one would think,
might have raised a strong expectation of seeing such a time; yet when it came,
it proved matter of offense and astonishment.

To consider mankind otherwise than brethren, to think favors are peculiar to one nation,
and to exclude others, plainly supposes a darkness in the understanding:
for as God's love is universal, so where the mind is sufficiently influenced by it,
it begets a likeness of itself, and the heart is enlarged towards all men.
Again, to conclude a people froward, perverse, and worse by nature than others,
who ungratefully receive favors, and apply them to bad ends,
will excite a behavior toward them unbecoming the excellence of true religion.

To prevent such an error, let us calmly consider their circumstance:
and the better to do it, make their case ours.
Suppose then that our ancestors and we had been exposed to constant servitude,
in the more servile and inferior employments of life;
that we had been destitute of the help of reading and good company;
that amongst ourselves we had had but few wise and pious instructors;
that the religious amongst our superiors seldom took notice of us;
that while others in ease have plentifully heaped up the fruit of our labor,
we had received barely enough to relieve nature;
and being wholly at the command of others, had generally been treated as a contemptible,
ignorant part of mankind, should we in that case be less abject than they now are?
Again, If oppression be so hard to bear, that a wise man is made mad by it, Ecc. 7:7.
,
then a series of oppressions altering the behavior and manners of a people,
is what may reasonably be expected.

When our property is taken contrary to our mind, by means appearing to us unjust,
it is only through Divine influence, and the enlargement of heart from there proceeding,
that we can love our reputed oppressors.
If the negroes fall short in this, an uneasy,
if not a disconsolate disposition will be awakened, and remain like seeds in their minds,
producing sloth and other habits which appear odious to us; and with which,
had they been free men, they would not perhaps have been chargeable.
These and other circumstances rightly considered,
will lessen the too great disparity which some make between us and them.

Integrity of heart has appeared in some of them;
so that if we continue in the word of Christ (previous to discipleship,
John 8:31) and our conduct towards them be seasoned with his love,
we may hope to see the good effect of it.
This, in a good degree, is the case with some into whose hands they have fallen;
but that too many treat them otherwise, not seeming conscious of any neglect.,
is alas! too evident.

When self-love presides in our minds, our opinions are biassed in our own favor;
and in this condition, being concerned with a people so situated,
that they have no voice to plead their own cause,
there is danger of using ourselves to an undisturbed partiality, until by long custom,
the mind becomes reconciled with it, and the judgment itself infected.

To apply humbly to God for wisdom,
that we may thereby be enabled to see things as they are, and as they ought to be,
is very needful.
Hereby the hidden things of darkness may be brought to light,
and the judgment made clear: we shall then consider mankind as brethren.
Though different degrees and a variety of qualifications and abilities,
one dependent on another, be admitted, yet high thoughts will be laid aside,
and all men treated as becomes the sons of one father,
agreeably to the doctrine of Christ Jesus.

"`He has laid down the best criterion,
by which mankind ought to judge of their own conduct,
and others judge for them of theirs, one towards another, namely:
'Whatsoever you would that men should do unto you, do you even so to them.'
I take it, that all men by nature, are equally entitled to the equity of this rule,
and under the indispensable obligations of it.
One man ought not to look upon another man or society of men, as so far beneath him,
that he should not put himself in their place, in all his actions towards them,
and bring all to this test, namely: "`How should I approve of this conduct,
were I in their circumstance, and they in mine?`"
This doctrine being of a moral unchangeable nature,
has been likewise inculcated in the former dispensation;
"`If a stranger sojourn with you in your land, you shall not vex him;
but the stranger that dwells with you, shall be as one born amongst you,
and you shall love him as yourself.`"
Had these people come voluntarily and dwelt amongst us,
to call them strangers would be proper; and their being brought by force,
with regret and a languishing mind,
may well raise compassion in a heart rightly disposed:
but there is nothing in such treatment, which upon a wise and judicious consideration,
will in any way lessen their right to be treated as strangers.

If the treatment which many of them meet with,
be rightly examined and compared with those precepts,
"`You shall not vex him nor oppress him; he shall be as one born amongst you,
and you shall love him as yourself,`" there will
appear an important difference between them.

It may be objected that there is the cost of purchase,
and risk of their lives to them who possess them,
and therefore it is needful that they make the best use of their time.
In a practice just and reasonable, such objections may have weight;
but if the work be wrong from the beginning, there is little or no force in them.
If I purchase a man who has never forfeited his liberty,
the natural right of freedom is in him;
and shall I keep him and his posterity in servitude and ignorance?
"`How should I approve of this conduct, were I in his circumstances, and he in mine?`"
It may be thought, that to treat them as we would willingly be treated,
our gain by them would be inconsiderable: and it were, in several respects,
better that there were none in our country.

We may further consider, that they are now amongst us,
and people of our nation were the cause of their being here;
that whatsoever difficulty accrues thereon, we are justly chargeable with,
and to bear all inconveniences attending it with a serious and
weighty concern of mind to do our duty by them,
is the best we can do.
To seek a remedy by continuing the oppression, because we have power to do it,
and see others do it, will, I apprehend, not be doing as we would be done by.

How deeply soever men are involved in difficulties, sincerity of heart,
and upright walking before God, freely submitting to his providence,
is the most sure remedy.
He only is able to relieve, not only persons but nations in their greatest calamities.

David in a great strait, when the sense of his past error,
and the full expectation of an impending calamity as
the reward of it were united to aggravate his distress,
after some deliberation, says, "`Let me fall now into the hand of the Lord,
for very great are his mercies; let me not fall into the hand of man.`"
To act continually with integrity of heart, above all narrow or selfish motives,
is a sure token of our being partakers of that salvation which
"`God has appointed for walls and bulwarks,`" and is,
beyond all contradiction,
a more happy situation than can ever be promised
by the utmost reach of art and power united,
not proceeding from heavenly wisdom.

A supply to nature's lawful needs, joined with a peaceful humble mind,
is the truest happiness in this life; and if we arrive at this,
and continue to walk in the path of the just, our case will be truly happy.
Though herein we may part with, or miss of the glaring show of riches,
and leave our children little else but wise instructions, a good example,
and the knowledge of some honest employment; these, with the blessing of Providence,
are sufficient for their happiness, and are more likely to prove so,
than laying up treasures for them, which are often rather a snare, than any real benefit;
especially to those, who instead of being exampled to temperance,
are in all things taught to prefer the getting of riches,
and to eye the temporal distinctions they give, as the principal business of this life.

These readily overlook the true happiness of man,
which results from the enjoyment of all things in the fear of God,
and miserably substituting an inferior good,
dangerous in the acquiring and uncertain in the fruition,
they are subject to many disappointments, and every sweet carries its sting.

It is the conclusion of our blessed Lord and his apostles,
as appears by their lives and doctrines, that the highest delights of sense,
or most pleasing objects visible,
ought ever to be accounted infinitely inferior to that real intellectual happiness,
suited to man in his primitive innocence, and now to be found in true renovation of mind;
and that the comforts of our present life, the things most grateful to us,
ought always to be received with temperance,
and never made the chief objects of our desire, hope, or love;
but that our whole heart and affections be principally looking to that "`city,
which has foundations, whose maker and builder is God.`"
Do we so improve the gifts bestowed on us,
that our children might have an education suited to these doctrines,
and our example to confirm it,
we might rejoice in hopes of their being heirs of an inheritance incorruptible.

This inheritance, as Christians, we esteem the most valuable;
and how then can we fail to desire it for our children?
O that we were consistent with ourselves, in pursuing the means necessary to obtain it!
It appears by experience, that where children are educated in fulness, ease,
and idleness, evil habits are more prevalent,
than is common amongst such who are prudently employed in the necessary affairs of life.
If children are not only educated in the way of so great temptation,
but have also the opportunity of lording it over their fellow-creatures,
and being masters of men in their childhood,
how can we hope otherwise than that their tender minds
will be possessed with thoughts too high for them;
which gaining strength by continuance, will prove like a slow current,
gradually separating them from or keeping from acquaintance with that
humility and meekness in which alone lasting happiness can be enjoyed.

Man is born to labor, and experience abundantly shows, that it is for our good:
but where the powerful lay the burden on the inferior,
without affording a Christian education, and suitable opportunity of improving the mind,
and a treatment which we, in their case, should approve,
in order that themselves may live at ease, and fare sumptuously,
and lay up riches for their posterity, this seems to contradict the design of Providence,
and I doubt not, is sometimes the effect of a perverted mind;
for while the life of one is made grievous by the rigor of another,
it entails misery on both.

Amongst the manifold works of Providence, displayed in the different ages of the world,
these which follow, with many others, may afford instruction.

Abraham was called of God to leave his country and kindred, to sojourn amongst strangers.
Through famine, and danger of death, he was forced to flee from one kingdom to another;
yet, at length, he not only had assurance of being the father of many nations,
but became a mighty prince. Genesis 23:6.


Remarkable were the dealings of God with Jacob in a low estate,
the just sense he retained of them after his advancement, appears by his words:
"`I am not worthy of the least of all your mercies.`"
The numerous afflictions of Joseph are very singular;
the particular providence of God therein, no less manifest:
he at length became governor of Egypt, and famous for wisdom and virtue.

The series of troubles which David passed through, few amongst us are ignorant of;
and yet he afterwards became as one of the great men of the earth.

Some evidences of the Divine wisdom appear in those things,
in that such who are intended for high stations, have first been very low and dejected,
that Truth might be sealed on their hearts;
and that the characters there imprinted by bitterness and adversity,
might in after years remain, suggesting compassionate ideas, and in their prosperity,
quicken their regard to those in the like condition.

This yet further appears in the case of Israel;
who were well acquainted with grievous sufferings, a long and rigorous servitude;
and then through many notable events, were made chief amongst the nations.
To them we find a repetition of precepts to the purpose above-said:
though for ends agreeable to infinite wisdom,
they were chosen as a peculiar people for a time; yet the Most High acquaints them,
that his love is not confined, but extends to the stranger;
and to excite their compassion, reminds them of times past,
"`You were strangers in the land of Egypt.`"
Again, "`You shall not oppress a stranger, for you know the heart of a stranger,
seeing you were strangers in the land of Egypt.`"
If we call to mind our beginning, some of us may find a time,
wherein our fathers were under afflictions, reproaches, and manifold sufferings.

Respecting our progress in this land,
the time is short since our beginning was small and number few,
compared with the native inhabitants.
He that sleeps not by day nor night, has watched over us,
and kept us as the apple of his eye.
His Almighty arm has been round about us, and saved us from dangers.

The wilderness and solitary deserts in which our
fathers passed the days of their pilgrimage,
are now turned into pleasant fields; the natives are gone from before us,
and we established peaceably in the possession of the land,
enjoying our civil and religious liberties;
and while many parts of the world have groaned under the heavy calamities of war,
our habitation remains quiet, and our land fruitful.

When We trace back the steps we have trodden,
and see how the Lord has opened a way in the wilderness for us,
to the wise it will easily appear, that all this was not done to be buried in oblivion;
but to prepare a people for more fruitful returns,
and the remembrance thereof ought to humble us in prosperity,
and excite in us a Christian benevolence towards our inferiors.

If we do not consider these things aright, but through a stupid indolence,
conceive views of interest separate from the general good of the great brotherhood,
and in pursuance thereof, treat our inferiors with rigor to increase our wealth,
and gain riches for our children; "`What then shall we do when God rises up?
and when he visits, what shall we answer him?
did not he that made us, make them?
and did not one fashion us?`"
To our great Master we stand or fall,
to judge or condemn us as is most suitable to his wisdom or authority;
my inclination is to persuade, and entreat, and simply give hints of my way of thinking.

If the Christian religion be considered, both respecting its doctrines,
and the happy influence which it has on the minds and manners of all real Christians,
it looks reasonable to think, that the miraculous manifestation thereof to the world,
is a kindness beyond expression.

Are we the people thus favored?
Are we they whose minds are opened, influenced, and governed by the Spirit of Christ,
and thereby made sons of God?
Is it not a fair conclusion, that we, like our heavenly Father,
ought in our degree to be active in the same great cause, of the eternal happiness of,
at least our whole families, and more, if thereto capacitated?
If we, by the operation of the Spirit of Christ,
become heirs with him in the kingdom of his Father,
and are redeemed from the alluring counterfeit joys of this world,
and the joy of Christ remain in us, to suppose that one in this happy condition, can,
for the sake of earthly riches,
not only deprive his fellow-creatures of the sweetness of freedom, which rightly used,
is one of the greatest temporal blessings,
but therewith neglect using proper means for their acquaintance with the Holy Scriptures,
and the advantage of true religion, seems at least a contradiction to reason.

Whoever rightly advocates the cause of some, thereby promotes the good of all.
The state of mankind was harmonious in the beginning,
and though sin has introduced discord,
yet through the wonderful love of God in Christ Jesus our Lord,
the way is open for our redemption,
and means appointed to restore us to primitive harmony.
That if one suffer by the unfaithfulness of another, the mind,
the most noble part of him that occasions the discord,
is thereby alienated from its true and real happiness.

Our duty and interest are inseparably united, and when we neglect or misuse our talents,
we necessarily depart from the heavenly fellowship,
and are in the way to the greatest of evils.
Therefore to examine and prove ourselves,
to find what harmony the power presiding in us bears with the Divine nature,
is a duty not more incumbent and necessary, than it would be beneficial.

In Holy Writ the Divine Being says of himself, "`I am the Lord,
which exercise lovingkindness, judgment and righteousness in the earth;
for in these things I delight, says the Lord.`"
Again, speaking in the way of man, to show his compassion to Israel,
whose wickedness had occasioned a calamity, and then being humbled under it, it is said,
"`His soul was grieved for their miseries.`"
If we consider the life of our blessed Saviour when on earth,
as it is recorded by his followers,
we shall find that one uniform desire for the eternal and temporal good of mankind,
discovered itself in all his actions.

If we observe men, both apostles and others, in many different ages,
who have really come to the unity of the Spirit, and the fellowship of the saints,
there still appears the like disposition,
and in them the desire for the real happiness of mankind,
has out-balanced the desire of ease, liberty, and many times, of life itself.

If upon a true search, we find that our natures are so far renewed,
that to exercise righteousness and loving-kindness, according to our ability,
towards all men, without respect of persons, is easy to us, or is our delight;
if our love be so orderly and regular,
that he who does the will of our Father who is in heaven,
appears in our view to be our nearest relation, our brother, and sister, and mother;
if this be our case, there is a good foundation to hope,
that the blessing of God will sweeten our treasures during our stay in this life,
and that our memory will be savory, when we are entered into rest.

To conclude, It is a truth most certain, that a life guided by wisdom from above,
agreeably with justice, equity and mercy, is throughout consistent and amiable,
and truly beneficial to society; the serenity and calmness of mind in it,
affords an unparalleled comfort in this life, and the end of it is blessed.

And it is no less true, that they who in the midst of high favors remain ungrateful,
and under all the advantages that a Christian can desire, are selfish,
earthly and sensual, do miss the true fountain of happiness,
and wander in a maze of dark anxiety,
where all their treasures are insufficient to quiet their minds:
hence from an insatiable craving, they neglect doing good with what they have acquired,
and too often add oppression to vanity, that they may compass more.

"`O that they were wise, that they understood this,
that they would consider their latter end!`"


CONSIDERATIONS ON THE KEEPING OF NEGROES;
RECOMMENDED TO THE PROFESSORS OF CHRISTIANITY OP EVERY DENOMINATION.

SECOND PART

FIRST PRINTED IN THE YEAR 1762.

"`You shall not respect persons in judgment;
but you shall hear the small as well as the great:
you shall not be afraid of the face of man; for the judgment is God's.`" Duet. 1:17.

PREFACE.

All our actions are of like nature with their root;
and the Most High weighs them more skillfully than men can weigh them one for another.

I believe that one Supreme Being made and supports the world;
nor can I worship any other Deity without being an idolater, and guilty of wickedness.

Many nations have believed in and worshipped a plurality of deities;
but I do not believe they were therefore all wicked.
Idolatry indeed is wickedness; but it is the thing, not the name, which is so.
Real idolatry is to pay that adoration to a creature,
which is known to be due only to the true God.

He who professes to believe in one Almighty Creator, and in his Son Jesus Christ,
and yet is more intent on the honors, profits and friendships of the world,
than he is in singleness of heart to stand faithful to the Christian religion,
is in the channel of idolatry; while the Gentile, who under some mistaken opinions,
is notwithstanding established in the true principle of virtue,
and humbly adores an Almighty power,
may be of that number who fear God and work righteousness.

I believe the bishop of Rome assumes a power that does
not belong to any officer in the church of Christ;
and if I should knowingly do anything tending to strengthen him in that capacity,
it would be great iniquity.

There are many thousands of people,
who by their profession acknowledge him to be
the representative of Jesus Christ on earth;
and to say that none of them are upright in heart, would be contrary to my sentiments.

Men who sincerely apply their minds to true virtue,
and find an inward support from above,
by which all vicious inclinations are made subject; that they love God sincerely,
and prefer the real good of mankind universally to their own private interest;
though these through the strength of education and tradition,
may remain under some speculative, and great errors, it would be uncharitable to say,
that therefore God rejects them.
He who creates, supports and gives understanding to all men,
possesses knowledge and goodness superior to the
various cases and circumstances of his creatures,
which to us appear the most difficult.

The apostles and primitive Christians did not censure all the Gentiles as wicked men, Rom. 2:14.
, Col. 3:11.;
but as they were favored with a gift to discern things more clearly,
respecting the worship of the true God,
they with much firmness declared against the worshipping of idols,
and with true patience endured many sufferings on that account.

Great numbers of faithful Protestants have contended for the Truth,
in opposition to papal errors;
and with true fortitude laid down their lives in the conflict, without saying,
that no man was saved who made profession of that religion.

While we have no right to keep men as servants for term of life,
but that of superior power;
to do this with design to profit ourselves and our families by their labor,
I believe is wrong; but I do not believe that all who have kept slaves,
have therefore been chargeable with guilt.
If their motives thereto were free from selfishness, and their slaves contented,
they were a sort of freemen; which I believe has sometimes been the case.

Whatever a man does in the spirit of charity, to him it is not sin:
and while he lives and acts in this spirit,
he learns all things essential to his happiness as an individual:
and if he does not see that any injury or injustice to any other person,
is necessarily promoted by any part of his form of government,
I believe the merciful Judge will not lay iniquity to his charge.
Yet others, who live in the same spirit of charity, from a clear convincement,
may see the relation of one thing to another, and the necessary tendency of each;
and hence it may be absolutely binding on them to desist from some parts of conduct,
which some good men have been in.

CONSIDERATIONS, etc.

As some in most religious societies amongst the English are concerned
in importing or purchasing the inhabitants of Africa as slaves;
and as the professors of Christianity of several other nations do the like;
these circumstances tend to make people less apt
to examine the practice as closely as they would,
if such a thing had not been, but was now proposed to be entered upon.
It is however our duty, and what concerns us individually,
as creatures accountable to our Creator,
to employ rightly the understanding which he has given us,
in humbly endeavoring to be acquainted with his will concerning us,
and with the nature and tendency of those things which we practice.
For as justice remains to be justice, so many people of reputation in the world,
joining with wrong things, does not excuse others in joining with them,
nor make the consequence of their proceedings less dreadful in the final issue,
than it would otherwise be.

Where unrighteousness is justified from one age to another,
it is like dark matter gathering into clouds over us.
We may know that this gloom will remain till the cause be removed by a reformation,
or a change of times, and may feel a desire from a love of equity,
to speak on the occasion; yet where error is so strong,
that it may not be spoken against without a
prospect of some inconvenience to the speaker,
this difficulty is likely to operate on our weakness, and quench the good desires in us;
except we dwell so steadily under the weight of it,
as to be made willing to "`endure hardness`" on that account.

Where men exert their talents against vices which are generally accounted such,
the ill effects whereof are presently perceived in a government,
all men who regard their own temporal good, are likely to approve the work.

But when that which is inconsistent with perfect equity,
has the law or the countenance of the great in its favor,
though the tendency thereof be contrary to the true happiness of mankind,
in an equal if not greater degree, than many things accounted reproachful to Christians;
yet as these ill effects are not generally perceived,
they who labor to dissuade from such things,
which people believe accord with their interest, have many difficulties to encounter.

The repeated charges which God gave to his prophets,
imply the danger they were in of erring on this hand.
"`Be not afraid of their faces; for I am with you, to deliver you, says the Lord.`"
"`Speak all the words that I command you to speak to them; diminish not a word.`"
"`And you, son of man, be not afraid of them, nor dismayed at their looks.
Speak my words to them, whether they will hear or forbear.`"
Under an apprehension of duty, I offer some further considerations on this subject,
having endeavored some years to consider it candidly.
I have observed people of our own color,
whose abilities have been inadequate to manage the
affairs which relate to their convenient subsistence,
who have been taken care of by others, and the profit of such work as they could do,
applied toward their support.

I believe there are such amongst negroes; and that some people in whose hands they are,
keep them with no view of outward profit, do not consider them as black men,
who as such ought to serve white men;
but account them persons who have need of guardians, and as such take care of them:
yet where equal care is taken in all parts of their education,
I do not apprehend cases of this sort are likely to occur more
frequently amongst one sort of people than another.

It looks to me that the slave trade was founded,
and has generally been carried on in a wrong spirit;
that the effects of it are detrimental to the real prosperity of our country;
and will be more so, except we cease from the common motives of keeping them,
and treat them in future agreeably to Truth and pure justice.

Negroes may be imported, who for their cruelty to their countrymen,
and the evil disposition of their minds, may be unfit to be at liberty;
and if we as lovers of righteousness undertake the management of them,
we should have a full and clear knowledge of their crimes,
and of those circumstances which might operate in their favor;
but the difficulty of obtaining this is so great,
that we have great reason to be cautious therein.
But should it plainly appear that absolute subjection is a
condition the most proper for the person who is purchased,
yet the innocent children ought not to be made slaves, because their parents sinned.

We have an account in Holy Scripture of some families suffering,
where mention is only made of the heads of the family committing wickedness;
and it is likely that the degenerate Jews,
misunderstanding some occurrences of this kind,
took occasion to charge God with being unequal; so that a saying became common,
"`The Fathers have eaten sour grapes, and the children's teeth are set on edge.`"
Jeremiah and Ezekiel, two of the inspired prophets, who lived near the same time,
were concerned to correct this error.
Ezekiel is large on the subject.
First, he reproves them for their error.
"`What mean you, that you do so.`"
"`As I live, says the Lord God,
you shall not have occasion any more to use this proverb in Israel.`"
The words, "`any more,`" have reference to time past; intimating,
that though they had not rightly understood some things they had heard or seen,
and from there supposed the proverb to be well grounded;
yet henceforth they might know of a certainty, that the ways of God are all equal;
that as surely as the Most High lives,
so surely men are only answerable for their own sins.
He thus sums up the matter, "`The soul that sins, it shall die.
The son shall not bear the iniquity of the father;
neither shall the father bear the iniquity of the son.
The righteousness of the righteous shall be upon him;
and the wickedness of the wicked shall be upon him.`"
Where men are wicked, they commonly are a means of corrupting the succeeding age;
and thereby hasten those outward calamities which fall on nations,
when their iniquities are full.

Men may pursue means which are not agreeable to perfect purity,
with a view to increase the wealth and happiness of their offspring,
and thereby make the way of virtue more difficult to them.
And though the ill example of a parent, or of a multitude,
does not excuse a man in doing evil,
yet the mind being early impressed with vicious notions and practices,
and nurtured up in ways of getting treasure, which are not the ways of Truth;
this wrong spirit first getting possession, and being thus strengthened,
frequently prevents a due attention to the true spirit of wisdom,
so that they exceed in wickedness those who lived before them.
And in this channel, though parents labor, as they think,
to forward the happiness of their children,
it proves a means of forwarding their calamity.

This being the case in the age next before the
grievous calamity in the siege of Jerusalem,
and carrying Judah captive to Babylon, they might say with propriety.
This came upon us, because our fathers forsook God,
and because we did worse than our fathers.
See Jer. 7:26.

As the generation next before them inwardly turned away from God,
who yet waited to be gracious;
and as they in that age continued in those things which
necessarily separated from perfect goodness,
growing more stubborn till the judgments of God were poured out upon them;
they might properly say, "`Our fathers have sinned, and we have borne their iniquities.`"
And yet, wicked as their fathers were, had they not succeeded them in their wickedness,
they had not borne their iniquities.

To suppose it right,
that an innocent man shall at this day be excluded from the common rules of justice;
be deprived of that liberty which is the natural right of human creatures,
and be a slave to others during life,
on account of a sin committed by his immediate parents; or a sin committed by Ham,
the son of Noah; is a supposition too gross to be admitted into the mind of any person,
who sincerely desires to be governed by just and solid principles.

It is alleged in favor of the practice, that Joshua made slaves of the Gibeonites.
What men do by the command of God,
and what comes to pass as a consequence of their neglect, are different;
the case now mentioned was such as the latter.

It was the express command of the Almighty to Israel,
concerning the inhabitants of the promised land, "`You shall make no covenant with them,
nor with their gods: they shall not dwell in your land.`"
Those Gibeonites came craftily, telling Joshua that they were come from a far country;
that their elders had sent them to make a league with the people of Israel;
and as an evidence of their being foreigners, showed their old clothes, etc.

"`And the men took of their victuals, and asked not counsel at the mouth of the Lord;
and Joshua made peace with them, and made a league with them, to let them live;
and the princes swear to them.`"
When the imposition was discovered, the congregation murmured against the princes:
"`But all the princes said to all the congregation,
we have sworn to them by the Lord God of Israel; now therefore we may not touch them;
we will even let them live, lest wrath be upon us;
but let them be hewers of wood and drawers of water unto the congregation.`"
Omitting to ask counsel, involved them in great difficulty.
The Gibeonites were of those cities, of which the Lord said,
"`You shall save alive nothing that breathes;`" and of the stock of the Hivites,
concerning whom he commanded by name, "`You shall smite them, and utterly destroy them:
You shall make no covenant with them, nor show mercy unto them.`"
Joshua and the princes not knowing them, had made a league with them to let them live;
and in this strait they resolved to make them servants.
Joshua and the princes suspected them to be deceivers:
"`Peradventure you dwell amongst us: and how shall we make a league with you?`"
Which words show that they remembered the command before mentioned;
and yet did not inquire at the mouth of the Lord, as Moses directed Joshua,
when he gave him a charge respecting his duty as chief man among that people. Num. 27:21.
By this omission things became so situated,
that Joshua and the princes could not execute the judgments of God on them,
without violating the oath which they had made.

Moses did amiss at the waters of Meribah, and doubtless he soon repented;
for the Lord was with him.
And it is likely that Joshua was deeply humbled, under a sense of his omission;
for it appears that God continued him in his office,
and spared the lives of those people,
for the sake of the league and oath made in his name.

The wickedness of these people was great, and they were worthy to die,
or perfect justice had not passed sentence of death upon them;
and as their execution was prevented by this league and oath,
they appear to have been contented to be servants:
"`As it seems good and right unto you to do unto us, do.`"
These criminals, instead of death, had the sentence of servitude pronounced on them,
in these words, "`Now therefore you are cursed;
and there shall none of you be freed from being bondmen,
and hewers of wood and drawers of water for the house of my God.`"
We find, Duet. 20:10., that there were cities far distant from Canaan,
against which Israel went to battle, unto whom they were to proclaim peace,
and if the inhabitants made answer of peace, and opened their gates,
they were not to destroy them, but make them tributaries.

The children of Israel were then the Lord's host,
and executioners of his judgments on people hardened in wickedness.
They were not to go to battle, but by his appointment.

The men who were chief in his army, had their instructions from the Almighty;
sometimes immediately, and sometimes by the ministry of angels.
Of these amongst others, were Moses, Joshua, Othniel and Gideon; see Exod.
iii, 2., and xviii.
19., Josh. 5:13. These people far off from Canaan,
against whom Israel was sent to battle, were so corrupt,
that the Creator of the universe saw it good to change their situation;
and in case of their opening their gates, and coming under tribute,
this their subjection, though probably more mild than absolute slavery,
was to last little or no longer than while Israel
remained in the true spirit of government.

It was pronounced by Moses the prophet, as a consequence of their wickedness,
"`The stranger that is within you shall get above you very high;
and you shall come down very low: he shall be the head, and you the tail.`"
This we find in some measure verified in their being made tributaries to the Moabites,
Midianites, Amorites and Philistines.

It is alleged in favor of the practice of slave-keeping,
that the Jews by their law made slaves of the heathen.
"`Moreover, of the children of the strangers that do sojourn amongst you,
of them shall you buy, and of their children which are with you,
which they begat in your land; and they shall be your possession;
and you shall take them as an inheritance for your children after you,
to inherit them as a possession, they shall be your bondmen forever.`"
It is difficult for us to have a certain knowledge of the mind of Moses,
in regard to keeping slaves,
in any other way than by looking upon him as a true servant of God,
whose mind and conduct were regulated by an inward principle of justice and equity.
To admit a supposition that he in that case was drawn
from perfect equity by the alliance of outward kindred,
would be to disown his authority.

Abraham had servants born in his house, and bought with his money:
"`And the Almighty said of Abraham, I know him,
that he will order his house after him,`" which implies, that he was as a father,
an instructor, and a good governor over his people.
Moses, considered as a man of God,
must necessarily have had a prospect of some real advantage in the
strangers and heathens being servants to the Israelites for a time.

As mankind had received and established many erroneous opinions and hurtful customs,
their living and conversing with the Jews,
while the Jews stood faithful to their principles,
might be helpful to remove those errors, and reform their manners.
But for men, with private views,
to assume an absolute power over the persons and properties of others,
and to continue it from age to age in the line of natural generation,
without regard to the virtues or vices of their successors,
as it is manifestly contrary to true universal love, and attended with great evils,
it requires the clearest evidence to beget a belief in us,
that Moses intended that the strangers should be such slaves to the Jews.

He directed them to buy strangers and sojourners.
It appears that there were strangers in Israel who were free men;
and considering with what tenderness and humanity the Jews, by their law,
were obliged to use their servants,
and what care was to be taken to instruct them in the true religion,
it is not unlikely that some strangers in poverty and distress were
willing to enter into bonds to serve the Jews as long as they lived;
and in such case the Jews, by their law, had a right to their service during life.

When the awl was bored through the ear of the Hebrew servant, the text says,
"`He shall serve forever;`" yet we do not suppose that by the word "`forever,`" it
was intended that none of his posterity should afterwards be free.
When it is said in regard to the strangers which they bought,
"`They shall be your possession,`" it may be well
understood to mean only the persons so purchased;
all that precedes relates to buying them,
and what follows to the continuance of their service;
"`You shall take them as an inheritance to your children after you;
they shall be your bondmen forever.`"
It may be well understood to stand limited to those they purchased.

Moses directing Aaron and his sons to wash their hands and feet,
when they went into the tabernacle of the congregation, says,
"`It shall be a statute forever to them,
even to him and his seed throughout all generations.`"
And to express the continuance of the law, it was his common language,
"`It shall be a statute forever throughout your generations.`"
So that had he intended the posterity of the strangers
so purchased to continue in slavery to the Jews,
it looks likely that he would have used some terms clearly to express it.
The Jews undoubtedly had slaves, whom they kept as such from one age to another;
but that this was agreeable to the genuine design of their inspired law-giver,
is far from being a clear case.

Making constructions of the law contrary to the true meaning of it,
was common amongst that people.
Samuel's sons took bribes, and perverted judgment.
Isaiah complained that they justified the wicked for reward.
Zephaniah, contemporary with Jeremiah,
on account of the injustice of the civil magistrates,
declared that those judges were evening wolves;
and that the priests did violence to the law.

Jeremiah acquaints us, that the priests cried peace, peace, when there was no peace;
by which means the people grew bold in their wickedness;
and having committed abominations, were not ashamed;
but through wrong constructions of the law, they justified themselves,
and boastingly said, "`We are wise; and the law of the Lord is with us.`"
These corruptions continued till the days of our Saviour, who told the Pharisees,
"`You have made the commandment of God of none effect through your tradition.`"
Thus it appears that they corrupted the law of Moses;
nor is it unlikely that among many others this was one;
for oppressing the strangers was a heavy charge against the Jews,
and very often strongly represented by the Lord's faithful prophets.

That the liberty of man was, by the inspired law-giver esteemed precious,
appears in this; that such who unjustly deprived men of it,
were to be punished in like manner as if they had murdered them.
"`He that steals a man, and sells him; or if he be founds in his hand,
shall surely be put to death.`"
This part of the law was so considerable, that Paul the learned Jew,
giving a brief account of the uses of the law, adds this,
"`It was made for men-stealers.`"
The great men amongst that people were exceedingly oppressive;
and it is likely exerted their whole strength and influence,
to have the law construed to suit their turns.

The honest servants of the Lord had heavy work with them in regard to their oppression;
a few instances follow.
"`Thus says the Lord of hosts, the God of Israel, amend your ways and your doings,
and I will cause you to dwell in this place.
If you thoroughly execute judgment between a man and his neighbor;
if you oppress not the stranger, the fatherless and the widow;
and shed not innocent blood in this place; neither walk after other gods to your hurt,
then will I cause you to dwell in this place.`"
Again this message was sent not only to the inferior ministers of justice,
but also to the chief ruler.

"`Thus says the Lord, go down to the house of the king of Judah,
and speak there this word; execute you judgment and righteousness,
and deliver the spoiled out of the hand of the oppressor; and do no wrong;
do no violence to the stranger, the fatherless and the widow;
neither shed innocent blood in this place.`"
Then adds, "`That in so doing they should prosper; but if you will not hear these words,
I swear by myself, says the Lord, that this house shall become a desolation.`"
The king, the princes,
and rulers were agreed in oppression before the Babylonish captivity;
for whatever courts of justice were retained amongst them,
or however they decided matters between men of estates,
it is plain that the cause of the poor was not judged in equity.

It appears that the great men amongst the Jews were fully resolved to have slaves,
even of their own brethren, Jer.
xxxiv.
Notwithstanding the promises and threatenings of the Lord, by the prophet,
and their solemn covenant to set them free,
confirmed by the imprecation of passing between the parts of a calf cut in twain;
intimating by that ceremony, that on breach of the covenant,
it were just for their bodies to be so cut in pieces.
Yet after all, they held fast to their old custom,
and called home the servants whom they had set free.
"`And you were now turned, and had done right in my sight,
in proclaiming liberty every man to his neighbor; and you had made a covenant before me,
in the house which is called by my name, but you turned and polluted my name,
and caused every man his servant, whom he had set at liberty at their pleasure,
to return, and brought them into subjection, to be unto you for servants,
and for handmaids: therefore thus says the Lord,
you have not hearkened unto me in proclaiming liberty every one to his neighbor,
and every one to his brother.
Behold, I proclaim liberty to you, says the Lord, to the sword, to the pestilence,
and to the famine; and I will make you to be removed into all the kingdoms of the earth.
The men who transgressed my covenant which they made,
and passed between the parts of the calf, I will give into the hands of their enemies,
and their dead bodies shall be for meat unto the fowls of the heaven,
and the beasts of the earth.`"
Soon after this their city was taken and burnt; the king's sons and the princes slain;
and the king, with the chief men of his kingdom, carried captive to Babylon.
Ezekiel, prophesying the return of that people to their own land, directs,
"`You shall divide the land by lot, for an inheritance unto you,
and to the strangers that sojourn amongst you; in what tribe the stranger sojourns,
there shall you give him his inheritance, says the Lord God.`"
Nor is this particular direction, and the authority with which it is enforced,
without a tacit implication,
that their ancestors had erred in their conduct towards the stranger.

Some who keep slaves, have doubted as to the equity of the practice;
but as they knew men, noted for their piety, who were in it, this, they say,
has made their minds easy.
To lean on the example of men in doubtful cases, is difficult: for only admit,
that those men were not faithful and upright to the highest degree,
but that in some particular case they erred,
and it may follow that this one case was the same, about which we are in doubt;
and to quiet our minds by their example, may be dangerous to ourselves;
and continuing in it, prove a stumbling-block to tender-minded people who succeed us,
in like manner as their examples are to us.

But supposing charity was their only motive,
and they not foreseeing the tendency of paying robbers for their booty,
were not justly under the imputation of being partners with a thief, Prov.
xxlx.
24., but were really innocent in what they did,
are we assured that we keep them with the same views they kept them?
If we keep them from no other motive than a real sense of duty,
and true charity governs us in all our proceedings toward them, we are so far safe:
but if another spirit, which inclines our minds to the ways of this world,
prevails upon us,
and we are concerned for our own outward gain more than for their real happiness,
it will avail us nothing that some good men have had the care and management of negroes.

Since mankind spread upon the earth,
many have been the revolutions attending the several families,
and their customs and ways of life different from each other.
This diversity of manners, though some are preferable to others,
operates not in favor of any, so far as to justify them to do violence to innocent men;
to bring them from their own into another way of life.
The mind, when moved by a principle of true love,
may feel a warmth of gratitude to the universal Father,
and a lively sympathy with those nations where Divine Light has been less manifest.

This desire for their real good may beget a
willingness to undergo hardships for their sakes,
that the true knowledge of God may be spread amongst them:
but to take them from their own land, with views of profit to ourselves,
by means inconsistent with pure justice,
is foreign to that principle which seeks the happiness of the whole creation.
Forced subjection, of innocent persons of full age, is inconsistent with right reason;
on one side,
the human mind is not naturally fortified with that firmness in wisdom and goodness,
necessary to an independent ruler; on the other side,
to be subject to the uncontrolled will of a man liable to err,
is most painful and afflicting to a conscientious creature.

It is our happiness faithfully to serve the Divine Being who made us:
his perfection makes our service reasonable;
but so long as men are biassed by narrow self-love,
so long they are unfit for absolute power over other men.
Men, taking on them the government of others, may intend to govern reasonably,
and make their subjects more happy than they would otherwise be;
but as absolute command belongs only to him who is perfect, where frail men,
in their own wills, assume such command, it has a direct tendency to vitiate their minds,
and make them more unfit for government.

Placing on men the ignominious title of slave, dressing them in uncomely garments,
keeping them to servile labor, in which they are often dirty,
tends gradually to fix a notion in the mind,
that they are a sort of people below us in nature,
and leads us to consider them as such in all our conclusions about them.
And moreover, where a person who is mean and contemptible in our esteem,
uses language or behavior toward us which is unseemly or disrespectful,
it excites wrath more powerfully than the like conduct
in one whom we account our equal or superior;
and where this happens to be the case, it disqualifies for candid judgment;
for it is unfit for a person to sit as judge in a case
where his own personal resentments are stirred up;
and as members of society in a well-framed government, we are mutually dependent.
Present interest incites to duty,
and makes each man attentive to the convenience of others;
but he whose will is a law to others, and who can enforce obedience by punishment;
he whose lacks are supplied without feeling any
obligation to make equal returns to his benefactor,
and whose irregular appetites find an open field for motion,
is in danger of growing hard,
and inattentive to their convenience who labor for his support,
and of losing that disposition, in which alone men are fit to govern.

The English government has been commended by
foreigners for the disuse of racks and tortures,
so much practiced in some states; but this multiplying of slaves leads to cruel tortures;
for where people exact hard labor of others, without a suitable reward,
and are resolved to continue in that way,
severity to such who oppose them becomes the consequence;
and several negro criminals among the English in America,
have been executed in a lingering painful way, very terrifying to others.

It is a happy case to set out right, and persevere in the same way:
a wrong beginning leads into many difficulties; for to support one evil,
another becomes customary; two produce more; and the further men proceed in this way,
the greater their dangers, their doubts and fears;
and the more painful and perplexing are their circumstances;
so that such who are true friends to the real and lasting interest of our country,
and candidly consider the tendency of things, cannot but feel concern on this account.

There is a superiority in men over the brute creatures,
and some of them are so manifestly dependent on men for a living,
that for them to serve us in moderation, so far as relates to the right use of things,
looks consonant to the design of our Creator.

There is nothing in their frame which argues the contrary; but in men there is.
The frame of men's bodies, and the dispositions of their minds are different;
some who are tough and strong, and their minds active,
choose ways of life requiring much labor to support them; others are soon weary;
and though use makes labor more tolerable, yet some are less apt for toil than others,
and their minds less sprightly.
These latter laboring for their subsistence,
commonly choose a mode of life easy to support, being content with a little.
When they are weary they may rest, take the most advantageous part of the day for labor,
and in all cases proportion one thing to another, so that their bodies be not oppressed.

Now while each is at liberty, the latter may be as happy,
and live as comfortably as the former;
but where men of the first sort have the latter under absolute command,
and not considering the odds in strength and firmness,
do sometimes in their eager pursuit, lay on them burdens grievous to be borne;
and by degrees grow more rigorous; these aspiring to greatness, increase oppression,
and the true order of a kind Providence is subverted.

There are weaknesses sometimes attending us,
which make little or no alteration in our countenances,
nor much lessen our appetite for food, and yet so affect us,
as to make labor very uneasy.
In such cases, masters intent on putting forward business,
and jealous of the sincerity of their slaves,
may disbelieve what they say and grievously afflict them.

Action is necessary for all men, and our exhausting frame requires a support,
which is the fruit of labor.
The earth must be tilled to keep us alive: labor is a proper part of our life;
to make one answer the other in some useful mode,
looks agreeable to the design of our Creator.
Motion rightly managed, tends to our satisfaction, health and support.

Those who quit all useful business, and live wholly on the labor of others,
have their exercise to seek; some such use less than their health requires;
others choose that which, by the circumstances attending it,
proves utterly adverse to true happiness.
Thus while some are in several ways, distressed for lack of useful action,
those who support them sigh, and are exhausted with exertions too powerful for nature,
spending their days with too little cessation from labor.

Seed sown with the tears of a confined oppressed people,
harvests cut down by an overborne discontented reaper,
make bread less sweet to the taste of an honest man, than that which is the produce,
or just reward of such voluntary action,
as is a proper part of the business of human creatures.

Again, the weak state of the human species, in bearing and bringing forth their young,
and the helpless condition of their young beyond that of other creatures,
clearly show that Perfect Goodness designs a tender
care and regard should be exercised toward them;
and that no imperfect,
arbitrary power should prevent the cordial effects of that sympathy,
which exists in the minds of well-met pairs, to each other, and toward their offspring.

In our species the mutual ties of affection are more
rational and durable than in others below us;
and the care and labor of raising our offspring are much greater.
The satisfaction arising to us in their innocent company,
and in their advances from one rational improvement to another, is considerable,
when two are thus joined, and their affections sincere.

It however happens among slaves, that they are often situate in different places;
and their seeing each other depends on the will of men, liable to human passions,
and a bias in judgment; who, with views of self-interest,
may keep them apart more than is right.

Being absent from each other, and often with other company,
there is a danger of their affections being alienated, jealousies arising,
the happiness otherwise resulting from the care of their offspring frustrated,
and the comforts of marriage destroyed.
These things being considered closely, as happening to a near friend,
will appear to be hard and painful.

He who reverently observes that goodness manifested by our gracious
Creator toward the various species of beings in this world,
will see, that in our frame and constitution it is clearly shown that innocent men,
capable to manage for themselves, were not intended to be slaves.

A person lately traveling amongst the negroes near Senegal, has this remark;
"`Which way so ever I turned my eyes on this pleasant spot,
I beheld a perfect image of pure nature; an agreeable solitude,
bounded on every side by charming landscapes,
the rural situation of cottages in the midst of trees;
the ease and indolence of the negroes reclining
under the shade of their spreading foliage;
the simplicity of their dress and manners;
the whole revived in my mind the idea of our first parents,
and I seemed to contemplate the world in its primitive state.`"
M+++.+++ Adanson, page 55.

Some negroes in these parts, who have had an agreeable education,
have manifested a brightness of understanding equal to many of us.
A remark of this kind we find in Bosman, page.
"`The negroes of Fida, says he, are so accurately quick in their merchandise accounts,
that they easily reckon as justly and quickly in their heads only,
as we with the assistance of pen and ink, though the sum amounts to several thousands.`"
Through the force of long custom, it appears needful to speak in relation to color.

Suppose a white child, born of parents of the meanest sort,
who died and left him an infant, falls into the hands of a person,
who endeavors to keep him a slave, some men would account him an unjust man in doing so,
who yet appear easy while many black people, of honest lives and good abilities,
are enslaved in a manner more shocking than the case here supposed.
This is owing chiefly to the idea of slavery being connected with the black color,
and liberty with the white; and where false ideas are twisted into our minds,
it is with difficulty we get fairly disentangled.

A traveller who in cloudy weather misses his way, makes many turns while he is lost,
yet still forms in his mind the bearing and situation of places,
and though the ideas are wrong, they fix as fast as if they were right.
Finding how things are, we see our mistake; yet the force of reason,
with repeated observations on places and things,
do not soon remove those false notions so fastened upon us,
but it will seem in the imagination as if the course of the sun was altered;
and though by recollection we are assured it is not,
yet those ideas do not suddenly leave us.

Selfishness being indulged, clouds the understanding;
and where selfish men for a long time proceed on their way without opposition,
the deceiveableness of unrighteousness gets so rooted in their intellects,
that a candid examination of things relating to self-interest is prevented;
and in this circumstance,
some who would not agree to make a slave of a person whose color is like their own,
appear easy in making slaves of others of a different color,
though their understandings and morals are equal
to the generality of men of their own color.

The color of a man avails nothing, in matters of right and equity.
Consider color in relation to treaties;
by which disputes between nations are sometimes settled.
And should the Father of us all so dispose things,
that treaties with black men should sometimes be necessary,
how then would it appear amongst the princes and ambassadors,
to insist on the prerogative of the white color?
Why is it that men, who believe in a righteous Omnipotent Being,
to whom all nations stand equally related, and are equally accountable,
remain so easy in it;
but because the ideas of negroes and slaves are so interwoven in the mind,
that they do not discuss this matter with that candor and freedom of thought,
which the case justly calls for.

To come at a right feeling of their condition, requires humble serious thinking;
for in their present situation,
they have but little to engage our natural affection in their favor.

Had we a son or a daughter involved in the same case, in which many of them are,
it would alarm us and make us feel their condition without seeking for it.
The adversity of an intimate friend will excite our compassion,
while that of others equally good, in the like trouble will but little affect us.

Again, the man in worldly honor whom we consider as our superior,
treating us with kindness and generosity,
begets a return of gratitude and friendship toward him.
We may receive as great benefits from men a degree lower than ourselves,
in the common way of reckoning, and feel ourselves less engaged in favor of them.
Such is our condition by nature, and these things being narrowly watched and examined,
will be found to center in self-love.

The blacks seem far from being our kinsfolks,
and did we find an agreeable disposition and sound understanding in some of them,
which appeared as a good foundation for a true friendship between us,
the disgrace arising from an open friendship with a person of so vile a stock,
in the common esteem, would naturally tend to hinder it.
They have neither honors, riches, outward magnificence nor power; their dress coarse,
and often ragged, their employ drudgery and much in the dirt,
they have little or nothing at command, but must wait upon and work for others,
to obtain the necessaries of life; so that in their present situation,
there is not much to engage the friendship, or move the affection of selfish men.
But such who live in the spirit of true charity,
sympathize with the afflicted even in the lowest stations of life.

Such is the kindness of our Creator, that people applying their minds to sound wisdom,
may in general with moderate exercise live comfortably,
where no misapplied power hinders it.
We in these parts have cause gratefully to acknowledge it.
But where men leave the true use of things, their lives become less calm,
and have less of real happiness in them.

Many are desirous of purchasing and keeping slaves,
that they may live in some measure conformably to those customs of the times,
which have in them a tincture of luxury; for when we, in the least degree,
depart from that use of the creatures, for which the Creator of all things intended them,
there luxury begins.

And if we consider this way of life seriously,
we shall see there is nothing in it sufficient to induce a wise man to choose it,
before a plain, simple way of living.
If we examine stately buildings and equipage, delicious food, superfine clothes,
silks and linens; if we consider the splendor of choice metal fastened upon raiment,
and the most showy inventions of men, it will yet appear that the humble-minded man,
who is contented with the true use of houses, food and garments,
and cheerfully exercises himself agreeably to his station in civil society, to earn them,
acts more reasonably, and discovers more soundness of understanding in his conduct,
than such who lay heavy burdens on others,
to support themselves in a luxurious way of living.

George Buchanan, in his history of Scotland, page 62,
tells of some ancient inhabitants of Britain,
who were derived from a people that "`had a way of marking their bodies, as some said,
with instruments of iron, with variety of pictures, and with animals of all shapes,
and wear no garments, that they should not hide their pictures;
and were therefore called Picts.`"
Did we see those people shrink with pain, for a considerable time together,
under the point or edge of this iron instrument,
and their bodies all bloody with the operation; did we see them sometimes naked,
suffering with cold, and yet refuse to put on garments,
that those imaginary ensigns of grandeur might not be concealed,
it is likely we should pity their folly and fondness for those things:
but if we candidly compare their conduct, in that case,
with some conduct amongst ourselves, will it not appear that our folly is the greatest?
In true Gospel simplicity, free from all wrong use of things,
a spirit which breathes peace and good will is cherished;
but when we aspire after imaginary grandeur,
and apply to selfish means to attain our end, this desire, in its original,
is the same with the Picts in cutting figures on their bodies;
but the evil consequences attending our proceedings are the greatest.

A covetous mind, which seeks opportunity to exalt itself,
is a great enemy to true harmony in a country:
envy and grudging usually accompany this disposition,
and it tends to stir up its likeness in others.
And where this disposition arises so high,
as to embolden us to look upon honest industrious men as our own property during life,
and to keep them to hard labor,
to support us in those customs which have not their foundation in right reason,
or to use any means of oppression; a haughty spirit is cherished on one side,
and the desire of revenge frequently excited on the other,
till the inhabitants of the land are ripe for great commotion and trouble;
and thus luxury and oppression have the seeds of war and desolation in them.

Some account of the slave-trade,
from the writings of persons who have been at the places where they are first purchased,
namely: Bosman on Guinea,
who was a factor for the Dutch about sixteen years in that country,
(page 339) thus remarks: "`But since I have so often mentioned that commerce,
I shall describe how it is managed by our factors.
The first business of one of our factors, when he comes to Fida,
is to satisfy the customs of the king, and the great men,
which amounts to about one hundred pounds, in Guinea value, as the goods must sell there.
After which we have free license to trade,
which is published throughout the whole land by the crier.
And yet before we can deal with any person,
we are obliged to buy the king's whole stock of slaves, at a set price;
which is commonly one third or fourth higher than ordinary.
After which we have free leave to deal with all his subjects, of what rank so ever.
But if there happen to be no stock of slaves,
the factor must resolve to run the risk of trusting the inhabitants with goods,
to the value of one or two hundred slaves;
which commodities they send into the inland country,
in order to buy with them slaves at all markets,
and that sometimes two hundred miles deep in the country: for you ought to be informed,
that markets of men are here kept in the same manner as they of beasts are with us.

"`Most of the slaves which are offered to us, are prisoners of war,
which are sold by the victors as their booty.
When these slaves come to Fida, they are put in prisons all together;
and when we treat concerning them, they are all brought out in a large plain, where,
by our surgeons, whose province it is, they are thoroughly examined,
even to the smallest member, and that naked, both men and women,
without the least distinction or modesty.
Those which are approved as good, are set on one side.
The invalids and maimed being thrown out, the remainder are numbered,
and it is entered who delivered them: in the mean while a burning iron,
with the arms or name of the company, lies in the fire,
with which ours are marked on the breast.

This is done that we may distinguish them from the slaves of the English, French,
or others.
When we have agreed with the owners of the slaves, they are returned to their prisons,
where, from that time forward, they are kept at our charge,
cost us two-pence a day a slave, which serves to subsist them, like our criminals,
on bread and water: so that, to save charges,
we send them on board our ships the first opportunity;
before which their masters strip them of all they have on their backs,
so that they come aboard stark naked, as well women as men;
in which condition they are obliged to continue,
if the master of the ship is not so charitable, which he commonly is,
as to bestow something on them, to cover their nakedness.`"
Same author, page 310. "`The inhabitants of Popo, as well as those of Goto,
depend on plunder and the slave trade, in both which they very much exceed the latter;
for being endowed with more courage, they rob more successfully,
and by that means increase their trade: notwithstanding which,
to freight a vessel with slaves, requires some months attendance.

In the year 1697, in three days time I could get but three slaves; but they assured me,
that if I would have patience for other three days only,
they should be able to deliver me one or two hundred.`"
Bosman, page 440. "`We cast anchor at Cape Mizurada, but not one negro coming on board;
I went on shore, and being desirous to be informed why they did not come on board,
was answered.
That about two months before, the English had been there with two vessels,
and had ravaged the country, destroyed all their canoes, plundered their houses,
and carried off some of their people for slaves;
upon which the remainder fled to the inland country.
They tell us, they live in peace with all their neighbors,
and have no notion of any other enemy than the English;
of which nation they had taken some then: and publicly declared,
that they would endeavor to get as many of them,
as the two-mentioned ships had carried off of their natives.
These unhappy English were in danger of being sacrificed to the memory of their friends,
which some of their nation carried off.`"
Extracts from a collection of voyages.

The author, a popish missionary,
speaking of his departing from the negro country to Brazil, says,
"`I remember the duke of Bambay, a negro chief,
one day sent me several blacks to be my slaves, which I would not accept,
but sent them back to him.
I afterwards told him, I came not into his country to make slaves;
but rather to deliver those from the slavery of the devil,
whom he kept in miserable thralldom.
The ship I went aboard was loaded with elephants' teeth,
and slaves to the number of six hundred and eighty men, women and children.
It was a pitiful sight to behold how all these people were bestowed.
The men were standing in the hold, fastened one to another with stakes,
for fear they should rise and kill the whites: the women were between the decks,
and the children in the steerage, pressed together like herrings in a barrel;
which caused an intolerable heat and stench.`"
Page 507.

"`It is now time, says the same author,
to speak of a brutish custom these people have amongst them in making slaves;
which I take not to be lawful for any person of a good conscience to buy.`"
He then describes how women betray men into slavery, and adds,
"`Others go up into the inland country, and through pretense of jurisdiction,
seize men upon any trifling offense, and sell them for slaves.`"
Page 537.

The author of this treatise, conversing with a person of good credit,
was informed by him, that in his youth, while in England,
he was minded to come to America, and happening on a vessel bound for Guinea,
and from there into America, he, with a view to see Africa, went on board her,
and continued with them in their voyage, and so came into this country.

Among other circumstances he related these.
"`They purchased on the coast about three hundred slaves;
some of them he understood were captives of war,
and some stolen by other negroes privately.
When they had got many slaves on board, but were still on that coast,
a plot was laid by an old negro,
notwithstanding the men had irons on their hands and feet,
to kill the English and take the vessel; which being discovered, the man was hanged,
and many of the slaves made to shoot at him as he hung up.

"`Another slave was charged with having a design to kill the English;
and the captain spoke to him in relation to the charge brought against him,
as he stood on deck; whereupon he immediately threw himself into the sea,
and was drowned.

"`Several negroes confined on board, were so extremely uneasy with their condition,
that after many endeavors used,
they could never make them eat nor drink after they came in the vessel;
but in a desperate resolution starved themselves to death,
behaving toward the last like mad-men.`"
In Randall's Geography, printed 1744, we are informed,
"`That in a time of full peace nothing is more common than for
the negroes of one nation to steal those of another,
and sell them to the Europeans.
It is thought that the English transmit annually
nearly fifty thousand of these unhappy creatures;
and the other European nations together, about two hundred thousand more.`"
It is through the goodness of God that the reformation from
gross idolatry and barbarity has been thus far effected.
If we consider our condition as Christians, and the benefits we enjoy,
and compare them with the condition of those people,
and consider that our nation trading with them for their country produce,
has had an opportunity of imparting useful instructions to them,
and remember that but little pains have been taken therein,
it must look like an indifference in us.
But when we reflect on a custom the most shocking of any amongst them, and remember,
that with a view to outward gain we have joined as parties in it;
that our concurrence with them in their barbarous proceedings,
has tended to harden them in cruelty,
and been a means of increasing calamities in their country,
we must own that herein we have acted contrary to the precepts of
Christ and the examples of those worthies whose lives and substance
were spent in propagating Truth and righteousness amongst the heathen.
When Saul, by the hand of Doeg, slew four-score priests at once,
he had a jealousy that one of them at least was confederate with David,
whom he considered as his enemy.
Herod slaying all the male children in Bethlehem of two 5'ears old and under,
was an act of uncommon cruelty; but he supposed there was a male child there,
within that age, who was likely to be king of the Jews,
and finding no way to destroy him, but by destroying them all,
thought this the most effectual means to secure the kingdom to his own family.

When the sentence against the Protestants of Marindol, etc., in France,
was put in execution, great numbers of people fled to the wilderness;
amongst whom were ancient people, women great with child,
and others with babes in their arms, who endured calamities grievous to relate,
and in the end some perished with hunger, and many were destroyed by fire and sword;
but they had this objection against them.
That they obstinately persisted in opposition to the holy mother church,
and being heretics, it was right to work their ruin and extirpation,
and raze out their memory from among men.
Fox's Acts and Monuments, page 646.

In favor of those cruelties, every one had what they deemed a plea.
These scenes of 412 blood and cruelty among the barbarous inhabitants of Guinea,
are not less terrible than those now mentioned.
They are continued from one age to another,
and we make ourselves parties and fellow-helpers in them;
nor do I see that we have any plea in our favor more plausible than the plea of Saul,
of Herod, or.
of the French, in those slaughters.

Many who are parties in this trade, by keeping slaves with views of self-interest,
were they to go as soldiers in one of these inland expeditions to catch slaves,
must necessarily grow dissatisfied with such employ,
or cease to profess their religious principles.
And though the first and most striking part of the scene is done at a great distance,
and by other hands, yet every one who is acquainted with the circumstances,
and notwithstanding joins in it, for the sake of gain only, must in the nature of things,
be chargeable with the others.

Should we consider ourselves present as spectators,
when cruel negroes privately catch innocent children, who are employed in the fields;
hear their lamentable cries, under the most terrifying apprehensions;
or should we look upon it as happening in our own families,
having our children carried off by savages, we must needs own,
that such proceedings are contrary to the nature of Christianity.

Should we meditate on the wars which are greatly increased by this trade,
and on that affliction which many thousands live in,
through apprehensions of being taken or slain;
on the terror and amazement that villages are in,
when surrounded by these troops of enterprisers;
on the great pain and misery of groaning dying men, who get wounded in those skirmishes;
we shall necessarily see, that it is impossible to be parties in such a trade,
on the motives of gain, and retain our innocence.

Should we consider the case of multitudes of those people, who in a fruitful soil,
and hot climate, with a little labor raise grain, roots and pulse to eat;
spin and weave cotton, and fasten together the large feathers of fowls,
to cover their nakedness; many of whom,
in much simplicity live inoffensively in their cottages,
and take great comfort in rearing up their children.

Should we contemplate their circumstances, when suddenly attacked,
and labor to understand their inexpressible anguish of soul who survive the conflict:
should we think on inoffensive women, who fled at the alarm,
and at their return saw that village in which they and their acquaintance were raised up,
and had pleasantly spent their youthful days, now lying in gloomy desolation;
some shocked at finding the mangled bodies of their near friends amongst the slain;
others bemoaning the absence of a brother, a sister, a child,
or a whole family of children, who by cruel men,
are bound and carried to market to be sold, without the least hopes of seeing them again:
add to this, the afflicted condition of these poor captives,
who are separated from family connections,
and all the comforts arising from friendship and acquaintance,
carried amongst a people of a strange language, to be parted from their fellow-captives,
put to labor in a manner more servile and wearisome than what they were used to,
with many sorrowful circumstances attending their slavery; we must necessarily see,
that it belongs not to the followers of Christ to be parties in such a trade,
on the motives of outward gain.

Though there were wars and desolations among the negroes,
before the Europeans began to trade there for slaves,
yet now the calamities are greatly increased,
so many thousands being annually brought from there;
and we by purchasing them with views of self-interest, are become parties with them,
and accessary to that increase.

In this case,
we are not joining against an enemy who is fomenting discords on our continent,
and using all possible means to make slaves of us and our children;
but against a people who have not injured us.

If those who were spoiled and wronged, should at length make slaves of their oppressors,
and continue slavery to their posterity, it would look rigorous to candid men:
but to act that part toward a people,
when neither they nor their fathers have injured us, has something in it extraordinary,
and requires our serious attention.

Our children breaking a bone; getting so bruised that a leg or an arm must be taken off;
lost for a few hours, so that we despair of their being found again; a friend hurt,
so thai he dies in a day or two; are circumstances that move us with grief.
Did we attend to these scenes in Africa,
in like manner as if they were transacted in our presence,
and sympathize with the negroes in all their afflictions and miseries,
as we do with our children and friends,
we should be more careful to do nothing in any degree helping
forward a trade productive of so many and so great calamities.
Great distance makes nothing in our favor.
Willingly to join with unrighteousness,
to the injury of men who live some thousand miles off, is the same in substance,
as joining with it to the injury of our neighbors.

In the eye of pure justice,
actions are regarded according to the spirit and disposition they arise from:
some evils are accounted scandalous,
and the desire of reputation may keep selfish
men from appearing openly to participate in them;
but he who is shy on that account, and yet by indirect means promotes that evil,
and shares in the profit of it, cannot be innocent.

He who with a view to self-interest buys a slave, made so by violence,
and on the strength of such purchase holds him a slave,
thereby joins hands with those who committed that violence,
and in the nature of things becomes chargeable with the guilt.

Suppose a man wants a slave, and being in Guinea,
goes and hides by the path where boys pass from one little town to another,
and there catches one the day he expects to sail; and taking him on board,
brings him home, without any aggravating circumstances;
suppose another buys a man taken by them who live by plunder and the slave-trade;
who often steal them privately, and shed much blood in getting them,
he who buys the slaves thus taken, pays those men for their wickedness,
and makes himself a party with them.

Whatever nicety of distinction there may be,
between going in person on expeditions to catch slaves,
and buying those with a view to self-interest, which others have taken;
it is clear and plain to an upright mind, that such distinction is in words,
not in substance; for the parties are concerned in the same work,
and have a necessary connection with and dependence on each other;
for were there none to purchase slaves, they who live by stealing and selling them,
would of consequence do less at it.

Some would buy a negro brought from Guinea, with a view to self-interest,
and keep him a slave, who yet would seem to scruple to take arms,
and join with men employed in taking slaves.
Others have civil negroes, who were born in our country,
capable and likely to manage well for themselves; whom they keep as slaves,
without ever trying them with freedom,
and take the profit of their labor as a part of their estates,
and yet disapprove of bringing them from their own country.

If those negroes had come here as merchants, with their ivory and gold-dust,
in order to trade with us, and some powerful person had taken their effects to himself,
and then put them to hard labor, and ever after considered them as slaves,
the action would be looked upon as unrighteous.

If those negro merchants should have children after being among us,
whose endowments and conduct were like other people's in common,
and on their attaining to mature age, and requesting to have their liberty,
they should be told they were born in slavery, and were lawful slaves,
and therefore their request should be denied;
such conduct toward them would be looked upon as unfair and oppressive.

In the present case, relating to home-born negroes,
whose understandings and behavior are as good as common among other people,
if we have any claim to them as slaves,
that claim is grounded on their being the children or offspring of slaves,
who in general were made such through means as unrighteous,
and attended with more terrible circumstances than the case last supposed;
so that when we trace our claim to the bottom,
these home-born negroes having paid for their education,
and given reasonable security to those who owned them,
in case of their becoming chargeable, we have no more equitable right to their service,
than we should if they were the children of honest merchants
who came from Guinea in an English vessel to trade with us.

If we claim any right to them as the children of slaves,
we build on the foundation laid by those who made slaves of their ancestors;
so that of necessity we must either justify the trade, or relinquish our right to them,
as being the children of slaves.

Why should it seem right to honest men to make advantage by
these people more than' by others'? Others enjoy freedom,
and receive wages equal to their work,
at or near such time as they have discharged these equitable
obligations they are under to those who educate them.
These have made no contract to serve; been no more expensive in raising up than others,
and many of them appear as likely to make a right use of freedom as other people;
how then can an honest man withhold from them that liberty,
which is the free gift of the Most High to his rational creatures?
The upright in heart cannot succeed the wicked in their wickedness;
nor is it consonant to the life they live, to hold fast an advantage unjustly gained.

The negroes who live by plunder and the slave-trade, steal poor innocent children,
invade their neighbors' territories, and spill much blood to get these slaves:
and can it be possible for an honest man to think that with a view to self-interest,
we may continue slavery to the offspring of these unhappy sufferers,
merely because they are the children of slaves', and not have a share of this guilt?
It is granted by many, that the means used in getting them are unrighteous,
and that buying them when brought here is wrong;
yet as setting them free is attended with some difficulty, they do not comply with it;
but seem to be of the opinion, that to give them food and raiment,
and keep them servants without any other wages,
is the best way to manage them that they know of;
and hoping that their children after them will not be cruel to the negroes,
conclude to leave them as slaves to their children.

While present outward interest is the chief object of our attention,
we shall feel many objections in our minds against renouncing our claim to them,
as the children of slaves; for being prepossessed with wrong opinions,
prevents our seeing things clearly, which to indifferent persons are easy to be seen.

Suppose a person seventy years past; in low circumstances, bought a negro man and woman,
and that the children of such person are now wealthy,
and have the children of such slaves;
admit that the first negro man and his wife did
as much business as their master and mistress,
and that the children of the slaves have done more than their young masters:
suppose on the whole,
that the expense of living has been less on the negroes side than on the other,
all which are no improbable suppositions, it follows,
that in equity these negroes have a right to a
part of this increase of worldly substance;
that should some difficulties arise on their being set free,
there is reason for us patiently to labor through them.

As the conduct of men varies, relating to civil society,
so different treatment is justly due to them.
Indiscreet men occasion trouble in the world;
and it remains to be the care of those who seek the good of mankind,
to admonish such as they find occasion.

The slothfulness of some of them, in providing for themselves and families,
it is likely would require the notice of their neighbors;
nor is it unlikely that some would, with justice, be made servants,
and others punished for their crimes.
Pure justice points out to each individual their due;
but to deny a people the privilege of human creatures, on a supposition that being free,
many of them would be troublesome to us,
is to mix the condition of good and bad men together,
and to treat the whole as the worst of them deserve.

If we seriously consider that liberty is the right of innocent men;
that the mighty God is a refuge for the oppressed;
that in reality we are indebted to them; that they being set free,
are still liable to the penalties of our laws,
and as likely to have punishment for their crimes as other people;
these may answer all our objections; and to retain them in perpetual servitude,
without just cause for it, will produce effects, in the event,
more grievous than setting them free would do,
when a real love to truth and equity is the motive to it.

Our authority over them stands originally in a purchase made from those who,
as to the general, obtained theirs by unrighteousness.
Whenever we have recourse to such authority,
it tends more or less to obstruct the channels through
which the perfect plant in us receives nourishment.

There is a principle, +++[+++the Spirit of Truth]
which is pure, placed in the human mind,
which in different places and ages has had different names; it is however pure,
and proceeds from God.
It is deep and inward, confined to no forms of religion, nor excluded from any,
where the heart stands in perfect sincerity.
In whomsoever this takes root and grows, of what nation soever, they become brethren,
in the best sense of the expression.

Using ourselves to take ways which appear most easy to us,
when inconsistent with that purity which is without beginning,
we thereby set up a government of our own, and deny obedience to Him,
whose service is true liberty.

He that has a servant made so wrongfully, and knows it to be so,
when he treats him otherwise than a free man, when he reaps the benefit of his labor,
without paying him such wages as are reasonably due to free men for the like service,
clothes excepted; these things, though done in calmness, without any show of disorder,
do yet deprave the mind in like manner, and with as great certainty,
as prevailing cold congeals water.
These steps taken by masters,
and their conduct striking the minds of their children while young,
leave less room for that which is good to work upon them.
The customs of their parents, their neighbors, and the people with whom they converse,
working upon their minds;
and they from there conceiving similar ideas of things and modes of conduct,
the entrance into their hearts becomes in a great measure,
shut up against the gentle movings of uncreated purity.

From one age to another, the gloom grows thicker and darker,
till error gets established by general opinion;
that whoever attends to perfect goodness and remains under the melting influence of it,
finds a path unknown to many,
and sees the necessity to lean upon the arm of Divine strength,
and dwell alone or with a few, in rightly committing their cause to Him,
who is a refuge for his people in all their troubles.

Where through the agreement of a multitude, some channels of justice are stopped,
and men may support their characters as just men, by being just to a party,
there is great danger of contracting an alliance with that spirit,
which stands in opposition to the God of love, and spreads discord,
trouble and vexation among such who give up to the influence of it.

Negroes are our fellow creatures,
and their present condition amongst us requires our serious consideration.
We know not the time when those scales, in which mountains are weighed, may turn.
The Parent of mankind is gracious: his care is over his smallest creatures:
and a multitude of men escape not his notice.
And though many of them are trodden down and despised, yet he remembers them:
he sees their affliction,
and looks upon the spreading increasing exaltation of the oppressor.
He turns the channels of power, humbles the most haughty people,
and gives deliverance to the oppressed,
at such periods as are consistent with his infinite justice and goodness.
And wherever gain is preferred to equity,
and wrong things publicly encouraged to that degree,
that wickedness takes root and spreads wide amongst the inhabitants of a country,
there is real cause for sorrow to all such,
whose love to mankind stands on a true principle,
and who wisely consider the end and event of things.


CONSIDERATIONS ON PURE WISDOM AND HUMAN POLICY; ON LABOR, ON SCHOOLS;
AND ON THE RIGHT USE OF THE LORD'S OUTWARD GIFTS.

FIRST PRINTED IN THE YEAR 1768.

"`The wisdom that is from above, is first pure, then peaceable, gentle,
and easy to be entreated, full of mercy and good fruits, without partiality,
and without hypocrisy.`" James 3:17.


INTRODUCTION.

My mind has often been affected with sorrow, on account of the prevailing of that spirit,
which leads from a humble waiting on the inward teaching of Christ,
to pursue ways of living, attended with unnecessary labor,
and which draws forth the minds of many people to seek after outward power,
and to strive for riches, which frequently introduce oppression,
and bring forth wars and grievous calamities.

It is with reverence that I acknowledge the mercies of our heavenly Father,
who in infinite love visited me in my youth, and wrought a belief in me,
that through true obedience a state of inward purity may be known in this life,
in which we may love mankind in the same love with which our Redeemer loves us,
and therein learn resignation to endure hardships for the real good of others.

"`While the eye is single, the whole body is full of light;`" but for lack of this,
selfish desires and an imaginary superiority, darken the mind;
hence injustice frequently proceeds; and where this is the case,
to convince the judgment, is the most effectual remedy.

Where violent measures are pursued in opposing injustice,
the passions and resentments of the injured,
frequently operate in the prosecution of their designs;
and after conflicts productive of very great calamities,
the minds of contending parties often remain as little
acquainted with the pure principle of Divine love,
as they were before;
but where people walk in that pure light in which all their "`works are
wrought in God,`" and under oppression persevere in the meek spirit,
and abide firm in the cause of Truth, without actively complying with oppressive demands,
through these the Lord has often manifested his power,
in opening the understandings of others, to the promoting of righteousness in the earth.

A time I believe is coming, wherein this Divine work will so spread and prevail,
that "`Nation shall not lift up sword against nation, nor learn war any more.`"
And as we, through the tender mercies of God, do feel that this precious work is begun,
I am concerned to encourage my brethren and sisters in a holy care and diligence,
that each of us may so live under the sanctifying power of Truth,
as to be redeemed from all unnecessary cares; that our eye being single to him,
no customs, however prevalent, which are contrary to the wisdom from above,
may hinder us from faithfully following his holy leadings,
in whatsoever he may graciously appoint for us.

CONSIDERATIONS, etc.

To have our trust settled in the Lord,
and not to seek after nor desire outward treasures,
any further than his holy Spirit leads us therein, is a happy state, as says the prophet,
"`Blessed is the man that trusts in the Lord, and whose hope the Lord is.`"
Pure wisdom leads people into lowliness of mind,
in which they learn resignation to the Divine will,
and contentment in suffering for his cause,
when they cannot keep a clear conscience without suffering.

In this pure wisdom the mind is attentive to the
root and original spring of motions and desires;
and as we know "`the Lord to be our refuge,`" and find
no safety but in humbly walking before him,
we feel a holy engagement,
that every desire which leads therefrom may be brought to judgment.

While we proceed in this precious way,
and find ardent longings for a full deliverance from every thing which defiles,
all prospects of gain that are not consistent with the wisdom from above,
are considered as snares, and an inward concern is felt,
that we may live under the cross, and faithfully attend to that holy Spirit,
which is sufficient to preserve out of them.

When I have considered that saying of Christ,
"`Lay not up for yourselves treasures upon earth,`" his
omnipotence has often occurred to my mind.

While we believe that he is every where present with his people,
and that perfect goodness, wisdom and power, are united in him,
how comfortable is the consideration.
Our needs may be great, but his power is greater.
We may be oppressed and despised,
but he is able to turn our patient sufferings into profit to ourselves,
and to the advancement of his work on earth.
His people who feel the power of his cross, to crucify all that is selfish in them,
who are engaged in outward concerns, from a convincement that it is their duty,
and resign themselves and their treasures to him;
these feel that it is dangerous to give way to that in us,
which craves riches and greatness in this world.

As the heart truly contrite,
earnestly desires "`to know Christ and the fellowship of his
sufferings,`" so far as the Lord for gracious ends may lead into them;
as such feel that it is their interest to put their trust in God,
and to seek no gain but that which he by his holy Spirit, leads into; so on the contrary,
they who do not reverently wait for this Divine Teacher, and are not humbly concerned,
according to their measure,
"`to fill up that which is behind of the afflictions of Christ,`" in
patiently suffering for the promotion of righteousness in the earth;
but have an eye toward the power of men and the outward advantage of wealth,
these are often attentive to those employments which appear profitable,
even though the gains arise from such trade and
business as proceed from the workings of that spirit,
which is estranged from the self-denying life of a humble contrite Christian.

While I write on this subject,
I feel my mind tenderly affected toward those honestly disposed people,
who have been brought up in employments attended with these difficulties.

To such I may say, in the feeling of our heavenly Father's love,
and number myself with you, O that our eyes may be single to the Lord!
May we reverently wait on him for strength to
lay aside all unnecessary expense of every kind,
and learn contentment in a plain simple life.

May we in lowliness submit to the leadings of his spirit,
and enter upon any outward employ which he graciously points out to us,
and then whatever difficulties arise in consequence of our faithfulness,
I trust they will work for our good.

Small treasure to a resigned mind is sufficient.
How happy is it to be content with a little, to live in humility, and feel that in us,
which breathes out this language, Abba!
Father.

If that called the wisdom of this world, had no resemblance of true wisdom,
the name of wisdom, I suppose, had not been given to it.

As wasting outward substance to gratify vain desires, on one hand;
so slothfulness and neglect on the other,
do often involve men and their families in trouble, and reduce them to lack and distress.
To shun both these vices is good in itself, and has a resemblance of wisdom;
but while people thus provident, have it principally in view to get riches and power,
and the friendship of this world,
and do not humbly wait for the Spirit of Truth to lead them in purity; these,
through an anxious care to obtain the end desired,
reach forth for gain in worldly wisdom, and in regard to their inward state,
fall into various temptations and snares.
And though such may think of applying wealth to good purposes,
and to use their power to prevent oppression,
yet wealth and power are often applied otherwise;
nor can we depart from the leadings of our holy Shepherd, without going into confusion.

Great wealth is frequently attended with power,
which nothing but Divine love can qualify the mind to use rightly;
and as to the humility and uprightness of our children after us,
how great is the uncertainty!
If, in acquiring wealth, we take hold on the wisdom which is from beneath,
and depart from the leadings of Truth, and example our children herein,
we have great cause to apprehend that wealth may be a snare to them,
and prove an injury to others, over whom their wealth may give them power.

To be redeemed from that wisdom which is from beneath,
and to walk in the light of the Lord, is a precious situation;
thus his people are brought to put their trust in him;
and in this humble confidence in his wisdom, goodness and power,
the righteous find a refuge in adversities, superior to the greatest outward help,
and a comfort more certain than any worldly advantages can afford.


ON LABOR.

Having from my childhood been used to bodily labor for a living,
I may express my experience therein.

Right exercise affords an innocent pleasure in the time of it,
and prepares us to enjoy the sweetness of rest; but from the extremes each way,
arise inconveniences.

Moderate exercise opens the pores, gives the blood a lively circulation,
and enables us to judge rightly respecting that
portion of labor which is the true medium.

"`The fowls of the air sow not, nor gather into barns,
yet our heavenly Father feeds them;`" nor do I believe that
infinite goodness and power would have allotted labor to us,
had he not seen that labor was proper for us in this life.

The original design and true medium of labor,
is a subject that to me appears worthy of our serious consideration.

Idle men are often a burden to themselves, neglect the duty they owe to their families,
and become burdensome to others also.

As outward labor directed by the wisdom from above,
tends to our health and adds to our happiness in this life; so on the contrary,
entering upon it in a selfish spirit, and pursuing it too long, or too hard,
have a contrary effect.

I have observed that too much labor not only makes the understanding dull,
but so intrudes upon the harmony of the body, that after ceasing from our toil,
we have another to pass through,
before we can be so composed as to enjoy the sweetness of rest.

From too much labor in the heat, frequently proceed immoderate sweats,
which often I believe open the way for disorders and impair our constitutions.

When we go beyond the true medium, and feel weariness approaching,
but think business may suffer if we cease,
at such a time spirituous liquors are frequently taken,
with a view to support nature under these fatigues.

I have found that too much labor in the summer heats the blood,
that taking strong drink to support the body under such labor, increases that heat,
and though a person may be so far temperate as not to manifest the least disorder,
yet the mind in such a circumstance, does not retain that calmness and serenity,
in which we should endeavor to live.

Thus toiling in the heat and drinking strong liquor,
make men more resolute and less considerate,
and tend very much to disqualify for following him who is meek and low of heart.

As laying out more business than is consistent with pure wisdom is an evil,
so this evil frequently leads into more.
Too much business leads to hurry.
In the hurry and toil strong drink is often used,
and hereby many proceed to noise and wantonness, and some, though more considerate,
do often suffer loss, as to a true composedness of mind.

I feel sincere desires in my heart that no rent or interest
may be laid so high as to be a snare to tenants;
and that no desires of gain may draw any too far in business.
That no cares to support customs, which have not their foundation in pure wisdom,
may have place in our minds, but that we may build on the sure foundation,
and feel our holy Shepherd to lead us, who alone is able to preserve us,
and bring forth from every thing which defiles.

Having several times in my travels,
had opportunity to observe the labor and manner of life of great numbers of slaves,
it appears to me that the true medium is lamentably neglected by many,
who assign them their portion of labor.

Without saying much at this time, concerning buying and selling men for term of life,
who have as just a right to liberty as we have;
nor about the great miseries and effusion of blood,
consequent on promoting the slave-trade; and to speak as favorably as may be,
with regard to continuing those in bondage who are amongst us,
we cannot say there is no partiality in it:
for whatever tenderness may be manifested by individuals in their life time toward them,
yet for people to be transmitted from a man to his posterity,
in the helpless condition of slaves,
appears inconsistent with the nature of the Gospel spirit.
From such proceedings it often follows, that persons in the decline of life,
are deprived of monies equitably due to them, and committed to the care,
and subjected to the absolute power, of young inexperienced men,
who know but little about the weakness of old age,
nor understand the language of declining life.

Where parents give their estates to their children,
and then depend on them for a maintenance, they sometimes meet with great inconveniences;
but if the power of possession thus obtained,
often reverses the obligations of gratitude and filial duty,
and makes manifest that youth are often ignorant of the language of old age,
how hard is the case of ancient negroes who, deprived of the wages equitably due to them,
are left to young people, who have been used to look upon them as their inferiors.

For men to behold the fruits of their labor withheld from them, and possessed by others,
and in old age to find themselves destitute of those comfortable accommodations,
and that tender regard, which their time of life requires; When they feel pains,
and stiffness in their joints and limbs, weakness of appetite,
and that a little labor is wearisome,
and still behold themselves in the neglected uncomfortable condition of a slave,
and oftentimes to a young unsympathizing man;
For men to be thus treated from one generation to another who,
besides their own distresses, think on the slavery entailed on their posterity,
and are grieved,
what disagreeable thoughts must they have of the professed followers
of Jesus! and how must their groans ascend to that Almighty Being,
who "`will be a refuge for the oppressed.`"


ON SCHOOLS.

"`Suffer little children to come unto me, and forbid them not,
for of such is the kingdom of God.`" Mark 10:14.


To encourage children to do things with a view to get the praise of men,
to me appears an obstruction to their being inwardly acquainted with the Spirit of Truth.
For it is the work of the holy Spirit to direct the mind to God,
that in all our proceedings we may have a single eye to him; to give alms in secret,
to fast in secret, and labor to keep clear of that disposition reproved by our Savior,
"`But all their works they do for to be seen of men.`"
That Divine light which enlightens all men,
I believe does often shine in the minds of children very early,
and humbly to wait for wisdom,
that our conduct toward them may tend to forward their acquaintance with it,
and to strengthen them in obedience thereto, appears to me to be a duty on all of us.

By cherishing the spirit of pride, and the love of praise in them,
I believe they may sometimes improve faster in learning, than otherwise they would,
but to take measures to forward children in learning,
which naturally tend to divert their minds from true humility,
appears to me to savor of the wisdom of this world.

If tutors are not acquainted with sanctification of spirit,
nor experienced in a humble waiting for the leadings of Truth,
but follow the maxims of the wisdom of this world, children who are under their tuition,
appear to me to be in danger of imbibing thoughts and
apprehensions reverse to that meekness and lowliness of heart,
which is necessary for all the true followers of Christ.

Children at an age fit for schools,
are in a time of life which requires the patient attention of pious people,
and if we commit them to the tuition of those whose minds we believe are not
rightly prepared to "`train them up in the nurture and admonition of the Lord,`" we
are in danger of not acting the part of faithful parents toward them;
for our heavenly Father does not require us to do evil, that good may come of it;
and it is needful that we deeply examine ourselves,
lest we get entangled in the wisdom of this world, and through wrong apprehensions,
take such methods in education, as may prove a great injury to the minds of our children.

It is a lovely sight to behold innocent children-;
and when they are sent to schools where their tender minds are
in imminent danger of being led astray by tutors,
who do not live a self-denying life,
or by the conversation of children who do not live in innocence,
it is a case much to be lamented.

While a pious tutor has the charge of no more children than he can take due care of,
and keeps his authority in the Truth, the good spirit in which he leads and governs,
works on the minds of such who are not hardened,
and his labors not only tend to bring them forward in outward learning,
but to open their understanding with respect to the true Christian life.
But where a person has charge of too many,
and his thoughts and time are so much employed in the outward affairs of his school,
that he does not so weightily attend to the spirit and conduct of each individual,
as to be enabled to administer rightly to all in due season;
through such omissions he not only suffers, as to the state of his own mind,
but the minds of the children are in danger of suffering also.

To watch the spirit of children, to nurture them in Gospel love,
and labor to help them against that which would mar the beauty of their minds,
is a debt we owe them; and a faithful performance of our duty,
not only tends to their lasting benefit, and our own peace,
but also to render their company agreeable to us.

Instruction thus administered,
reaches the pure witness in the minds of children who are not hardened,
and begets love in them toward those who thus lead them on;
but where too great a number are committed to a tutor, and he, through much cumber,
omits a careful attention to the minds of the children,
there is a danger of disorders gradually increasing amongst them,
until the effects thereof appear in their conduct, too strong to be easily remedied.

A care has lived on my mind, that more time might be employed by parents at home,
and by tutors at school,
in weightily attending to the spirit and inclinations of children,
and that we may so lead, instruct and govern them, in this tender part of life,
that nothing may be omitted which is in our power,
to help them on their way to become the children of our Father, who is in heaven.

Meditating on the situation of schools in our provinces,
my mind has at times been affected with sorrow,
and under these exercises it has appeared to me,
that if those who have large estates were faithful stewards, and laid no rent,
or interest, or other demand, higher than is consistent with universal love;
and those in lower circumstances would, under a moderate employ,
shun unnecessary expense, even to the smallest article,
and all unite in humbly seeking to the Lord, he would graciously instruct us,
and strengthen us,
to relieve the youth from various snares in which many of them are entangled.


ON THE RIGHT USE OF THE LORD'S OUTWARD GIFTS.

As our understandings are opened by the pure light,
we experience that through an inward approaching to God,
the mind is strengthened in obedience;
and that by gratifying those desires which are not of his begetting,
these approaches to him are obstructed, and the deceivable spirit gains strength.

These truths being as it were engraven upon our hearts,
and our everlasting interest in Christ evidently concerned therein,
we become fervently engaged,
that nothing may be nourished which tends to feed pride or self-love in us.
Thus in pure obedience, we are not only instructed in our duty to God,
but also in the affairs which necessarily relate to this life,
and the Spirit of Truth which guides into all truth,
leavens the mind with a pious concern, that "`whatsoever we do in word or deed,
may be done in His name.`"
Hence such buildings, furniture, food and raiment, as best answer our necessities,
and are the least likely to feed that selfish spirit which is our enemy,
are the most acceptable to us.

In this state the mind is tender, and inwardly watchful,
that the love of gain draw us not into any business
which may weaken our love to our heavenly Father,
or bring unnecessary trouble to any of his creatures.

Thus the way gradually opens to cease from that spirit
which craves riches and things fetched far,
which so mixes with the customs of this world,
and so intrudes upon the true harmony of life,
that the right medium of labor is very much departed from.

As the minds of people are settled in a steady concern,
not to hold or possess anything but what may be held
consistently with the wisdom which is from above,
they consider what they possess as the gift of God, and are inwardly exercised,
that in all parts of their conduct they may act agreeably to
the nature of the peaceable government of Christ.

A little supports such a life; and in a state truly resigned to the Lord,
the eye is single to see what outward employ he leads into as a means of our subsistence,
and a lively care is maintained to hold to that, without launching further.

There is a harmony in the several parts of this divine work in the hearts of people:
he who leads them to cease from those gainful employments,
carried on in that wisdom which is from beneath,
delivers also from the desire after worldly greatness,
and reconciles the mind to a life so plain, that a little suffices.

Here the real comforts of life are not lessened.
Moderate exercise, in the way of true wisdom, is pleasant both to mind and body.
Food and raiment sufficient, though in the greatest simplicity,
is accepted with contentment and gratitude.

The mutual love subsisting between the faithful followers of Christ,
is more pure than that friendship which is not seasoned with humility,
how specious soever the appearance.

Where people depart from pure wisdom in one case,
it is often an introduction to depart from it in many more;
and thus a spirit which seeks for outward greatness,
and leads into worldly wisdom to attain it and support it, gets possession of the mind.

In beholding the customary departure from the true medium of labor,
and that unnecessary toil which many go through, in supporting outward greatness,
and procuring delicacies;
in beholding how the true calmness of life is changed into hurry, and how many,
by eagerly pursuing outward treasure,
are in great danger of withering as to the inward state of the mind;
in meditating on the works of this spirit,
and on the desolations it makes amongst the professors of Christianity,
I may thankfully acknowledge, that I often feel pure love beget longings in my heart,
for the exaltation of the peaceable kingdom of Christ,
and an engagement to labor according to the gift bestowed on me, for promoting a humble,
plain, temperate way of living:
a life where no unnecessary cares or expenses may encumber our minds,
or lessen our ability to do good; where no desires after riches,
or greatness may lead into hard dealing; where no connexions with worldly minded men,
may abate our love to God, or weaken a true zeal for righteousness:
a life wherein we may diligently labor for resignedness to do
and suffer whatever our heavenly Father may allot for us,
in reconciling the world to himself When the prophet Isaiah had uttered his vision,
and declared that a time was coming wherein "`swords should be beaten into plowshares,
and spears into pruning-hooks, and that nation should not lift up sword against nation,
neither shall they learn war any more;`" he immediately
directs the minds of people to the Divine teacher,
in this remarkable language: "`O house of Jacob,
come you and let us walk in the light of the Lord.`"
To wait for the direction of this light, in all temporal as well as spiritual concerns,
appears necessary; for if in any case we enter lightly into temporal affairs,
without feeling this Spirit of Truth to open our way therein,
and through the love of this world proceed on,
and seek for gain by that business or traffic, which "`is not of the Father,
but of the world,`" we fail in our testimony to the purity and peace of his government,
and get into that which is for chastisement.

This matter has lain heavy on my mind, it being evident, that a life less humble,
less simple and plain, than that which Christ leads his sheep into,
necessarily requires a support, for which pure wisdom does not provide;
hence there is no probability of our being "`a peculiar people, so zealous of good works,
as to have no fellowship with works of darkness,`" while we
have lacks to supply which have their foundation in custom,
and do not come within the meaning of those expressions,
"`your heavenly Father knows that you have need of all these things.`"
Those things which he beholds to be necessary for his people,
he fails not to give them in his own way and time; but as his ways are above our ways,
and his thoughts above our thoughts,
so imaginary needs are different "`from those
things which he knows that we have need of.`"
As my meditations have been on these things,
compassion has filled my heart toward my fellow-creatures, involved in customs,
which have grown up in "`the wisdom of this world, which is foolishness with God.`"
O that the youth may be so thoroughly experienced in a humble walking before the Lord,
that they may be his children, and know him to be their refuge,
their safe unfailing refuge,
through the various dangers attending this uncertain state of being.

If those whose minds are redeemed from the love of wealth,
and who are contented with a plain, simple way of living,
find that to conduct the affairs of a family,
without giving countenance to unrighteous proceedings,
or having fellowship with works of darkness, the most diligent care is necessary;
If customs, distinguishable from universal righteousness,
and opposite to the true self-denying life, are now prevalent, and so mixed with trade,
and with almost every employ,
that it is only through humble waiting on the inward guidance of Truth,
that we may reasonably hope to walk safely,
and support a uniform testimony to the peaceable government of Christ;
if this be the case, how lamentably do they expose themselves to temptations,
who give way to the love of riches, conform to expensive living,
and reach forth for gain, to support customs which our holy Shepherd leads not into.

