
[#harmony, short="Considerations on the Harmony of Mankind"]
== Considerations on the True Harmony of Mankind, and How It Is To Be Maintained

[.chapter-subtitle--blurb]
First Printed in the Year 1770

[quote.scripture, , Micah 5:7]
____
"`And the remnant of Jacob shall be in the midst of many people, as a dew from the Lord,
as the showers upon the grass, that tarries not for man, nor waits for the sons of men.`"
____


=== Introduction

As mankind, though descended from one parent, are divided into many families,
and as trading to sea is greatly increased within a few ages past;
amidst this extended commerce,
how necessary is it that the professed followers of Christ keep sacred his Holy name,
and be employed about trade and traffic no farther than
justice and equity evidently accompany them;
that we may give no just cause of offense to any, however distant,
or unable to plead their own cause; and may continually keep in view,
the spreading of the true and saving knowledge of God and of his son Jesus Christ,
amongst our fellow-creatures, which through his infinite love,
some feel to be more precious than any other treasure.

[.old-style]
=== Chapter I. / On serving the Lord in our outward employments.

Under the humbling dispensations of the Father of mercies,
I have felt an inward labor for the good of my fellow-creatures,
and a concern that the holy Spirit,
which alone can restore mankind to a state of true harmony,
may with singleness of heart be waited for and followed.

I trust there are many under that visitation, which, if faithfully attended to,
will make them quick of understanding in the fear of the Lord,
and qualify them with firmness to be true patterns of the Christian life, who,
in living and walking, may hold forth an invitation to others,
to come out of the entanglements of the spirit of this world.

That which I feel first to express is,
a care for those who are in circumstances which appear difficult,
with respect to supporting their families in a way answerable to pure wisdom,
that they may not be discouraged,
but remember that in humbly obeying the leading of Christ, he owns us as his friends;
"`You are my friends if you do whatsoever I command you;`" and to be a friend to Christ,
is to be united to him who has all power in heaven and in earth;
and though a woman may forget her sucking child,
yet will he not forget his faithful ones.

The condition of many who dwell in cities has
often affected me with a brotherly sympathy,
attended with a desire that resignation may be labored for,
and where the holy Leader directs to a country life or some change of employ,
he may be faithfully followed; for under the refining hand of the Lord,
I have seen that the inhabitants of some cities are greatly increased
through some branches of business which his holy Spirit does not lead into,
and that being entangled in these things,
tends to bring a cloud over the minds of people
convinced of the leadings of this holy Leader,
and obstructs the coming of the kingdom of Christ on earth as it is in heaven.

If we indulge a desire to imitate our neighbors in those
things which harmonize not with the true Christian walking,
these entanglements may hold fast to us, and some who in an awakening time,
feel tender scruples with respect to their manner of life,
may look on the example of others more noted in the church,
who yet may not be refined from every degree of dross; and by looking on these examples,
and desiring to support their families in a way pleasant to the natural mind,
there may be danger of the worldly wisdom gaining strength in them,
and of their departing from that pure feeling of Truth, which if faithfully attended to,
would teach contentment in the Divine will, even in a very low estate.

One formerly speaking on the profitableness of true humility, says,
"`He that troubles not himself with anxious thoughts for more than is necessary,
lives little less than the life of angels; while by a mind content with little,
he imitates their lack of nothing.`"
Cave's Primitive Christianity, page 31.

"`It is not enough, says Tertullian, that a Christian be chaste and modest,
but he must appear to be so: a virtue of which he should have so great a store,
that it should flow from his mind upon his habit,
and break from the retirements of his conscience, into the superficies of his life.`"
Same book, page 43.

"`The garments we wear, says Clemens,
ought to be mean and frugal--that is true simplicity of habit,
which takes away what is vain and superfluous; that the best and most solid garment,
which is the farthest from curiosity.`" Page 49.

Though the change from day to night,
is by a motion so gradual as scarcely to be perceived,
yet when night is come we behold it very different from the day;
and thus as people become wise in their own eyes, and prudent in their own sight,
customs rise up from the spirit of this world, and spread by little and little,
until a departure from the simplicity that there is in Christ,
becomes as distinguishable as light from darkness,
to such who are crucified to the world.

Our holy Shepherd, to encourage his flock in firmness and perseverance,
reminds them of his love for them; "`As the Father has loved me, so have I loved you;
continue you in my love;`" and in another place he
graciously points out the danger of departing therefrom,
by going into unsuitable employments.

This he represents in the similitude of offense from that useful active member, the hand;
and to fix the instruction the deeper, he names the right hand;
"`If your right hand offend you cut it off and cast it
from you:`"--If you feel offense in your employment,
humbly follow him who leads into all Truth,
and is a strong and faithful friend to those who are resigned to him.

Again, he points out those things which appearing pleasant to the natural mind,
are not best for us, in the similitude of offense from the eye;
"`If your right eye offend you pluck it out, and cast it from you.`"
To pluck out the eye, or cut off the hand, is attended with sharp pain;
and how precious is the instruction which our Redeemer thus opens to us,
that we may not faint under the most painful trials, but put our trust in him,
even in him who sent an angel to feed Elijah in the wilderness;
who fed a multitude with a few barley loaves,
and is now as attentive to the needs of his people as ever.

The prophet Isaiah represents the unrighteous doings of the Israelites toward the poor,
as the fruits of an effeminate life; "`As for my people, children are their oppressors,
and women rule over them; what mean you that you beat my people to pieces,
and grind the faces of the poor, says the Lord God.`"
Then he mentions the haughtiness of the daughters of Zion,
and enumerates many ornaments as instances of their vanity, to uphold which,
the poor were so hardly dealt with, that he sets forth their poverty,
their leanness and inability to help themselves,
in the similitude of a man maimed by violence or "`beaten to
pieces,`" and forced to endure the painful operation of having
his face gradually worn away in the manner of grinding.

I may here add, that at times,
when I have felt true love open my heart towards my fellow-creatures,
and been engaged in weighty conversation in the cause of righteousness,
the instructions I have received under these exercises,
in regard to the true use of the outward gifts of God,
have made deep and lasting impressions on my mind.

I have beheld how the desire to provide wealth,
and to uphold a delicate life has grievously entangled many,
and been like snares to their offspring;
and though some have been affected with a sense of their difficulties,
and appeared desirous at times to be helped out of them;
yet for lack of abiding under the humbling power of Truth,
they have continued in these entanglements; for in remaining conformable to this world,
and giving way to a delicate life, this expensive way of living,
in parents and in children, has called for a large supply,
and in answering this call "`the faces of the poor`" have been
ground away and made thin through hard dealing.

There is balm, there is a physician;
and O what longings do I feel that we may embrace the means appointed for our healing;
know that removed which now ministers cause for the cries of
many people to ascend to heaven against their oppressors,
and that we may see the true harmony restored.

Behold "`how good and how pleasant it is, for brethren to dwell together in unity.`"
The nature of this unity is thus opened by the apostle, "`If we walk in the light,
as He +++[+++God+++]+++
is in the light, we shall have fellowship one with another,
and the blood of Jesus Christ, his Son, cleanses us from all sin.`"
The land may be polluted with innocent blood,
which like the blood of Abel may cry to the Almighty;
but those who "`walk in the light as Christ is
in the light,`" they know the "`Lamb of God,
who takes away the sin of the world.`"
Walking is a phrase frequently used in Scripture to represent our journey through life,
and appears to comprehend the various affairs and transactions
properly relating to our being in this world.

Christ being the light dwells always in the light, and if our walking be thus,
and in every affair and concern we faithfully follow this divine Leader;
he preserves from giving just cause for any to quarrel with us;
and where this foundation is laid and mutually kept to,
by families conversant with each other, the way is open for those comforts in society,
which our heavenly Father intends as a part of our happiness in this world;
and we may experience the goodness and pleasantness of dwelling together in unity.
But where ways of living take place which tend to oppression,
and in the pursuit of wealth,
people do that to others which they know would not be acceptable to themselves,
either in exercising an absolute power over them,
or otherwise laying on them inequitable burdens;
here a fear lest that measure should be measured out to them,
which they have measured to others,
incites a care to support that by craft and cunning devices
which stands not on the firm foundation of righteousness:
thus the harmony of society is broken,
and from hence commotions and wars do frequently arise in the world.

"`Come out of Babylon my people, that you be not partakers of her sins,
and that you receive not of her plagues.`"
This babel, or Babylon, was built in the spirit of self-exaltation:
"`Let us build us a city and a tower, whose top may reach to heaven,
and let us make us a name.`"
In departing from a humble trust in God, and in following a selfish spirit,
people have intentions to get the upper-hand of their fellow creatures,
privately meditate on means to obtain their ends,
and have a language in their hearts which is hard to understand.
In Babel the language is confounded.

This city is represented as a place of business,
and those employed in it as merchants of the earth:
"`The merchants of the earth are waxed rich through the abundance of her delicacies.`"
It is remarkable in this call, that the language from the Father of mercies is,
"`my people,`" "`Come out of Babylon my people!`"
Thus his tender mercies are toward us in an imperfect state;
and as we faithfully attend to the call,
the path of righteousness is more and more opened;
cravings which have not their foundation in pure wisdom, more and more cease;
and in an inward purity of heart,
we experience a restoration of that which was lost at Babel,
represented by the inspired prophet, in the "`returning of a pure language.`"
Happy for those who humbly attend to the call, "`Come out of Babylon my people.`"
For though in going forth we may meet with trials, which for a time may be painful,
yet as we bow in true humility and continue in it,
an evidence is felt that God only is wise;
and that in weaning us from all that is selfish,
he prepares the way to a quiet habitation where
all our desires are bounded by his wisdom.

An exercise of spirit attends me,
that we who are convinced of the pure leadings of Truth,
may bow in the deepest reverence, and so watchfully regard this leader,
that many who are grievously entangled in a wilderness of vain customs,
may look upon us and be instructed.

And O that such who have plenty of this world's goods,
may be faithful in that with which they are entrusted,
and example others in the true Christian walking.

Our blessed Saviour speaking on worldly greatness,
compares himself to one waiting and attending on a company at dinner:
"`Whether is greater, he that sits at meat or he that serves?
Is not he that sits at meat?
But I am amongst you as he that serves.`"
Thus in a world greatly disordered,
where men aspiring to outward greatness are wont
to oppress others to support their designs,
he who was of the highest descent, being the Son of God,
and greater than any amongst the greatest families of men,
by his example and doctrines foreclosed his followers
from claiming any show of outward greatness,
and from any supposed superiority in themselves, or derived from their ancestors.

He who was greater than earthly princes, was not only meek and low of heart,
but his outward appearance was plain and lowly,
and free from every stain of the spirit of this world.

Such was the example of our blessed Redeemer, of whom the beloved disciple said,
"`He that says he abides in him, ought also to walk even as he walked.`"
John Bradford, who suffered martyrdom under Queen Mary,
wrote a letter to his friends out of prison a short time before he was burnt,
in which are these expressions;
"`Consider your dignity as children of God and temples of the Holy Ghost,
and members of Christ; be ashamed therefore to.
think, speak, or do anything unseemly, for God's children and the members of Christ.`"
Fox's Acts and Monuments, page 1177.

[.old-style]
=== Chapter II. / On the Example of Christ.

My mind has been brought into a brotherly feeling with the poor,
as to the things of this life,
who are under trials in regard to getting a living in a
way answerable to the purity of Truth;
and a labor of heart has attended me,
that their way may not be made difficult through the love of
money in those who are tried with plentiful estates,
but that they with tenderness of heart may sympathize with them.

It is the saying of our blessed Redeemer, "`You cannot serve God and mammon.`"
There is a deep feeling of the way of purity,
a way in which the wisdom of the world has no part, but is opened by the Spirit of Truth,
and is "`called the way of holiness;`" a way in which
the traveller is employed in watching unto prayer;
and the outward gain we get in this journey,
is considered as a trust committed to us by Him, who formed and supports the world,
and is the rightful director of the use and application of the products of it.

Except the mind be preserved chaste, there is no safety for us;
but in an estrangement from true resignation, the spirit of the world casts up a way,
in which gain is many times principally attended to,
and in which there is a selfish application of outward treasures.

How agreeable to the true harmony of society, is that exhortation of the apostle,
"`Look not every man on his own things, but every man also on the things of others.
Let this mind be in you which was also in Christ Jesus.`"
A person in outward prosperity may have the power of obtaining riches,
but the same mind being in him which was in Christ Jesus,
he may feel a tenderness of heart towards those of low degree;
and instead of setting himself above them,
may look upon it as an unmerited favor that his way
through life is more easy than the way of many others;
may improve every opportunity of leading forth out of
those customs which have entangled the family;
employ his time in looking into the needs of the poor members,
and hold forth such a perfect example of humiliation,
that the pure witness may be reached in many minds,
and the way opened for a harmonious walking together.

Jesus Christ in promoting the happiness of others,
was not deficient in looking for the helpless, who lay in obscurity,
nor did he save anything to render himself honorable amongst men,
which might have been of more use to the weak members in his Father's family;
of whose compassion towards us I may now speak a little.
He who was perfectly happy in himself, moved with infinite love,
"`took not upon him the nature of angels,`" but our imperfect natures,
and therein wrestled with the temptations which attend us in this life;
and although he was the Son of Him who is greater than earthly princes,
yet he became a companion to poor, sincere hearted men;
and though he gave the clearest evidence that Divine power attended him,
yet the most unfavorable constructions of his
acts were framed by a self-righteous people;
his miracles represented as the effect of a diabolical power,
and endeavors used to render him hateful,
as having his mission from the prince of darkness;
nor did their envy cease until they took him like a criminal and brought him to trial.
Though some may affect to carry the appearance
of being unmoved at the apprehension of distress,
our dear Redeemer, who was perfectly sincere, having the same human nature which we have,
and feeling, a little before he was apprehended, the weight of that work upon him,
for which he came into the world, was "`sorrowful even unto death.`"
Here the human nature struggled to be excused from a cup so bitter;
but his prayers centered in resignation, "`Not my will but yours be done.`"
In this conflict,
so great was his agony that "`sweat like drops of blood fell from him to the ground.`"
Behold now, as foretold by the prophet,
he is in a judicial manner "`numbered with the transgressors.`"
Behold him as some poor man of no reputation, standing before the high priest and elders,
and before Herod and Pilate, where witnesses appear against him, and he,
mindful of the most gracious design of his coming, declines to plead in his own defense,
"`but as a sheep that is dumb before his shearer,`" so under many accusations,
revilings and buffetings, he remained silent.

And though he signified to Peter that he had access to
power sufficient to overthrow all their outward forces;
yet retaining a resignation to suffer for the sins of mankind, he exerted not that power,
but permitted them to go on in their malicious designs,
and pronounce him to be worthy of death, even him who was perfect in goodness.
Thus, "`in his humiliation his judgment was taken away,`" and like some vile criminal,
"`he was led as a lamb to the slaughter.`"
Under these heavy trials, though poor unstable Pilate was convinced of his innocence,
yet the people generally looked upon him as a deceiver and a blasphemer,
and the approaching punishment as a just judgment upon him,
"`They esteemed him smitten of God and afflicted.`"
So great had been the surprise of his disciples, at his being taken by armed men,
that they "`forsook him and fled:`" thus they hid their faces from him, he was despised,
and by their conduct it appeared as though "`they esteemed him not.`"
But contrary to that opinion, of his being smitten of God and afflicted,
it was for our sakes that "`he was put to grief; he was wounded for our transgressions;
he was bruised for our iniquities;`" and under the weight of them,
manifesting the deepest compassion for the instruments of his misery,
he labored as their advocate, and in the deeps of affliction,
with an unconquerable patience, cried out, "`Father forgive them,
for they know not what they do!`"
Now this mind being in us, which was in Christ Jesus,
it removes from our hearts the desire of superiority, worldly honor or greatness;
a deep attention is felt to the Divine Counsellor,
and an ardent engagement to promote as far as we may be enabled,
the happiness of mankind universally.

This state, where every motion from a selfish spirit yields to pure love,
I may with gratitude to the Father of mercies acknowledge,
is often opened before me as a pearl to dig after; attended with a living concern,
that amongst the many nations and families on the earth,
those who believe in the Messiah,
that "`he was manifested to destroy the works of the devil,`" and thus to "`take
away the sins of the world,`" may experience the will of our heavenly Father,
"`to be done on earth as it is in heaven.`"
Strong are the desires I often feel, that this holy profession may remain unpolluted,
and that the believers in Christ may so abide in the pure inward feeling of his Spirit,
that the wisdom from above may shine forth in their living,
as a light by which others may be instrumentally helped on their way,
in the true harmonious walking.

[.old-style]
=== Chapter III. / On Merchandising.

Where the treasures of pure love are opened,
and we obediently follow Him who is the light of life, the mind becomes chaste;
and a care is felt,
that the unction from the Holy one may be our leader in every undertaking.

In being crucified to the world,
broken off from that friendship which is enmity with God,
and dead to the customs and fashions which have not their foundation in the Truth;
the way is prepared to lowliness in outward living, and to a disentanglement from those

snares which attend the love of money;
and where the faithful friends of Christ are so
situated that merchandising appears to be their duty,
they feel a restraint from going farther than he owns their proceeding;
being convinced that "`we are not our own, but are bought with a price,
that none of us may live to ourselves, but to Him who died for us.`"
Thus they are taught not only to keep to a moderate
advance and uprightness in their dealings,
but to consider the tendency of their proceeding;
to do nothing which they know would operate against the cause of universal righteousness,
and to keep continually in view the spreading of
the peaceable kingdom of Christ amongst mankind.

The prophet Isaiah spoke of the gathered church, in the similitude of a city,
where many being employed were all preserved in purity;
"`They shall call them the holy people, the redeemed of the Lord,
and you shall be called, sought out, a city not forsaken.`"
The apostle after mentioning the mystery of Christ's sufferings,
exhorts "`Be you holy in all manner of conversation.`"
There is a conversation necessary in trade;
and there is a conversation so foreign from the nature of Christ's kingdom,
that it is represented in the similitude of one
man pushing another with a warlike weapon;
"`There is that speaks like the piercing of a sword.`"
In all our concerns it is necessary that the leading of the
spirit of Christ be humbly waited for and faithfully followed,
as the only means of being preserved chaste as a holy people,
who "`in all things are circumspect,`" that nothing we do may
carry the appearance of approbation of the works of wickedness,
make the unrighteous more at ease in unrighteousness,
or occasion the injuries committed against the oppressed to be more lightly looked over.

Where morality is kept to and supported by the inhabitants of a country,
there is a certain reproach attends those individuals amongst them,
who manifestly deviate therefrom.

Thus if a person of good report is charged with
stealing goods out of an open shop in the day time,
and on a public trial is found guilty, and the law in that case is put in execution,
he therein sustains a loss of reputation;
but if he be convicted a second and third time of the like offense,
his good name would cease amongst such who knew these things.
If his neighbor, reputed to be an honest man, is charged with buying goods of this thief,
at a time when the purchaser knew they were stolen,
and on a public trial is found guilty, this purchaser would meet with disesteem;
but if he persisted in buying stolen goods, knowing them to be such,
and was publicly convicted thereof a second and third time,
he would no longer be considered as an honest man by those who knew these things;
nor would it appear of good report to be found in his company, or buying his traffic,
until some evident tokens of sincere repentance appeared in him.
But where iniquity is committed openly,
and the authors of it are not brought to justice or put to shame,
their hands grow strong.
Thus the general corruption of the Jews shortly before
their state was broken up by the Chaldeans,
is described by their boldness in impiety;
for as their leaders were connected together in wickedness,
they strengthened one another and grew confident.

"`Were they ashamed when they had committed abominations?
no, they were not at all ashamed,
neither could they blush;`" on which account the Lord thus expostulates with them,
"`What has my beloved to do in my house, seeing she has wrought lewdness with many?
and the holy flesh is passed from you: when you do evil, then you rejoice.`"
The faithful friends of Christ, who hunger and thirst after righteousness,
and inwardly breathe that his kingdom may come on earth as it is in heaven,
are taught by him to be quick of understanding in his fear,
and to be very attentive to the means he may appoint
for promoting pure righteousness in the earth;
and as shame is due to those whose works manifestly operate
against the gracious design of his sufferings for us,
a care lives on their minds that no wrong customs, however supported,
may bias their judgments, but that they may humbly abide under the cross,
and be preserved in a conduct which may not contribute to
strengthen the hands of the wicked in their wickedness,
or to remove shame from those to whom it is justly due.

The coming of that day is precious in which we experience the truth of this expression,
"`The Lord our righteousness,`" and feel him to
be "`made unto us wisdom and sanctification.`"
The example of a righteous man is often looked at with attention.
Where righteous men join in business their company gives encouragement to others;
and as one grain of incense deliberately offered to the prince of this world,
renders an offering to God in that state unacceptable,
and from those esteemed leaders of the people may be injurious to the weak;
it requires deep humility of heart to follow him faithfully,
who alone gives sound wisdom and the spirit of true discerning.
O how necessary it is to consider the weight of a holy profession!
The conduct of some formerly, gave occasion of complaint against them,
"`You have defiled your sanctuaries by the multitude of your iniquities,
by the iniquity of your traffic.`"
And in several places it is charged against Israel that they had polluted the holy Name.

The prophet Isaiah represents inward sanctification in the
similitude of being purged from that which is fuel for fire;
and particularly describes the outward fruits,
brought forth by those who dwell in this inward holiness, "`they walk righteously,
and speak uprightly.`"
By walking he represents the journey through life, as a righteous journey;
and "`by speaking uprightly,`" seems to point at
that which Moses appears to have had in view,
when he thus expressed himself, "`You shall not follow a multitude to do evil,
nor speak in a case to decline after many to wrest judgment.`"
He goes on to show their firmness in equity;
representing them as persons superior to all the arts of getting money,
which have not righteousness for their foundation;
"`They despise the gain of oppressions:`" and he further shows
how careful they are that no prospects of gain may induce them
to become partial in judgment respecting an injury;
"`They shake their hands from holding bribes.`"
Again, where any interest is so connected with shedding blood,
that the cry of innocent blood goes also with it;
he points out their care to keep innocent blood from crying against them,
in the similitude of a man stopping his ears to prevent a sound from entering his head,
"`They stop their ears from hearing of blood;`"
and where they know that wickedness is committed,
he points out with care,
that they do not by an unguarded friendship with the authors of it,
appear like unconcerned lookers on, but as people so deeply affected with sorrow,
that they cannot endure to stand by and behold it;
this he represents in the similitude of a man "`shutting his eyes from seeing evil.`"
"`Who amongst us shall dwell with the devouring fire?
Who amongst us shall dwell with everlasting burnings?
He that walks righteously and speaks uprightly.
He that despises the gain of oppressions, that shakes his hands from holding of bribes,
that stops his ears from hearing of blood, and shuts his eyes from seeing evil.`"
He proceeds in the spirit of prophecy to show how the
faithful being supported under temptations,
would be preserved from the defilement which there is in the love of money;
that as they who, in a reverent waiting on God, feel their strength renewed,
are said to "`mount upward;`" so here their
preservation from the snare of unrighteous gain,
is represented in the likeness of a man, borne up above all crafty,
artful means of getting the advantage of another,
"`They shall dwell on high;`" and he points out
the stability and firmness of their condition,
"`His place of defense shall be the munitions of rocks;`" and
that under all the outward appearances of loss,
in denying himself of gainful profits for righteousness sake,
through the care of Him who provides for the sparrows,
he should have a supply answerable to infinite wisdom, "`Bread shall be given him,
his waters shall be sure.`"
And as our Savior mentions the sight of God to be attainable
by "`the pure in heart,`" so here the prophet pointed out,
how in true sanctification the understanding is opened,
to behold the peaceable harmonious nature of his kingdom,
"`your eyes shall see the King in his beauty;`" and that
looking beyond all the afflictions which attend the righteous,
to "`a habitation eternal in the heavens,`" with an eye divinely opened,
they "`shall behold the land that is 'very far off.`"
"`He shall dwell on high, his place of defense shall be the munitions of rocks,
bread shall be given him, his water shall be sure.

Your eyes shall see the King in his beauty;
they shall behold the land that is very far off.`"
I often remember, and to me the subject is awful,
that the great Judge of all the earth does that which is right,
and that he "`before whom the nations are as the drop
of a bucket,`" is "`no respecter of persons.`"
Happy for them, who like the inspired prophet, "`in the way of his judgments,
wait for him.`"
When we feel him to sit as a refiner with fire, and know a resignedness wrought in us,
to that which he appoints for us, his blessing in a very low estate,
is found to be more precious than much outward treasure in those ways
of life where the leadings of his Spirit are not followed.

The prophet, in a sight of the Divine work amongst many people,
declared in the name of the Lord, "`I will gather all nations and tongues,
and they shall come and see my glory.`"
And again, "`from the rising of the sun to the going down of the same,
my name shall be great amongst the Gentiles,
and in every place incense shall be offered to my name, and a pure offering.`"
Behold here how the prophets had an inward sense
of the spreading of the kingdom of Christ;
and how he was spoken of as one who should "`take the heathen for his inheritance,
and the utmost parts of the earth for his possession.`"
That "`he was given for a light to the Gentiles;
and for salvation to the ends of the earth.`"
When we meditate on this Divine work, as a work of ages;
a work that the prophets felt long before Christ appeared visibly on earth,
and remember the bitter agonies he endured when he "`poured out his
soul unto death,`" that the heathen nations as well as others,
might come to the knowledge of the Truth and be saved;
when we contemplate this marvelous work,
as that which "`the angels desire to look into,`" and behold
people amongst whom this light has eminently broken forth,
and who have received many favors from the bountiful hand of our heavenly Father,
not only indifferent with respect to publishing the glad tidings amongst the Gentiles,
as yet sitting in darkness and entangled with many superstitions;
but aspiring after wealth and worldly honors, and taking means to obtain their ends,
tending to stir up wrath and indignation,
and ta beget an abhorrence in them to the name of Christianity--when
these things are weightily attended to,
how mournful is the subject?
It is worthy of remembrance, that people in different ages,
deeply baptized into the nature of that work for which Christ suffered,
have joyfully offered up their liberty and lives for promoting it in the earth.
Policarp, who was reputed a disciple of St.

John, having attained to great age, was at length sentenced to die for his religion,
and being brought to the fire, prayed nearly as follows,
"`You God and Father of our Lord Jesus Christ,
by whom I have received the knowledge of you!
O God of the angels and powers, and of every living creature,
and of all sorts of just men who live in your presence;
I thank you! that you have graciously vouchsafed this day and
this hour to allot me a portion among the number of martyrs,
among the people of Christ, unto the resurrection of everlasting life;
among whom I shall be received in your sight, this day,
as a fruitful and acceptable sacrifice: wherefore for all this, I praise you,
I bless you, I glorify you through the everlasting High Priest, Jesus Christ,
your well-beloved Son; to whom, with you and the Holy Ghost, be all glory,
world without end. Amen.`"
Bishop Latimer, when sentence of death by fire, was pronounced against him,
on account of his firmness in the cause of religion, said, "`I thank God most heartily,
that he has prolonged my life to this end; that I may,
in this case glorify him by this kind of death.`"
Fox's Acts and Monuments, 936.

William Dewsbury, who had suffered much for his religion, in his last sickness,
encouraging his friends to faithfulness, made mention, like good old Jacob,
of the loving-kindness of God to him in the course of his life,
and that through the power of Divine love,
he for Christ's sake had joyfully entered prisons.

I mention these, as a few examples, out of many,
of the powerful operation of the Spirit of Christ, where people are fully devoted to it,
and of the ardent longings in their minds for
the spreading of his kingdom amongst mankind.
Now to those, in the present age, who truly know Christ,
and feel the nature of his peaceable government opened in their understandings,
how loud is the call wherewith we are called to faithfulness;
that in following this pure light of life,
"`we as workers together with him,`" may labor in that great
work for which he was offered as a sacrifice on the cross;
and that his peaceable doctrines may shine through us in their real harmony,
at a time when the name of Christianity has become hateful to many of the heathen.

When Gehazi had obtained treasures which the prophet under Divine direction had refused,
and was returned from the business; the prophet, troubled at his conduct,
queried if it was a time thus to prepare for specious living.

"`Is it a time to receive money and garments, men servants and maid servants?
The leprosy therefore of Naaman shall cleave to you and to your seed forever.`"
O that we may lay to heart the condition of the present time,
and humbly follow His counsel,
who alone is able to prepare the way for a true harmonious walking amongst mankind.

[.old-style]
=== Chapter IV. / On Divine Admonitions.

Such are the perfections of our heavenly Father,
that in all the dispensations of his providence, it is our duty, "`in every thing,
to give thanks.`"
Though from the first settlement of this part of America,
he has not extended his judgments to the degree of famine,
yet worms at times have come forth beyond numbering,
and laid waste fields of grain and grass, where they have appeared: another kind,
in great multitudes, working out of sight, in grass ground,
have so eaten the roots that the surface, being loosened from the soil beneath,
might be taken off in great sheets.

These devouring creatures appearing seldom, and coming in such multitudes,
their generation appears different from most other reptiles,
and by the prophet they were called "`God's army sent amongst the people.`"
There have been tempests of hail,
which have very much destroyed the grain where they extended.
Through long drought in summer,
grain in some places has been less than half the usual quantity;^
footnote:[When crops fail,
I often feel a tender care that the case of poor tenants may be mercifully considered.]
and in the continuance thereof, I have beheld with attention, from week to week,
how dryness from the top of the earth, has extended deeper and deeper,
while the corn and plants have languished;
and with reverence my mind has been turned toward Him, who being perfect in goodness,
in wisdom and power, does all things right.
After long drought, when the sky has grown dark with a collection of matter,
and clouds like lakes of water have hung over our heads,
from which the thirsty land has been soaked; I have at times,
with awful ness beheld the vehement operation of lightning,
made sometimes to accompany these blessings,
as a messenger from Him who created all things,
to remind us of our duty in a right use of those benefits,
and to give striking admonitions, that we do not misapply those gifts,
in which an Almighty power is exerted, in bestowing them upon us.

When I have considered that many of our fellow-creatures suffer much in some places,
for lack of the necessaries of life,
while those who rule over them are too much given to luxury and many vanities;
and behold the apparent deviation from pure wisdom amongst us,
in the use of the outward gifts of God;
those marks of famine have appeared like humbling admonitions from him,
that we might be instructed by gentle chastisements,
and might seriously consider our ways;
remembering that the outward supply of life is a gift from our heavenly Father,
and that we should not venture to use, or to apply his gifts,
in a way contrary to pure wisdom.

Should we continue to reject those merciful admonitions, and use his gifts at home,
contrary to the gracious design of the giver, or send them abroad in a way of trade,
which the Spirit of Truth does not lead into;
and should he whose eyes are upon all our ways,
extend his chastisements so far as to reduce us to much
greater distress than has yet been felt by these provinces;
with what sorrow of heart might we meditate on that saying,
"`Have you not procured this unto yourself, in that you have forsaken the Lord your God,
when he led you by the way?
Your own wickedness shall correct you, and your backslidings shall reprove you:
know therefore and see, that it is an evil thing and bitter,
that you have forsaken the Lord your God, and that my fear is not in you,
says the Lord God of hosts.`"
My mind has often been affected with sorrow,
in beholding a wrong application of the gifts of our heavenly Father;
and those expressions concerning the defilement of the
earth have been opened to my understanding,
"`The earth was corrupt before God, and the earth was filled with violence.`"
Again, "`The earth also, is defiled under the inhabitants thereof,
because they have broken the everlasting covenant.`"

The earth being the work of a Divine power, may not as such be accounted unclean;
but when violence is committed thereon, and the channel of righteousness so obstructed,
that "`in our skirts are found the blood of the souls of poor innocents;
not by a secret search but upon all these`"^
footnote:[See a Caution and Warning to Great Britain and her colonies,
page 31.]--when blood, shed unrighteously, remains un-atoned for,
and the inhabitants are not effectually purged from it,
when they do not wash their hands in innocency, as was figured in the law,
in the case of one being found slain;
but seek for gain arising from scenes of violence and oppression,
here the land is polluted with blood. Duet. 21:6.

Moreover, when the earth is planted and tilled,
and the fruits brought forth are applied to support unrighteous purposes;
here the gracious design of Infinite Goodness, in these his gifts, being perverted,
the earth is defiled; and the complaint formerly uttered becomes applicable;
"`You have made me to serve with your sins; you have wearied me with your iniquities.`"
